### ISSUE TITLE
CUDA and Optix versions?

### ISSUE THREAD

**Issue by alexcolburn** [mitsuba-renderer/mitsuba2#10]
What versions of CUDA and Optix are you building against?  I’m building on Windows 10, and Optix 7, CUDA 10.2, and there is a include file missing during compile.  I’d like to rule out dependency versions first.

**Comment by wjakob** [comment]
We use the latest CUDA and OptiX 6.5. Can you post the compiler error message you encountered? Most of our development takes place on Linux, and it's definitely possible that a Windows regression snuck in. We're currently in the process of reviving the build bots to ensure a working build on all platforms in the future.

**Comment by alexcolburn** [comment]
The specific error is \mesh.cpp(17,14): fatal error C1083: Cannot open include file: 'optix_cuda_interop.h': No such file or directory

optix_cuda_interop.h is part of the Optix 6.5 distribution, not in 7.   I'll see if 6.5 works for me thanks.
This would be good version info for the how to build notes.
Thanks

**Comment by wjakob** [comment]
I think the version requirement is documented here: https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling/. Please let me know if it works out.

**Comment by alexcolburn** [comment]
I should have read further down in the docs to see the GPU requirements!
I still need to work through a couple more problems, I'll note those down as I solve them.
Thanks!
