### ISSUE TITLE
u_int undefined on vanilla Windows 10 scalar_rgb configuration

### ISSUE THREAD

**Issue by bcollins526** [mitsuba-renderer/mitsuba2#105]
I get:

mitsuba2\src\librender\mesh.cpp(208,14): error C2065: 'u_int': undeclared identifier

when trying to build Release x64. It may have something to do with _XOPEN_SOURCE getting defined somewhere. If I change that u_int to unsigned int, the renderer does build.

**Comment by Speierers** [comment]
Thanks for reporting this @bcollins526. This should now be fixed.
