### ISSUE TITLE
VS2019 Running Issue: dlls under different relative paths

### ISSUE THREAD

**Issue by elegabriel** [mitsuba-renderer/mitsuba2#107]
I used cmake to create mitsuba.sln and opened it with visual studio 2019.
All the output directories of projects(dependencies, plugins, mistuba-core and etc.) are related path, just like
.\mitsuba2\src\mitsuba\Debug\
.\mitsuba2\src\films\Debug\

All dlls are under different paths.
I can change all the output directories into one manually, but is there some other ways to fix it?

**Comment by Speierers** [comment]
There should be a `dist-copy` target which will copy all the compiled DLL to a `dist` folder. Then you can use the `setpath.bat` so add this folder to you `path`. Is this what you are looking for?

**Comment by elegabriel** [comment]
> There should be a `dist-copy` target which will copy all the compiled DLL to a `dist` folder. Then you can use the `setpath.bat` so add this folder to you `path`. Is this what you are looking for?

Hi Speierers,
Thanks a lot!
I set mitsuba as startup project. And this issue is fixed after I built ALL_BUILD project.
