### ISSUE TITLE
Issues in compiling the system(not providing "PythonLibsNew")

### ISSUE THREAD

**Issue by GraphZou** [mitsuba-renderer/mitsuba2#109]
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindPythonLibsNew.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "PythonLibsNew", but CMake did not find one.

  Could not find a package configuration file provided by "PythonLibsNew"
  with any of the following names:

    PythonLibsNewConfig.cmake
    pythonlibsnew-config.cmake

  Add the installation prefix of "PythonLibsNew" to CMAKE_PREFIX_PATH or set
  "PythonLibsNew_DIR" to a directory containing one of the above files.  If
  "PythonLibsNew" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "C:/Users/90652/Desktop/mitsuba2-master/CMakeFiles/CMakeOutput.log".

**Comment by GraphZou** [comment]
It seems can't find "PythonLibsNew",when i'm compiling the system.What should I do now?

**Comment by GraphZou** [comment]
It have already solved.I'm lost some dependent file.

**Comment by Hamapy** [comment]
hi, I met the same problem, how do you solve this problem?

**Comment by GraphZou** [comment]
hi,I solve it by cloning the repository again with "git&nbsp;submodule&nbsp;update&nbsp;--init&nbsp;--recursive".


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZJX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 下午5:04
收件人:&nbsp;"mitsuba-renderer/mitsuba2"<mitsuba2@noreply.github.com&gt;;
抄送:&nbsp;"Graphics"<906520989@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [mitsuba-renderer/mitsuba2] Issues in compiling the system(not providing "PythonLibsNew") (#109)





 
hi, I met the same problem, how do you solve this problem?

**Comment by foreachthing** [comment]
Thanks @GraphZou !
`git submodule update --init --recursive` helped a lot!
