### ISSUE TITLE
GUI not working?

### ISSUE THREAD

**Issue by Daichip** [mitsuba-renderer/mitsuba2#110]
Hello. I installed Mitsuba a few times, trying to change the conf files and whatnot but I cannot seem to have the GUI working. I have yet to find any statements about it not working, so I assume it should.
The issue only lies in the GUI version of Mitsuba, as I am able to render via command line (e.g.: if I type `mitsuba my_scene.xml ` I am able to render it into "my_scene.exr").
When I open the GUI the windows stays black until I click on it, in that case It starts "working": the buttons are there but they don't do anything. Also the progress bar in the bottom remains at 30% with and ETA of 0.2s.
If I try to open mtsgui from the command line I get the following error:

> GLFW error 65545: GLX: Failed to find a suitable GLXFBConfig
> Could not allocate floating point framebuffer, retrying without..

I tried to look for solutions but none of the things I tried worked. 

Everything mentioned above has been done on both Ubuntu 19.10 (Eoan Ermine) and MacOS Catalina (10.15.4). In the latter I didn't get the GLFW error notice on the shell, but the behaviour of the window was the same.

Thank you very much.

**Comment by Speierers** [comment]
Hi @Daichip,

Actually the GUI isn't suppose to work at the moment. This is on our roadmap, so keep an eye open for future release!

I might add a line to the doc saying that the GUI isn't working ATM.

Thanks!

**Comment by wjakob** [comment]
It's already mentioned in README.md and on readthedocs.
