### ISSUE TITLE
Missing foreshortening factor in BSDF plugins?

### ISSUE THREAD

**Issue by schunkes** [mitsuba-renderer/mitsuba2#113]
I am trying to write a custom BSDF plugin and I am confused by the different sources of information, Mitsuba 2 provides: 

- The documentation for the `BSDF->sample` method ([docs page](https://mitsuba2.readthedocs.io/en/latest/generated/render_api.html?highlight=bsdf#mitsuba.render.BSDF.sample)) states, that the `value` return value is multiplied by a *cosine foreshortening factor* for non delta components.

- When I look at the BSDF example guide for custom plugins written in python ([docs page](https://mitsuba2.readthedocs.io/en/latest/src/advanced_topics/custom_plugins.html)), the cosine factor is not applied. It is present as expected in the `eval` and `pdf` methods.

Can you clarify why this factor is not present?
I suspect, it is not an error in the tutorial, since the C++ implementation of the `diffuse` BSDF is exactly the same.

**Comment by merlinND** [comment]
The sampling weight returned by `sample` is `eval() / pdf()`, so the foreshortening factor cancels out.

**Comment by schunkes** [comment]
Ahh! Well that makes sense. Thank you very much!
