### ISSUE TITLE
Ideal lens

### ISSUE THREAD

**Issue by dedean16** [mitsuba-renderer/mitsuba2#119]
Hi,

What would you think would be the best way to implement an ideal lens (infinitely thin, with no aberrations) in Mitsuba? Would it be possible to implement it as a special, location dependent BTDF? If not, would you recommend a different approach?

Kind regards,
Daniël

**Comment by Speierers** [comment]
Hi @dedean16 ,

The best way to implement it would be as a sensor plugin.
For inspiration on various sensor implementations, please have a look a the Mitsuba 0.6 codebase:
https://github.com/mitsuba-renderer/mitsuba/tree/master/src/sensors

You should also have a look at:
http://www.pbr-book.org/3ed-2018/Camera_Models.html

Good luck

**Comment by dedean16** [comment]
Hi @Speierers , thanks for your response.
I'm not actually trying to implement a camera model, but a separate object that can be placed anywhere in the scene, and refracts light according to the ideal lens law 1/focal_distance = 1/object_distance + 1/image_distance. Note that no real physical lens can do this without aberrations.

**Comment by Speierers** [comment]
Some combination of BSDF and implicit shape should do the trick then 😉
