### ISSUE TITLE
Compilation fails with packet_* variants and the Embree backend

### ISSUE THREAD

**Issue by Mike-Leo-Smith** [mitsuba-renderer/mitsuba2#12]
When using packet_* variants and the Embree backend, compilation fails due to the static assertion in file "scene_embree.inl", line 25, which simply checks if `is_float_v<Float>`. However, when using the packet_* variants, the `Float` type is a `Packet<float>`.

**Comment by Mike-Leo-Smith** [comment]
A simple and dirty fix would be commenting this `static_assert` out... but using some type_traits should be a better solution.

**Comment by Speierers** [comment]
Thanks for reporting this. I will fix it.

**Comment by Speierers** [comment]
Fixed in 71cb577fffef6796796e1c5407a9df8f543d91fa
