### ISSUE TITLE
Python created Mesh doesn't support traverse()

### ISSUE THREAD

**Issue by mlamarre** [mitsuba-renderer/mitsuba2#120]
This is a marginal use case for users that would like to create & change the geometry from python without saving it to file.

For example in the test cases [test_mesh.py](../tree/master/src/librender/tests/test_mesh.py) or [mesh_generation.py](../tree/master/src/librender/tests/mesh_generation.py), it's shown that a `Mesh` can be created from Python using a `Mesh` constructor with geometry inputs. When such a mesh is added to a Scene, see for example [test_kdtrees.py](../tree/master/src/librender/tests/test_kdtrees.py#L10), running `traverse` on this scene will raise an exception.

```
mitsuba/python/util.py", line 166, in put_object
    node.traverse(cb)
AttributeError: 'NoneType' object has no attribute 'traverse'
``` 

This is caused by the geometry input Mesh constructor, which doesn't call the base class `Shape(const Properties &)` constructor, which leaves the member `m_bsdf` as a null pointer which cause `SceneTraversal` to receive a `node==None` in `put_object`. 

Summary the following ctor:
```
Mesh::Mesh(const std::string &name,
         Struct *vertex_struct, ScalarSize vertex_count,
         Struct *face_struct,   ScalarSize face_count)
```
doesn't call 

```
Shape::Shape(const Properties &)
```

This constructor usually assigns or creates the shape BSDF. Since it's not called, `m_bsdf` is an empty pointer and **traverse()** will make a **put_object** call with a `node==None`.

A quick fix would be to call `Shape::Shape(const Properties &)` with an empty **Properties** to get the default diffuse **m_bsdf**. 

However, it would be nice for users to have some way to specify a BSDF along with the geometry in the Mesh constructor.

**Comment by Speierers** [comment]
Hi @mlamarre ,

Thanks for your suggestions.

We are in the process of refactoring/ re-writting `mesh.h` and `mesh.cpp` in PR #88 . This PR will also adress the issues mentioned above. Hopefully I will be merged soon.
