### ISSUE TITLE
gpu_autodiff_*  does not build

### ISSUE THREAD

**Issue by isolin** [mitsuba-renderer/mitsuba2#126]
I was building the autodiff variants tonight and encountered the following errors (Focal Foss, CUDA 10.2, the rest is visible in the error report). The error comes in the `ninja` call.

```sh
[273/708] Building CXX object src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o
FAILED: src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o 
/usr/bin/clang++-9  -DLITTLE_ENDIAN -DMTS_BUILD_MODULE=MTS_MODULE_RENDER -DMTS_ENABLE_OPTIX=1 -DMTS_ENABLE_PROFILER -D__LINUX__ -I/usr/include/libcxxabi -I../include -I../ext/tinyformat -I../ext/enoki/include -I../ext/tbb/include -I../ext/pybind11/include -I/usr/include/python3.8 -Isrc/librender -I../ext/rgb2spec -I/home/ubuntu/NVIDIA-OptiX-SDK-6.5.0-linux64/include -flto=thin  -stdlib=libc++ -D_LIBCPP_VERSION -std=gnu++17 -fcolor-diagnostics -O3 -DNDEBUG -fPIC   -fno-stack-protector -fomit-frame-pointer -fno-math-errno -ffp-contract=fast -march=native -Wall -Wextra -Wno-unused-local-typedefs -fvisibility=hidden -Wdouble-promotion -MD -MT src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o -MF src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o.d -o src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o -c ../src/librender/scene.cpp
In file included from ../src/librender/scene.cpp:1:
In file included from ../include/mitsuba/core/properties.h:5:
In file included from ../include/mitsuba/core/spectrum.h:5:
In file included from ../ext/enoki/include/enoki/matrix.h:16:
In file included from ../ext/enoki/include/enoki/array.h:30:
In file included from ../ext/enoki/include/enoki/array_generic.h:14:
In file included from ../ext/enoki/include/enoki/array_static.h:3:
In file included from ../ext/enoki/include/enoki/array_base.h:16:
../ext/enoki/include/enoki/array_struct.h:87:35: error: no member named 'scatter' in 'enoki::struct_support<enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4>, int>'
        struct_support_t<Target>::scatter(target, value, index, mask);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~^
../ext/enoki/include/enoki/stl.h:77:16: note: in instantiation of function template specialization 'enoki::scatter<0, true, false, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4>, enoki::CUDAArray<unsigned int>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4>, enoki::CUDAArray<bool>, 0>' requested here
        enoki::scatter(dst.second, value.second, index, mask);
               ^
../ext/enoki/include/enoki/array_struct.h:87:35: note: in instantiation of function template specialization 'enoki::struct_support<std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, int>::scatter<std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::CUDAArray<unsigned int>, enoki::CUDAArray<bool> >' requested here
        struct_support_t<Target>::scatter(target, value, index, mask);
                                  ^
../ext/enoki/include/enoki/array_call.h:162:25: note: in instantiation of function template specialization 'enoki::scatter<0, true, true, std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::CUDAArray<unsigned int>, std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::CUDAArray<bool>, 0>' requested here
                        scatter<0, true, true>(result, temp, permutation);
                        ^
In file included from ../src/librender/scene.cpp:1:
In file included from ../include/mitsuba/core/properties.h:5:
In file included from ../include/mitsuba/core/spectrum.h:5:
In file included from ../ext/enoki/include/enoki/matrix.h:16:
In file included from ../ext/enoki/include/enoki/array.h:30:
In file included from ../ext/enoki/include/enoki/array_generic.h:14:
In file included from ../ext/enoki/include/enoki/array_static.h:3:
In file included from ../ext/enoki/include/enoki/array_base.h:16:
../ext/enoki/include/enoki/array_struct.h:87:35: error: no member named 'scatter' in 'enoki::struct_support<enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4>, int>'
        struct_support_t<Target>::scatter(target, value, index, mask);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~^
../ext/enoki/include/enoki/stl.h:77:16: note: in instantiation of function template specialization 'enoki::scatter<0, true, false, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4>, enoki::CUDAArray<unsigned int>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4>, enoki::CUDAArray<bool>, 0>' requested here
        enoki::scatter(dst.second, value.second, index, mask);
               ^
../ext/enoki/include/enoki/array_struct.h:87:35: note: in instantiation of function template specialization 'enoki::struct_support<std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, int>::scatter<std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::CUDAArray<unsigned int>, enoki::CUDAArray<bool> >' requested here
        struct_support_t<Target>::scatter(target, value, index, mask);
                                  ^
../ext/enoki/include/enoki/array_call.h:162:25: note: in instantiation of function template specialization 'enoki::scatter<0, true, true, std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::CUDAArray<unsigned int>, std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::CUDAArray<bool>, 0>' requested here
                        scatter<0, true, true>(result, temp, permutation);
                        ^
In file included from ../src/librender/scene.cpp:1:
In file included from ../include/mitsuba/core/properties.h:5:
In file included from ../include/mitsuba/core/spectrum.h:5:
In file included from ../ext/enoki/include/enoki/matrix.h:16:
In file included from ../ext/enoki/include/enoki/array.h:30:
In file included from ../ext/enoki/include/enoki/array_generic.h:14:
In file included from ../ext/enoki/include/enoki/array_static.h:3:
In file included from ../ext/enoki/include/enoki/array_base.h:16:
../ext/enoki/include/enoki/array_struct.h:87:35: error: no member named 'scatter' in 'enoki::struct_support<enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, int>'
        struct_support_t<Target>::scatter(target, value, index, mask);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~^
../ext/enoki/include/enoki/stl.h:77:16: note: in instantiation of function template specialization 'enoki::scatter<0, true, false, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, enoki::DiffArray<enoki::CUDAArray<bool> >, 0>' requested here
        enoki::scatter(dst.second, value.second, index, mask);
               ^
../ext/enoki/include/enoki/array_struct.h:87:35: note: in instantiation of function template specialization 'enoki::struct_support<std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, int>::scatter<std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, enoki::DiffArray<enoki::CUDAArray<bool> > >' requested here
        struct_support_t<Target>::scatter(target, value, index, mask);
                                  ^
../ext/enoki/include/enoki/array_call.h:162:25: note: in instantiation of function template specialization 'enoki::scatter<0, true, true, std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::DiffArray<enoki::CUDAArray<bool> >, 0>' requested here
                        scatter<0, true, true>(result, temp, permutation);
                        ^
In file included from ../src/librender/scene.cpp:1:
In file included from ../include/mitsuba/core/properties.h:5:
In file included from ../include/mitsuba/core/spectrum.h:5:
In file included from ../ext/enoki/include/enoki/matrix.h:16:
In file included from ../ext/enoki/include/enoki/array.h:30:
In file included from ../ext/enoki/include/enoki/array_generic.h:14:
In file included from ../ext/enoki/include/enoki/array_static.h:3:
In file included from ../ext/enoki/include/enoki/array_base.h:16:
../ext/enoki/include/enoki/array_struct.h:87:35: error: no member named 'scatter' in 'enoki::struct_support<enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4>, int>'
        struct_support_t<Target>::scatter(target, value, index, mask);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~^
../ext/enoki/include/enoki/stl.h:77:16: note: in instantiation of function template specialization 'enoki::scatter<0, true, false, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4>, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4>, enoki::DiffArray<enoki::CUDAArray<bool> >, 0>' requested here
        enoki::scatter(dst.second, value.second, index, mask);
               ^
../ext/enoki/include/enoki/array_struct.h:87:35: note: in instantiation of function template specialization 'enoki::struct_support<std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, int>::scatter<std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, enoki::DiffArray<enoki::CUDAArray<bool> > >' requested here
        struct_support_t<Target>::scatter(target, value, index, mask);
                                  ^
../ext/enoki/include/enoki/array_call.h:162:25: note: in instantiation of function template specialization 'enoki::scatter<0, true, true, std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::DiffArray<enoki::CUDAArray<bool> >, 0>' requested here
                        scatter<0, true, true>(result, temp, permutation);
                        ^
4 errors generated.

[282/708] Linking CXX shared library src/libcore/python/core_gpu_autodiff_spectral_ext.cpython-38-x86_64-linux-gnu.so
ninja: build stopped: subcommand failed.
```

## Update 
I noticed the same issue with `gpu_autodiff_rgb`.

**Comment by magicknight** [comment]
> I was building the autodiff variants tonight and encountered the following errors (Focal Foss, CUDA 10.2, the rest is visible in the error report). The error comes in the `ninja` call.
> 
> ```shell
> [273/708] Building CXX object src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o
> FAILED: src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o 
> /usr/bin/clang++-9  -DLITTLE_ENDIAN -DMTS_BUILD_MODULE=MTS_MODULE_RENDER -DMTS_ENABLE_OPTIX=1 -DMTS_ENABLE_PROFILER -D__LINUX__ -I/usr/include/libcxxabi -I../include -I../ext/tinyformat -I../ext/enoki/include -I../ext/tbb/include -I../ext/pybind11/include -I/usr/include/python3.8 -Isrc/librender -I../ext/rgb2spec -I/home/ubuntu/NVIDIA-OptiX-SDK-6.5.0-linux64/include -flto=thin  -stdlib=libc++ -D_LIBCPP_VERSION -std=gnu++17 -fcolor-diagnostics -O3 -DNDEBUG -fPIC   -fno-stack-protector -fomit-frame-pointer -fno-math-errno -ffp-contract=fast -march=native -Wall -Wextra -Wno-unused-local-typedefs -fvisibility=hidden -Wdouble-promotion -MD -MT src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o -MF src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o.d -o src/librender/CMakeFiles/mitsuba-render-obj.dir/scene.cpp.o -c ../src/librender/scene.cpp
> In file included from ../src/librender/scene.cpp:1:
> In file included from ../include/mitsuba/core/properties.h:5:
> In file included from ../include/mitsuba/core/spectrum.h:5:
> In file included from ../ext/enoki/include/enoki/matrix.h:16:
> In file included from ../ext/enoki/include/enoki/array.h:30:
> In file included from ../ext/enoki/include/enoki/array_generic.h:14:
> In file included from ../ext/enoki/include/enoki/array_static.h:3:
> In file included from ../ext/enoki/include/enoki/array_base.h:16:
> ../ext/enoki/include/enoki/array_struct.h:87:35: error: no member named 'scatter' in 'enoki::struct_support<enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4>, int>'
>         struct_support_t<Target>::scatter(target, value, index, mask);
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
> ../ext/enoki/include/enoki/stl.h:77:16: note: in instantiation of function template specialization 'enoki::scatter<0, true, false, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4>, enoki::CUDAArray<unsigned int>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4>, enoki::CUDAArray<bool>, 0>' requested here
>         enoki::scatter(dst.second, value.second, index, mask);
>                ^
> ../ext/enoki/include/enoki/array_struct.h:87:35: note: in instantiation of function template specialization 'enoki::struct_support<std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, int>::scatter<std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::CUDAArray<unsigned int>, enoki::CUDAArray<bool> >' requested here
>         struct_support_t<Target>::scatter(target, value, index, mask);
>                                   ^
> ../ext/enoki/include/enoki/array_call.h:162:25: note: in instantiation of function template specialization 'enoki::scatter<0, true, true, std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::CUDAArray<unsigned int>, std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::CUDAArray<float>, 3>, 4> >, enoki::CUDAArray<bool>, 0>' requested here
>                         scatter<0, true, true>(result, temp, permutation);
>                         ^
> In file included from ../src/librender/scene.cpp:1:
> In file included from ../include/mitsuba/core/properties.h:5:
> In file included from ../include/mitsuba/core/spectrum.h:5:
> In file included from ../ext/enoki/include/enoki/matrix.h:16:
> In file included from ../ext/enoki/include/enoki/array.h:30:
> In file included from ../ext/enoki/include/enoki/array_generic.h:14:
> In file included from ../ext/enoki/include/enoki/array_static.h:3:
> In file included from ../ext/enoki/include/enoki/array_base.h:16:
> ../ext/enoki/include/enoki/array_struct.h:87:35: error: no member named 'scatter' in 'enoki::struct_support<enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4>, int>'
>         struct_support_t<Target>::scatter(target, value, index, mask);
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
> ../ext/enoki/include/enoki/stl.h:77:16: note: in instantiation of function template specialization 'enoki::scatter<0, true, false, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4>, enoki::CUDAArray<unsigned int>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4>, enoki::CUDAArray<bool>, 0>' requested here
>         enoki::scatter(dst.second, value.second, index, mask);
>                ^
> ../ext/enoki/include/enoki/array_struct.h:87:35: note: in instantiation of function template specialization 'enoki::struct_support<std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, int>::scatter<std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::CUDAArray<unsigned int>, enoki::CUDAArray<bool> >' requested here
>         struct_support_t<Target>::scatter(target, value, index, mask);
>                                   ^
> ../ext/enoki/include/enoki/array_call.h:162:25: note: in instantiation of function template specialization 'enoki::scatter<0, true, true, std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::CUDAArray<unsigned int>, std::__1::pair<mitsuba::DirectionSample<enoki::CUDAArray<float>, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::CUDAArray<float>, 4>, 4> >, enoki::CUDAArray<bool>, 0>' requested here
>                         scatter<0, true, true>(result, temp, permutation);
>                         ^
> In file included from ../src/librender/scene.cpp:1:
> In file included from ../include/mitsuba/core/properties.h:5:
> In file included from ../include/mitsuba/core/spectrum.h:5:
> In file included from ../ext/enoki/include/enoki/matrix.h:16:
> In file included from ../ext/enoki/include/enoki/array.h:30:
> In file included from ../ext/enoki/include/enoki/array_generic.h:14:
> In file included from ../ext/enoki/include/enoki/array_static.h:3:
> In file included from ../ext/enoki/include/enoki/array_base.h:16:
> ../ext/enoki/include/enoki/array_struct.h:87:35: error: no member named 'scatter' in 'enoki::struct_support<enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, int>'
>         struct_support_t<Target>::scatter(target, value, index, mask);
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
> ../ext/enoki/include/enoki/stl.h:77:16: note: in instantiation of function template specialization 'enoki::scatter<0, true, false, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, enoki::DiffArray<enoki::CUDAArray<bool> >, 0>' requested here
>         enoki::scatter(dst.second, value.second, index, mask);
>                ^
> ../ext/enoki/include/enoki/array_struct.h:87:35: note: in instantiation of function template specialization 'enoki::struct_support<std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, int>::scatter<std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, enoki::DiffArray<enoki::CUDAArray<bool> > >' requested here
>         struct_support_t<Target>::scatter(target, value, index, mask);
>                                   ^
> ../ext/enoki/include/enoki/array_call.h:162:25: note: in instantiation of function template specialization 'enoki::scatter<0, true, true, std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::Matrix<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4> >, enoki::DiffArray<enoki::CUDAArray<bool> >, 0>' requested here
>                         scatter<0, true, true>(result, temp, permutation);
>                         ^
> In file included from ../src/librender/scene.cpp:1:
> In file included from ../include/mitsuba/core/properties.h:5:
> In file included from ../include/mitsuba/core/spectrum.h:5:
> In file included from ../ext/enoki/include/enoki/matrix.h:16:
> In file included from ../ext/enoki/include/enoki/array.h:30:
> In file included from ../ext/enoki/include/enoki/array_generic.h:14:
> In file included from ../ext/enoki/include/enoki/array_static.h:3:
> In file included from ../ext/enoki/include/enoki/array_base.h:16:
> ../ext/enoki/include/enoki/array_struct.h:87:35: error: no member named 'scatter' in 'enoki::struct_support<enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4>, int>'
>         struct_support_t<Target>::scatter(target, value, index, mask);
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
> ../ext/enoki/include/enoki/stl.h:77:16: note: in instantiation of function template specialization 'enoki::scatter<0, true, false, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4>, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4>, enoki::DiffArray<enoki::CUDAArray<bool> >, 0>' requested here
>         enoki::scatter(dst.second, value.second, index, mask);
>                ^
> ../ext/enoki/include/enoki/array_struct.h:87:35: note: in instantiation of function template specialization 'enoki::struct_support<std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, int>::scatter<std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, enoki::DiffArray<enoki::CUDAArray<bool> > >' requested here
>         struct_support_t<Target>::scatter(target, value, index, mask);
>                                   ^
> ../ext/enoki/include/enoki/array_call.h:162:25: note: in instantiation of function template specialization 'enoki::scatter<0, true, true, std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::DiffArray<enoki::CUDAArray<unsigned int> >, std::__1::pair<mitsuba::DirectionSample<enoki::DiffArray<CUDAArray<float> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<CUDAArray<float> >, 4>, 4> >, enoki::DiffArray<enoki::CUDAArray<bool> >, 0>' requested here
>                         scatter<0, true, true>(result, temp, permutation);
>                         ^
> 4 errors generated.
> 
> [282/708] Linking CXX shared library src/libcore/python/core_gpu_autodiff_spectral_ext.cpython-38-x86_64-linux-gnu.so
> ninja: build stopped: subcommand failed.
> ```
> 
> ## Update
> Probably caused by my mistake setting up the global variables.


Hi @isolin ,

I got this error too. I am building mitsuba2 on ubuntu 18.04, with clang 9.0, cmake 3.15,  ninja 1.8, and python 3.6. 
Would you please let me know how did you solved this problem? Thank you!

**Comment by HeidiHe** [comment]
I have the same error too. Could you share how you fix this?
