### ISSUE TITLE
Problems with traverse() + packet_rgb-variants +  embree (non-embree)

### ISSUE THREAD

**Issue by dnageo** [mitsuba-renderer/mitsuba2#128]
Hello, 

in the current version mitsuba (compiled with ` MTS_ENABLE_EMBREE                ON `) throws an exception

```
020-05-06 18:28:16 INFO  main  [Scene] Embree ready. (took 1ms)
Traceback (most recent call last):
  File "render_scene_traverse.py", line 25, in <module>
    print(params)
  File "~/mitsuba2/build/dist/python/mitsuba/python/util.py", line 69, in __repr__
    ('*' if is_differentiable(self[k]) else ' '), k)
  File "~/mitsuba2/build/dist/python/mitsuba/python/util.py", line 41, in __getitem__
    return self.get_property(*(self.properties[key]))
RuntimeError: [object_v.cpp:68] get_property(): unsupported type "mitsuba::Color<enoki::Packet<float, 16ul>, 3ul>"!
```
when running the following and selecting the `mitsuba.set_variant('packet_rgb')` variant

```
params = traverse(scene)
print(params)
```

[Attached, ](https://github.com/mitsuba-renderer/mitsuba2/files/4588088/render_scene_traverse.zip) you may find a minimal example for reproduction. You can place it directly in 

`/mitsuba2/docs/examples/01_render_scene/`

and try out the other variants (`scalar_rgb` and `gpu_autodiff_rgb`) work fine so far.

Thank you for your help!

Sorry for directly rendering into /tmp, normally I enjoy my results ...

**Comment by dnageo** [comment]
Hello,

I just compiled mitsuba with `MTS_ENABLE_EMBREE                OFF ` and yield a similar problem: 

```
2020-05-06 20:19:34 INFO  main  [ShapeKDTree] Building a SAH kd-tree (2256 primitives) ..
2020-05-06 20:19:34 INFO  main  [ShapeKDTree] Finished. (191 KiB of storage, took 17ms)
Traceback (most recent call last):
  File "render_scene_traverse.py", line 25, in <module>
    print(params)
  File "~/mitsuba2/build/dist/python/mitsuba/python/util.py", line 69, in __repr__
    ('*' if is_differentiable(self[k]) else ' '), k)
  File "~/mitsuba2/build/dist/python/mitsuba/python/util.py", line 41, in __getitem__
    return self.get_property(*(self.properties[key]))
RuntimeError: [object_v.cpp:68] get_property(): unsupported type "mitsuba::Color<enoki::Packet<float, 16ul>, 3ul>"!
```
So I think its not embree but packet_rgb-related.

**Comment by Speierers** [comment]
Hi @dnageo ,
Thanks for reporting this!

Originally the `traverse()` mechanism was only design for scene optimization, hence `gpu_*` variants of the renderer.

Your issue comes from the fact that the `get_property()` function only knows how to deal with `ScalarColor3f` (aka `Color<float, 3>`)  or `Color3f` (aka `Color<DynamicArray<Packet<float>>, 3>`).

For this to work, we would need to add support for the `Packet` types as well (e.g. `Color<Packet<Float>, 3>`.

This will be solved in a later release of Mitsuba 2 which will handle `Packet` types differently.

Anyway, do you really need to traverse the scene in `packet_*` mode? Looking at your script you aren't using the result of the `traverse(scene)` anywhere.

I am closing this as it is a known issue and we are working on this at the moment.

Cheers!

**Comment by dnageo** [comment]
Hi @Speierers,
 
> Originally the `traverse()` mechanism was only design for scene optimization, hence `gpu_*` variants of the renderer.

Ok, I suspected that, but as it worked for sclar_rgb too -  I thought it might be meant to run for all variants.
 
> This will be solved in a later release of Mitsuba 2 which will handle `Packet` types differently.

I didn't know that -  than this issue was superfluous. 
 
> Anyway, do you really need to traverse the scene in `packet_*` mode? Looking at your script you aren't using the result of the `traverse(scene)` anywhere.

No, I came along the issue in a more complex scene and just used the simple hello.xml as a minimal example to reproduce the issue. Its not a pressing issue for me, I just wanted to let you know.

> I am closing this as it is a known issue and we are working on this at the moment.
> 
> Cheers!

Thank you for your fast response. Keep up the good work, I like mitsuba a lot so far!
