### ISSUE TITLE
Cornell Box incorrectly rendered

### ISSUE THREAD

**Issue by gavguile** [mitsuba-renderer/mitsuba2#132]
Hello,

I'm rendering a cornell box and get the following image: 
![image](https://user-images.githubusercontent.com/3316022/81550414-79654b80-9380-11ea-8c72-19f78900566e.png)
As you see, the outer box is missing. However, If I look at the depth image the outer box is clearly present:
![image](https://user-images.githubusercontent.com/3316022/81550523-a87bbd00-9380-11ea-81a2-f4e60eac7e01.png)

I have no clue why this happens and I've attached the scene file I used to render (exported from blender)
[cornell_mitsuba2.zip](https://github.com/mitsuba-renderer/mitsuba2/files/4608964/cornell_mitsuba2.zip)

It does render correctly in Blender using Cycles and with standalone PBRT.

**Comment by Speierers** [comment]
Using the `aov` integrator, I can see that the normals of the walls are pointing outward.
```
<string name="aovs" value="nn:sh_normal, dd.y:depth"/>
```
Maybe have a look at this ;)

**Comment by gavguile** [comment]
I'll be damned. Sorry for this rookie mistake ;). I wonder why both Cycles and PBRT did not care.

Thank you very much!
