### ISSUE TITLE
Scene renders on float variants, but not on double variants

### ISSUE THREAD

**Issue by pjessesco** [mitsuba-renderer/mitsuba2#133]
Hi, I'm trying to render scenes that are able on Mitsuba1 with some fixes.

[link](https://drive.google.com/open?id=1BooxHPc7U2hNRTQIlmxP7VfK2zSvz2ue)

The above link is the living-room scene. It works well on the `scalar_rgb` variant, however, I get assertion failure if I try it on the `scalar_rgb_double` :

    /ext/enoki/include/enoki/array_avx.h:935: void enoki::StaticArrayImpl<double, 4, IsMask_, Derived_>::store_(void*) const [with bool IsMask_ = false; Derived_ = mitsuba::Vector<double, 4>]: Assertion `(uintptr_t) ptr % 32 == 0' failed.
    Aborted (core dumped)

I tracked the error on debug mode, and I found that if I comment the emitter (line 620), it works on double variant too :

    <emitter type="envmap" >
	    <transform name="toWorld" >
		    <matrix value="-4.37114e-008 0 1 0 0 1 0 0 -1 0 -4.37114e-008 0 0 0 0 1"/>
	    </transform>
	    <string name="filename" value="textures/Sky 19.exr" />
    </emitter>

I use Ubuntu 18.04, thanks.

**Comment by Speierers** [comment]
Hi @pjessesco ,

Thanks for reporting this. It should be fixed now (91a2913).
