### ISSUE TITLE
Examples from paper

### ISSUE THREAD

**Issue by dedean16** [mitsuba-renderer/mitsuba2#137]
Hi!

I was wondering whether the examples from the paper are available for download. Specifically, I'm interested in the geometrical optimization with the Georges Seurat painting from figure 1c. I'm aware that the pull request for geometrical optimization loubetg:pathreparam is not implemented yet.

Kind regards,
Daniël

**Comment by wjakob** [comment]
Hi Daniel,
in between writing the paper and shipping the Mitsuba release, we did a lot of refactoring, and these dielectric optimization examples have not been ported yet. We can share a dump of the pre-submission codebase with you, but this would be for a kind of messy version of the renderer that might be very difficult to get to run on your machine (and you'd be on your own, we unfortunately cannot provide that level of support). I would suggest to wait a bit longer if it's not very time sensitive.
Wenzel

**Comment by dedean16** [comment]
Ok. In that case I will wait for your implementation. Thank you! :)
Daniël
