### ISSUE TITLE
Packet_spectral variant makes darker images then scalar_spectral on mac

### ISSUE THREAD

**Issue by SergeyShlyaev** [mitsuba-renderer/mitsuba2#140]
### **System**
Platform: MacOS 10.15.4
Mitsuba version 2.0.0 (master[2694adf8], Mac OS, 64bit, 8 threads, 8-wide SIMD)
Enabled processor features: avx2 avx fma f16c sse4.2 x86_64

### **Problem**
Images rendered with `packet_spectral` variant are about 1 stop darker then `scalar_spectral`.
Switching to packet variant renders about 2–3 times faster but makes darker image.
Images rendered with `scalar_spectral` are matching docs images.

### **Repro Steps**

1. Compile Mitsuba with the aforementioned variants.
2. Render with `scalar_spectral`, for example `mitsuba -m scalar_spectral /docs/scenes/bsdf_roughconductor_textured_carbon.xml`
3. Render with `packet_spectral`, for example `mitsuba -m packet_spectral /docs/scenes/bsdf_roughconductor_textured_carbon.xml`
4. Compare rendered images

![bug_packet_metal](https://user-images.githubusercontent.com/63272131/82238017-98298c00-9904-11ea-92cc-81f1e89c7b18.jpg)

![bug_packet_cornell](https://user-images.githubusercontent.com/63272131/82238350-2140c300-9905-11ea-8583-f448df452a5f.jpg)

**Comment by SergeyShlyaev** [comment]
### Update

It affects alpha channel as well.
Enabling alpha via `<string name="pixel_format" value="rgba"/>`
and comparing alpha channels shows that in `packet_spectral`  alpha is 0.5 where in `scalar_spectral` it is 1.0 (correct value)

**Comment by Speierers** [comment]
This is the same bug as #14 . We are working on it. I am going to close this issue as it is a duplicate.
