### ISSUE TITLE
Double variants still not correct

### ISSUE THREAD

**Issue by tatue64** [mitsuba-renderer/mitsuba2#141]
Today an issue concerning the double variants was closed. 

> With latest master the scalar_mono_double now compiled and renders on my machine. This was probably related to some bugs that have been fix since the opening of this issue. Therefore I will close this. Please let us know if this is still an issue on your side.

I can confirm that the code now compiles and mitsuba renders, but the result is nonsensical.  The result of rendering "matpreview" from the "mitsuba-data" repository is a circular pattern (see attachment). This holds for several variants that I have tested, for instance "packet_rgb_double".

I am on manjaro-linux and compiled the latest version with clang.  

![matpreview](https://user-images.githubusercontent.com/36105081/82339244-1dd53680-99ee-11ea-9287-e7998153b26f.png)

**Comment by Speierers** [comment]
Fixed here: 2e9ac603

I will add some more tests for the `*_double` variants to make sure we don't break it in the future.
