### ISSUE TITLE
Documentation needed: Texture "Mesh Attribute"

### ISSUE THREAD

**Issue by oligami** [mitsuba-renderer/mitsuba2#146]
I can't understand how to use mesh_attribute textures and how to make a colorful bunny like the image in the section of mesh_attribute.
Also, the document says the character string that specifies the type of texture is mesh attribute is  "meshattribute", but the actual character string is "mesh_attribute". The document should be corrected.

**Comment by Speierers** [comment]
Here is a simple python script to add random face and vertex colors to an existing mesh:
```python
import numpy as np
from mitsuba.core import xml
m = xml.load_dict({
    "type" : "ply",
    "filename" : "bunny.ply"
})

m.add_attribute("face_color", 3)[:] = np.random.rand(3 * m.face_count())
m.add_attribute("vertex_color", 3)[:] = np.random.rand(3 * m.vertex_count())
m.write_ply("bunny_attribute_color.ply")
```

Then your XML scene description should look like this:
```xml
<scene version="2.0.0">
    <bsdf type="diffuse" id="object_bsdf">
        <texture type="mesh_attribute" name="reflectance">
            <string name="name" value="vertex_color"/>
        </texture>
    </bsdf>

    <shape type="ply">
        <string name="filename" value="meshes/bunny_attribute_color.ply"/>
        <ref id="object_bsdf"/>
    </shape>
    ...
</scene>
```

Note that this works well for ` *_rgb` modes. For `*_spectral`  modes you will need to convert the RGB values with `srgb_model_fetch()` before storing those on the mesh.

I hope this helps!

Also, I will fix the type in the doc, thanks for that!

**Comment by oligami** [comment]
Thank you for the guide. I'll try it!
