### ISSUE TITLE
Recommendations for changing the CMFS.

### ISSUE THREAD

**Issue by KelSolaar** [mitsuba-renderer/mitsuba2#15]
Hi,

This is not really an issue but more seeking advice on what would be the best approach for changing the  CMFS. If there is a better place to discuss this, e.g. mailing list or email thread please let me know!

I would like to change the CMFS for a different set of functions, i.e. camera sensitivities, and I wanted to know if you had any recommendations on how to do that gracefully and en-mass. After a quick peek at the code it does not seem like there is a way to do that without recompiling the whole engine but maybe I missed something.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Another related question is: Recommendations on how to output spectral-images? :)

**Comment by wjakob** [comment]
Discussing here is fine. But what is a "CMFS"? :-)

**Comment by KelSolaar** [comment]
Hi @wjakob,

First congratulations are in order, and I should have started there! Quite an awesome release, I'm super excited :)

CMFS stands for Colour Matching Functions, I would like to replace the CIE 1931 2 Degree Standard Observer data with cameras sensitivities.

I'm part of an [Academy working group trying to come up with a gamut mapping algorithm for scene-referred data](https://acescentral.com/t/new-aces-working-group-gamut-mapping/2454), and I would like to generate spectral imagery from multiple camera models.

I have been using existing hyper-spectral images and integrated them with narrow-band LEDs and various camera sensitivities here: https://academy-vwg-gm-hyper-spectral-images.imfast.io/  The problem with that approach (even though it generates offending data as we require) is that it does it too well, the entire image is affected! I would like to generate synthetic data in Mitsuba with mixed lighting and that is where the different sensitivities come to play.

Hope it makes sense!

Cheers,

Thomas

**Comment by wjakob** [comment]
Hi @KelSolaar,

that makes sense. As a quick-and-dirty solution, you could simply replace the CIE XYZ tables in `src/libcore/spectrum.cpp` by something else. A cleaner solution, and a technique for outputting arbitrary number of spetral channels should not be too hard by implementing a new meta-integrator that calls a nested "sub-integrator". This is already done in `aov.cpp` and and would just need some small changes to integrate against different spectral response functions.

Best,
Wenzel

**Comment by KelSolaar** [comment]
> As a quick-and-dirty solution, you could simply replace the CIE XYZ tables in src/libcore/spectrum.cpp by something else.

Yeah that is what I have been doing for now. I reckon it would be 2 new useful features!

**Comment by KelSolaar** [comment]
First light test:

![image](https://user-images.githubusercontent.com/99779/76129351-1a2b4800-606c-11ea-9604-73c0c625036f.png)

The Google Colab notebook to generate the sensitivities data is here: https://colab.research.google.com/drive/18X8ICpZ6MZmWxOzXNpUF0ehb_emfUOf-

It makes me wonder if you have a build of the renderer (or recipe) that works on the Colab VMs? That could be useful! If not I will work on one when I have some spare cycles.

Note that I have an almost exactly 1 stop energy loss between the CMFS and the camera sensitivities that I need to investigate but it reminds me #14. The issue is most likely between the chair and the screen.

**Comment by Speierers** [comment]
> It makes me wonder if you have a build of the renderer (or recipe) that works on the Colab VMs? 
Not really. It would be great to have!

I am going to close this as this is not really an issue.
