### ISSUE TITLE
How to input images using the Bitmap class

### ISSUE THREAD

**Issue by udemegane** [mitsuba-renderer/mitsuba2#150]
First of all, I need to tell you that I am a beginner in programming.

In my differentiable rendering experiment, I want to input the reference image externally, without having to render it in Mitsuba2 as in the sample code.
I understood from the sample code that when calculating the loss in differentiable rendering, the image is calculated with type enoki.cuda_autdiff.Float32.
`ob_val = ek.hsum(ek.sqr(image - image_ref)) / len(image)　`
`print(type(image)) :<class 'enoki.cuda_autodiff.Float32'> `
`ek.backward(ob_val)`

The externally imported reference image is a .png or .jpg, so I read the core API reference and tried to convert this using the Bitmap class, but failed.

wrong code:
`myimage_ref = np.array(Bitmap('path/to/myimage.png', Bitmap.FileFormat.PNG).convert(Bitmap.PixelFormat.RGB, Struct.Type.Float32, srgb_gamma=True))`
`myimage_ref = myimage_ref.reshape(myimage_ref.size)`

I would like to be taught the correct way to use it.
Thank you.

**Comment by Speierers** [comment]
Hi @udemegane ,

Maybe could you try something like this?
```python
mybitmap = Bitmap('path/to/myimage.png').convert(Bitmap.PixelFormat.RGB, Struct.Type.Float32, srgb_gamma=True)
myimage_ref =np.array(mybitmap).flatten()
```

**Comment by udemegane** [comment]
@Speierers Thank you for your reply.
Unfortunately, it hasn't been successful yet.
Below is my entire code, the log, and the output image.
invert_mycbox.py is almost the same as the sample code invert_cbox.py The only difference between them is whether the program generates the image_ref on its own or loads it from somewhere else.
The image to be loaded is rendered by the sample code render_scene.py.

invert_mycbox.py
``` invert_mycbox.py

import enoki as ek
import mitsuba
mitsuba.set_variant('gpu_autodiff_rgb')

from mitsuba.core import Thread, Color3f
from mitsuba.core.xml import load_file
from mitsuba.core import Bitmap, Struct
from mitsuba.python.util import traverse
from mitsuba.python.autodiff import render, write_bitmap, Adam
import time
import numpy as np

# Load the Cornell Box
Thread.thread().file_resolver().append('cbox')
scene = load_file('cbox/cbox.xml')

# Find differentiable scene parameters
params = traverse(scene)

# Discard all parameters except for one we want to differentiate
params.keep(['red.reflectance.value'])

# Print the current value and keep a backup copy
param_ref = Color3f(params['red.reflectance.value'])
print(param_ref)

# Load a reference image 
bitmap_tmp = Bitmap('/home/usrname/mitsuba2/docs/example/01_render_scene/out.png', Bitmap.FileFormat.PNG).convert(Bitmap.PixelFormat.RGB, Struct.Type.Float32, srgb_gamma=True)
image_ref = np.array(bitmap_tmp).flatten()
crop_size = scene.sensors()[0].film().crop_size()

# Change the left wall into a bright white surface
params['red.reflectance.value'] = [.9, .9, .9]
params.update()

# Construct an Adam optimizer that will adjust the parameters 'params'
opt = Adam(params, lr=.05)

time_a = time.time()

iterations = 100
for it in range(iterations):
    # Perform a differentiable rendering of the scene

    image = render(scene, optimizer=opt, unbiased=True, spp=1)
    write_bitmap('out_mycbox/out_%03i.png' % it, image, crop_size)

    # Objective: MSE between 'image' and 'image_ref'
    ob_val = ek.hsum(ek.sqr(image - image_ref)) / len(image)

    # Back-propagate errors to input parameters
    ek.backward(ob_val)

    # Optimizer: take a gradient step
    opt.step()

    # Compare iterate against ground-truth value
    err_ref = ek.hsum(ek.sqr(param_ref - params['red.reflectance.value']))
    print('Iteration %03i: error=%g' % (it, err_ref[0]), end='\r')

time_b = time.time()

print()
print('%f ms per iteration' % (((time_b - time_a) * 1000) / iterations))

```

out.png: Images to be loaded by the program (rendered by render_scene.py)
![out](https://user-images.githubusercontent.com/49067142/82871615-d4946200-9f6c-11ea-8fed-5a8d7f12dcac.png)

Program runtime log: As you can see, the error values are not converging.
```
2020-05-26 16:22:30 INFO  main  [xml.cpp:1117] Loading XML file "cbox/cbox.xml" ..
2020-05-26 16:22:30 INFO  main  [xml.cpp:1118] Using variant "gpu_autodiff_rgb"
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/regular.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/srgb.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/srgb_d65.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/path.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/independent.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/gaussian.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/hdrfilm.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/perspective.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/diffuse.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/area.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/uniform.so" ..
2020-05-26 16:22:30 INFO  main  [PluginManager] Loading plugin "plugins/obj.so" ..
2020-05-26 16:22:30 INFO  main  [Scene] Validating and building scene in OptiX.
[[0.569717, 0.0430141, 0.0443234]]
Iteration 099: error=1.37477
117.748876 ms per iteration

Process finished with exit code 0

```

out_099.png:The output image is poorly optimized.
![out_099](https://user-images.githubusercontent.com/49067142/82871890-32c14500-9f6d-11ea-949c-c5f5deaf03d5.png)

Then, when I printed the value of ob_val, invert_mycbox printed an extremely large value [0.98425].
The loaded image_ref certainly seems to be a flat value with 196608 elements, but the only thing that seems accurate is its shape.

**Comment by Speierers** [comment]
In your case, the reference image isn't in the same color space as the rendered image, therefore it isn't really correct to compare the two like this. You need to make sure that the values used when computing the loss are using the same "units" and space.

A first step towards that in your case would be to turn off the `srgb_gamma` when importing the reference image from the file.

I will leave the rest for you ;)

**Comment by udemegane** [comment]
I was able to understand what was going on with this issue.The rest is my problem, so I will close this place. Thank you!

**Comment by ShreyanshDarshan** [comment]
> ```python
> mybitmap = Bitmap('path/to/myimage.png').convert(Bitmap.PixelFormat.RGB, Struct.Type.Float32, srgb_gamma=True)
> myimage_ref =np.array(mybitmap).flatten()
> ```

One might want to convert this further into
```python
import enoki
myimage_ref_enoki = enoki.cuda_autodiff.Float32(myimage_ref)
```
