### ISSUE TITLE
scalar_rgb_polarized Import Error

### ISSUE THREAD

**Issue by matthewpurri** [mitsuba-renderer/mitsuba2#158]
I am able to successfully compile the library with the "scalar_rgb_polarized" variant enabled in the configuration file but I am not able to set the variant to this setting. 

```
import os
import mitsuba

mitsuba.set_variant('scalar_rgb_polarized')
```
Results in the following error:
`ImportError: pybind11_type_alias(): source type not found!`

I've tried to use this variant on both Mac and Ubuntu operating systems but receive the same error without compilation errors.

Mac OS: 10.15.5
Ubuntu: 18.04

Any help would be appreciated, thanks ahead of time!

**Comment by Speierers** [comment]
Hi @matthewpurri ,

Do you mean `scalar_spectral_polarized`?

If you added a custom variant `scalar_rgb_polarized`, what is the type of `Spectrum` you defined in your `mitsuba.conf`?

**Comment by tizian** [comment]
Hi @matthewpurri ,

Polarization support in Mitsuba 2 was designed to work on top of spectral (and monochromatic) rendering and this variant you mentioned was thus never tested by us.
If you have a really specific use case where you actually need to combine accurate polarized light simulation with a non-physical color representation there might be a few things that need to be adjusted. For instance, there is currently no internal type for the right dimension of Mueller matrices in that case (4x4x3).

- Tizian

**Comment by matthewpurri** [comment]
Thanks for the quick responses!

@Speierers I actually have `scalar_rgb_polarized` in my `mitsuba.conf` file.

@tizian Ahhh okay, I must have missed that in the docs. No, I was just trying to run some relatively simple experiments with polarized light and the non-spectral RGB optioned seemed like the simplest case.  I started using `scalar_spectral_polarized` and haven't run into this problem again.

Thanks for the awesome library:)
