### ISSUE TITLE
polarized gpu variants fail to build

### ISSUE THREAD

**Issue by nmatsuda** [mitsuba-renderer/mitsuba2#159]
Not sure if this is an issue in the Enoki repo or here, will move this issue if that's the case.

When building with any gpu polarization variant, clang throws a bunch of errors such as:

```
../include/mitsuba/core/traits.h:67:82: error: no type named 'Scalar' in 'mitsuba::detail::spectrum_traits<enoki::Array<enoki::Array<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, 4> >'
    using Scalar       = enoki::detail::MaskedArray<typename spectrum_traits<T>::Scalar>;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from ../include/mitsuba/core/math.h:5:
../include/mitsuba/core/traits.h:68:82: error: no type named 'Wavelength' in 'mitsuba::detail::spectrum_traits<enoki::Array<enoki::Array<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, 4> >'
    using Wavelength   = enoki::detail::MaskedArray<typename spectrum_traits<T>::Wavelength>;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
../include/mitsuba/core/traits.h:69:82: error: no type named 'Unpolarized' in 'mitsuba::detail::spectrum_traits<enoki::Array<enoki::Array<mitsuba::Color<enoki::DiffArray<CUDAArray<float> >, 3>, 4>, 4> >'
    using Unpolarized  = enoki::detail::MaskedArray<typename spectrum_traits<T>::Unpolarized>;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
../src/integrators/volpath.cpp:182:17: error: no matching function for call to 'masked'
                masked(si, intersect) = scene->ray_intersect(ray, intersect);
                ^~~~~~
```
and so on. All other variants build and run.

**Comment by dvicini** [comment]
Hi,

We haven't tested polarization on the GPU. This is something which is expected to fail currently. It is on our radar and will be fixed eventually, but we are focusing on other things right now. If you have fixes, please feel free to make a pull request. FYI, there will also be a pretty significant Enoki update soon, so might be worth waiting for that unless you need this working right now.

Delio

**Comment by nmatsuda** [comment]
Ok, will close the issue and keep an eye out for updates.

**Comment by Yingyan-Xu** [comment]
Hi @dvicini , do you have any update regarding this issue? I'm working on a inverse rendering project and I would like to try the polarized feature in Mitsuba 2.

**Comment by Speierers** [comment]
Hi @Yingyan-Xu ,

Unfortunately the current version of Mitsuba 2 doesn't support polarization on the GPU. As @dvicini said already, this is on our radar and will be fixed eventually. It should be fixed in the upcoming update of Mitsuba 2 / enoki.
