### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [mitsuba-renderer/mitsuba2#16]
I would like to point out that identifiers like “[`__classes`](https://github.com/mitsuba-renderer/mitsuba2/blob/dbcecba782a228fcda134558f9ae57fa91033967/src/libcore/class.cpp#L16 "Update candidate")” and “[`__EXPAND`](https://github.com/mitsuba-renderer/mitsuba2/blob/dbcecba782a228fcda134558f9ae57fa91033967/include/mitsuba/python/docstr.h#L6 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wjakob** [comment]
@elfring -- I'd rather not have these bug-reports for superficial syntax tweaks when there are so many more important things to work on.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by wjakob** [comment]
(banned @elfring, who appears to be a bot.)
