### ISSUE TITLE
Infrared renders

### ISSUE THREAD

**Issue by SergeyShlyaev** [mitsuba-renderer/mitsuba2#161]
Hello,

Not an issue, more of a question. Can mitsuba be used to produce infrared images?
Which are in range from 700nm to 3400nm.

Will it be enough to recompile with MTS_WAVELENGTH_MIN and MTS_WAVELENGTH_MAX redefined to the above values?
What data should be put instead of cie1931_tbl in spectrum.cpp which contain sensitivities for visible spectrum?

Thank you.

![cat](https://user-images.githubusercontent.com/63272131/83356266-09b8ff80-a333-11ea-940c-b6f72de9d0f9.jpg)

**Comment by wjakob** [comment]
see #142, that's basically what you want :). Note that Mitsuba solves the radiative transfer equation and does not account for thermal aspects that are important for mid IR (i.e. everything becomes a light source, thermal conduction happens within objects, etc.).
