### ISSUE TITLE
Building error: array_avx.h error: always_inline function '_pext_u32' requires 'bmi2',  compiled without support for 'bmi2'

### ISSUE THREAD

**Issue by NelisW** [mitsuba-renderer/mitsuba2#163]
Trying to build Mitsuba on behalf of someone else. I am not very strong in Linux, no experience with Clang.

Updated with alias.pullall as per docs. 
mitsuba2$ git rev-parse HEAD: 621c9695532ef3e801b171274db32b5b9fcabe67
ext/enoki$ git rev-parse HEAD: c90632be15310d06950e50af87eed2ada6e4e71d
Ubuntu 20.04, amd64 clang-9 amd64 1:9.0.1-12
mitsuba.conf:  "scalar_rgb", "scalar_spectral"

Followed all the instructions in the docs.

Building error as follows:

(base) nwillers@nwillers-VirtualBox:~/mitsuba2/build$ ninja
[5/623] Building CXX object ext_build/enoki/CMakeFiles/enoki-python-dynamic.dir/src/python/dynamic_0d.cpp.o
FAILED: ext_build/enoki/CMakeFiles/enoki-python-dynamic.dir/src/python/dynamic_0d.cpp.o 
/usr/bin/clang++-9  -DENOKI_BUILD=1 -Denoki_python_dynamic_EXPORTS -I/usr/include/libcxxabi -I../ext/enoki/include -I../ext/pybind11/include -I/usr/include/python3.8 -stdlib=libc++ -D_LIBCPP_VERSION -std=c++17 -O3 -DNDEBUG -fPIC -fvisibility=hidden   -march=native -fno-stack-protector -fomit-frame-pointer -fno-math-errno -ffp-contract=fast -flto=thin -g0 -Os -std=gnu++17 -MD -MT ext_build/enoki/CMakeFiles/enoki-python-dynamic.dir/src/python/dynamic_0d.cpp.o -MF ext_build/enoki/CMakeFiles/enoki-python-dynamic.dir/src/python/dynamic_0d.cpp.o.d -o ext_build/enoki/CMakeFiles/enoki-python-dynamic.dir/src/python/dynamic_0d.cpp.o -c ../ext/enoki/src/python/dynamic_0d.cpp
In file included from ../ext/enoki/src/python/dynamic_0d.cpp:1:
In file included from ../ext/enoki/src/python/common.h:9:
In file included from ../ext/enoki/include/enoki/dynamic.h:16:
In file included from ../ext/enoki/include/enoki/array.h:30:
../ext/enoki/include/enoki/array_generic.h:499:50: error: always_inline function '_pdep_u64' requires target feature 'bmi2', but would be inlined into function 'assign_' that is compiled without support for 'bmi2'
                    uint64_t result = (uint64_t) _pdep_u64(k, 0x0101010101010101ull);
                                                 ^
In file included from ../ext/enoki/src/python/dynamic_0d.cpp:1:
In file included from ../ext/enoki/src/python/common.h:9:
In file included from ../ext/enoki/include/enoki/dynamic.h:16:
In file included from ../ext/enoki/include/enoki/array.h:51:
../ext/enoki/include/enoki/array_avx2.h:536:39: error: always_inline function '_pext_u32' requires target feature 'bmi2', but would be inlined into function 'compress_' that is compiled without support for 'bmi2'
            uint32_t wanted_indices = _pext_u32(0x76543210, k);
                                      ^
etc.......
Many more of the same error.

Thanks!

**Comment by wjakob** [comment]
Fascinating -- could you post the contents of `/proc/cpuinfo` for one of the processors?

**Comment by wjakob** [comment]
Ah, never mind -- VirtualBox. That's the reason. You have to compile on real hardware.

**Comment by NelisW** [comment]
yes, virtual box, thanks!

**Comment by NelisW** [comment]
As per https://mitsuba2.readthedocs.io/en/latest/src/getting_started/faq.html    
I added this to the cmakelist.txt file and all compiled perfectly (no error and no warning) in virtualbox **but not vectorized optimized**.

    add_definitions(-DENOKI_DISABLE_VECTORIZATION=1)

setup:  

    Windows 7
    virtualbox 6.1.8
    mitsuba2$ git rev-parse HEAD: 621c969
    ext/enoki$ git rev-parse HEAD: c90632be15310d06950e50af87eed2ada6e4e71d
    Ubuntu 20.04, 
    amd64 clang-9 amd64 1:9.0.1-12
    mitsuba.conf: "scalar_rgb", "scalar_spectral"
