### ISSUE TITLE
Is there any way to load an .MTL along with .OBJ file

### ISSUE THREAD

**Issue by woolpeeker** [mitsuba-renderer/mitsuba2#167]
I'm using mitsuba2.
It's easy to load a obj file to scene by inserting a obj in the .xml file
But the obj file I'm using has a mtl file. I don't find any informatin about how to load a mtl

Thanks in advance.

**Comment by Speierers** [comment]
Hi @woolpeeker ,

The `MTL` file format isn't currently supported by Mitsuba. If you would like to give this a try and open a PR, I would be happy to review it!

I will close this as it is not an issue.
