### ISSUE TITLE
Mitsuba 2.1 for Blender 2.82a/2.90 [Windows 7 x64bit]

### ISSUE THREAD

**Issue by odil24** [mitsuba-renderer/mitsuba2#168]
hi there. can somebody make win7 x64 build for blender 2.82a/2.90?

here my mail:
odilkhanyakubov@gmail.com

thanks

**Comment by Speierers** [comment]
Hi @odil24 ,

Please refer to the documentation for instructions regarding building Mitsuba 2 on Windows.

I will close this as it is not an issue.
