### ISSUE TITLE
Heightmap intersection from 0.6 in v2

### ISSUE THREAD

**Issue by mirlip** [mitsuba-renderer/mitsuba2#169]
Hello,
first of all, Mitsuba 2 looks very promising. I'm truly impressed by your work.
Will heightmap also work in the version 2 of Mitsuba or will we have to switch back to 0.6 when this feature is needed? Adaptive subdivision like in Cycles is really bad memory wise and actually barely usable. Mitsuba 0.6 was really great for that with a few 100 MBs used for huge terrains. It would be awesome to have it in v2 too!

**Comment by Speierers** [comment]
Hi @mirlip ,

The heightmap plugin hasn't yet been ported from Mitsuba 0.6. If you would like to give it a try and open a PR, I will be happy to review it!

I will close this as it is not an issue.

Cheers!
