### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [mitsuba-renderer/mitsuba2#17]
[An extra null pointer check is not needed in a function](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like [the destructor for the class “ImageBlock”](https://github.com/mitsuba-renderer/mitsuba2/blob/3df7a05d01d1eefaa74ab27f8ce6e95e9ade2ff1/src/librender/imageblock.cpp#L26 "Update candidate").

**Comment by wjakob** [comment]
Yes, that is a valid point, and you could probably auto-generate hundreds of tickets of this flavor throughout the codebase. I don't want to have to deal with them!
