### ISSUE TITLE
Optix API error = 7200 (Invalid PTX input)

### ISSUE THREAD

**Issue by errissa** [mitsuba-renderer/mitsuba2#178]
When I tried to use gpu_rgb I got the following error:

`rt_check(): OptiX API error = 7200 (Invalid PTX input) in ../src/librender/scene_optix.inl:117.
	Log:`

The Optix log is empty. This first happened on my laptop with an Nivida 980m. It also happened on my desktop with a 980. Both systems have Ubuntu 18.04 with Nvidia's 440.59 drivers and CUDA 10.2.

I tested on a system with a V100 and the gpu_rgb mode worked.

I realize that RTX is not supported on the Maxwell parts but Optix 7 does support them. Is it expected that the gpu modes will not work on gpus that don't support RTX?

**Comment by Speierers** [comment]
Could it be that this GPU doesn't have the right cuda compute capability? Maybe you could try to update the driver?

**Comment by errissa** [comment]
The CUDA capability of the 980m is 5.2. What is the minimum requirement for Mitsuba2?

When I get a chance next week I will try the latest stable and beta drivers. Though I will note that the system with the V100 on which gpu_rgb worked has the same driver as my laptop and GTX980 desktop where I saw the error.

**Comment by merlinND** [comment]
You could try updating the hardcoded capability in this Makefile, and then running `make` in the `resources/ptx` directory:
https://github.com/mitsuba-renderer/mitsuba2/blob/a9a0b0403f8defd633432556a3e3fc30af5a229c/resources/ptx/Makefile#L10

**Comment by errissa** [comment]
Thanks @merlinND. Your suggestion worked. Manually recompiling optix_rt.cu with compute_52 generated a PTX that runs on my two older systems. The default for ENOKI_CUDA_COMPUTE_CAPABILITY is 50 so it wasn't necessary to modify it.

**Comment by arpit15** [comment]
@merlinND I am facing the same error. I tried the suggestion mentioned in the thread. However, I am still facing the error. 
## system configs
Ubuntu 18.04
Nvidia Quadro P1000
Compute capability 6.1
CUDA 10.2
Nvidia driver 440.33.01

**Comment by merlinND** [comment]
Strange, that's definitely a configuration that should work. Could you try the following just to make sure the change in compute capability was taken into account?

0. Get the latest master.
1. Set `ENOKI_CUDA_COMPUTE_CAPABILITY` to `61` in CMake options
2. Set the same compute capability in `resources/ptx/Makefile`
3. `cd resources/ptx/Makefile; rm optix_rt.ptx; make`
4. `cd build; cmake ..`
5. Build

**Comment by arpit15** [comment]
I have commit `e5464812f7cb14a835c7e38daf311711044c3178`. I used ninja and kept the rest of your instructions the same. I still get the same bug. I am building a debug version and will post if it has any different characteristics.
clang version 9.0.0

**Comment by errissa** [comment]
@arpit15 You can check the optix_rt.ptx file and make sure you see `.target sm_61`near the top of the file to confirm that it's properly recompiled.

**Comment by arpit15** [comment]
@errissa yes I see that line. 
```
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-27506705
// Cuda compilation tools, release 10.2, V10.2.89
// Based on LLVM 3.4svn
//

.version 6.5
.target sm_61
.address_size 64
```
Though, I still see the error. I will revert to the commit which works for me. Though, I will have to find that commit first.

**Comment by merlinND** [comment]
@arpit15 (If you've never used it), `git bisect` is great for this kind of situation. Just don't forget to checkout the sub modules as well every time you try a new commit.

**Comment by arpit15** [comment]
@merlinND I know about `git bisect` but have never used. If there a way to test `optix_rt.ptx` without recompiling `mitsuba2`. Currently, I compile the whole mitsuba2(which takes substantial time) and then run example `render_scene.py` with `hello.xml` scene.

**Comment by arpit15** [comment]
It turns out `ptx` was finding my Optix-6.5 headers by default and thus was allowing to rebuild without any problems. After I included the correct headers for Optix7.0 everything seems to work fine. Maybe I missed the setup step in Mitsuba for Optix-7.0 after the update.

**Comment by magicknight** [comment]
I got the same error on P100, but no error on V100 with the same build
