### ISSUE TITLE
Could you tell me how to make the binary data (Tensor File) used for Measured.cpp?

### ISSUE THREAD

**Issue by t-ky** [mitsuba-renderer/mitsuba2#179]
Hello. This is not a problem, but a question.
I want to render a metal using the measured normal distribution function (ndarray).
I'm thinking of using Mitsuba2's measured.cpp as a method.
However, I don't know how to make binary data (Tensor File) for input. I think the format of this binary data is similar to Numpy(.npy) and Matlab(.mat).
Would you please tell me if there is any good way?
Thank you.

**Comment by Speierers** [comment]
Hi @t-ky ,

For this you will need to implement your own tool following the data format description in the paper.

https://rgl.epfl.ch/publications/Dupuy2018Adaptive

Take a look at the `MemoryMappedFile(filename, array)` constructor in the python API to generate a binary file.

**Comment by t-ky** [comment]
Thank you for your reply.
Successfully I have created my own tool to make the binary data.
Thank you for your help.

**Comment by standardisedfitting** [comment]
Hi @t-ky,

I am also trying to input my own data through the measured.cpp plugin.
Would it be possible for you to share your tool?
I would apprechiate any help.

**Comment by t-ky** [comment]
Hi @standardisedfitting 
Thank you for contacting me.

Here's the code.
https://github.com/omilab-naist/Mitsuba2_measured_mat

You may find save_tensor.py useful.
make_measured_data.py is the code that creates the data to be input.
For my convenience, I haven't completed the code to input.
I am able to render the xml code.
However, I haven't been able to fully validate the values of each parameter that I am entering.
Thank you.

**Comment by standardisedfitting** [comment]
@t-ky, this is great! Thank you very much for replying so fast.

**Comment by t-ky** [comment]
Hi @standardisedfitting 
I hope my code has been helpful since then. 
If you have a code that works, I would appreciate it if you could share it with me. 
Thank you.

**Comment by standardisedfitting** [comment]
Hi @t-ky ,
yes I was planing to send you a message once I finish.
So far I haven't had much time to look at it, so not everything works yet.
I will probably have more time next month to try and fix it.
I hope that works for you. If you prefer I am also happy to upload the code that I have so far.

**Comment by t-ky** [comment]
Hi @standardisedfitting
I am very happy to receive your message.
My implementation is a bit stagnant, but if it works, I'll share it with you.
Thank you for your help.

**Comment by standardisedfitting** [comment]
Hi @t-ky ,

sorry for the delay. I finally found some time to look over my implementations.
I'm not quite sure if this similar to what you are intending to do, but I am trying to measure retro-reflections to create a micro-facet model and ultimately a BRDF for some materials.

Under https://github.com/standardisedfitting/brdf-fitting you can find the code wrote so far to fit my measurements to the format from the paper that @Speierers referred to. Although, it is not complete yet and I still have a small error in the NDF computation that I have not found yet.
I hope it can still be helpful to you. Please feel free to let me know in case you find any mistakes or have anything to add.

Maybe also this repository and the thesis could interest you https://github.com/jdupuy/dj_brdf.
The aim is to fit BRDFs to micro-facet models such as Beckmann, but the theory is explained in more detail.

**Comment by t-ky** [comment]
Hi @standardisedfitting
Thank you for the message of sharing your wonderful code.
My research is aimed at BRDF estimation of metals. 
In addition, my laboratory also performs BRDF measurements on historical artifacts. 
So we are very grateful for your sharing of the code.
I will share additional code for BRDF measurements when it is available.
Thank you.

**Comment by fitzzc** [comment]
Hi @t-ky @standardisedfitting 
I am also trying to make the binary data now. 
However, sadly, the link @t-ky provided isn't active now.
I would appreciate it if you could give me some guidance about how to make my own binary data.
Thank you in advance!




> Hi @standardisedfitting Thank you for contacting me.
> 
> Here's the code. https://github.com/omilab-naist/Mitsuba2_measured_mat
> 
> You may find save_tensor.py useful. make_measured_data.py is the code that creates the data to be input. For my convenience, I haven't completed the code to input. I am able to render the xml code. However, I haven't been able to fully validate the values of each parameter that I am entering. Thank you.

**Comment by scalingsolution** [comment]
Hi @fitzzc,

its been quite a while ago and I couldn't completely reproduce results from the database, but If you want to have a look at my code your welcome, it's public. Just be aware that there some test failed when it comes to determine the luminance maps.
