### ISSUE TITLE
Ambient lighting/occlusion available in Mitsuba2?

### ISSUE THREAD

**Issue by t-taniai** [mitsuba-renderer/mitsuba2#180]
Thank you very much for a great software!

I am currently looking for a way to use ambient lighting in Mitsuba2. It seems that the fist version of Mitsuba has this feature as `ambient occlusion`, but I could not find such a feature in Mitsuba2. Could anyone know how to use ambient lighting/occlusion in Mitsuba2?

Thanks

**Comment by Speierers** [comment]
Hi @t-taniai ,

I believe this is implemented as a custom integrator plugin in Mitsuba 1. It hasn't yet been ported to Mitsuba 2. This isn't on our roadmap at the moment, although if you want to give this a try, please open a PR and I will be happy to help you with this.
