### ISSUE TITLE
Geometric differentiation cannot optimize vertex positions at all.

### ISSUE THREAD

**Issue by udemegane** [mitsuba-renderer/mitsuba2#182]
I'm not an English native, so I first apologize for the unnatural English.
I am using the "pathreparam" plugin (OptiX6.5) to test geometric differentiation. It transforms the base sphere object into another body.
However, it exhibits very unnatural behaviour. 
The following is a video that attempts to transform a sphere into an ear.
![sphere2ear](https://user-images.githubusercontent.com/49067142/84799401-30677d80-b037-11ea-8b79-2c209d69b3a3.gif)

![out_000](https://user-images.githubusercontent.com/49067142/84800013-1c704b80-b038-11ea-8457-7d3b5a4c145e.png)
 - base object(sphere)

![Screenshot_20200617_011827](https://user-images.githubusercontent.com/49067142/84800254-80930f80-b038-11ea-946e-2ba3cc3290f3.png)
 - ref object(ear)

I've tried multiple approaches, such as parameter tuning, regularization, 
setting background objects and adjusting lighting etc.but I can't avoid mesh collapse.
Curiously, this collapse of the mesh changes shape each time you run your code. (Despite the exact same program)

Depending on the object to be transformed, the collapse of the mesh can be almost avoided.

![sphere2s08 (1)](https://user-images.githubusercontent.com/49067142/84801048-a40a8a00-b039-11ea-95ce-0c692429acfc.gif)

![Screenshot_20200617_012634](https://user-images.githubusercontent.com/49067142/84801015-9bb24f00-b039-11ea-9177-93a29a7b6353.png)
- ref objects

I have no idea what is happening.

Thank you.

**Comment by arpit15** [comment]
Have you given the new [version](https://github.com/mitsuba-renderer/mitsuba2/pull/157) of the plugin a try?

**Comment by udemegane** [comment]
I tried the new version but it still doesn't work. If I make any progress, I will report it here.

**Comment by Speierers** [comment]
Hi @udemegane ,

Please have a look at the tutorials in the `pathreparam-optix7` branch, this could be helpful.

How do you modify the mesh at every iteration? Do you let the optimizer move the vertices directly using gradient descent to are you implementing a intermediate step, like in the tuto? (e.g. constrained to displacement along the normals)?

**Comment by arpit15** [comment]
@Speierers I get errors when I run pathreparam ex. For ex, I ran `invert_pose.py` and I get following error
```
cuda_check(): runtime API error = 0002 "cudaErrorMemoryAllocation" in ../ext/enoki/src/cuda/horiz.cu:59.
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDABackend: referenced unknown variable 112575
Aborted (core dumped)
```
I have RTX 2080 with 11MiB RAM. When I build in debug mode, the gdb bt complains [path-reparam.cpp:449](https://github.com/mitsuba-renderer/mitsuba2/blob/pathreparam-optix7/src/integrators/path-reparam.cpp#L449)

**Comment by Speierers** [comment]
It is possible that you are running out of memory on your GPU, the `pathreparam` integrator uses quite a bit of VRAM. Could you try to renderer with lower SPP maybe?

**Comment by udemegane** [comment]
@Speierers 
I do not give direct constraints on individual vertices, such as constrained to displacement along the normals. But that's a good idea, so I'd like to put it into practice, but I couldn't find a description in the documentation that would limit the vertices. Am I overlooking something?

**Comment by arpit15** [comment]
@Speierers Yeah it turns out spp got me again. I reduced it to 16 and everything worked. Is there a rule of thumb for memory with `pathreparam` to decide on the image size and spp?

**Comment by udemegane** [comment]
I finally got the understanding about the pre render callback function. I also fully understood this issue by reading the pathreparam paper. All causes are simply that there were cases where the mesh was "not valid". Careful reading of the documentation tutorials will work around this issue, so I shut this out. Thank you for all your efforts!
