### ISSUE TITLE
enoki submodule e240a4 does not exist

### ISSUE THREAD

**Issue by RiverIntheSky** [mitsuba-renderer/mitsuba2#185]
# Error Message while pulling submodule
fatal: remote error: upload-pack: not our ref e240a4ba9f75240b03964a119e427474850826bfadcasting
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'ext/enoki', but it did not contain e240a4ba9f75240b03964a119e427474850826bf. Direct fetching of that commit failed.

**Comment by Speierers** [comment]
Sorry I forgot to push my patch on the enoki repo. It should work now.

Thanks for reporting this!
