### ISSUE TITLE
mitsuba not executing from command line

### ISSUE THREAD

**Issue by Lights-and-Shadows** [mitsuba-renderer/mitsuba2#188]
Hey folks,

Something strange is going on with my particular build. Compiled and built as normal with I assume no particularly breaking issues (dist folder contains all necessary files). Yet, when I got to use the setpath file, it never updated my PATH variable. Weirder still, after manually adding in the appropriate values myself it still does not recognize Mitsuba as a command. 
![image](https://user-images.githubusercontent.com/36210321/85322295-19d88080-b494-11ea-9fc0-ed9419690dde.png)

![image](https://user-images.githubusercontent.com/36210321/85322354-35438b80-b494-11ea-8555-05fc7f78ae3a.png)

Built on a x64 Windows 7 machine, pretty much followed the documentation for necessary programs and files to the letter (even uses Miniconda) I made an example .xml that I saved onto a folder in my Blender projects side (I originally wanted to use the plugin for Blender but that is having its own problems atm, I'll address them later) using just the default sphere.

Pasting what I have if it helps at all. About to head into work so I won't be able to reply right away but I'll try to keep an eye on this. Thanks in advance!

**Comment by Speierers** [comment]
You probably need to run the `setpath.bat` script to set the environment variables as stated in the doc 😉

**Comment by Lights-and-Shadows** [comment]
That's what I tried doing. That in particular is what's not working. Why I made this issue to begin with.

**Comment by Lights-and-Shadows** [comment]
The registry edit didn't work, so I tried the setpath on the laptop. Confirmed that the .bat file does not execute at all, whether in CMD or even double-clicking on it in the folder itself. It registers a response but never actually does anything. So now I'm a little confused.

**Comment by Lights-and-Shadows** [comment]
Huh, that's strange. On the laptop, setpath actually worked correctly, but it still won't recognize mitsuba in the command line. Unless it's something silly I'm forgetting (restarting the laptop for example)

**Comment by Speierers** [comment]
Could you try from a clean build again?

Btw which shell are you using on Windows? I noticed the other day than when using `GitBash` I had to run `source setpath.sh` to get it to work.

**Comment by Speierers** [comment]
@Lights-and-Shadows,

Did you manage to fix this on your end?

**Comment by chenyiming-start** [comment]
I have exactly the same problem. setpath.sh and setpath.bat did not export anything to my dist. Wondering whether you fixed this.

**Comment by Speierers** [comment]
@chenyiming-start did you try to run this from a Git Bash terminal? Or from you Python distribution terminal (e.g. anaconda)?

**Comment by chenyiming-start** [comment]
@Speierers Thank you! I have tried git bash and command prompt but it turned out to be my problem. Compile step went well when I performed it in a "build" folder.
