### ISSUE TITLE
integrator addition in mitsuba2

### ISSUE THREAD

**Issue by ZFaniso** [mitsuba-renderer/mitsuba2#189]
Hi Everyone
I'm trying to render my scene file, part of its discription/parameters is the use of field integrator since i'm rendering an object that is outside with sunsky radiation etc, but now mitsuba2 doesn't find integrator field or emitter sunsky ,so i tried using area instead of field but area seems to be already assigned as an emitter in mitsuba2. The file was working on mitsuba0.5.0 but now i want to load it in mitsuba 2.
So i want to know how can i add a new field integrator or emitter in mitsuba2 ?

![2ndnotebook](https://user-images.githubusercontent.com/41281683/85670771-82f10b80-b6c1-11ea-92d7-5093e32ed2c9.png)

![emitterissue](https://user-images.githubusercontent.com/41281683/85672141-df085f80-b6c2-11ea-99e2-2a9dab2bd046.png)

**Comment by dvicini** [comment]
Hi,
Mitsuba 2 currently doesn't have a sunsky emitter. In general adding a new emitter type is quite a bit of work and requires a fairly deep understanding of the rendering process. So given that you have to ask this question, it's probably a bit too difficult for you to implement it yourself. However, there are actually two pull requests implementing (https://github.com/mitsuba-renderer/mitsuba2/pull/85,
https://github.com/mitsuba-renderer/mitsuba2/pull/49), so you could try using one of them. 

Delio

**Comment by ZFaniso** [comment]
Alright thanks.




>>> Delio Vicini <notifications@github.com> 06/25/20 9:57 AM >>>

 Hi,
 Mitsuba 2 currently doesn't have a sunsky emitter. In general adding a
new emitter type is quite a bit of work and requires a fairly deep
understanding of the rendering process. So given that you have to ask
this question, it's probably a bit too difficult for you to implement it
yourself. However, there are actually two pull requests implementing
(#85,
 #49), so you could try using one of them.
 Delio
