### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by isolin** [mitsuba-renderer/mitsuba2#19]
Please make sure to include `build-essentials` in the `apt install` Ubuntu/Debian instructions. Some images, like the `ubuntu:minimal` do not have the package included by default and `cmake -GNinja ..` then fails.

BTW Thank you very much for publishing Mitsuba2, great job!

**Comment by wjakob** [comment]
Quick question: which package was missing specifically? Our instructions specify to install clang, libc++, cmake, and ninja. So that should actually be everything that's needed regardless of build-essentials.

**Comment by isolin** [comment]
As far as I remember it was `build-essentials`, but I will repeat the installation to check that. I installed Mitsuba inside of an LXD container, so it should be easy to reproduce.

**Comment by KelSolaar** [comment]
For what it is worth I have that recipe for Google Colab: https://colab.research.google.com/drive/1lPUdWiE1C1Xe9pBod9AMXfDp5KBWIODm

**Comment by hiyyg** [comment]
Hi @KelSolaar, thanks for your recipe. I followed it to install the dependencies but I failed to install clang-9. 
```
sudo apt install clang-9 libc++-9-dev libc++abi-9-dev cmake ninja-build
```
It seems my ubuntu 16.04 can not find the correct apt resource.
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package clang-9
E: Unable to locate package libc++-9-dev
E: Couldn't find any package by regex 'libc++-9-dev'
E: Unable to locate package libc++abi-9-dev
E: Couldn't find any package by regex 'libc++abi-9-dev'
```
Do you have any ideas?

**Comment by KelSolaar** [comment]
@hiyyg : Colab runs 18.04:

```bash
!lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by hiyyg** [comment]
@KelSolaar So it doesn't work on 16.04?

**Comment by KelSolaar** [comment]
Good question! At any rate, Ubuntu 16.04 is EOL next year, not sure it is worth the hassle trying to make it work on that OS.

**Comment by merlinND** [comment]
@hiyyg I'm pretty sure you could make it work on Ubuntu 16.04, but the `clang-9` packages are not available so you would have to obtain a recent clang in another way.

**Comment by hiyyg** [comment]
Yeah, I mean I can not find a easy-to-follow recipe to install clang-9 packages on Ubuntu 16.04. I suppose many people will still stick on Ubuntu 16.04 for a long time, because of covid-19, we can not physically access the lab servers to upgrade the system.

**Comment by isolin** [comment]
@hiyyg What about launching an LXD container with a different Ubuntu version? Mitsuba can happily compile and run inside without any noticable overhead and directly using the GPU. I do that regularly. If you need help, just tell me and I will prepare a short setup guide or script for you. A second option would be a docker container.

**Comment by hiyyg** [comment]
I have no experience with LXD container. It would be very nice if you could prepare some guide or script.

**Comment by isolin** [comment]
I'll have a look on that ... in case you don't hear anything from me until Wednesday, please ping me :)

**Comment by isolin** [comment]
Are you actually going for a GPU or just a CPU build?

**Comment by hiyyg** [comment]
For GPU build.

**Comment by isolin** [comment]
OK working on that!

Regarding my original issue, `build-essentials` are required by `cuda` so they get installed along in a GPU build.

**Comment by isolin** [comment]
So I have an installation & build script almost ready. A few more checks tomorrow and it should be good to go.

**Comment by isolin** [comment]
@hiyyg I published the script and I will be happy if you can give me feedback if it works for you. Feel free to ask me about any details.

https://github.com/isolin/mitsuba2lxd

**Comment by daralthus** [comment]
Here's a quick Dockerfile if anyone needs one: https://github.com/daralthus/mitsuba2-docker
