### ISSUE TITLE
Derivative with respect to object attributes

### ISSUE THREAD

**Issue by karthikkovalam** [mitsuba-renderer/mitsuba2#190]
Apologies if I am posting at the wrong place since I could not find a forum. 

I would like to know about 2 things.
1.  Derivatives with respect to object attributes:
- Can I obtain a derivative with respect to object attributes like translation and rotation of an object. 
- Can I obtain these derivatives for multiple objects. 
For example, I would like to get the derivative wrt translation of each object in the scene for some final output like shadow. 
Is that possible? 

2. Is it possible to get auxiliary outputs like object masks/ segmentations when there are multiple objects present in the scene. 
I have the same question for depth, but I saw an example where such a thing was demonstrated. But I am not sure if it works for multiple objects in the scene. 

Thanks in advance.

**Comment by dvicini** [comment]
1. For these kind of optimization, you can have a look at the branch `pathreparam-optix7`. As far as I know this isn't merge yet into master, but it contains code which allows you to optimize object positions and rotations. There shouldnt be any restrictions as to how many objects you can compute gradients for at once (as far as I know).

2. You can have a look at the [AOV](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#arbitrary-output-variables-integrator-aov) integrator. Currently we dont support an object ID pass, but you could add this fairly easily yourself.  Just have a look at how the AOV integrator is implemented and extend it to your needs. 

Delio

**Comment by hakanyi** [comment]
Thanks @dvicini! Would it be possible to provide an example as to how to go about implementing a custom mask/silhouette AOV integrator in python?
