### ISSUE TITLE
The Roadmap

### ISSUE THREAD

**Issue by jiangwei007** [mitsuba-renderer/mitsuba2#191]
Since I contacted Mitsuba 2, I'm very much looking forward to its subsequent development process, is there any follow-up development plan for Mitsuba 2 to be disclosed?

**Comment by Speierers** [comment]
Hi @jiangwei007 ,

Unfortunately, at the moment we don't have a clear development plan to be disclosed publicly.

This is something we might look into as the userbase grows up.
