### ISSUE TITLE
lookat interpolation

### ISSUE THREAD

**Issue by alhirzel** [mitsuba-renderer/mitsuba2#192]
I'd like to investigate support for a different animation strategy for animated transformations that involve `<lookat ... />`. Specifically, it would be ideal in some cases for the animation to ensure that lerping takes place on the `origin` and `target` rather than translation, rotation, and scale (the current behavior). One way to visualize this is with the following scene, where my desire would be for the sphere to not be "smeared". The sphere becomes smeared due to the constant "look-down" angle of the camera. (Ideally it would vary because the camera is moving closer to the sphere, then further away.) Any suggestions on how I could proceed? One thought I had was adding a `type` attribute to the `<animation>` tag to allow the interpolation behavior to be specified by the user.

![image](https://user-images.githubusercontent.com/324152/85900006-0a777100-b7cd-11ea-86a6-53b7623a67d9.png)

```xml
<scene version="0.6.0">
	<shape type="sphere">
		<float name="radius" value="0.04" />
		<emitter type="area">
			<spectrum name="intensity" value="10" />
		</emitter>
	</shape>
	<sensor type="perspective">
		<float name="fov" value="90" />
		<string name="fovAxis" value="x" />
		<float name="shutterOpen" value="0" />
		<float name="shutterClose" value="1" />
		<sampler type="independent">
			<integer name="sampleCount" value="256" />
		</sampler>
		<film type="ldrfilm">
			<integer name="width" value="512" />
			<integer name="height" value="512" />
			<string name="fileFormat" value="png" />
			<string name="pixelFormat" value="rgb" />
		</film>
		<animation name="toWorld">
			<transform time="0">
				<lookat up="0,0,1" target="0,0,0" origin="-1,-1,1" />
			</transform>
			<transform time="1">
				<lookat up="0,0,1" target="0,0,0" origin="1,-1,1" />
			</transform>
		</animation>
	</sensor>
</scene>
```

**Comment by Speierers** [comment]
Hi @alhirzel ,

Thanks for this suggestion. As you might have noticed, `animation` in Mitsuba 2 is barely supported and not tested at all. 

Adding an extra `interpolation_type` property to `AnimatedTransform` could be way of handling this. Feel free to open a PR if you make some interesting progress on this.

Looking into polishing `AnimatedTransform` in on our roadmap, although it is not our priority at the moment.

I am closing this as it isn't an issue.

**Comment by alhirzel** [comment]
Thanks for the guidance!
