### ISSUE TITLE
Building python interface solutions on Windows

### ISSUE THREAD

**Issue by boonta** [mitsuba-renderer/mitsuba2#195]
Hello, 
I have a problem about building mitsuba2 solutions on Windows.

I have tried following the instructions on this page.
https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html#windows

However, once the compiling was done, I couldn't find any mitsuba python interface in 'dist' directory.
![dist1](https://user-images.githubusercontent.com/2579302/86078966-7bfb3c00-bab9-11ea-8ab9-5108ac08b240.jpg)

Inside 'python' directory.

![dist2](https://user-images.githubusercontent.com/2579302/86078974-7e5d9600-bab9-11ea-8659-0061dd9825c1.jpg)

Inside 'mitsuba' directory.
![dist3](https://user-images.githubusercontent.com/2579302/86078979-80bff000-bab9-11ea-8e7e-53f20d6b593d.jpg)

What are instructions I have to follow to build the python interface ?

(All the builds were succeeded and only 5 were skipped building.

9>Project not selected to build for this solution configuration 
10>------ Skipped Build: Project: mkdoc-api, Configuration: Release x64 ------
10>Project not selected to build for this solution configuration 
11>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
11>Project not selected to build for this solution configuration 
12>------ Skipped Build: Project: PACKAGE, Configuration: Release x64 ------
12>Project not selected to build for this solution configuration 
========== Build: 7 succeeded, 0 failed, 200 up-to-date, 5 skipped ==========
)

Additionally, I got this error when compiling pytest.

204>..\src\librender\tests\test_integrator.py::test03_render_teapot[gpu_rgb-depth]
204>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 1.
204>Done building project "pytest.vcxproj" -- FAILED.

Thank you.

**Comment by boonta** [comment]
Additionally, I got this error when compiling pytest.

204>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 1.
204>Done building project "pytest.vcxproj" -- FAILED.

**Comment by Speierers** [comment]
Hi @boonta ,

What do you mean by "Python interface" ?

You should be able to compile and then rung the following:
``` bash
./setpath.bat
python
>>> import mitsuba
```

Let me know if this fixes your issue.

**Comment by boonta** [comment]
> Hi @boonta ,
> 
> What do you mean by "Python interface" ?
> 
> You should be able to compile and then rung the following:
> 
> ```shell
> ./setpath.bat
> python
> >>> import mitsuba
> ```
> 
> Let me know if this fixes your issue.

Thank you for your reply. 
I run 'setpath.bat' but nothing happened when i tried importing mitsuba in python.

here is the error :

```
PS D:\mitsuba2> python
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import mitsuba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mitsuba'
```

Here is what is inside 'setpath.bat'.

```
@echo off

REM ***************************************************************
REM * This script adds Mitsuba to the current path on Windows.
REM * It assumes that Mitsuba is either compiled within the 
REM * source tree or within a subdirectory named 'build'.
REM ***************************************************************

set MITSUBA_DIR=%~dp0
set MITSUBA_DIR=%MITSUBA_DIR:~0,-1%
set PATH=%PATH%;%MITSUBA_DIR%\dist;%MITSUBA_DIR%\build\dist
set PYTHONPATH=%PYTHONPATH%;%MITSUBA_DIR%\dist\python;%MITSUBA_DIR%\build\dist\python
```

It looks like there is no 'mitsuba.py' in the paths above.

**Comment by Speierers** [comment]
and your `dist` directory is either at the root folder of `mitsuba2` or in a `build` folder right?

**Comment by boonta** [comment]
> and your `dist` directory is either at the root folder of `mitsuba2` or in a `build` folder right?

Yes, exactly.
I haven't changed anything.
I just followed the instructions in the web page.

**Comment by boonta** [comment]
> > and your `dist` directory is either at the root folder of `mitsuba2` or in a `build` folder right?
> 
> Yes, exactly.
> I haven't changed anything.
> I just followed the instructions in the web page.

Here is where the 'dist' directory is.

![ฟฟฟฟ](https://user-images.githubusercontent.com/2579302/86581356-31425e00-bfaa-11ea-8553-56089e76ba8c.jpg)

**Comment by Speierers** [comment]
Could you try to run `setpath` and then `python` from the anaconda terminal maybe?

**Comment by boonta** [comment]
> Could you try to run `setpath` and then `python` from the anaconda terminal maybe?

```
(base) D:\mitsuba2>python
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mitsuba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mitsuba'
```

It still throws an error.

I tried searching for 'mitsuba.py' in the 'mitsuba2' directory. The result is nothing. There is no such file named 'mitsuba.py'.

**Comment by boonta** [comment]
> Could you try to run `setpath` and then `python` from the anaconda terminal maybe?

I am sorry. 
It works now.

Thank you so much for you help !

**Comment by thesigmaguy** [comment]
Hi @boonta, Can you let me know how were you able to get the DLLs. I followed the same procedure as the [https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html#windows](this), cloned recursively. used the CMake command as on the page, later opened mitsuba.sln and built it. I could not see any .dll files in my dist director I could only see the python and data folder over there. When I tried running the mitsuba file I receive mitusba-render.dll not found

**Comment by boonta** [comment]
> Hi @boonta, Can you let me know how were you able to get the DLLs. I followed the same procedure as the [https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html#windows](this), cloned recursively. used the CMake command as on the page, later opened mitsuba.sln, and built it. I could not see any .dll files in my dist director I could only see the python and data folder over there. When I tried running the mitsuba file I receive mitsuba-render.dll not found

You can get it automatically after you compile the solution.

**Comment by thesigmaguy** [comment]
No, I have not got them. I had to run the dist-copy and python-copy slns separately, then they appeared
