### ISSUE TITLE
bitmap.cpp Compile Errors

### ISSUE THREAD

**Issue by troywilliams1** [mitsuba-renderer/mitsuba2#203]
### Problem

When Building Release for Mitsuba2 in Visual Studio 2019, errors are generated with bitmap.cpp. 

1>------ Build started: Project: tbb_def_files, Configuration: Release x64 ------
2>------ Build started: Project: CopyIlmBaseLibs, Configuration: Release x64 ------
3>------ Build started: Project: bitmap-obj, Configuration: Release x64 ------
4>------ Build started: Project: python-copy, Configuration: Release x64 ------
5>------ Build started: Project: enoki-python-init, Configuration: Release x64 ------
6>------ Build started: Project: mitsuba-enoki-python-init, Configuration: Release x64 ------
7>------ Skipped Build: Project: mkdoc, Configuration: Release x64 ------
7>Project not selected to build for this solution configuration 
8>------ Build started: Project: rgb2spec_opt_run, Configuration: Release x64 ------
3>bitmap.cpp
3>C:\mitsuba2\src\textures\bitmap.cpp(455,18): error C2039: 'lock_guard': is not a member of 'std'
3>C:\mitsuba2\ext\tbb\include\tbb\internal/_tbb_windef.h(33): message : see declaration of 'std'
3>C:\mitsuba2\src\textures\bitmap.cpp(452): message : while compiling class template member function 'Float mitsuba::BitmapTextureImpl<Float,Spectrum,3,false>::pdf_position(const mitsuba::Point<float,2> &,bool) const'
3>        with
3>        [
3>            Float=float,
3>            Spectrum=mitsuba::Color<float,3>
3>        ]
3>C:\mitsuba2\src\textures\bitmap.cpp(230): message : see reference to class template instantiation 'mitsuba::BitmapTextureImpl<Float,Spectrum,3,false>' being compiled
3>        with
3>        [
3>            Float=float,
3>            Spectrum=mitsuba::Color<float,3>
3>        ]
3>C:\mitsuba2\src\textures\bitmap.cpp(225): message : see reference to function template instantiation 'mitsuba::Object *mitsuba::BitmapTexture<float,mitsuba::Color<float,3>>::expand_3<3,false>(void) const' being compiled
3>C:\mitsuba2\src\textures\bitmap.cpp(225): message : see reference to function template instantiation 'mitsuba::Object *mitsuba::BitmapTexture<float,mitsuba::Color<float,3>>::expand_3<3,false>(void) const' being compiled
3>C:\mitsuba2\src\textures\bitmap.cpp(221): message : see reference to function template instantiation 'mitsuba::Object *mitsuba::BitmapTexture<float,mitsuba::Color<float,3>>::expand_2<3>(void) const' being compiled
3>C:\mitsuba2\src\textures\bitmap.cpp(221): message : see reference to function template instantiation 'mitsuba::Object *mitsuba::BitmapTexture<float,mitsuba::Color<float,3>>::expand_2<3>(void) const' being compiled
3>C:\mitsuba2\src\textures\bitmap.cpp(220): message : while compiling class template member function 'mitsuba::Object *mitsuba::BitmapTexture<float,mitsuba::Color<float,3>>::expand_1(void) const'
3>C:\mitsuba2\src\textures\bitmap.cpp(604): message : see reference to class template instantiation 'mitsuba::BitmapTexture<float,mitsuba::Color<float,3>>' being compiled
3>C:\mitsuba2\src\textures\bitmap.cpp(455,1): error C2065: 'lock_guard': undeclared identifier
3>C:\mitsuba2\src\textures\bitmap.cpp(455,34): error C2275: 'tbb::spin_mutex': illegal use of this type as an expression
3>C:\mitsuba2\src\textures\bitmap.cpp(455): message : see declaration of 'tbb::spin_mutex'
3>C:\mitsuba2\src\textures\bitmap.cpp(455,46): error C3861: 'guard': identifier not found
3>Done building project "bitmap-obj.vcxproj" -- FAILED.
9>------ Build started: Project: bitmap (plugins\textures\bitmap\bitmap), Configuration: Release x64 ------
9>LINK : fatal error LNK1181: cannot open input file 'C:\mitsuba2\src\textures\bitmap-obj.dir\Release\bitmap.obj'
9>Done building project "bitmap.vcxproj" -- FAILED.
10>------ Build started: Project: dist-copy, Configuration: Release x64 ------
10>Generating dist/plugins/bitmap.dll
10>Error copying file "C:/mitsuba2/src/textures/Release/bitmap.dll" to "C:/mitsuba2/dist/plugins/bitmap.dll".
10>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 1.
10>Done building project "dist-copy.vcxproj" -- FAILED.
11>------ Skipped Build: Project: mkdoc-api, Configuration: Release x64 ------
11>Project not selected to build for this solution configuration 
12>------ Skipped Build: Project: pytest, Configuration: Release x64 ------
12>Project not selected to build for this solution configuration 
13>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
13>Project not selected to build for this solution configuration 
14>------ Skipped Build: Project: PACKAGE, Configuration: Release x64 ------
14>Project not selected to build for this solution configuration 
========== Build: 6 succeeded, 3 failed, 172 up-to-date, 5 skipped ==========

### Steps to Reproduce

1. Follow Compiling the system instructions for Windows platform in Mitsuba2 Docs
2. Use Anaconda (miniconda 3) environment when running cmake

###Cmake Results

c:\mitsuba2>cmake -G "Visual Studio 16 2019" -A x64
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- Building the following variants of Mitsuba:
--  * scalar_rgb
--  * scalar_spectral
-- Mitsuba: building the Python plugin.
-- Enoki: building the Python plugin.
-- pybind11 v2.4.dev4
-- Mitsuba: using builtin implementation for CPU ray tracing.
-- Mitsuba: LTO support enabled.
-- Mitsuba: sampling profiler disabled.
-- Found Sphinx: C:/Users/Troy/Miniconda3/Scripts/sphinx-build.exe
-- Configuring done
-- Generating done
-- Build files have been written to: C:/mitsuba2

### Versions

conda 4.8.3
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
git version 2.27.0.windows.1
cmake version 3.17.2 (Installed as package through Anaconda)
Microsoft Visual Studio 2019 Version 16.6.3 (Community)
Windows 10 Enterprise 64-bit

**Comment by wjakob** [comment]
Should be fixed in  9913cb5c.

**Comment by troywilliams1** [comment]
Hello wjakob,

Thank you for the quick response, I can confirm that this bug is still present with the changes in [https://github.com/mitsuba-renderer/mitsuba2/commit/9913cb5c833cb587dfa2439664c8121258b7c185](url) 

I believe your correction would need to be made in C:\mitsuba2\src\textures\bitmap.cpp as well. I modified my local file here to test and the Build passes. 

### Visual Studio Output

7>Project not selected to build for this solution configuration 
8>------ Build started: Project: rgb2spec_opt_run, Configuration: Release x64 ------
3>bitmap.cpp
3>bitmap-obj.vcxproj -> C:\mitsuba2\src\textures\bitmap-obj.dir\Release\bitmap-obj.lib
9>------ Build started: Project: bitmap (plugins\textures\bitmap\bitmap), Configuration: Release x64 ------
9>   Creating library C:/mitsuba2/src/textures/Release/bitmap.lib and object C:/mitsuba2/src/textures/Release/bitmap.exp
9>Generating code
9>Finished generating code
9>bitmap.vcxproj -> C:\mitsuba2\src\textures\Release\bitmap.dll
10>------ Build started: Project: dist-copy, Configuration: Release x64 ------
10>Generating dist/plugins/bitmap.dll
10>Generating dist/plugins/checkerboard.dll
10>Generating dist/plugins/constvolume.dll
10>Generating dist/plugins/gridvolume.dll
10>Generating dist/plugins/mesh_attribute.dll
10>Generating dist/data/srgb.coeff
11>------ Skipped Build: Project: mkdoc-api, Configuration: Release x64 ------
11>Project not selected to build for this solution configuration 
12>------ Skipped Build: Project: pytest, Configuration: Release x64 ------
12>Project not selected to build for this solution configuration 
13>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
13>Project not selected to build for this solution configuration 
14>------ Skipped Build: Project: PACKAGE, Configuration: Release x64 ------
14>Project not selected to build for this solution configuration 
========== Build: 9 succeeded, 0 failed, 172 up-to-date, 5 skipped ==========

**Comment by wjakob** [comment]
oops, can you try again please?

**Comment by troywilliams1** [comment]
Yes that new correction seems to have fixed the problem, thank you.
