### ISSUE TITLE
Cannot add labels to issues

### ISSUE THREAD

**Issue by leroyvn** [mitsuba-renderer/mitsuba2#216]
The new PR and issue templates require to apply appropriate labels, but it seems that specific permissions (at least contributor AFAIK) are required for that. I think it's a common problem, and GitHub hasn't yet found a way to solve that... See for instance https://github.com/KhronosGroup/Vulkan-Docs/issues/15. Have I missed something?

**Comment by Speierers** [comment]
You are right @leroyvn . I will update the issue template then. Thanks!
