### ISSUE TITLE
About shape groups/assemblies

### ISSUE THREAD

**Issue by KelSolaar** [mitsuba-renderer/mitsuba2#22]
Hi,

I might have missed the obvious but I could not find a way to make `shape` groups or assemblies.

In the past, with Mitsuba 1, I have been relying on translators to export data for me so it never has been an issue. I am however currently building scenes manually so I'm wondering if it is possible to create groups of shapes and transform them as a single entity. I would like, for example, assemble a colour checker with the frame and the patches and put it in place wherever I need.

Hope that makes sense,

Cheers,

Thomas

**Comment by chaosink** [comment]
Maybe you can try my script: [rm_instance](https://github.com/chaosink/mitsuba_tools/tree/master/rm_instance).
It can convert `instance` and `shapegroup` shapes into non-instanced shapes.

**Comment by wjakob** [comment]
Hi @KelSolaar,

instancing is one of the features that we haven't yet ported to Mitsuba 2. We are currently looking  into this, as it is obviously an important feature.

Best,
Wenzel

**Comment by KelSolaar** [comment]
Sweet thanks @wjakob!

@chaosink : I searched for `group` in the entire codebase and could not find anything, hence my thread. Bookmarked your repo for future reference though!

Cheers,

Thomas

**Comment by chaosink** [comment]
@KelSolaar Try searching `shapegroup` instead.

**Comment by KelSolaar** [comment]
Unless I missed something super obvious (and as I stated it earlier), nothing like that in Mitsuba 2!

![image](https://user-images.githubusercontent.com/99779/76169471-60ec7f80-61dd-11ea-9db6-235cef305663.png)

**Comment by chaosink** [comment]
@KelSolaar  Convert `instance` and `shapegroup` shapes in XML files to non-instanced shapes.
Is this what you want?
Or I misunderstood you needs?

**Comment by KelSolaar** [comment]
I need to be able to take a bunch of shapes, group them and transform that group.

For example, I have that ColorChecker geometry here: https://github.com/colour-science/colour-mitsuba/tree/master/colour_mitsuba/colorchecker_classic/geometry. I want to assemble it a the origin of the world, group everything under a group/assembly and then move that group at the location I wish. At the moment I have to export everything at the final worldspace location, e.g. against the Cornell Box wall for that precise ColorChecker geometry.

Hope that makes sense!

**Comment by chaosink** [comment]
I mean, you can first generate a XML scene file for Mitsuba1 just as before.
> In the past, with Mitsuba 1, I have been relying on translators to export data for me so it never has been an issue.

And then, use this Python script [rm_instance](https://github.com/chaosink/mitsuba_tools/tree/master/rm_instance) to convert `instance` and `shapegroup` shapes in XML to non-instanced shapes, for the lack of instance in Mitsuba2.

Finally, use Mitsuba2 to render the converted scene.

This is only a workaround, which may consume more memory than using instance.

**Comment by KelSolaar** [comment]
Well, I'm generating the scene manually now! I could compute the transformations and slot them as required but it is a stretch too much for my liking and not really efficient.

Cheers,

Thomas

**Comment by Speierers** [comment]
I am going to close this. Instancing and shape grouping is on our roadmap.
