### ISSUE TITLE
Visual Studio: packet_rgb variant (and maybe others) build errors

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [mitsuba-renderer/mitsuba2#222]
*compilation issue*

## Summary

Following the documentation, when trying to build with the `packet_rgb` option, the Visual Studio build fails.

## System configuration

- Platform: Windows
- Compiler: cmake version 3.18.0-rc2
- Python version: 3.7.7
- Mitsuba 2 version: 2.2.0
- Miniconda version: 4.8.3
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`

## Description

I followed the documentation closely and still get these build errors when trying it with the variant `packet_rgb` included. Everything works fine with just `scalar_rgb`.

`Error	C2039	'partition_': is not a member of 'enoki::DynamicArray<enoki::Packet<const mitsuba::Shape<enoki::Packet<float,8>,mitsuba::Color<enoki::Packet<float,8>,3>> *,8>>'	render_packet_rgb_ext-obj	C:\Users\micha\Documents\mitsuba2\ext\enoki\include\enoki\array_router.h	671`

## Steps to reproduce

Followed the documentation exactly until this point.

**Comment by Speierers** [comment]
Thanks @MajorMeerkatThe3rd for reporting this. It should be fixed now.
