### ISSUE TITLE
A refractive slab optimized by inverse rendering to focus light with three primary colors into a rendition of the painting 

### ISSUE THREAD

**Issue by magicknight** [mitsuba-renderer/mitsuba2#224]
Hello,

I am interested in reproducing one of the four examples in your video: 
"A refractive slab optimized by inverse rendering to focus light with three primary colors into a rendition of the painting A Sunday Afternoon on the Island of La Grande Jatte by Georges Seurat."

Just wondering is the code for this example available? Thank you!

**Comment by merlinND** [comment]
Dear @magicknight,

Thanks for your interest in this demo! Unfortunately, there were major code improvements between the paper and the Mitsuba 2 release, and I haven't had time to port that experiment yet to the latest codebase.

Three components are needed for this experiment:
- Light tracer integrator (currently, only path tracing is implemented)
- Collimated area light source
- Support for displacement maps

**Comment by magicknight** [comment]
Ah, I see. I will try to reproduce this with my own code :D 
Thank you for your reply merlinND.
