### ISSUE TITLE
🐛 [Bug report] "Independent" sampler's argument "seed" is not reflected in c++

### ISSUE THREAD

**Issue by Mine-525** [mitsuba-renderer/mitsuba2#225]
##  Summary
Argument "seed" is not reflected in c++ processing.

## System configuration

- Platform: Windows10
- Compiler: Visual Studio 2019 Version 16.5.3
- Python version: 3.7.6
- Mitsuba 2 version: 2.2.0
- Compiled variants:
    * `scalar_rgb`

## Description
I need to sample random numbers with specified seed for my plugin in c++.
However, I always got a same result nevertheless I changed `seed` .

## Steps to reproduce
1. Add below code to beginning of the function SamplingIntegrator<Float, Spectrum>::render()
```
ref<Sampler> sampler_test = sensor->sampler()->clone();
for (int i = 0; i < 5; i++){
    Log(Info, "rand: %f", sampler_test->next_1d());
}
```

2. Render any .xml scene file with sampling integrator.
Even if any integer is input at `seed`, same output are displayed at console.
In my environment, I get the result of `next_1d()` as below.
```
2020-07-24 02:10:32 INFO  main  [SamplingIntegrator] rand: 0.108379
2020-07-24 02:10:32 INFO  main  [SamplingIntegrator] rand: 0.906960
2020-07-24 02:10:32 INFO  main  [SamplingIntegrator] rand: 0.406692
2020-07-24 02:10:32 INFO  main  [SamplingIntegrator] rand: 0.875239
2020-07-24 02:10:32 INFO  main  [SamplingIntegrator] rand: 0.694849
```

**Comment by Speierers** [comment]
Thanks for reporting this. 

This is using the `independent` sampler?

**Comment by Mine-525** [comment]
Yes
Furthermore, I checked other types of Samplers, `ldsampler`, `orthogonal`...., but only `independent` sampler seems to have this problem.

I also checked `seed` right after cloning sampler i.e. 
```
ref<Sampler> sampler_test = sensor->sampler()->clone();
Log(Info, "seed: %i", sampler_test->base_seed());
for (int i = 0; i < 10; i++){
    Log(Info, "rand: %f", sampler_test->next_1d());
}
```
where `base_seed()` just returns the `m_base_seed` value.
In this test, `m_base_seed` of a instance was correct.

**Comment by Speierers** [comment]
The problem here is that you always need to seed the sampler (e.g. `sampler->seed(0)`) before calling `next_1d()`. Especially after calling `clone()`, the resulting sampler needs to be seeded.

Your code should assert in debug mode.

I will add a few lines on this in the doc.

**Comment by Mine-525** [comment]
Thank you for your answer!
I misunderstood about using `Sampler`.
