### ISSUE TITLE
[Bug report] enoki.linspace(Float, ...) return wrong values from python code with scalar_rgb variant

### ISSUE THREAD

**Issue by guoxx** [mitsuba-renderer/mitsuba2#226]
## Summary

Following python code return a scalar 0 instead of a array

```
import mitsuba
mitsuba.set_variant('scalar_rgb')
from mitsuba.core import Float
import enoki as ek
ek.linspace(Float, 0, ek.pi, 10)
```

## System configuration

- Platform: Window 10
- Compiler: Visual studio 2019 16.6.2
- Python version: 3.7.6
- Mitsuba 2 version: b196695023897ff7d3e3d9ad2944589524031b5f
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectrum`

## Steps to reproduce

1. Compile mitsuba 2 with system configuration listed
2. Open python console, paste python code listed before

**Comment by Speierers** [comment]
You will need to use the `Float32` type in `enoki.dynamic` for this as `mitsuba.core.Float` is `float` for `scalar_rgb`.

```python
from enoki.dynamic import Float32 as MyFloat
ek.linspace(MyFloat, 0, ek.pi, 10)
```

**Comment by guoxx** [comment]
Why mitsuba.core.Float and enoki.dynamic is not interchangeable? 
There are code from chi2.py

```
        from mitsuba.core import Float, Vector2f, ScalarVector2f

        # Compute a set of nodes where the PDF should be evaluated
        x, y = ek.meshgrid(
            ek.linspace(Float, self.bounds.min.x, endpoint.x, self.res.x),
            ek.linspace(Float, self.bounds.min.y, endpoint.y, self.res.y)
        )
```

It works fine with packet_rgb, but I do believe it's not working with scalar_rgb.

**Comment by Speierers** [comment]
Exactly. This is because for `scalar_*` variants of Mitsuba, `mitsuba.core.Float` is equivalent to `float`. If you look carefully, the chi2 tests only run for the `packet_*` and `cuda_*` variants for the renderer.

**Comment by guoxx** [comment]
Make sense. Thank you very much for quick response!!
