### ISSUE TITLE
Always happen an exception in `Sampler`'s function `advance()` in debug mode

### ISSUE THREAD

**Issue by Mine-525** [mitsuba-renderer/mitsuba2#227]
## Summary
In debug mode, Assert in `Sampler`'s function `advance()`,
```
Assert(m_sample_index < (m_sample_count / m_samples_per_wavefront));
```
always returns false and gets error.

## System configuration
- Platform: Windows10
- Compiler: Visual Studio 2019 Version 16.5.3
- Python version: 3.7.6
- Mitsuba 2 version: 2.2.0
- Compiled variants:
    * `scalar_rgb`

## Description
Condition of this assert returns false.
It's because as `m_sample_count`th iteration at a pixel, `m_sample_index` and `m_sample_count` have a same value.

## Steps to reproduce
Render in debug mode

**Comment by Speierers** [comment]
Hi @Mine-525 ,

Thanks for reporting this. It should be fixed now.
