### ISSUE TITLE
Heightfield plugin✨

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/mitsuba2#231]
##  Summary
I am interested in using heightfield for representing deformation on a surface. I have looked at  [path param heightfield ex](https://github.com/mitsuba-renderer/mitsuba2/blob/pathreparam-optix7/docs/examples/10_inverse_rendering/invert_heightfield.py) and mitsuba 0.6 heightfield plugin. Are these doing the same thing or it is worth to port the heightfield plugin from old mitsuba?

**Comment by Speierers** [comment]
Hi @arpit15 ,

Those are very different and it would definitely be nice to have a `heightfield` plugin like the one in Mitsuba 0.6.

The heightfield python example showcases the flexibility of the bindings but it wouldn't be a viable solution when assembling a scene with many `heightfield` assets in it.

If you are interesed in this plugin, please go ahead and open a PR, I will be happy to help you on this!

Cheers!

**Comment by arpit15** [comment]
@Speierers The older plugin refers [this](https://dl.acm.org/doi/abs/10.1145/1342250.1342279?casa_token=4QDZykFF-1oAAAAA:AdNT0MwI9T-92b_x97VT7wQSdlc50QuGolL47GEcL4OBxIs7u4-FX-IF3z_OxzEXbCJoRpjsCODNig) paper. Is there a better technique than the one mentioned in the paper?

**Comment by Speierers** [comment]
Not entierly sure, but this is probably a good starting point ;)

**Comment by alhirzel** [comment]
Are there any other efforts to implement this? I was considering taking it on. Is there a plugin porting guide yet?

**Comment by Speierers** [comment]
No other efforts that we know off. 

Unfortunately there is no plugin porting guide at the moment. Please go ahead and open a PR, I will be happy to help you with this!
