### ISSUE TITLE
Hdrfilm crop - 🐛 bug report

### ISSUE THREAD

**Issue by Samia067** [mitsuba-renderer/mitsuba2#232]
##  Summary

Hdrmfilm crop options does not work properly

## System configuration

- Platform: Ubuntu 18.04
- Compiler: clang-9
- Python version: 3.6.10, 3.7.4
- Mitsuba 2 version: 2.1.0
- Compiled variants: 
    * scalar_rgb
    * gpu_autodiff_rgb

## Description

I am trying to render only a certain portion of the hdrfilm as output. The parameters for that is crop_offset_x, crop_offset_y, crop_width and crop_height. However, it seems like its not working as expected. It only works if the crop offset is set at (0,0). Any other offset will show a partially or fully black rendered image. 

## Steps to reproduce

To illustrate this, I rendered the cbox images with a resolution of 256x256.
1. Specify crop_offset_y = 0, crop_offset_x = 0, crop_height = 128 and crop_width = 128. The produces the expected image.
![Figure_1](https://user-images.githubusercontent.com/6562084/88834392-9d1e7d80-d188-11ea-8f66-448d2320e220.png)

2. Now if you change the parameters to crop_offset_y = 30, crop_offset_x = 0, crop_height = 128 and crop_width = 128, then this image shows up:
![Figure_2](https://user-images.githubusercontent.com/6562084/88834454-b7585b80-d188-11ea-9753-7da1eec77826.png)

3. If you change the parameters to crop_offset_y = 30, crop_offset_x = 60, crop_height = 128 and crop_width = 128, then this image is produced:
![Figure_3](https://user-images.githubusercontent.com/6562084/88834508-cfc87600-d188-11ea-8734-317cfed75c59.png)

How can I fix this?

**Comment by arpit15** [comment]
I only see this problem on `gpu_rgb` variant.

**Comment by Speierers** [comment]
Hi @Samia067 ,

Thanks for reporting this. It should be fixed now: 450b4192
