### ISSUE TITLE
Batched (Multi-GPU) rendering [✨ feature request]

### ISSUE THREAD

**Issue by aluo-x** [mitsuba-renderer/mitsuba2#236]
## Summary

I did a quick review of the mitsuba2 documentation, and I don't think there is a way to perform batched multi-GPU rendering. This is a feature supported by most other differentiable renderers (Pytorch 3D -- via the native Pytorch DataParallel, Softras -- via the native Pytorch DataParallel, NMR supports batch but multi-GPU is unknown, Kaolin/DIB-R supports batch but doesn't support multi-GPU). 

## Description
Such a function ideally would take in a list of scene/mesh objects, and a list of ray bundles, and divide up the work (with scenes as the minimum unit) among pre-specified GPUs. I have considered using [Ray](https://docs.ray.io/en/master) to perform GPU allocation & parallelization, but a native solution that does not require repeated CUDA context setup would be ideal.

**Comment by Speierers** [comment]
Hi @aluo-x ,

We are currently working on refactoring the whole codebase, including significant changes in the `enoki` "backend". This will hopefully take us a step closer to supporting multi-GPUs.

This is on our roadmap and we will likely get to it once done with the refactoring.

Cheers!

**Comment by PerryXDeng** [comment]
> Hi @aluo-x ,
> 
> We are currently working on refactoring the whole codebase, including significant changes in the `enoki` "backend". This will hopefully take us a step closer to supporting multi-GPUs.
> 
> This is on our roadmap and we will likely get to it once done with the refactoring.
> 
> Cheers!

How can I help? Is there a time line for this?

**Comment by Speierers** [comment]
We don't have a specific timeline for this, but we are making good progress.

Thanks for offering your help but at this point it's mostly about polishing code and documentation. Feedbacks will always be welcome once it is released ;)
