### ISSUE TITLE
Orthogonal camera - [✨ feature request]

### ISSUE THREAD

**Issue by wangchi87** [mitsuba-renderer/mitsuba2#239]
- [✨ feature request]

## Summary

Orthogonal camera is highly appreciated

## Description

Orthogonal camera is reported in the doc, but we cann't find it. So maybe it can be supported in the near future?

**Comment by Speierers** [comment]
Hi @wangchi87 ,

This isn't currently on our roadmap, although it should be pretty straightforward to import this plugin from the Mitsuba 0.6 codebase.

I would be more than happy to assist you if you want to open a PR for this.

Cheers!
