### ISSUE TITLE
Resolution in mitsuba.python.autodiff.write_bitmap / crop_size  is transpose

### ISSUE THREAD

**Issue by pitchaya** [mitsuba-renderer/mitsuba2#24]
Hi,
   This is a very minor issue.   I have a simple scene that the output is rectangular, not square. If I use the following code to render the image and save to file

```
image_ref = render(scene, spp=16)
crop_size = scene.sensors()[0].film().crop_size()
write_bitmap('out_ref.png', image_ref, crop_size)

```
The result would be incorrect. The correct usage has to be 
```
image_ref = render(scene, spp=16)
crop_size = scene.sensors()[0].film().crop_size()
write_bitmap('out_ref.png', image_ref, (crop_size[1], crop_size[0]))

```

This is not a big issue. However, if one read examples in the documents, they would assume that the above one is the correct one. So, I think either change the behavior in the crop_size, write_bitmap, or the document would be an appropriate things.

Best Regards,

**Comment by wjakob** [comment]
Fixed, thanks!
