### ISSUE TITLE
 [❔ other question] `set_property` in `object_v.cpp` does not support float variables in `scalar_*` variant

### ISSUE THREAD

**Issue by Mine-525** [mitsuba-renderer/mitsuba2#240]
## Summary
For my work, I want edit parameters of scene object from python directly.
However, in `scalar_*` variant, this edit does not support float variables, and I solved this problem roughly.
Since I'm not sure whether my solution is correct or not, could you tell me the solution can cause other critical problems?

## System configuration

Platform: Windows10
Compiler: Visual Studio 2019 Version 16.5.3
Python version: 3.7.6
Mitsuba 2 version: 2.2.0
Compiled variants:
scalar_rgb, gpu_rgb

## Description
I want to render with various medium parameters and other identical objects and parameters.
Because loading a whole scene file takes time, I want to just change parameters of scene object, i.e., 
```
params = traverse(scene)
params["dielectric_bsdf.eta"] = 1.5
params.update()
```
I want to use this operation in `scalar_*` variant because it can render volumetric path tracing faster than `gpu_*`.
However, when float parameters are changed in `scalar_*` variant, this operation causes a runtime error
```
RuntimeError: ​[object_v.cpp:122] set_property(): unsupported type "float"!
```

Therefore, I add a code below in `set_property()` in `object_v.cpp`
```
SET_ATTR(Float);
```
This can solve the runtime error and render correctly, but I'm not sure that this solution may cause other critical problems in whole systems.

I won't use differentiable rendering but only usual rendering

**Comment by Speierers** [comment]
Hi @Mine-525 ,

Thanks for reporting this. It should be fixed in e3f1b31f
