### ISSUE TITLE
[✨ feature request] Support Cuda 11

### ISSUE THREAD

**Issue by JulianKnodt** [mitsuba-renderer/mitsuba2#241]
## Summary

I was wondering if Cuda 11 could be supported? I'd also be willing to make changes to support it, if it could be pointed out where changes needed to be made and what they should in general follow

## System configuration

This is because I'm using Ubuntu 20.04 or smth and Nvidia has dropped support for Cuda 10.2 for it, which is really a pain in the neck.

**Comment by Speierers** [comment]
Hi @JulianKnodt ,

I don't think this would be too hard to support. We are currently in the process of refactoring the whole codebase, which includes significant changes in the way the framework interacts with CUDA. Once we are done with this, it would be great to give this a try.

Let's keep this issue open for now as a reminder.

**Comment by JulianKnodt** [comment]
That sounds fantastic, it's good to hear that there are things in the works; is there anyway to try to compile it with CUDA 11 as of this current point? Waiting for the codebase to change might be a while, and if there's a slight chance that trying to compile with 11 might "just work", it'd be easy for me for now to quickly try out it.

**Comment by merlinND** [comment]
@JulianKnodt I believe that CUDA 11 is already supported without changes. It should just be a matter of making sure CMake picks up the right `nvcc` version (`CMAKE_CUDA_COMPILER`), and trying to build.

**Comment by JulianKnodt** [comment]
ah ok I was specifying an incorrect version of NVCC, so I set it to 11 with `cmake .. -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.0/bin/nvcc`

Upon doing so I got this error:
```
[1/180] cd /home/kadmin/projects/mitsuba2/build/ext_build/openexr && /usr/bin/cmake -E copy_directory /home/kadmin/projects/mitsuba2/build/ext_build/openexr/IlmBase/Half/ /home/kadmin/projects/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/ && /usr/bin/cmake -E copy_directory /home/kadmin/projects/mitsuba2/build/ext_build/openexr/IlmBase/IlmThread/ /home/kadmin/projects/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/ && /usr/bin/cmake -E copy_directory /home/kadmin/projects/mitsuba2/build/ext_build/openexr/IlmBase/Iex/ /home/kadmin/projects/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/ && /usr/bin/cmake -E copy_directory /home/kadmin/projects/mitsuba2/build/ext_build/openexr/IlmBase/Imath/ /home/kadmin/projects/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/
[2/180] Building CUDA object ext_build/enoki/CMakeFiles/enoki-cuda.dir/src/cuda/horiz.cu.o
FAILED: ext_build/enoki/CMakeFiles/enoki-cuda.dir/src/cuda/horiz.cu.o 
/usr/local/cuda-11.0/bin/nvcc  -DENOKI_AUTODIFF=1 -DENOKI_BUILD=1 -DENOKI_CUDA=1 -DENOKI_CUDA_COMPUTE_CAPABILITY=50 -Denoki_cuda_EXPORTS -I/usr/include/libcxxabi -I../ext/enoki/include -I../ext/enoki/ext/cub -gencode arch=compute_50,code=compute_50 -cudart shared -Xcompiler -fvisibility=hidden -DNDEBUG -O3 -DNDEBUG -Xcompiler=-fPIC -x cu -c ../ext/enoki/src/cuda/horiz.cu -o ext_build/enoki/CMakeFiles/enoki-cuda.dir/src/cuda/horiz.cu.o && /usr/local/cuda-11.0/bin/nvcc  -DENOKI_AUTODIFF=1 -DENOKI_BUILD=1 -DENOKI_CUDA=1 -DENOKI_CUDA_COMPUTE_CAPABILITY=50 -Denoki_cuda_EXPORTS -I/usr/include/libcxxabi -I../ext/enoki/include -I../ext/enoki/ext/cub -gencode arch=compute_50,code=compute_50 -cudart shared -Xcompiler -fvisibility=hidden -DNDEBUG -O3 -DNDEBUG -Xcompiler=-fPIC -x cu -M ../ext/enoki/src/cuda/horiz.cu -MT ext_build/enoki/CMakeFiles/enoki-cuda.dir/src/cuda/horiz.cu.o -o ext_build/enoki/CMakeFiles/enoki-cuda.dir/src/cuda/horiz.cu.o.d
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/local/cuda-11.0/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/execution_policy.h:33,
                 from /usr/local/cuda-11.0/bin/../targets/x86_64-linux/include/thrust/iterator/detail/device_system_tag.h:23,
                 from /usr/local/cuda-11.0/bin/../targets/x86_64-linux/include/thrust/iterator/detail/iterator_facade_category.h:22,
                 from /usr/local/cuda-11.0/bin/../targets/x86_64-linux/include/thrust/iterator/iterator_facade.h:37,
                 from ../ext/enoki/ext/cub/cub/device/../iterator/arg_index_input_iterator.cuh:48,
                 from ../ext/enoki/ext/cub/cub/device/device_reduce.cuh:41,
                 from ../ext/enoki/src/cuda/horiz.cu:17:
/usr/local/cuda-11.0/bin/../targets/x86_64-linux/include/thrust/system/cuda/config.h:78:2: error: #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
   78 | #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
      |  ^~~~~
[3/180] Building CXX object ext_build/tbb/CMakeFiles/tbb.dir/src/tbb/tbb_misc.cpp.o
ninja: build stopped: subcommand failed.
```

I think the warning is negligible, but the other issue seems to be not super trivial, and was fixed in other repositories like here:
https://github.com/rapidsai/cudf/issues/5369

In order to fix it I moved `mitsuba/ext/enoki/ext/cub` to `mitsuba/ext/enoki/ext/_cub` and it seems to be compiling alright! Will have to see if it runs properly, but might take a bit.

**Comment by merlinND** [comment]
Cool, thanks for trying it out! We'll need to handle this CUB version error properly to consider real CUDA 11 support, but in the meantime this looks like an easy workaround.

**Comment by Xaldew** [comment]
I believe this have actually been fixed now after https://github.com/mitsuba-renderer/enoki/commit/ae3923759c637b244605e4948c8938f9da7be16b, so this ticket can probably be closed.

**Comment by Speierers** [comment]
Thanks @Xaldew
