### ISSUE TITLE
[🐛 bug report] Runtime Error with Unhelpful Messages

### ISSUE THREAD

**Issue by JulianKnodt** [mitsuba-renderer/mitsuba2#242]
## Summary

After successfully compiling `gpu_autodiff_rgb`, errors are unhelpful when missing shared libraries, such as
`cuda_check(): runtime API Error = 0999 "cudaErrorUnknown" in ../ext/enoki/src/cuda/jit.cu:279`

or

`rt_check(): OptiX API error = 7200 (Invalid PTX input) in ../src/librender/scene_optix.inl:100`

## System configuration

`gcc-8` for compilation with `nvcc`, `clang-9` for compilation with mitsuba. Python3.7, variants `scalar_rgb` & `gpu_autodiff_rgb`, Running on a shared linux cluster which I believe is `x86_64`. I was running from `origin/master`, but might've been a bit behind the latest commits by about a week.

## Description

Compilation of the system completes successfully, but upon running, a runtime errors pops which does not clearly delineate what is missing from the system. Notably, running `ldd` on the binary seems to show that all dynamically loaded libraries are met, but a runtime error occurs. Currently, I have no idea why I'm receving
`rt_check(): OptiX API error = 7200 (Invalid PTX input) in ../src/librender/scene_optix.inl:100`.

## Steps to reproduce

The only real way to reproduce is to run on the system I'm using with my exact configuration, but if I had more specific error messages I could figure out what is missing and how to reproduce elsewhere.

- Small note: I also submitted a request for Cuda 11. This issue is for a completely different system which I attempted the same thing on.

**Comment by Speierers** [comment]
Hi @JulianKnodt ,

We are aware that those optix/cuda error messages are sometimes unhelpful. We will address this in the current refactoring of the whole codebase for sure.

Regarding your problem, one thing you could try is to generate the PTX kernels your self:
```
cd mitsuba/resources/ptx
make
```
see if this solves you issue.

**Comment by JulianKnodt** [comment]
ah yes, I'm not sure if it solves it, as I'm not getting an error that it cannot find `optix.h`, so once I get that sorted I'll see if that helps!

**Comment by Yingyan-Xu** [comment]
@JulianKnodt I got the same error that it cannot find `optix.h`. Did you solve it?

**Comment by JulianKnodt** [comment]
ah I was running on a shared server where I didn't have direct access to the resources, so I think I had to expose something more to my local env to get it to work. It probably depends a lot on your specific environment to debug by checking in usr/lib/ to see if the correct nvidia headers are there

**Comment by Spandan-Madan** [comment]
@JulianKnodt Could you share what solved your problem? I am also running mitsuba on a shared machine and getting the same error - 

`cuda_check(): runtime API Error = 0999`.  

When I tried to make PTX kernels myself as suggested by @Speierers above I too get the error:-

`optix.h: No such file or directory`

**Comment by JulianKnodt** [comment]
Hm, for my specific case I believe that the `optix.h` file was not exposed to non-interactive nodes, which can probably solved by adding some configuration to symlink `optix.h` to the environment in the script you're running elsewhere. You'd probably have to download `optix.h` somewhere onto the cluster and then add some linking somewhere.

**Comment by Spandan-Madan** [comment]
Where should the `optix.h` header file be ideally? When I run a find on the entire directory for the file I only get the following files present in the subdirectories: 

```
find mitsuba2/ -name 'optix*'

mitsuba2/build/src/librender/CMakeFiles/mitsuba-render-obj.dir/optix_api.cpp.o
mitsuba2/include/mitsuba/render/optix
mitsuba2/include/mitsuba/render/optix_api.h
mitsuba2/resources/ptx/optix_attr.cu
mitsuba2/resources/ptx/optix_attr.ptx
mitsuba2/resources/ptx/optix_rt.cu
mitsuba2/resources/ptx/optix_rt.ptx
mitsuba2/src/librender/optix
mitsuba2/src/librender/optix/optix_rt.cu
mitsuba2/src/librender/optix_api.cpp
mitsuba2/src/shapes/optix

```

Am I missing some subdirectory where this header file should be? Or am I looking in the wrong place?

**Comment by JulianKnodt** [comment]
it's probably looking inside of your `/usr/include/` directory, but I'm not particularly sure

**Comment by Spandan-Madan** [comment]
Ran find on the entire docker container and there's no `optix.h` anywhere so I guess I will have to download it from somewhere. Any ideas how I should go about that?

**Comment by JulianKnodt** [comment]
Er, this is a bit out of my scope, but I imagine either you want to link your machine's [cuda from outside](https://stackoverflow.com/questions/35230475/symbolic-link-host-to-docker-container), or build your docker container from the official [nvidia one](https://hub.docker.com/r/nvidia/cuda/). I'm not sure which works, but it's probably the symlinking one because the docker cuda might not match the machines

**Comment by Spandan-Madan** [comment]
The issue got resolved for me by installing a higher nvidia-driver that comes pre-installed with optix 7. Specifically, I'm using:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:03:00.0 Off |                  N/A |
| 23%   38C    P0    52W / 250W |      0MiB / 12194MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

It is important to note that updating the driver requires a few reboots, and it is important to ensure that there are no old bits remaining from previous nvidia driver/cuda versions.

Closing the issue, thanks for all your help @JulianKnodt and @Speierers!

**Comment by Speierers** [comment]
This is great to hear! Should I close this issue then?

**Comment by JulianKnodt** [comment]
Considering that this issue is really specific to the instances being run on, and for these specific cases the issue was resolved, it'd probably be good to close this and direct future issues of the same kind here and if there's a difference handle it individually, but up to y'all

**Comment by Speierers** [comment]
Great, thanks @JulianKnodt

**Comment by karticsubr** [comment]
I observe this error after 'waking up' Ubuntu 20.04. Fixed by a reboot.
