### ISSUE TITLE
[❔ other question] Track autodiff across numpy/torch conversions?

### ISSUE THREAD

**Issue by JulianKnodt** [mitsuba-renderer/mitsuba2#244]
## Summary

Will Enoki track autodiff across calls to Numpy? I want to convert an enoki array to a flat set of floats, and this is much easier in Numpy than in Enoki, but I'm worried that if I do so it will not be able to backpropogate gradients properly, and wanted to check whether it was possible to do so using either torch or numpy?

I suspect the answer is no because it seems like Enoki is meant to be embedded in torch graphs, rather than vice-versa.

I also realize this is much more specific to Enoki than Mitsuba, but I am using Mitsuba and Enoki feels to be part of the ecosystem.

I was also wondering if it was possible to add a pytorch computation graph inside of an enoki one?

If this is not possible, does the python API support arbitrary nested arrays with `cuda_autodiff`?

**Comment by Speierers** [comment]
Indeed, futher computations on the "converted" numpy array won't record anything in the autodiff graph.

I am not sure to understand what you mean by "I want to convert an enoki array to a flat set of floats"? This is probably similar to the `ravel()/unravel()` function here: [invert_heightfield.py](
https://github.com/mitsuba-renderer/mitsuba2/blob/70af33ff4d69e6d14205f1826d63c9cf0bdcb639/docs/examples/10_inverse_rendering/invert_heightfield.py)

> I was also wondering if it was possible to add a pytorch computation graph inside of an enoki one?

please refer to the [enoki doc](https://enoki.readthedocs.io/en/master/autodiff.html?highlight=pytorch#interfacing-with-pytorch) for this.

> If this is not possible, does the python API support arbitrary nested arrays with cuda_autodiff?

If you mean `CUDAArray<CUDAArray<float>>` then the answer is no unfortunately. But you can have a `CUDAArray` inside any number of nested static arrays like: `Array<Array<Array<CUDAArray<float>, 3>, 4>, 5>`

**Comment by JulianKnodt** [comment]
ah yes I expected in the python API that something like `[*Vec3f, *Vec2f]` might return `[Float, Float, Float, Float, Float, Float]`, but I guess it needs to be done manually.

How would I go about using `Array<Array<Array<CUDAArray<float>, 3>, 4>, 5>` in the python API? all I see in `enoki.cuda_autodiff` is fixed sized arrays, but I might've missed something.

**Comment by Speierers** [comment]
> ah yes I expected in the python API that something like [*Vec3f, *Vec2f] might return [Float, Float, Float, Float, Float, Float], but I guess it needs to be done manually.

That you will have to do manually (just call ravel twice)

> How would I go about using Array<Array<Array<CUDAArray<float>, 3>, 4>, 5> in the python API? all I see in enoki.cuda_autodiff is fixed sized arrays, but I might've missed something.

It isn't exposed in python, although you can add it yourself (see `ext/enoki/src/python/cuda_4d.cpp` for instance.

> I really just want to perform matrix multiplication of arbitrary size, and I can simulate that by taking multiple dot products of vectors, but the vector I want to take the dot product of is length > 4, and I'm unsure how to proceed with that.

Please keep in mind that enoki is not a "tensor" library so to say. For this it might be easier to convert you enoki array into pytorch tensor and do the operations there.

**Comment by JulianKnodt** [comment]
Ah yea, the main issue is backprop integration from enoki into pytorch. I was hoping to be able to just avoid that by having a naive version, but if there's an easy integration in that direction that would be convenient as well. I think I only saw docs for Pytorch -> Enoki and not vice-versa.

**Comment by Speierers** [comment]
So you need to do `enoki -> pytorch -> enoki` for some reason?

**Comment by JulianKnodt** [comment]
ah just `enoki -> pytorch`, but if that's supported then it should be automatic to go `enoki -> pytorch -> enoki` because `pytorch -> enoki` is already supported

**Comment by Speierers** [comment]
I believe there is a `my_enoki_array.pytorch()` method to do the `enoki -> pytorch` conversion.

**Comment by JulianKnodt** [comment]
ah yea but will it track autodiff across that? You did mention that [converted `numpy`](https://github.com/mitsuba-renderer/mitsuba2/issues/244#issuecomment-671761484) arrays will not but will torch arrays?

**Comment by Speierers** [comment]
> ah yea but will it track autodiff across that? You did mention that converted numpy arrays will not but will torch arrays?

I believe that calling `.backward()` on the subsequent pytorch variable should propagate the gradients to the enoki graph. I don't have much experience with this myself. The best is to give it a try ;)

> Also, somewhat unrelated, but is there a way to specify the number of items processed at ones during GPU rendering? I run out of memory with the default but am ok with slower renderings.

You can split a render job into passes with the `samples_per_pass` property of the integrators.

> Hm, I continue to have questions, is there some more convenient way to ask in a batch?

For now github issues is the way to go for questions. We might setup a different channel/forum in the future. Although please open seperate issues if you have many questions, it is easier to follow.

Can I close this issue then?

**Comment by JulianKnodt** [comment]
Yup feel free to close it! Will try to separate issues from now on, but I might have quite a few.
