### ISSUE TITLE
❔ other question - Input arrays/objects directly into scene instead of using files

### ISSUE THREAD

**Issue by Samia067** [mitsuba-renderer/mitsuba2#246]
## Summary 
You can specify shapes as ply files, reflectance maps as texture files, etc in a scene. And for that the documentation states that you insert the name of the desired texture/ply file into the xml file. However, can I insert shapes, reflectance maps and environment maps as arrays / mesh objects instead of files?

## Description

I am using Mitsuba2 as part of a bigger model. My model outputs a depth map, environment map and a reflectance map which I want to pass to mitsuba2. The documentation states one way of passing these parameters into a scene by specifying a filename which stores the shape/reflectance/envmap information. However, if I save the arrays as files and then insert to mitsuba2, then the whole pipeline is not differentiable any more. So I wanted to know if there is a way to insert these arrays/objects directly into mitsuba2 instead of inserting filenames into the scene. 

Thanks for any help!

**Comment by Speierers** [comment]
Hi @Samia067 ,

For this, you should take a look a the python bindings ans the `traverse()` method. This can be used to access and modify elements of the scene, for instance data buffers of some textures or the vertex position of a mesh.

Have a look at the [inverse rendering tutorials](https://mitsuba2.readthedocs.io/en/latest/src/inverse_rendering/diff_render.html) in the doc. It uses this quite a lot.

**Comment by merlinND** [comment]
Hi @Samia067,

The type of your new data should match the previous type of `params['PLYMesh.bsdf.diffuse_reflectance.data' ]`. Depending on your application, it's most likely an Enoki CUDA array (that lives on the GPU).

The following should work:

```python
key = 'PLYMesh.bsdf.diffuse_reflectance.data' 
tp = type(params[key])
params[key] = tp(new_array)
```

**Comment by Samia067** [comment]
Hello @merlinND,

Thank you for your input. I tried the approach you mentioned but still get the same error when I call params.update(). I do not get any error messages when assigning the actual array to params[key].

**Comment by Samia067** [comment]
I figured out the issue. I was mistakenly assigning a new reflectance of a different shape compared to the original reflectance. Once I fixed the shape, I could get it learn the textured reflectance. 
Thanks for your help!
