### ISSUE TITLE
[❔ other question] Acoustic rendering

### ISSUE THREAD

**Issue by LeonardEyer** [mitsuba-renderer/mitsuba2#247]
## Summary
Looking for insights into the process of extending mitsuba2 for acoustic rendering using ray tracing.

## Description
Since ray acoustic rendering follows similar concepts as ray graphic rendering methods I am curious if it is plausible to use mitsuba2 for this purpose. In general, the rendering equation has to be extended by the time dependency since propagation delays are important for correct auralization. As far as I can tell from the source code rays and interactions already store a time record. Could this record be used for that purpose? Since mitsuba already works with spectra I assume the extension to use the audible spectrum wouldn't be much of a problem. 

To be concrete: I would like to use differentiable ray tracing to generate impulse responses.

Are my assumptions correct? Any hints on challenges that need to be tackled when extending the codebase?

**Comment by Speierers** [comment]
Hi @LeonardEyer ,

This all sounds very interesting!

I do not have much experience with ray acoustic rendering, but the framework is quite flexible so you should be able to write your own integrator plugin and so on to get it to work.

Currently `Ray3f::time` isn't used at all (e.g. would be used for motion blur). In a dynamic scene (moving objects), it would be used to compute the appropriate transforms for every moving object during the ray intersection routines. I guess in your case your scene would be static (no motion) and the integrator would simply update the ray time at every intersection?

Note that it wouldn't be too hard to implement your own ray type, as long as it extends the `Ray` struct.

Hope this helps!

**Comment by LeonardEyer** [comment]
Thanks for the quick Response!
This sounds encouraging. I’ll start out by looking into the Integrators then. And yes the scene would be static.

**Comment by Speierers** [comment]
Good luck!
