### ISSUE TITLE
Custom Integrator with packet_rgb

### ISSUE THREAD

**Issue by AakashKT** [mitsuba-renderer/mitsuba2#249]
Seems similar to #46 , but let me know.
Tried on Ubuntu 18.04 with the "packet_rgb" variant.

Using the direct integrator example, I get the following error message:
```
make_tuple(): unable to convert argument of type 'mitsuba::RayDifferential<mitsuba::Point<enoki::Packet<float, 8ul>, 3ul>, mitsuba::Color<enoki::Packet<float, 8ul>, 3ul> >' to Python object
```

Thanks!
Aakash

**Comment by Speierers** [comment]
Yes it is similar. We are currently refactoring the whole codebase and this issue will be solved once we are done. Stay tuned ;)
