### ISSUE TITLE
[❔ other question] User-defined BRDF function

### ISSUE THREAD

**Issue by seashell123** [mitsuba-renderer/mitsuba2#250]
Is it currently possible to use a user-defined BRDF function for rendering? Instead of specifying a constant BRDF type and parameters for an object in XML format, I would like to have Mitsuba query my user-defined function that takes in (1) 3D position, (2) incoming direction, and (3) outgoing direction, and outputs the corresponding BRDF.

**Comment by Speierers** [comment]
Hi @seashell123 ,

Yes this is possible by creating your own BSDF plugin. For instance, just copy paste the `diffuse.cpp` file, change the name of the BSDF and edit the `eval()`, `pdf()` and `sample()` methods.

Note that you can also do this directly in Python: 
https://mitsuba2.readthedocs.io/en/latest/src/advanced_topics/custom_plugins.html
