### ISSUE TITLE
Custom python BRDF runtime error

### ISSUE THREAD

**Issue by nmatsuda** [mitsuba-renderer/mitsuba2#253]
I'm trying to copy over the roughconductor BSDF plugin into Python and I'm getting the following error for the 
 scalar_mono_polarized variant:

RuntimeError: Unable to cast Python instance of type <class 'enoki.scalar.Matrix4f'> to C++ type 'enoki::Matrix<mitsuba::Color<float,1>,4>'

It runs fine with scalar_rgb, and given my previous questions about the polarization variants as well as https://github.com/mitsuba-renderer/mitsuba2/issues/46, should I assume this is due to missing bindings?

**Comment by Speierers** [comment]
Hi @nmatsuda,

This indeed looks like missing bindings. 

You could try to add bindings or aliases for it in the `libcore/python/main_v.cpp` file. I think this should work.

We are currently refactoring the whole codebase, including some major changes in enoki and the bindings. Hopefully this issue will go away with those changes. Stay tuned ;)

**Comment by nmatsuda** [comment]
Yep! That worked.
