### ISSUE TITLE
[🐛 bug report] OptiX 7.1 Triggers Crash in Debug Mode (gpu_autodiff_rgb)

### ISSUE THREAD

**Issue by ommaury** [mitsuba-renderer/mitsuba2#254]
## Summary

OptiX 7.1 triggers an crash in **debug** mode when exercising `gpu_autodiff_rgb` variant.

## System configuration

- Platform: Windows 10
- Compiler: Visual Studio 16.6.5
- Python version: 3.7.7
- Mitsuba 2 version: Latest (2fb0c9634e696887fae3921a60818a3a503c892e)
- Compiled variants:
    * `scalar_rgb`
    * `gpu_rgb`
    * `gpu_autodiff_rgb`

## Description

Compiling mitsuba2 against OptiX 7.1 (Driver 451.48) in **debug** mode, I get the following error when running `invert_cbox.xml`, 
```
cuda_check(): runtime API error = 0700 "cudaErrorIllegalAddress" in D:/rnd/mitsuba2/ext/enoki/src/cuda/horiz.cu:88
```
In comparison, OptiX 7.0 did not exhibit this behavior. Inverse rendering problems seem to run fine in **release** mode.

## Steps to reproduce

1. Install OptiX 7.1.
2. Compile mitsuba2 in **debug** mode.
3. Run invert_cbox.xml

**Comment by Speierers** [comment]
Hi @ommaury ,

Thanks for reporting this. We are currently busy with a major refactoring task. I will look into this once we are done.

**Comment by ommaury** [comment]
Thanks for the heads up Sebastien, no rush, just thought I'd mention it.

**Comment by ommaury** [comment]
Looking into this, it turns out that OptiX 7.1 has become sensitive to `infs` and `nans` in debug mode, and mts2 is specifically filling ray data with `nans` at the same time as setting the `ray.maxt` to `inf` for most rays. Trapping both these cases in `scene_optix.inl` fixes the problem.

**Comment by juicyzhucx** [comment]
> Looking into this, it turns out that OptiX 7.1 has become sensitive to `infs` and `nans` in debug mode, and mts2 is specifically filling ray data with `nans` at the same time as setting the `ray.maxt` to `inf` for most rays. Trapping both these cases in `scene_optix.inl` fixes the problem.

Thanks for the heads up, but can you tell me how to change the code in scene_optix.inl, thanks s lot!

**Comment by Speierers** [comment]
In `optix_rt.cu` you can add the following two lines:
```c++
    float mint = params.in_mint[launch_index],
          maxt = params.in_maxt[launch_index];

    // HERE
    if (maxt == CUDART_INF_F)
        maxt = 1e38f;
```

And then recompile the ptx shaders:
```bash
cd resources/ptx
make
```

I will fix this on `master` ASAP

**Comment by Speierers** [comment]
This is fixed on `master` now.

**Comment by juicyzhucx** [comment]
> This is fixed on `master` now.

thank you!
