### ISSUE TITLE
[❔ other question] Preprocessing of Integrator

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [mitsuba-renderer/mitsuba2#257]
## Summary

Is there a preprocessing function for integrators planned?
I'm asking because I'm interested how one would implement a method like VPL into the current system, as in a two pass approach.

**Comment by Speierers** [comment]
I guess this would happen in the `Integrator::render()` function. Current integrators rely on the "default" implementation in `integrator.cpp`. This is how light tracer, bidirectional path tracer or a photon mapper would be implemented. It is probably similar for the VPL stuff?
