### ISSUE TITLE
Geometric differentiation does not yet work

### ISSUE THREAD

**Issue by lvjiahui** [mitsuba-renderer/mitsuba2#26]
In Inverse rendering example  `invert_cbox.py` and `invert_bunny.py`, if I change the differentiated parameters to `vertex_positions` ( which have asterisk (*) on the left ),  I receive the following error:

> RuntimeError: set_gradient(): no gradients are associated with this variable (a prior call to requires_gradient() is required.)

I wonder why  no gradients when they are differentiable? How should I differentiate with them?
Thanks!

**Comment by lvjiahui** [comment]
Tutorial says I don't need to call `requires_gradient()` when I use `optimizer`. If I call it manually the error is still the same.

**Comment by wjakob** [comment]
Hi @lvjiahui,

differentiation of shapes in Mitsuba 2 requires a plugin that is based on a separate paper (http://rgl.epfl.ch/publications/Loubet2019Reparameterizing). We have not released this plugin yet, but we are about to do so. I will ping this ticket once it's ready.

Cheers,
Wenzel

**Comment by LeonidMill** [comment]
Hi @wjakob,

will this plugin also provide a possibility to learn the weight texture for a blended material? And is there a rough timeline for the release? Thanks!

**Comment by mmgutsche** [comment]
Any update on this?

**Comment by merlinND** [comment]
Hi @mmgutsche,
You can track progress on this feature in PR #44.
