### ISSUE TITLE
[🔨 compilation issue] Radiative Backpropagation (2020-08-21)

### ISSUE THREAD

**Issue by diiigle** [mitsuba-renderer/mitsuba2#265]
## Summary

Getting the code from [Radiative Backpropagation (2020-08-21)](https://rgl.epfl.ch/publications/NimierDavid2020Radiative) to run.

## System configuration

- Platform: Docker Ubuntu 18.04
- Compiler: Clang 9
- CUDA: 10.2
- OptiX: 6.5
- Python version: 3.6.9
- Mitsuba 2 version: ?
- Compiled variants:
    * `scalar_rgb`
    * ...

## Description
Thanks @merlinND for releasing the code. Here I'm listing my workarounds to get it working. Hopefully it will save somebody some time.
The packaged source code comes with some missing submodules, and potential upstream fixes.

## Steps to fix

1. Compilation issues with `ENOKI_PYTHON` (`pybind11_*` cmake command not found) and missing headers from the `cub` library are due to missing submodules in `ext/enoki/ext/`
   ```
   cd mitsuba2/ext/enoki
   git init
   git submodule init
   git submodule add https://github.com/NVlabs/cub ext/cub
   git submodule add https://github.com/pybind/pybind11 ext/pybind11
   git submodule update --init --recursive
   ```
2. If you experience issues compiling it without GL headers you can backport https://github.com/mitsuba-renderer/mitsuba2/commit/ff23f86ea5ecb9b3abb5855f4b0cc1158d454cce
3. If you have a non-default installation of OptiX, make sure it is in your `LD_LIBRARY_PATH`
4. With my setup I ran into #27 again. 
5. As suggested in the README, multi-gpu setups need `CUDA_VISIBLE_DEVICES=0/1` or you will get
   ```
   INFO  main [Scene] Validating and building scene in OptiX.                                                                                                                                                                  
   cuda_check(): driver API error = 0700 "CUDA_ERROR_ILLEGAL_ADDRESS" in ../ext/enoki/src/cuda/jit.cu:1446.                                                                                                                                        
   cuda_check(): runtime API error = 0700 "cudaErrorIllegalAddress" in ../ext/enoki/src/cuda/jit.cu:148. 
   ```

**Comment by merlinND** [comment]
Hello @diiigle,

Thanks a lot for reporting your findings, this was super helpful!

1. I found the bug responsible in my archive preparation script: submodules that appear more than once in the tree were only exported once.
2. I've backported the commit to disable building the GUI by default. And anyway, there was no actual GUI to build.
3. and 4.: Added a note in the README.

I've updated the code archive with these fixes. Thanks again!
Merlin
