### ISSUE TITLE
- [🐛 bug report] mtsgui GLFW error 65545

### ISSUE THREAD

**Issue by RomboDev** [mitsuba-renderer/mitsuba2#269]
## Summary

Can't run mtsgui :(

## System configuration

- Platform: ubuntu 18.04.3
- Compiler: clang-9
- Python version: 3.7.5
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
- OpenGL:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 740M/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 440.100
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 440.100
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 440.100
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

## Description

Running mtsgui gives me back this:

> GLFW error 65545: GLX: Failed to find a suitable GLXFBConfig
> Could not allocate floating point framebuffer, retrying without..

## Steps to reproduce

I simply start the mtsgui by drag and drop it in a terminal.
NANOGUI backend is OpenGL. Everything else is default.
I run other sw that uses nanogui with no problems at all.

**Comment by Speierers** [comment]
Hi @RomboDev ,

`mtsgui` isn't supported/maintained ATM. So it is very likely that it doesn't compile or run on your system. 

We will get back to it at some point, but it isn't on our priority list.

Cheers
