### ISSUE TITLE
[❔ other question]  Camera coordinate system convention?

### ISSUE THREAD

**Issue by Kai-46** [mitsuba-renderer/mitsuba2#271]
Great work! What is the convention for camera coordinate system in Mitsuba? Is it the same as **opencv**, i.e., x axis points right, y axis points down, z axis points towards scene,or **opengl**, i.e., x axis points right, y axis points up, z axis points away from scene? Meanwhile, when we set up a camera with 4x4 matrix in the xml file, does the matrix represent camera-to-world transformation or world-to-camera transformation? Thanks in advance for the clarification.

**Comment by Speierers** [comment]
Hi @Kai-46 ,

> What is the convention for camera coordinate system in Mitsuba?

Looking at `look_at()` in `transform.h`: x axis points right, y axis points down, z axis points towards scene

> Meanwhile, when we set up a camera with 4x4 matrix in the xml file, does the matrix represent camera-to-world transformation or world-to-camera transformation? Thanks in advance for the clarification.

It represents camera-to-world transformation (see `perspective.cpp` doc)

**Comment by Kai-46** [comment]
Hi @Speierers ,

Thanks for replying. But "x axis points right, y axis points up, z axis points towards scene" is a left-handed coordinate system. Wasn't it a right-handed coordinate system, which leads to "x axis points left, y axis points up, z axis points towards scene"?

**Comment by Speierers** [comment]
You are right, x points left. Sorry for the confusion.
