### ISSUE TITLE
[🐛 bug report] Importing mitsuba and pytorch at the same time causes an error

### ISSUE THREAD

**Issue by Mine-525** [mitsuba-renderer/mitsuba2#273]
## Summary
I tested a example code `invert_cbox_torch.py` for my research, but importing mitsuba and pytoch in  one script causes some errors.
Importing only one module, e.g., import only mitsuba or pytorch, doesn't generate error and a module can be imported correctly.
Only importing both two modules generates error.

## System configuration
- Platform: Windows10
- Compiler: Visual Studio 2019
- Python version: 3.8.3
- CUDA: 10.2
- Optix: 7.0.0
- pytorch: 1.6, 1.5
- Mitsuba 2 version: 
(latest version) [2fb0c96](https://github.com/mitsuba-renderer/mitsuba2/commit/2fb0c9634e696887fae3921a60818a3a503c892e), (ver. 2.1.0) [c3d2bbb](https://github.com/mitsuba-renderer/mitsuba2/commit/c3d2bbb8249522cf9428bfa00e8b2c1cd9cf38ef)
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
    * `gpu_rgb`
    * `gpu_autodiff_rgb`

## Description
To use mitsuba and pytorch, I tested `invert_cbox_torch.py`, but importing mitsuba and pytorch generates error.
Importing each one module works well, but
```
import mitsuba
mitsuba.set_variant("gpu_autodfiff_rgb")
import torch
```
generates an error below.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mineg\miniconda3\lib\site-packages\torch\__init__.py", line 116, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\USERNAME\miniconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```

Furthermore, when the order of import is switched, i.e., 
```
import torch
import mitsuba
```
causes an error,
```
Traceback (most recent call last):
  File "C:\Users\USERNAME\mitsuba2\build\dist\python\mitsuba\__init__.py", line 12, in <module>
    _import('mitsuba.core_ext')
  File "C:\Users\USERNAME\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing core_ext: The specified procedure could not be found.+

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mineg\mitsuba2\build\dist\python\mitsuba\__init__.py", line 33, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported.
```
occurs.

I tried to reinstall miniconda, cuda, optix and mitsuba, but this problem can't be solved.
Can anyone reproduce this problem?

## Steps to reproduce
In console, run python, and import mitsuba and pytorch

**Comment by realWDC** [comment]
Putting `import torch` before importing any mitsuba modules works for me.

**Comment by Mine-525** [comment]
Thank you for your reply, @realWDC.
I recovered OS and reinstall all applications, but it can't solve this problem.
Can you tell me your system configuration, e.g., python, mitsuba and pytorch?

**Comment by realWDC** [comment]
I am on Ubuntu 18.04 with Python 3.7.6 miniconda, Mitsuba latest version, torch 1.6.0.

**Comment by Mine-525** [comment]
Thank you for your answer.
Unfortunately, I tried with your configuration except OS, but it can't solve the problem...

Anyway, your replies are very helpful for me!

**Comment by ommaury** [comment]
Hi, fwiw, I experience the same problem on windows, i.e. get exactly the same errors reported above.

**Comment by Mine-525** [comment]
Hi, @ommaury. Thank you for your reply.
Did you solve the problem?

**Comment by ommaury** [comment]
Nope, sorry, I haven't really looked at it: I'm just confirming that this is prob a pervasive issue on windows.

**Comment by AirGuanZ** [comment]
Hi, I have exactly same problem on Windows.

I guess this is caused by different lib versions. For example, both mitsuba2 and pytorch (directly or indirectly) depend on asmjit, but symbol names in those two dlls are quite different. Once we import one of them, another one will be very likely to fail to find required precedures in the dll, which is loaded by previous import. I have only checked asmjit only. Not sure whether this problem exists in other external libraries.

**Comment by wjakob** [comment]
Can you try adding
```
set_property(TARGET asmjit PROPERTY OUTPUT_NAME "asmjit-mitsuba")
```
to the main `CMakeLists.txt`?

**Comment by AirGuanZ** [comment]
It works for me. Looks like dll conflict is the root cause.
Thanks!

**Comment by Mine-525** [comment]
Thank you for your solution, @wjakob. And thank you for your reply, @AirGuanZ .
I added the code in `mitsuba2/CMakeLists.txt` and compiled without any error, but unfortunately, I can not import mitsuba in python with a error message below, 
```
Traceback (most recent call last):
  File "C:\Users\USERNAME\mitsuba2\build\dist\python\mitsuba\__init__.py", line 12, in <module>
    _import('mitsuba.core_ext')
  File "C:\Users\USERNAME\Miniconda3\envs\mitsuba\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: specified module can not be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\USERNAME\mitsuba2\myscripts\gen_train\gen_train.py", line 5, in <module>
    import mitsuba
  File "C:\Users\USERNAME\mitsuba2\build\dist\python\mitsuba\__init__.py", line 33, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported.
```

I just add 
```
set_property(TARGET asmjit PROPERTY OUTPUT_NAME "asmjit-mitsuba")
```
at the end line of `CMakeLists.txt`, but is it correct?
I can import mitsuba if the code is not added.

**Comment by AirGuanZ** [comment]
Try adding  :

```cmake
set_property(TARGET asmjit PROPERTY OUTPUT_NAME "asmjit-mitsuba")
```

to `mitsuba2/ext/CMakeLists.txt`, after line 237. That is:

```cmake
if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "x86_64|AMD64")
  # Build asmjit
  set(ASMJIT_BUILD_X64 TRUE)
  if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-inconsistent-missing-override -Wno-undefined-inline")
  endif()
  add_subdirectory(asmjit)
  set(ASMJIT_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/asmjit/src PARENT_SCOPE)
  set_property(TARGET asmjit PROPERTY FOLDER "dependencies")
  if (MSVC)
    target_compile_options(asmjit PRIVATE "/wd4804" "/wd4838")
  endif()
  set_property(TARGET asmjit PROPERTY OUTPUT_NAME "asmjit-mitsuba")
endif()
```

And remeber to restart the terminal after recompile mitsuba.

**Comment by Mine-525** [comment]
Thank you for quick response and detailed answer, @AirGuanZ.
It works, and I can import both mitsuba and pytorch!

**Comment by wpalfi** [comment]
Thank you! I can confirm that the `asmjit-mitsuba` solution works with pytorch 1.7.1.
Any reason why you dont make this the default name?

**Comment by derrick-xwp** [comment]
Is this fix successfully commited into mitsuba-renderer/mitsuba2?

**Comment by njroussel** [comment]
Hi @derrick-xwp
No, it doesn't look like this was ever committed. You would need to do the changes yourself and re-compile the project if you're encountering the same issue.
