### ISSUE TITLE
[✨ feature request] roughplastic texture input for alpha/roughness

### ISSUE THREAD

**Issue by Xenation** [mitsuba-renderer/mitsuba2#275]
## Summary

Implement support for texture type in the `alpha` parameter of the `roughplastic` BSDF.

## Description

Currently the `roughplastic` BSDF does not seem to support using a texture for the `alpha` (driving the roughness) parameter. In contrast `roughconductor` and `roughdielectric` both support a texture for this parameter, so it seems logical that `roughplastic` should support it too.

**Comment by Speierers** [comment]
Hi @Xenation ,

We are well aware of this limitation. The `roughplastic` plugin precomputes some `transmittance` tables in its constructor, which depend on the `alpha` parameter. Adding support for a textured `alpha` parameter means that such tables would need to be precomputed for every values in the texture. This is quite involved and we would need to come up with a good solution for this.

We will look into this issue in the future. Although it is pretty low on our priority list, so I would recommend that you stick with the `roughconductor` plugin for now if you need textured `alpha`.

**Comment by GuillaumeLeclerc** [comment]
Also very interested in this!
