### ISSUE TITLE
[❔ other question] Manually updating positions is not reflected in scene.

### ISSUE THREAD

**Issue by TuurStuyck** [mitsuba-renderer/mitsuba2#276]
## Summary

When manually setting the positions for one of the boxes in the Cornell box, the scene is not updated properly. When manually calling `parameters_changed()` on the object, the code crashes when calling `recompute_bbox()` in `librender/mesh.cpp`. 

## System configuration

- Platform: Windows 10
- Python version: 3.8
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
    * `gpu_autodiff_rgb`

## Description

Starting from the Cornell box example used in `docs/examples/10_inverse_rendering/invert_cbox`, I am trying to modify the code to change the position of the smaller box. More precisely, I translate all vertices by (200.0, 200.0, 200.0). This should look something like this:

![Capture](https://user-images.githubusercontent.com/10683749/93161858-4af9d300-f6c8-11ea-96ac-821dcdd0ca04.JPG)

Instead, this is the render I get:

![out_Initialization](https://user-images.githubusercontent.com/10683749/93161325-2ea96680-f6c7-11ea-9387-9ed9ecef3d30.png)

It looks like the smaller box has the shading correctly updated (e.g. brighter on top and the black surfaces due to occlusion of now being inside the larger box), however, the positions are not correct in the render.

For comparison, this is the original Cornell box scene rendered without modifications 

![out_ref](https://user-images.githubusercontent.com/10683749/93162459-ae383500-f6c9-11ea-8162-e64e7e058cbb.png)

When I call `m.parameters_changed()` on the object, this triggers a crash in `recompute_bbox()` when retrieving `vertex_position(i)`. Alternatively, using `params.set_dirty(varToOptimize)` and `params.update()` also causes the same crash.

Calling `write_ply` on the object before and after the translation confirms that the translation is applied correctly to the small box in the Cornell box.

## Steps to reproduce

Run accompanied script with the Cornel box scene:
[question.txt](https://github.com/mitsuba-renderer/mitsuba2/files/5222335/question.txt)

**Comment by Speierers** [comment]
Hi @TuurStuyck ,

Sorry for replying so late.

Indeed the `bbox` of the smaller box will only get updated once you call `m.parameters_changed()` (or alternatively `params.set_dirty(..) + params.update()`).

How do you update the `vertex_position` buffer exactly? You can take a look at this [tutorial](https://github.com/mitsuba-renderer/mitsuba2/blob/70af33ff4d69e6d14205f1826d63c9cf0bdcb639/docs/examples/10_inverse_rendering/invert_pose.py) which shows how to optimize the pose of an object in the scene.

Cheers!

**Comment by TuurStuyck** [comment]
Hi @Speierers ,

Thank you for the reply. The problem is that calling `m.parameters_changed()` triggers a crash in the cpp function `recompute_bbox()`.

I am updating the positions as follows:

```
param_ref = params[varToOptimize]
param_start = copy.copy(param_ref.numpy())
for i in range(0, len(param_start), 1):
    #move all vertices of cbox_smallbox
    param_start[i] += 200.0
    
tp = type(params[varToOptimize])
params[varToOptimize][:] = tp(param_start)
```

Any pointers are greatly appreciated.

Thank you!

Copied the whole script here for your convenience

```
import enoki as ek
import mitsuba
import copy
mitsuba.set_variant('gpu_autodiff_rgb')

from mitsuba.core import Float, Thread, Color3f
from mitsuba.core.xml import load_file
from mitsuba.python.util import traverse
from mitsuba.python.autodiff import render, write_bitmap, Adam
import time

Thread.thread().file_resolver().append('cbox')
scene = load_file('cbox/cbox.xml')

# Find differentiable scene parameters
params = traverse(scene)
# Discard all parameters except for one we want to differentiate
varToOptimize = 'OBJMesh_6.vertex_positions_buf'
ek.set_requires_gradient(params[varToOptimize])
params.set_dirty(varToOptimize)
params.keep([varToOptimize])
params.update()
assert scene.shapes_grad_enabled() == True

# Render a reference image (no derivatives used yet)
image_ref = render(scene, spp=8)
crop_size = scene.sensors()[0].film().crop_size()
write_bitmap('out_ref.png', image_ref, crop_size)

param_ref = params[varToOptimize]
param_start = copy.copy(param_ref.numpy())
for i in range(0, len(param_start), 1):
    #move all vertices of cbox_smallbox up
    param_start[i] += 200.0
    
tp = type(params[varToOptimize])
params[varToOptimize][:] = tp(param_start)

m = scene.shapes()[6]
#m.parameters_changed() # <- this triggers the crash in recompute_bbox()
# Alternatively using set_dirty will also trigger the same bug
#params.set_dirty(varToOptimize) # commenting both will give us the wrong render
#scene.parameters_changed() # seems to have no effect
params.update() 

image_ref = render(scene, spp=8)
crop_size = scene.sensors()[0].film().crop_size()
write_bitmap('out_Initialization.png', image_ref, crop_size)

```

**Comment by Speierers** [comment]
It might be that when overriding the `vertex_position_buffer` in your python script, the resulting `CUDAArray` is located on the device only. Therefore I won't be accessible from the CPU, causing the crash in the `recompute_bbox()` call.

To make it accessible from both the GPU and CPU, we need to use managed memory for this buffer. It can be achieve by calling `.managed()` on a `CUDAArray`. This is done in the various `Mesh/PLY/OBJ` constructors.

Could you try to add a call to `m_vertex_positions_buf.managed();` in the `Mesh::parameters_changed()` method (right before the `cuda_eval()` call. This is very likely going to fix your issue.

This problem will be fixed in the upcoming refactored codebase as this whole memory management is done differently.

**Comment by TuurStuyck** [comment]
Thanks @Speierers! This does indeed fix the crash. Unfortunately, the render is still wrong so I will have to look into it some more.

**Comment by kopetri** [comment]
This problem seems to persist. Is it really fixed in the refactored codebase?

**Comment by Speierers** [comment]
Hi @kopetri ,

Yes it should be fixed. Which version (commit) of the codebase are you using?

**Comment by TigerHix** [comment]
@Speierers Same issue here. I am using the latest commit, and `params.set_dirty() / params.update()` seems not updating the vertex positions correctly. I have followed [invert_pose.py](https://github.com/mitsuba-renderer/mitsuba2/blob/70af33ff4d69e6d14205f1826d63c9cf0bdcb639/docs/examples/10_inverse_rendering/invert_pose.py) (which was removed from the latest codebase for some reason?) and modified the vertex to translate the small box by (200.0, 200.0, 200.0), same as OP's scenario. The first rendered image is as below:

![image](https://user-images.githubusercontent.com/3406505/142093393-75636306-261a-4d64-a0eb-180ee725a42f.png)

The shading is updated but not the vertices.

**Comment by TigerHix** [comment]
A side note: I have verified that once I applied the transformation, the `bbox` and `vertices` of the small box `OBJMesh` are indeed updated in the `Scene` node, but the changes are just not reflected in the render. @Speierers Could you provide some pointers on this? Thanks!

**Comment by Speierers** [comment]
Hi @TigerHix 

Could you try to call `ek.cuda_eval()` and `ek.cuda_sync()` after the call to `params.update()`. This might solve your issue.
