### ISSUE TITLE
[✨ feature request] depth integrator no-intersection value

### ISSUE THREAD

**Issue by frautschmied** [mitsuba-renderer/mitsuba2#277]
It's hardcoded to 0.f
Maybe make it softcoded?

**Comment by joeylitalien** [comment]
Seems like something you could easily implement yourself, no? Create a new integrator from `src/integrators/depth.cpp`, add it to `src/integrator/CMakeLists.txt` and pass your desired value in the constructor via `props`. You can look at other integrators to see how to get the syntax right.

**Comment by Speierers** [comment]
Hi @frautschmied,

I will let you change this on your own if it is useful to you. This is not something we will change on the master version of Mitsuba.

Cheers.
