### ISSUE TITLE
[❔ other question] Setting log level in Python

### ISSUE THREAD

**Issue by joeylitalien** [mitsuba-renderer/mitsuba2#280]
## Description
Is there a way to specify the log level in Python? I'm using Mitsuba as part of a deep learning training pipeline and I would like to decrease the log level to a minimum to avoid contaminating my logs with BVH construction & tracing stats everytime I render. I've written a quiet mode by simply adding a new `LogLevel` to `include/core/logger.h` that works well for the CLI, but ideally I would be able to change this in Python to match my logger behavior. The syntax I'm looking for is something similar to `Logger.set_log_level(...)` that could be added after specifying a Mitsuba variant.

Any tips how this could be achieved?
Thanks! :slightly_smiling_face:

**Comment by Speierers** [comment]
You should be able to do something like this:
``` python
from mitsuba.core import Thread, LogLevel
Thread.thread().logger().set_log_level(LogLevel.Error)
```

**Comment by garrido-pablo** [comment]
You can additionally decrease the cuda log level:
import enoki as ek
ek.cuda_set_log_level(0)
