### ISSUE TITLE
[❔ other question] Setting bsdf for Mesh instance

### ISSUE THREAD

**Issue by jungbluthb** [mitsuba-renderer/mitsuba2#284]
## Summary

I am trying to create `mitsuba.render.Mesh` instances from numpy arrays representing heightmaps. I succeed in creating and rendering the geometry, but fail in setting defining the used BSDF.

## System configuration

- Platform: openSUSE 15.1 x86_64
- Compiler: Clang 7.0.1
- Python version: 3.7.5
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
    * `packet_rgb`
    * `packet_spectral`

## Description

I am working with meshes created from heightmaps. Since the heightmaps are computed via an interative process I am trying to avoid using files (e.g. ply) for data handling. I want to keep the data in instances of `mitsuba.render.Mesh`. I succeeded in creating and rendering those objects. For this I copied some code from _src/librender/tests/mesh_generation.py_:

    num_steps = 20
    size_step = 1.0 / num_steps
    
    m = mitsuba.render.Mesh("stairs", 4 * num_steps, 4 * num_steps - 2)
    params = mitsuba.python.util.traverse(m)

    v = numpy.zeros((4 * num_steps, 3))
    f = numpy.zeros((4 * num_steps - 2, 3))
    
    for i in range(num_steps):
        h  = i * size_step
        s1 = i * size_step
        s2 = (i + 1) * size_step
        k = 4 * i
        
        v[k + 0] = [0.0, s1, h]
        v[k + 1] = [1.0, s1, h]
        v[k + 2] = [0.0, s2, h]
        v[k + 3] = [1.0, s2, h]
        
        f[k]   = [k, k + 1, k + 2]
        f[k + 1] = [k + 1, k + 3, k + 2]
        if i < num_steps - 1:
            f[k + 2] = [k + 2, k + 3, k + 5]
            f[k + 3] = [k + 5, k + 4, k + 2]
    
    m.vertex_positions_buffer()[:] = v.reshape(-1)
    m.faces_buffer()[:] = f.reshape(-1)
    m.recompute_bbox()
    return m

The created instance m can be rendered fine, but has the default SmoothDiffuse BSDF assigned to it:

    In [238]: m.bsdf()
    Out[238]: 
    SmoothDiffuse[
      reflectance = UniformSpectrum[value=0.500000]
    ]

Now I am struggeling to change this. From the docs I can see that I would be able to change the reflectance value (which is not my goal). But I did not find a way to replace or set the BSDF attribute from SmoothDiffuse to some other BSDF. Maybe someone can give me a hint in how to achieve this.

Thanks in advance!

**Comment by Speierers** [comment]
Mitsuba 2 currently doesn't support adding/setting child `Object` to instances. I would recommand you use the `m.write_ply()` method to write the heightfield mesh to disk and then use it in a scene, assigning the appropriate BSDF.

**Comment by jungbluthb** [comment]
Thank you for the quick answer. SInce my meshes might get quite large I want to avoid writing files to disk. But if I think the other way round, is there a way of modifiying the vertex and triangle buffer of PLY instances?

**Comment by Speierers** [comment]
Yes, using `params = traverse(scene)` to access the scene parameters. You can have a look at the tutorials on differential rendering to see how to use it. You can then call `params.update()` once you're done changing the heighfield.

**Comment by jungbluthb** [comment]
Thank you! I will try it this way.
