### ISSUE TITLE
[🐛 bug report] Unable to add a Texture to Alpha Values

### ISSUE THREAD

**Issue by priyamvad** [mitsuba-renderer/mitsuba2#285]
Mitsuba2 seems to complain with this XML syntax for adding textures to roughness (alpha)
```
	<bsdf type="roughplastic" id="mat-Skin_Blend_01">
		<texture type="bitmap" name="alpha">
			<string name="filename" value="C:\Work\Mitsuba\examples\textures\gray.jpg"/>
		</texture>
		<string name="distribution" value="ggx"/>
	</bsdf>
``` 

I get this error:
``could not instantiate bsdf plugin of type "roughplastic":
[xml.cpp:1047]   [properties.cpp:383] The property "alpha" has the wrong type (expected <float>``

I cannot find any other syntax for texturing a 'float' attribute. Yes I clearly see a rendered example of an alpha-textured widget on the Docs. Could someone please point me in the right direction?
Thank you!

**Comment by priyamvad** [comment]
Oh of course, RoughPlastic alpha cannot be textured as per the docs but RoughDielectric can be?
Could I request RoughPlastic alpha to be exposed as a texturable param as well please? Thanks!

**Comment by Speierers** [comment]
This question was already answered in #275.
