### ISSUE TITLE
[❔ other question] How to make background as the only light source

### ISSUE THREAD

**Issue by 1asso** [mitsuba-renderer/mitsuba2#286]
How do I make the background image as a light source, like LED, each pixel emits a different color of light.
For now, I can only get a background with a single color of light.

Here is the code of background:

<shape type="obj">

    <string name="filename" value="assets/meshes/rectangle.obj"/>

    <bsdf type="diffuse">

      <texture name="reflectance" type="bitmap">

        <string name="filename" value="assets/textures/0696.png"/>

      </texture>

    </bsdf>

    <transform name="to_world">

      <scale value="0.5, 0.5, 0.5"/>

      <rotate angle="180.0" z="1.0"/>

    </transform>

</shape>

**Comment by Speierers** [comment]
Hi @1asso ,

Not sure to understand what you mean by "background image". If your goal is to set an image texture on a 2D plane, and use it as an emitter, then you should take a look at `area` lights. It is possible to use a texture for the `radiance` parameter as follow:

```xml
<shape type="obj">
    <string name="filename" value="assets/meshes/rectangle.obj"/>

    <emitter type="area">
        <texture name="radiance" type="bitmap">
            <string name="filename" value="assets/textures/0696.png"/>
        </texture>
    </emitter>

    <transform name="to_world">
        <scale value="0.5, 0.5, 0.5"/>
        <rotate angle="180.0" z="1.0"/>
    </transform>
</shape>
```

**Comment by 1asso** [comment]
> Hi @1asso ,
> 
> Not sure to understand what you mean by "background image". If your goal is to set an image texture on a 2D plane, and use it as an emitter, then you should take a look at `area` lights. It is possible to use a texture for the `radiance` parameter as follow:
> 
> ```
> <shape type="obj">
>     <string name="filename" value="assets/meshes/rectangle.obj"/>
> 
>     <emitter type="area">
>         <texture name="radiance" type="bitmap">
>             <string name="filename" value="assets/textures/0696.png"/>
>         </texture>
>     </emitter>
> 
>     <transform name="to_world">
>         <scale value="0.5, 0.5, 0.5"/>
>         <rotate angle="180.0" z="1.0"/>
>     </transform>
> </shape>
> ```

**Comment by 1asso** [comment]
Problem solved, thank you very much!
