### ISSUE TITLE
[❔ other question] How to set an image texture on area lights

### ISSUE THREAD

**Issue by hrkd1316** [mitsuba-renderer/mitsuba2#288]
# Summary
I wanted to express similarly to #286 and tried [the solution](https://github.com/mitsuba-renderer/mitsuba2/issues/286#issuecomment-699812002) indicated by @speierers, but an error occurred.

## System configuration
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`

## Description
I ran the code shown in the answer to #286, only changing the file location.
```XML
<shape type="obj">
    <string name="filename" value="../rectangle.obj"/>

    <emitter type="area">
        <texture name="radiance" type="bitmap">
            <string name="filename" value="texture/floor_tiles_bumpmap.png"/>
        </texture>
    </emitter>

    <transform name="to_world">
        <scale value="0.5, 0.5, 0.5"/>
        <rotate angle="180.0" z="1.0"/>
    </transform>
</shape>
```
However, this caused an error in eval_parameterization().

`Caught a critical exception: [Mesh] eval_parameterization(): mesh does not have UV `

What is the solution to this error?

**Comment by merlinND** [comment]
Hi @hrkd1316,
To apply a texture to a mesh (whether it's an area light or a normal surface), the mesh must provide a UV parametrization. The parametrization assigns the 2D position in texture space to lookup for each vertex.

If you open `rectangle.obj`, I'm guessing that you won't see any lines starting with `vt` (these would define the UV mapping).

Blender has tools to automatically create reasonable UV maps for any mesh (e.g. "Smart UV unwrap").

**Comment by merlinND** [comment]
If your mesh is a simple rectangle, you could just add `vt` lines to your OBJ files to assign the 4 corners of UV space to the 4 vertices though. This is an example from `mitsuba-data`:

**Comment by hrkd1316** [comment]
Thanks for the quick answer!
We were able to apply it successfully.
