### ISSUE TITLE
[❔ other question] Timeline of refactoring

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [mitsuba-renderer/mitsuba2#289]
In multiple of the issues I read that you are currently working on a major refactoring of the project.
I just wanted to ask what the timeline is, as it would be interesting when using Mitsuba 2 for other projects.

**Comment by garrido-pablo** [comment]
Will the hair plugin be included in the new version? Just curious as I'm working on my own version currently.

**Comment by Speierers** [comment]
I would rather not proclaim a specific ETA for the release of the refactored codebase as it would probably not be correct. We are making final adjustements and writing documentations at the moment. What I can say is that we hope to release it before the end of the year.

This next release will not contain any new plugins as it mostly concerns the core of the Mitsuba framework and Enoki.

@MajorMeerkatThe3rd we made sure porting existing code to the new version will be effortless. Therefore you should be able to start working with the current `master` branch without worrying about the upcoming refactoring.

Happy to answer any other questions regarding the refactoring!
