### ISSUE TITLE
[❔ other question] Applying a texture to a area light source yields WARN(No sensors found & No integrator found)

### ISSUE THREAD

**Issue by hrkd1316** [mitsuba-renderer/mitsuba2#293]
## Summary
I applied the texture to the area light source and got `No sensors found` and `No integrator found`, which did not give me the desired result.

## System configuration
- Platform: Windows 10 Home
- Mitsuba 2 version: 2.2.0
- Compiled variants:
    * `scalar_rgb`

## Description
I am trying to apply the texture to a simple rectangular area light source. 
The answer to my previous question (#288) allowed me to complete the rendering without outputting any errors.

However, the following WARN is output and the rendered image is a uniform surface light source.
This happens only when applying texture tag to emitter tag.

WARNs
```
2020-10-14 17:13:36 WARN  tbb02 [Scene] No sensors found! Instantiating a perspective camera..
2020-10-14 17:13:36 WARN  tbb02 [Scene] No integrator found! Instantiating a path tracer..
```

code
```
<scene version="2.2.1">
    <integrator type="path"/>

    <sensor type="perspective">
        <transform name="to_world">
            <lookat origin="0, 0, -200"
                    target="0, 0, 0"
                    up="0, 1, 0"/>
        </transform>

        <float name="fov" value="45"/>

        <film type="hdrfilm">
            <string name="pixel_format" value="rgb"/>
            <integer name="width" value="512"/>
            <integer name="height" value="512"/>
        </film>

        <sampler type="independent">
            <integer name="sample_count" value="256"/>
        </sampler>
    </sensor>

    <emitter type="envmap">
        <string name="filename" value="../../museum.exr"/>
    </emitter>

    <shape type="obj" id="my_emitter">
        <string name="filename" value="../rectangle_normals_uv.obj"/>
        <emitter type="area">
            <texture name="radiance" type="bitmap">
                <string name="filename" value="./texture/wood.jpg"/>
            </texture>
        </emitter> 
        <transform name="to_world">
            <rotate x="1" angle="270"/>
            <scale x="30" y="20"/>
            <translate value="0, 0, 10"/>
        </transform>
    </shape>
</scene>
```

output image
![lucy_bssrdf_with_area_emitter](https://user-images.githubusercontent.com/48472692/95964172-798fd880-0e43-11eb-96a8-41ee98aae143.png)

Why do I get this WARN and how do I get a correctly applied light source?

**Comment by Speierers** [comment]
Hi @hrkd1316 ,

Internally, textured emitters create another `scene` (see `Shape::eval_parameterization()`) which only contains a unit square. Eventually it would be good to turn off those warnings in this case.

You're problem must come from somewhere else. It renders fine on my machine when using the `resources/data/common/textures/wood.jpg` texture and the `resources/data/tests/obj/rectangle_normals_uv.obj` mesh. Could you try this?

**Comment by hrkd1316** [comment]
I'm sorry. I checked again and it seemed to be due to the fact that the rendering mode was switched.
Thanks for the advice.
