### ISSUE TITLE
[🔨 compilation issue] Embree not correctly linked to instance plugin

### ISSUE THREAD

**Issue by Microno95** [mitsuba-renderer/mitsuba2#296]
## Summary

When embree support is enabled, the `shapes/instance` plugin does not compile as the embree library is not correctly linked in CMakeLists.txt.

## Description

Essentially, it seems that in `instance.cpp` that when MTS_ENABLE_EMBREE is defined, embree specific headers are included, but the embree libraries are not correctly linked.

Here embree headers are added:
https://github.com/mitsuba-renderer/mitsuba2/blob/fc3ab82dfec18f5c16628721e84f2a0cc5ec3a07/src/shapes/instance.cpp#L10-L13

but here `target_link_libraries` is not called to link the embree libraries:
https://github.com/mitsuba-renderer/mitsuba2/blob/fc3ab82dfec18f5c16628721e84f2a0cc5ec3a07/src/shapes/CMakeLists.txt#L17-L20

The solution is quite simple, the lines 
```cmake
if (MTS_ENABLE_EMBREE)
    target_link_libraries(instance PRIVATE $<TARGET_FILE:embree>)
endif()
```
should be inserted after https://github.com/mitsuba-renderer/mitsuba2/blob/fc3ab82dfec18f5c16628721e84f2a0cc5ec3a07/src/shapes/CMakeLists.txt#L17

Since I wasn't sure how Pull Requests are handled in this repository, I have put the solution here and hope that someone can quickly apply it.

**Comment by Speierers** [comment]
@Microno95 ,

Just fixed this on `master`. Thanks for this!

**Comment by Microno95** [comment]
@Speierers I had originally copied the line from the linking for the `sphere` example, but from further testing, I think the correct line for both is actually `target_link_libraries(instance PRIVATE embree)` and `target_link_libraries(sphere PRIVATE embree)`.

With `$<TARGET_FILE:embree>`, only embree3(.lib/.dll) is included under additional dependencies in VS, but with `embree`, all the compiled embree `.lib`/`.dll` files are included.

Sorry for the incomplete fix! This also solves the issue where plugins/shapes/sphere doesn't compile with embree as a shared library.

**Comment by Speierers** [comment]
Thanks @Microno95.

I didn't try to run it on Windows, that's why I didn't catch this issue. Should be fixed now!
