### ISSUE TITLE
[🐛 bug report] Caught a critical exception: [optix_api.cpp:154] optix_initialize(): could not find symbol optixQueryFunctionTable 

### ISSUE THREAD

**Issue by Spandan-Madan** [mitsuba-renderer/mitsuba2#299]
## Summary

Unable to run gpu_autodiff_rgb mode

## System configuration

Compiled gpu_autodiff_rgb variant on google colab. Colab available here: https://colab.research.google.com/drive/1K2baMP6xLASIgMJnnqerko4-FOosWRb6?usp=sharing

- Compiled variants:
    * `scalar_rgb`
    * `gpu_autodiff_rgb`

## Description

Using scalar_rgb mode works fine, but when I run gpu_autodiff_rgb mode I get the following error:

```
2020-10-21 02:22:55 INFO  main  [optix_api.cpp:56] Dynamic loading of the Optix library ..
Caught a critical exception: [optix_api.cpp:154] optix_initialize(): could not find symbol optixQueryFunctionTable

```

**Comment by Speierers** [comment]
Hi @Spandan-Madan ,

Could you maybe try to install cuda before compiling Mitsuba in this colab notebook?

**Comment by Spandan-Madan** [comment]
@Speierers I tried that as well, I've tried CUDA 10.1 and 11.1 both. I think it has something to do with installation/location of optix when mitsuba2 is compiled.

Acc to compilation instructions: optix comes bundled with the recent nvidia drivers I am currently running driver 418.67 along with CUDA 10.1 as can be seen from this output:

```
Fri Oct 23 00:31:43 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**A couple questions about optix:**

1. Do we need to install optix ourselves, or should it come pre-installed with NVIDIA driver 418.67?

2. In the Makefile for PTX, I can see that it's trying to look for optix at `/opt/optix-7.0.0/include/`, but there is no optix directory under `/opt/`. How should we address this?

**Comment by merlinND** [comment]
Hi @Spandan-Madan,

1. OptiX 7 is part of the driver starting from version 435.80. The version you have only supports OptiX 6.
2. By default, you don't need to provide headers and it won't try to include them unless you have set `MTS_USE_OPTIX_HEADERS` to `ON`:

https://github.com/mitsuba-renderer/mitsuba2/blob/b87c11ace78e110b094b23b83ac5902a4773202d/CMakeLists.txt#L72-L74

**Comment by Spandan-Madan** [comment]
Hey @merlinND, I tried on a machine with Driver version 440.33 and CUDA 10.2 - I can't find optix installed in `/opt/optix` where mitsuba Makefile mentions it should be. 

So, does optix need to be installed separately?

**Comment by Spandan-Madan** [comment]
Surprisingly, it worked on another machine with the exact same cuda version and nvidia driver. I have no clue why or how it worked on one machine but not the other. But, cheers and thanks for all your help @merlinND!

**Comment by merlinND** [comment]
Glad to hear it ended up working!
Are you running within a container in both cases, or directly on the host OS? I'm guessing there's some other component's version that ended up making a difference, but I don't know which.
