### ISSUE TITLE
[❔ other question] differentiate wrt texture patch

### ISSUE THREAD

**Issue by Yingyan-Xu** [mitsuba-renderer/mitsuba2#300]
Hi, I would like to ask whether it is possible to differentiate wrt just a patch of the texture map. I have limited GPU memory but I want to recover high resolution texture map via inverse rendering. I tried both `path` and `pathreparam` integrator. Both seem not to work. What I'm doing now is to define a gpu array varaible that has the same size as the patch I want to recover, and then use `ek.scatter` to substitute the related indices in params in each iteration. I was wondering if it's theoretically infeasible or there're just some bugs in my code. 

Thanks a lot!

**Comment by merlinND** [comment]
Hi @Yingyan-Xu,
The approach you describe sounds like a good way to optimize only a patch of a texture. However, if that's just for memory savings and you'll still end up optimizing the whole texture, I think it's not worth it. In my experience, the resolution of the texture being optimized doesn't matter much for memory usage. The size of the wavefront (image dimensions * spp) matters a lot more.

**Comment by Yingyan-Xu** [comment]
Hi @merlinND, thanks for the suggestion! But I'm working with really high resolution textures (~8k). Just loading the fullsize map takes up a lot memory. I was wondering if it's even possible if I just want to optimize over a small patch, i.e., a subset of entries for `params['diffuse_reflectance']`. Because I the error I encounter now looks like it's not differentiable.

Error message:
`AttributeError: 'dict' object has no attribute 'all_differentiable'`

My code:
```
roi = ek.full(Float, 1.0, len(indices))
ek.set_requires_gradient(roi)
params_optim = {
    'roi_diffuse': roi
}

def update_roi():
    ek.scatter(params[target_param], params_optim['roi_diffuse'], indices)
    params.set_dirty(target_param)
    params.update()

lr = 0.02
opt = Adam(params_optim, lr=lr)

for it in range(iterations):
        image = render(scene, 
                       optimizer=opt, 
                       unbiased=True, 
                       spp=8,
                       pre_render_callback=update_roi)
        ob_val = ek.hsum(ek.sqr(image - image_ref)) / len(image)
        ek.backward(ob_val)
        opt.step()
```

**Comment by Speierers** [comment]
Hi @Yingyan-Xu ,

Are you working on the `master` branch? 

Optimizing variables "eternal" to the scene (e.g. `roi` in your case) isn't supported yet on `master`. You could take a look at the `pathreparam-optix7` branch for this (although it hasn't been updated in a long time).

To work around the error message above, please change line 212 in `autodiff.py`:
```
-     if not params.all_differentiable():
+     if not all(is_differentiable(params[k]) for k in params.keys()):
```

**Comment by Yingyan-Xu** [comment]
Hi @Speierers,

I'm working on the `pathreparam-optix7`. Thanks for your reply and I fixed the bug.

However, I got another error
```
RuntimeError: set_gradient(): no gradients are associated with this variable (a prior call to requires_gradient() is required.) 
```

Simply changing
```
ek.scatter(params['mybsdf.diffuse_reflectance'], params_optim['roi_diffuse'], indices)
```
to 
```
ek.scatter(params['OBJMesh.vertex_positions_buf'], params_optim['roi_diffuse'], indices)
```
I didn't get the error message anymore.

For me it seems that `pathreparam` integrator doesn't work for texture maps yet? (In my case, I only want to optimize wrt a small patch of the bitmap so I define a variable "external" to the scene (`roi`) and substitute that patch in each iteration.)

Thanks a lot!

**Comment by Yingyan-Xu** [comment]
Hi,

Sorry for the confusion! I found it's a bug with my parameter setting of the integrator. Everything works now!
