### ISSUE TITLE
[🐛 bug report] Rendered image is blank with Embree backend

### ISSUE THREAD

**Issue by Microno95** [mitsuba-renderer/mitsuba2#303]
## Summary

When mitsuba2 is compiled with the Embree backend for CPU rendering, the resulting image from the cbox.xml example `resources/data/scenes/cbox` is completely blank with all pixel values set to `(0, 0, 0, 0)`.

## System configuration

- Platform: Windows 10 - OS Build: 19041.572
- Compiler: MSVC Version 19.27.29112 for x64 with CUDA 11.1 - nvcc V11.1.74
- Python version: 3.8.5
- Mitsuba 2 version: b87c11ace78e110b094b23b83ac5902a4773202d
- Compiled variants:
	* `scalar_rgb`
	* `scalar_spectral`
	* `scalar_spectral_polarized`
	* `gpu_rgb`
	* `gpu_spectral`
	* `gpu_autodiff_rgb`
	* `gpu_autodiff_spectral`

## Description

Running mitsuba2 in `scalar_spectral` mode compiled with the aforementioned variants on Windows using the Embree backend for CPU rendering and Optix for GPU rendering, leads to a blank image where pixel values are set to `(0, 0, 0, 0)` for any images rendered using the Embree backend. I've primarily tested this using the cbox.xml example that is provided as part of [mitsuba-renderer/mitsuba-data](https://github.com/mitsuba-renderer/mitsuba-data).

By compiling mitsuba in debug mode and using an appropriate breakpoint, I think a good starting place to debug this issue is to look at https://github.com/mitsuba-renderer/mitsuba2/blob/b87c11ace78e110b094b23b83ac5902a4773202d/src/librender/integrator.cpp#L265 as I've discovered that with the Embree backend, the call to `sample` always returns a Spectrum that is completely zero thus the computed colour in `aovs` is always `(0, 0, 0, 0)`.

I'm trying to become more familiar with the code itself, but I'm not sure where to look further because the only place I could find where the `sample` function is defined is further down https://github.com/mitsuba-renderer/mitsuba2/blob/b87c11ace78e110b094b23b83ac5902a4773202d/src/librender/integrator.cpp#L291-L299 where it should, as far as I understand, raise an error of some sort.

## Steps to reproduce

1. Compile Mitsuba 2 - from commit b87c11ace78e110b094b23b83ac5902a4773202d- using the MSVC and CUDA compiler versions shown above.
2. Use the command line to run `setpath.bat` and cd to the `resources/data/scenes/cbox.xml` directory.
3. Run mitsuba using the command `mitsuba cbox.xml -m scalar_spectral -o "cbox_scalar_spectral_embree.exr"`
4. The output image(s), `cbox.exr` and `cbox_scalar_spectral_embree.exr`, will be completely blank with all pixel values set to `(0, 0, 0, 0)`

**Comment by Speierers** [comment]
Hi @Microno95 ,

Unfortunately I am unable to reproduce this issue on my end. It renders fine when compiling those variants (with Embree enabled) on Windows.

In the description above, you mentioned colours in `aovs`, but the scene `cbox.xml` uses the `path` integrator which doesn't produce any aov. Could you clarify this maybe?

**Comment by Microno95** [comment]
Sorry about the lack of clarity. I may be entirely wrong as to the actual code path taken by the renderer, but I compiled mitsuba in debug mode and during rendering interrupted the execution using the visual studio debugger. This almost always interrupts the execution within the function https://github.com/mitsuba-renderer/mitsuba2/blob/b87c11ace78e110b094b23b83ac5902a4773202d/src/librender/integrator.cpp#L234-L289

From what I can tell, mitsuba uses the `put` method of the ImageBlock class to buffer the raytraced pixel values which are then used to write out the final image. I'm not quite clear on how ImageBlock works, but the `put` method seems to essentially take a Vector2f defining the coordinates and an array `aovs` that contain the pixel colour values in the CIE XYZ format (plus additional data). These colour values are always zero regardless of when the code is interrupted and at which sample.

My natural guess was that since the the ImageBlock is receiving pixel values of 0, this must be the cause of the empty rendered exr. I don't know how to debug this so if you have any suggestions I can look in that direction.

**Comment by Speierers** [comment]
Could you maybe try a different integrator (you will need to edit the XML scene file for that) e.g. `depth` or `aov` to see whether your rays are actually intersecting some geometry or not?

**Comment by Microno95** [comment]
I deleted the entire build folder and recompiled (which I had attempted before), but somehow it fixed the problem. My apologies for wasting your time, I could reproduce the issue yesterday, but today, I decided to recompile, and the issue disappeared.
