### ISSUE TITLE
[🔨 compilation issue] GCC10 type import issue in src/shapes/instance.cpp

### ISSUE THREAD

**Issue by LukasRuppert** [mitsuba-renderer/mitsuba2#308]
## Summary
Compilation of `src/shapes/instance.cpp` fails on Linux with GCC 10.
Should use `MTS_IMPORT_TYPES(ShapeGroup)` instead of `using ShapeGroup = ShapeGroup<Float, Spectrum>;`.

## System configuration

- Platform: openSUSE Tumbleweed (same issue on Ubuntu 20.04)
- Compiler: GCC 10.2.1
- Python version: 3.8.5
- Mitsuba 2 version: 2.2.1 (`b87c11ace78e110b094b23b83ac5902a4773202d`)
- Compiled variants:
    * `scalar_rgb`
    * `spectral_rgb`

## Description
Just extend `MTS_IMPORT_TYPES(BSDF)` to `MTS_IMPORT_TYPES(BSDF, ShapeGroup)` and remove the manual type definition.
Then, it compiles without issues.

## Steps to reproduce

1. Configure the project to compile with GCC 10
2. make
```
.../mitsuba2/src/shapes/instance.cpp:59:11: error: declaration of ‘using ShapeGroup = class mitsuba::ShapeGroup<Float, Spectrum>’ changes meaning of ‘ShapeGroup’ [-fpermissive]
   59 |     using ShapeGroup = ShapeGroup<Float, Spectrum>;
```

**Comment by Speierers** [comment]
Hi @LukasRuppert ,

Thanks for reporting this. It should be fixed now.
