### ISSUE TITLE
[❔ other question] subsurface scattering feature

### ISSUE THREAD

**Issue by Yingyan-Xu** [mitsuba-renderer/mitsuba2#313]
Hi, can you provide the `xml` file for producing the "Textured translucent slab" experiment in the paper? I'm trying to render a skin material with subsurface scattering but haven't  managed to get the right scene setting.

Thanks a lot!

**Comment by diiigle** [comment]
Maybe some example scenes from the data repo would help you:
https://github.com/mitsuba-renderer/mitsuba-data/tree/master/tests/scenes/participating_media

**Comment by Yingyan-Xu** [comment]
Hi @diiigle, thanks a lot for your reply. Actually I've tried all these configurations. The main problem is that I cannot render "textured" subsurface scattering. The `medium` plugin seems to work with only `dielectric` or `null` bsdf. I want to use `plastic` or `roughplastic`...

**Comment by dvicini** [comment]
The `plastic` and `roughplastic` BSDFs both don't support any transmission. To render subsurface scattering, you should use a `dielectric` or `roughdielectric` BSDF and a textured medium.

**Comment by Yingyan-Xu** [comment]
I see. Thanks a lot!

**Comment by ankus-wu** [comment]
> I see. Thanks a lot!

Hi, I am trying to render skin with subsurface scattering too. I also tried all the example configurations. Have you tried blendbsdf or have you found the right configuration for skin? I'd appreciate it if you could share your experience with me. Thank you.

**Comment by Yingyan-Xu** [comment]
Hi @ankus-wu , I think only the dipole subsurface model in old Mitsuba can be used to render human skin if you don't have volumetric data (only surface geometry of the face), and it's not in Mitsuba2. So I didn't manage to set it up in the end. You could try implement a dipole model yourself if you definitely need it. I didn't try blendbsdf

**Comment by ankus-wu** [comment]
@Yingyan-Xu Thank you for your response! I will try. If there is any progress I will reply to you.

**Comment by BlackPi3** [comment]
> The `plastic` and `roughplastic` BSDFs both don't support any transmission. To render subsurface scattering, you should use a `dielectric` or `roughdielectric` BSDF and a textured medium.

Hey @dvicini , would you please elaborate on "textured medium"? How can I add texture to `dielectric` BSDF? I tried adding `texture` in `medium`, but didn't work (in the scene.XML).

**Comment by xyx2999** [comment]
Hello @dvicini , I have the same problem in how to create "textured medium".

**Comment by BlackPi3** [comment]
Hello @xyx2999, unfortunately not. Please let me know if you could.
@dvicini If it's possible please share the code for the examples on the Mitsuba paper: _textured translucent slab_ and _volume density resconstruction_. Thank you.

**Comment by dvicini** [comment]
Apologies, my Github inbox is quite flooded with notifications so I missed this one. @BlackPi3 @xyx2999 We currently don't support driving subsurface scattering parameters using a surface texture. Since we don't have a dipole model, you would need to implement a way in which the parameters of a participating medium can be driven by the texture.
