### ISSUE TITLE
[❔ other question] - Best way to load a .bsdf file into a object

### ISSUE THREAD

**Issue by naachoo0** [mitsuba-renderer/mitsuba2#314]
HI team,

I would like to know if to read a .bsdf file, which are provided on your [page](http://rgl.epfl.ch/materials), I need to create a plugin or is there a way to load these files in a simpler way.

Thanks for advance.

**Comment by Speierers** [comment]
Hi,

I am not really sure to understand your question. To use it as a BSDF, then you will need to create a `measured` plugin which will load the file.

Otherwise you can also take a look at [Tekari](https://rgl.epfl.ch/software/Tekari), our interactive visualization tool for reflectance data.

**Comment by naachoo0** [comment]
Thanks for answer so briefly,

So there isn't any plugin already created which load a material of the page (for instance, an acrylic_felt_green spectral) like a BSDF, isn't?

Thanks

**Comment by Speierers** [comment]
The `measured` plugin maybe? [source code](https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/bsdfs/measured.cpp)

It isn't documented but you can use it as follow:
```xml
        <bsdf type="measured">
            <string name="filename" value="my_file.bsdf"/>
        </bsdf>
```

**Comment by naachoo0** [comment]
That was what I was looking for! Many thanks.
