### ISSUE TITLE
updating kdtree

### ISSUE THREAD

**Issue by qilinsun** [mitsuba-renderer/mitsuba2#316]
*Please add one of the following label to your issue's title, and delete this section:*

- [🐛 bug report]
1. When I changed the to_world transform matrix and do a params[''].update(), the scene parameter (like the bbox of the scene) are not changed
correctly. The bbox of the scene is not updated automatically. BTW, when I add 'ConsistantEmitter*.center' to python and successfully re assign the bbox's value successfully. But in the later rendering, the object position is still not changed.
Is there a problem of scene kdtree updating? 
- [🔨 compilation issue]
- [✨ feature request]
need a function for python to update the kdtree of the scene, or maybe solve the 'bug reported' problem in another way.
- [❔ other question]

## Summary

*Please enter a brief description of your issue <- [remove this]*

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: ...
- Compiler: ...
- Python version: ...
- Mitsuba 2 version: ...
- Compiled variants:
    * `scalar_rgb`
    * ...

## Description

*Please enter the full description of your issue <- [remove this]*

## Steps to reproduce

*For bug report, please enumerate the steps to follow in order to reproduce the issue <- [remove this]*

1. ...
2. ...

**Comment by Speierers** [comment]
Hi @qilinsun ,

The `traverse` mechanism (hence `params.upate()`) is only supported for differential variants of the renderer.

In the upcoming refactoring, there will be a CPU variant of Mitsuba (based on LLVM) that will be differentiable.

For now, when using `scalar_*` variant, you need to re-load the scene to update the kd-tree.
