### ISSUE TITLE
[✨ feature request] Fixing random seed for rendering using random_torch()

### ISSUE THREAD

**Issue by Spandan-Madan** [mitsuba-renderer/mitsuba2#317]
## Summary

`render_torch()` creates a different image every time it is run. This creates a problem when optimizing with a neural network for inverse rendering applications. Is there a way to fix random seeds while rendering so that the image created is consistent every time `render_torch()` is called?

**Comment by Speierers** [comment]
Hi @Spandan-Madan ,

This shouldn't be the case. The following two lines in `_render_helper(..)` should reset the sampler seed to zero:
```python
    if sampler.wavefront_size() != total_sample_count:
        sampler.seed(0, total_sample_count)
```

Could it be that the total_sample_count changes in between iterations in your case? (e.g. different samples per pixels or different image resolution)

**Comment by Speierers** [comment]
Actually it's the other way around. In any case you should be able to fix the random seed in between the iterations by calling `sampler.seed(0, total_sample_count)` at every iteration.

**Comment by Spandan-Madan** [comment]
This worked @Speierers, thanks for your help!!
