### ISSUE TITLE
Pixel-to-UV texture: How to unwrap image pixels in Object's UV texture without solving inverse rendering problem?

### ISSUE THREAD

**Issue by garrido-pablo** [mitsuba-renderer/mitsuba2#318]
- [❔ other question]

## Summary

I'd like to know how I can directly unwrap plain image pixels in the UV texture of a 3D object without solving an inverse rendering problem. In other words, I'd like to know where I can get the mapping between the image pixels and the UV coordinates of the 3D object.

## Description

I'd like to optimize the texture of my 3D object via inverse rendering. The texture should preserve certain low-level shape structures observed in the original image. I plan to add a custom regularizer based on an anisotropic filter.
To be able to compare the texture values with my custom image features properly, I need to unwrap the image features in the UV texture space. Such a map exists implicitly exist when doing inverse rendering, but solving another inverse rendering problem just to transform the space of the image features is obviously overkilling.

Could you please give some hints on how I can get this map (or what functions would I need to use) to represent my custom image features in the Object's UV space?

Thanks!

**Comment by Speierers** [comment]
Hi @garrido-pablo ,

If I understand correctly, what you need is an AOV buffer that outputs the object's UV coordinates. With this you should be able to map a pixel location to a UV coordinate on your object. Please take a look at the `integratos/aov.cpp`.

Please let me know if this helps!

**Comment by garrido-pablo** [comment]
Yes, I had to implemet some new AOV's in integratos/aov.cpp and realized that I can use the uv coordinates.

Thanks!
