### ISSUE TITLE
[🐛 bug report] Thread::thread_id() is not unique - main thread and tbb00 both have thread_id 0

### ISSUE THREAD

**Issue by LukasRuppert** [mitsuba-renderer/mitsuba2#319]
## Summary

Thread::thread_id() returns 0 for the main thread as well as the thread "tbb00".

## System configuration

- Platform: Ubuntu 20.04
- Compiler: GCC 10.2.0
- Python version: 3.8.5
- Mitsuba 2 version: 2.2.1 153bae88067f0cd6b1641a6c9ae24185121c2a20
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`

## Description

The `thread_ctr` in `src/libcore/thread.cpp` starts at `0` and is not incremented by the main thread.
As a result of this, `Thread::thread_id()` returns `0` for two threads and never returns the id `__global_thread_count-1`.

## Steps to reproduce

1. add the following logging code to any integrator:
```
static ThreadLocal<bool> initialized;
if (!initialized)
{
    Log(Info, "thread_id: %u, thread: %s", Thread::thread_id(), Thread::thread());
    initialized = true;
}
```

2. render any scene
3. see that both `main` and `tbb00` have thread_id `0`.

**Comment by Speierers** [comment]
Hi @LukasRuppert ,
Thanks for reporting this. Indeed we should start counting the thread at `1` to include the main thread. Later registration of external thread (e.g. TBB) will increase that counter appropriately. This should be fixed on `master` now.
