### ISSUE TITLE
[🐛 bug report] the use of fmaf in dot()/squared_norm() of vector.cuh

### ISSUE THREAD

**Issue by slongle** [mitsuba-renderer/mitsuba2#321]
## Summary

When I try to compile ptx on Windows10, it shows the picture below.  
![Snipaste_2020-11-10_19-09-49](https://user-images.githubusercontent.com/10596216/98667178-09646c00-2389-11eb-806a-0350a5333d7d.png)
It seems that in `include\mitsuba/render/optix/vector.cuh` file, these two functions cannot invoke the fmaf function due to the unmatch argument list. So I modify the `fmaf` to `__fmaf_rn` like the picture below. And everything works well after doing this.
![Snipaste_2020-11-10_19-10-54](https://user-images.githubusercontent.com/10596216/98667285-2ac55800-2389-11eb-9c8d-b19c8946aed9.png)

## System configuration

- Platform: Windows10/CUDA 11/Optix 7.0
- Compiler: MSVC 19.27.29112
- Python version: 3.8.5
- Mitsuba 2 version: latest commit - https://github.com/mitsuba-renderer/mitsuba2/commit/8fa0a80a1f1c4e750521b9f31fdc00c6fc8fa1ae
- Compiled variants:
    * `scalar_rgb`
    * `gpu_autodiff_rgb`

**Comment by Speierers** [comment]
Hi @slongle ,

So far we have always compiled the PTX code on Linux machines. I just pushed a patch on `master` which should fix your problem on Windows. 

Please let me know if it now works on your end.

**Comment by slongle** [comment]
Thanks, it works for me!
