### ISSUE TITLE
[🐛 bug report] volpath in RGB mode weights with a wrong PDF

### ISSUE THREAD

**Issue by tomasiser** [mitsuba-renderer/mitsuba2#323]
## Summary

[As shown in the PBRT book for homogeneous media](http://www.pbr-book.org/3ed-2018/Light_Transport_II_Volume_Rendering/Sampling_Volume_Scattering.html#HomogeneousMedium), if we sample a distance in a randomly chosen channel (R, G, or B), the total PDF (probability density function) is given by the average of the transmittances in all channels. That is because a distance _t_ can be chosen either in channel R, channel G, or channel B, so the PDF is:

(PDF of channel R * PDF of distance _t_ according to R) + (PDF of channel G * PDF of distance _t_ according to G) + (PDF of channel B * PDF of distance _t_ according to G)

This is how it is done in both PBRT and [Mitsuba 1 for homogeneous media with the `EBalance` (default) method](https://github.com/mitsuba-renderer/mitsuba/blob/master/src/medium/homogeneous.cpp#L322).

In Mitsuba 2, this weighting is not part of the medium anymore, it happens in `volpath`. In case the RGB mode is selected, [a random channel is chosen](https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/integrators/volpath.cpp#L66) and then all transmittance calculations are done according to that channel. However, the throughput is [**not weighted with the correct PDF**](https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/integrators/volpath.cpp#L116), as it does not use the average of all the channels, but **only uses the selected channel**.

**Note:** For spectral rendering in Mitsuba 2, this does not seem to be a problem, because the 0th channel is always used, so the pdf does not have to take other channels into account. Althought using `scalar_spectral` mode on the same scene also behaves a bit weird, but that can be because of spectral uplifting issues.

The funny thing is that if the extinction (sigma_t) does not vary a lot over the RGB channels, then the wrong PDF is close to the correct PDF, so you cannot see the problem. However, if you use a sigma_t of, let's say, `0.1, 0.8, 0.1`, the PDF becomes more and more wrong and the following starts to happen:

Mitsuba 1, 512 spp:
![mitsuba1](https://user-images.githubusercontent.com/10374559/98807041-60665180-241a-11eb-9c24-46bce8ebdeb2.png)

Mitsuba 2, 512 spp:
![mitsuba2](https://user-images.githubusercontent.com/10374559/98807047-61977e80-241a-11eb-9ca2-bc352e1c8791.png)

You can verify this by running:

```
mitsuba -o test.exr -D sample_count=512 -D film_height=512 -D film_width=512 scene.xml
```

with both Mitsuba 1 and Mitsuba 2 with the following scene:

```xml
<?xml version='1.0' encoding='utf-8'?>

<scene version="0.5.0">

    <default name="object_scale" value="1.0" />
    <default name="camera_lookat" value="0.0, 0.0, 0.0"/>
    <default name="camera_position" value="4.0, 4.0, 4.0"/>
    <default name="camera_fov" value="20.0"/>
    <default name="camera_up" value="0, 1, 0"/>

    <integrator type="volpath">
        <integer name="maxDepth" value="1000"/>
        <integer name="rrDepth" value="1000"/>
    </integrator>

    <sensor type="perspective">
        <float name="nearClip" value="1.0"/>
        <float name="farClip" value="1000.0"/>
        <float name="fov" value="$camera_fov"/>

        <transform name="toWorld">
            <lookat target="$camera_lookat" origin="$camera_position" up="$camera_up"/>
        </transform>

        <sampler type="independent">
            <integer name="sampleCount" value="$sample_count"/>
        </sampler>

        <film type="hdrfilm">
            <boolean name="banner" value="false"/>
            <rfilter type="box"/>
            <integer name="height" value="$film_height"/>
            <integer name="width" value="$film_width"/>
            <string name="pixel_format" value="rgb"/>
        </film>
    </sensor>

    <emitter type="constant">
        <rgb name="radiance" value="1" />
    </emitter>

    <shape type="obj">
        <string name="filename" value="unit_cube_centered.obj"/>
        <medium type="homogeneous" name="interior">
            <rgb name="albedo" value="0.5, 0.5, 0.5" />
            <rgb name="sigmaT" value="0.1, 0.8, 0.1" />
            <float name="scale" value="10" />
            <phase type="isotropic" />
        </medium>
        <bsdf type="null" />
        <transform name="toWorld">
            <scale x="1" y="1" z="1" />
        </transform>
    </shape>

</scene>
```

using the `unit_cube_centered.obj` model:

```obj
# Blender v2.82 (sub 7) OBJ File: ''
# www.blender.org
# mtllib unit_cube_centered.mtl
o Unit_Cube_Centered
v -0.500000 0.500000 -0.500000
v 0.500000 0.500000 0.500000
v 0.500000 0.500000 -0.500000
v -0.500000 0.500000 0.500000
v -0.500000 -0.500000 0.500000
v 0.500000 -0.500000 -0.500000
v 0.500000 -0.500000 0.500000
v -0.500000 -0.500000 -0.500000
vn 0.0000 1.0000 0.0000
vn 0.0000 -1.0000 0.0000
vn 0.0000 0.0000 1.0000
vn 1.0000 0.0000 0.0000
vn 0.0000 0.0000 -1.0000
vn -1.0000 0.0000 0.0000
# usemtl None
s off
f 1//1 2//1 3//1
f 2//1 1//1 4//1
f 5//2 6//2 7//2
f 6//2 5//2 8//2
f 5//3 2//3 4//3
f 2//3 5//3 7//3
f 2//4 6//4 3//4
f 6//4 2//4 7//4
f 6//5 1//5 3//5
f 1//5 6//5 8//5
f 5//6 1//6 8//6
f 1//6 5//6 4//6 
```

**Comment by dvicini** [comment]
Hi Tomas

Thanks for looking into this. The `volpath` integrator does not perform any MIS between the different sampling strategies, that's why we divide by the PDF of the current color channel, and don't account for the other potential sampling strategies. This is a fairly bad approach to render scenes with spectrally varying extinction, that's why we also have the `volpathmis` integrator (I should really finally write the docs for these...). The `volpathmis` integrator does full MIS between color channels and also works well to render heterogeneous media with spectrally varying extinction.

The image you output with Mitsuba 2 is therefore quite noisy. If you render with a higher sample count, it should converge to the right result. Or you can switch to `volpathmis`, which gives similar noise performance as the Mitsuba 1 integrator. 

I find it surprising that you observed the behavior to be fundamentally different between RGB and spectral mode, this is something which I will have to investigate. There shouldn't be a difference in behavior from that point of view. In the spectral mode we always use the 0th channel, but this one is already sampled (so choosing a random index would not make a difference).

Delio

**Comment by tomasiser** [comment]
Hi, thanks for the fast reply! I have to admit I am a bit confused. :) The estimator in `volpath` randomly selects a color channel, but this random decision does not seem to be accounted for in the estimator PDF, unlike in PBRT or Mitsuba 1. I guess more experiments would be needed to verify whether it really does converge to the same solution or not.

**Comment by dvicini** [comment]
PBRT and Mitsuba 1 use the "balance heuristic" MIS to weight the samples. That's why the PDF of the free flight distance accounts for the PDFs of sampling the same distance using the other color channels. This reduces the variance, but it is not necessary for correctness. Our `volpathmis` does a more extensive version of that kind of MIS weighting, which PBRT and Mitsuba 1 did not do. So you could also compare between `volpath` and `volpathmis`. If they don't converge to the same result, we indeed have a bug

**Comment by tomasiser** [comment]
Ok! I think I get it now. I forgot that PBRT and Mitsuba 1 choose the channel randomly in _each_ distance sample, while Mitsuba 2 `volpath` chooses the channel randomly _once_ for the _whole_ path.

I tried the convergence and you are probably right that it does, eventually, converge, albeit extremely poorly. For some reason, `volpathmis` creates a lot of `inf` values (yellow dots in the image), I did not have time to investigate that yet.

| **Mitsuba 1, 10k spp** | **Mitsuba 2, `volpath`, 10k spp** |
| :---: | :---: |
| ![cube_m1_10000spp_crop](https://user-images.githubusercontent.com/10374559/99146972-2d6fc800-267d-11eb-8c21-99c0239cc708.png) | ![cube_m2_10000spp_crop](https://user-images.githubusercontent.com/10374559/99147019-935c4f80-267d-11eb-8857-b5b244543a80.png) |
| **Mitsuba 2, `volpath`, 1M spp** | **Mitsuba 2, `volpathmis`, 10k spp** |
| ![cube_m2_1000000spp_crop](https://user-images.githubusercontent.com/10374559/99147046-c272c100-267d-11eb-9828-5f572ab61288.png) | ![cube_m2_10000spp_mis_crop](https://user-images.githubusercontent.com/10374559/99147058-d9b1ae80-267d-11eb-928f-0e5fba950c74.png) |

**Comment by dvicini** [comment]
Thanks for doing these experiments! It makes sense that `volpath` converges very poorly, as it does not do any MIS. However, the infinite values in `volpathmis` are clearly a bug. This should not happen. Could you check if the infinite values also occur for a medium with monochrome extinction?

**Comment by dvicini** [comment]
I pushed a fix for the infinite values. There was a small numerical issue in the accumulation of the MIS weights. I also fixed an unrelated bug which lead to wrong results when disabling NEE in the volume. I am closing this issue now, feel free to re-open or create new ones if you encounter new issues
