### ISSUE TITLE
[❔ other question] Any built-in regularization mechanism?

### ISSUE THREAD

**Issue by Yingyan-Xu** [mitsuba-renderer/mitsuba2#324]
Hey thanks for the great work on Mitsuba 2!

I was wondering whether there's any built-in regularization in the differentiable renderer.

**Comment by Speierers** [comment]
Hi @Yingyan-Xu ,

Could you please elaborate further on this?

Are you talking about regularization in the context of scene parameters optimization using the differentiable renderer? In which case the answer would be no. The differentiable renderer produces gradients for the scene parameters w.r.t. some objective function. It is up to you to regularize / constraint this optimization process by a design different objective function, whose gradients will be properly backpropagated through the light transport simulation to produce the scene parameters gradients.

**Comment by Yingyan-Xu** [comment]
Hi @Speierers, thanks a lot for the quick reply! I asked the question because I noticed that Mitsuba 2 worked quite well even with just single view. The gradients didn't explode when the reference was very noisy. Also the optimization converged really fast! Your reply answered my question. I will close this issue. Thanks again!
