### ISSUE TITLE
error: encountered ray with nan or inf values:

### ISSUE THREAD

**Issue by juicyzhucx** [mitsuba-renderer/mitsuba2#325]
*Please add one of the following label to your issue's title, and delete this section:*

- [🐛 bug report]

## Summary

when I run the docs/examples/10_diff_render/forward_diff.py ，the program said ：(  60,  56,   0) error: encountered ray with nan or inf values:
what this mean and how to deal with this？

## System configuration

- Platform: windows 10
- Compiler: VS2019
- Python version: 3.7.0
- Mitsuba 2 version: 2.2.1
- Compiled variants:"scalar_rgb",
        "scalar_spectral",
        "gpu_autodiff_rgb",
        "gpu_autodiff_spectral"

## Description

(  60,  56,   0) error: encountered ray with nan or inf values:

**Comment by Speierers** [comment]
Hi @juicyzhucx ,

I tested it this morning and it runs fine on my end. Could you try to pull the latest changes from `master`?

This error means that OptiX is dealing with some invalid ray, which shouldn't happen in this simple setup.

You could also try to manual change `ray.maxt=inf` to a large float value in `optix_rt.cu` by adding the following to lines:
```c++
    float mint = params.in_mint[launch_index],
          maxt = params.in_maxt[launch_index];
    // ADDIND THE FOLLOWING TWO LINES
    if (maxt == CUDART_INF_F)
        maxt = 1e38f;
```

You will then need to recompile the ptx shaders:
```bash
cd resources/ptx
make
```

**Comment by Speierers** [comment]
This issue will be fixed in the upcoming release.
