### ISSUE TITLE
[❔ other question] Render without shading?

### ISSUE THREAD

**Issue by Yingyan-Xu** [mitsuba-renderer/mitsuba2#328]
## Summary

Is it possible to render without shading

## Description

Is it possible to render without shading just for visualization purpose? I'm working on inverse rendering to optimize over texture maps given different camera views. The camera weights are defined in texture space. I somehow need to project them into screen space. The shading of the rendering with will affect the true values.

**Comment by Speierers** [comment]
Hi @Yingyan-Xu ,

For this I would recommend you write your own integrator plugin. Just copy the code from `integrator/path.cpp` or `integrator/direct.cpp`.

You could also use the `aov` integrator for this. Just add another channel that returns the surface BSDF evaluated with an incoming direction orthogonal to the surface normal.
