### ISSUE TITLE
[🔨 compilation issue] - Fail to generate build with gpu variants.

### ISSUE THREAD

**Issue by naachoo0** [mitsuba-renderer/mitsuba2#329]
## Summary

I am trying build mitsuba with gpu_variants, but a get an error when it is generate in cmake. 

## System configuration

- Platform: Windows 10
- Compiler: cmake 3.18.4
- Python version: 3.8.6
- Cuda Compiler (nvcc): 10.2.89
- Mitsuba 2 version: the lastest (with git pullalll)
- Compiled variants:
    * `gpu_*`

## Description

After I configure with cmake, I get the error that I show below:

![imagen](https://user-images.githubusercontent.com/45198042/99527573-4a6a0b00-299d-11eb-965e-f3d285cf64b7.png)

## Steps to reproduce

1.  Set mitsuba.conf with some GPU_variant.
2.  Configurate with cmake the mitsuba source.
3. Generate with cmake the configuration.

**Comment by Speierers** [comment]
Hi @naachoo0 ,
Could you please try to update you CUDA compiler?

**Comment by naachoo0** [comment]
Hi, I have updated the CUDA compiler to the last version, but the problem persist.

![imagen](https://user-images.githubusercontent.com/45198042/99547821-4ac3cf80-29b8-11eb-9aea-376112bc0136.png)

**Comment by Speierers** [comment]
By the way those seems to just be warnings. Did Mitsuba compile fine after that?

**Comment by Speierers** [comment]
Could you please tell me the version of you MSVC compiler?

**Comment by naachoo0** [comment]
Yes, the version I am using is: 19.28.29334

**Comment by Speierers** [comment]
Could you try to add `scalar_rgb` to the list of variants to compile. It is possible that parts of the codebase assume this variant will always be compiled.

**Comment by naachoo0** [comment]
Sir, I have reinstalled all and now is working well, but i have a question. When is the exception cuda_malloc() launch?

![image](https://user-images.githubusercontent.com/45198042/99945534-131ca500-2d75-11eb-8f60-b156114a7a87.png)

**Comment by Speierers** [comment]
You are simply running out of memory on your GPU. You should try to reduce the resolution of the renders, or use a lower amount of samples per pixel.
