### ISSUE TITLE
[SerializedMesh] Error while loading serialized file "lightsource.serialized": file not found!

### ISSUE THREAD

**Issue by karim-eladl** [mitsuba-renderer/mitsuba2#330]
Hi I just installed mitsuba2 and am using python3.8. I'm just running an example python script from the docs and an example .xml file with my own .obj but I get the following error. I really have no idea how to fix this issue. Thank you for your help!

**Error:**
```
$ python mitsuba_renderer.py 
2020-11-18 14:18:47 INFO  main  [xml.cpp:1221] Loading XML file "scene.xml" ..
2020-11-18 14:18:47 INFO  main  [xml.cpp:1222] Using variant "scalar_rgb"
2020-11-18 14:18:47 INFO  main  [xml.cpp:355] "scene.xml": in-memory version upgrade (v2.0.0 -> v2.2.1) ..
2020-11-18 14:18:47 INFO  main  [PluginManager] Loading plugin "plugins/srgb_d65.so" ..
2020-11-18 14:18:47 INFO  main  [PluginManager] Loading plugin "plugins/path.so" ..
2020-11-18 14:18:47 INFO  tbb00 [PluginManager] Loading plugin "plugins/roughdielectric.so" ..
2020-11-18 14:18:47 INFO  tbb00 [PluginManager] Loading plugin "plugins/uniform.so" ..
2020-11-18 14:18:47 INFO  tbb00 [PluginManager] Loading plugin "plugins/obj.so" ..
2020-11-18 14:18:47 INFO  tbb03 [PluginManager] Loading plugin "plugins/hdrfilm.so" ..
2020-11-18 14:18:47 INFO  tbb03 [PluginManager] Loading plugin "plugins/gaussian.so" ..
2020-11-18 14:18:47 INFO  tbb02 [PluginManager] Loading plugin "plugins/area.so" ..
2020-11-18 14:18:47 INFO  tbb01 [PluginManager] Loading plugin "plugins/independent.so" ..
2020-11-18 14:18:47 INFO  tbb01 [PluginManager] Loading plugin "plugins/perspective.so" ..
2020-11-18 14:18:47 INFO  tbb02 [PluginManager] Loading plugin "plugins/serialized.so" ..
2020-11-18 14:18:47 INFO  tbb02 [PluginManager] Loading plugin "plugins/diffuse.so" ..
Traceback (most recent call last):
  File "mitsuba_renderer.py", line 18, in <module>
    scene = load_file(filename)
RuntimeError: ​[xml.cpp:1047] Error while loading "scene.xml" (near line 40, col 6): could not instantiate shape plugin of type "serialized": 
[xml.cpp:1047]   [SerializedMesh] Error while loading serialized file "lightsource.serialized": file not found!
```

**mitsuba_renderer.py:**
```
import os
import numpy as np
import mitsuba

mitsuba.set_variant('scalar_rgb')
from mitsuba.core import Bitmap, Struct, Thread
from mitsuba.core.xml import load_file

filename = 'scene.xml'

Thread.thread().file_resolver().append(os.path.dirname(filename))

scene = load_file(filename)

scene.integrator().render(scene, scene.sensors()[0])

film = scene.sensors()[0].film()

film.set_destination_file('output.exr')
film.develop()

bmp = film.bitmap(raw=True)
bmp.convert(Bitmap.PixelFormat.RGB, Struct.Type.UInt8, srgb_gamma=True).write('output.jpg')

bmp_linear_rgb = bmp.convert(Bitmap.PixelFormat.RGB, Struct.Type.Float32, srgb_gamma=False)
image_np = np.array(bmp_linear_rgb)
print(image_np.shape)
```

**scene.xml:**
```
<scene version="2.0.0">
    <integrator type="path">
        <!-- Instantiate a path tracer with a max. path length of 8 -->
        <integer name="max_depth" value="8"/>
    </integrator>

    <!-- Instantiate a perspective camera with 45 degrees field of view -->
    <sensor type="perspective">
        <!-- Rotate the camera around the Y axis by 180 degrees -->
        <transform name="to_world">
            <rotate y="1" angle="180"/>
        </transform>
        <float name="fov" value="45"/>

        <!-- Render with 32 samples per pixel using a basic
             independent sampling strategy -->
        <sampler type="independent">
            <integer name="sample_count" value="32"/>
        </sampler>

        <!-- Generate an EXR image at HD resolution -->
        <film type="hdrfilm">
            <integer name="width" value="1920"/>
            <integer name="height" value="1080"/>
        </film>
    </sensor>

    <!-- Add a dragon mesh made of rough glass (stored as OBJ file) -->
    <shape type="obj">
        <string name="filename" value="ico.obj"/>

        <bsdf type="roughdielectric">
            <!-- Tweak the roughness parameter of the material -->
            <float name="alpha" value="0.01"/>
        </bsdf>
    </shape>

    <!-- Add another mesh, this time, stored using Mitsuba's own
         (compact) binary representation -->
    <shape type="serialized">
        <string name="filename" value="lightsource.serialized"/>
        <transform name="toWorld">
            <translate x="5" y="-3" z="1"/>
        </transform>

        <!-- This mesh is an area emitter -->
        <emitter type="area">
            <rgb name="radiance" value="100,400,100"/>
        </emitter>
    </shape>
</scene>
```

**Comment by Speierers** [comment]
Hi @karim-eladl ,

Is the file `lightsource.serialized` place in the same directory as the `xml` file?

**Comment by comewei** [comment]
> Hi I just installed mitsuba2 and am using python3.8. I'm just running an example python script from the docs and an example .xml file with my own .obj but I get the following error. I really have no idea how to fix this issue. Thank you for your help!
> 
> **Error:**
> 
> ```
> $ python mitsuba_renderer.py 
> 2020-11-18 14:18:47 INFO  main  [xml.cpp:1221] Loading XML file "scene.xml" ..
> 2020-11-18 14:18:47 INFO  main  [xml.cpp:1222] Using variant "scalar_rgb"
> 2020-11-18 14:18:47 INFO  main  [xml.cpp:355] "scene.xml": in-memory version upgrade (v2.0.0 -> v2.2.1) ..
> 2020-11-18 14:18:47 INFO  main  [PluginManager] Loading plugin "plugins/srgb_d65.so" ..
> 2020-11-18 14:18:47 INFO  main  [PluginManager] Loading plugin "plugins/path.so" ..
> 2020-11-18 14:18:47 INFO  tbb00 [PluginManager] Loading plugin "plugins/roughdielectric.so" ..
> 2020-11-18 14:18:47 INFO  tbb00 [PluginManager] Loading plugin "plugins/uniform.so" ..
> 2020-11-18 14:18:47 INFO  tbb00 [PluginManager] Loading plugin "plugins/obj.so" ..
> 2020-11-18 14:18:47 INFO  tbb03 [PluginManager] Loading plugin "plugins/hdrfilm.so" ..
> 2020-11-18 14:18:47 INFO  tbb03 [PluginManager] Loading plugin "plugins/gaussian.so" ..
> 2020-11-18 14:18:47 INFO  tbb02 [PluginManager] Loading plugin "plugins/area.so" ..
> 2020-11-18 14:18:47 INFO  tbb01 [PluginManager] Loading plugin "plugins/independent.so" ..
> 2020-11-18 14:18:47 INFO  tbb01 [PluginManager] Loading plugin "plugins/perspective.so" ..
> 2020-11-18 14:18:47 INFO  tbb02 [PluginManager] Loading plugin "plugins/serialized.so" ..
> 2020-11-18 14:18:47 INFO  tbb02 [PluginManager] Loading plugin "plugins/diffuse.so" ..
> Traceback (most recent call last):
>   File "mitsuba_renderer.py", line 18, in <module>
>     scene = load_file(filename)
> RuntimeError: ​[xml.cpp:1047] Error while loading "scene.xml" (near line 40, col 6): could not instantiate shape plugin of type "serialized": 
> [xml.cpp:1047]   [SerializedMesh] Error while loading serialized file "lightsource.serialized": file not found!
> ```
> 
> **mitsuba_renderer.py:**
> 
> ```
> import os
> import numpy as np
> import mitsuba
> 
> mitsuba.set_variant('scalar_rgb')
> from mitsuba.core import Bitmap, Struct, Thread
> from mitsuba.core.xml import load_file
> 
> filename = 'scene.xml'
> 
> Thread.thread().file_resolver().append(os.path.dirname(filename))
> 
> scene = load_file(filename)
> 
> scene.integrator().render(scene, scene.sensors()[0])
> 
> film = scene.sensors()[0].film()
> 
> film.set_destination_file('output.exr')
> film.develop()
> 
> bmp = film.bitmap(raw=True)
> bmp.convert(Bitmap.PixelFormat.RGB, Struct.Type.UInt8, srgb_gamma=True).write('output.jpg')
> 
> bmp_linear_rgb = bmp.convert(Bitmap.PixelFormat.RGB, Struct.Type.Float32, srgb_gamma=False)
> image_np = np.array(bmp_linear_rgb)
> print(image_np.shape)
> ```
> 
> **scene.xml:**
> 
> ```
> <scene version="2.0.0">
>     <integrator type="path">
>         
>         <integer name="max_depth" value="8"/>
>     </integrator>
> 
>     
>     <sensor type="perspective">
>         
>         <transform name="to_world">
>             <rotate y="1" angle="180"/>
>         </transform>
>         <float name="fov" value="45"/>
> 
>         
>         <sampler type="independent">
>             <integer name="sample_count" value="32"/>
>         </sampler>
> 
>         
>         <film type="hdrfilm">
>             <integer name="width" value="1920"/>
>             <integer name="height" value="1080"/>
>         </film>
>     </sensor>
> 
>     
>     <shape type="obj">
>         <string name="filename" value="ico.obj"/>
> 
>         <bsdf type="roughdielectric">
>             
>             <float name="alpha" value="0.01"/>
>         </bsdf>
>     </shape>
> 
>     
>     <shape type="serialized">
>         <string name="filename" value="lightsource.serialized"/>
>         <transform name="toWorld">
>             <translate x="5" y="-3" z="1"/>
>         </transform>
> 
>         
>         <emitter type="area">
>             <rgb name="radiance" value="100,400,100"/>
>         </emitter>
>     </shape>
> </scene>
> ```

hello do you solve it. I also meet it.

`:~/UnsupervisedPointCloudReconstruction/mitsuba/Reconstruct_foldnet_plane/shapenetcorev2/train0$ mitsuba -m scalar_rgb test.xml 
2021-04-19 16:57:17 INFO  main  [mitsuba.cpp:218] Mitsuba version 2.2.1 (master[e1c09283], Linux, 64bit, 20 threads, 16-wide SIMD)
2021-04-19 16:57:17 INFO  main  [mitsuba.cpp:219] Copyright 2020, Realistic Graphics Lab, EPFL
2021-04-19 16:57:17 INFO  main  [mitsuba.cpp:220] Enabled processor features: avx512f avx512cd avx512dq avx512vl avx512bw avx2 avx fma f16c sse4.2 x86_64
2021-04-19 16:57:17 INFO  main  [xml.cpp:1221] Loading XML file "test.xml" ..
2021-04-19 16:57:17 INFO  main  [xml.cpp:1222] Using variant "scalar_rgb"
2021-04-19 16:57:17 INFO  main  [xml.cpp:355] "test.xml": in-memory version upgrade (v2.0.0 -> v2.2.1) ..
2021-04-19 16:57:17 INFO  main  [PluginManager] Loading plugin "plugins/srgb_d65.so" ..
2021-04-19 16:57:17 INFO  main  [PluginManager] Loading plugin "plugins/path.so" ..
2021-04-19 16:57:17 INFO  tbb00 [PluginManager] Loading plugin "plugins/roughdielectric.so" ..
2021-04-19 16:57:17 INFO  tbb00 [PluginManager] Loading plugin "plugins/uniform.so" ..
2021-04-19 16:57:17 INFO  tbb00 [PluginManager] Loading plugin "plugins/obj.so" ..
2021-04-19 16:57:17 INFO  tbb03 [PluginManager] Loading plugin "plugins/area.so" ..
2021-04-19 16:57:17 INFO  tbb03 [PluginManager] Loading plugin "plugins/serialized.so" ..
2021-04-19 16:57:17 INFO  tbb03 [PluginManager] Loading plugin "plugins/diffuse.so" ..
2021-04-19 16:57:17 INFO  tbb01 [PluginManager] Loading plugin "plugins/independent.so" ..
2021-04-19 16:57:17 INFO  tbb02 [PluginManager] Loading plugin "plugins/hdrfilm.so" ..
2021-04-19 16:57:17 INFO  tbb02 [PluginManager] Loading plugin "plugins/gaussian.so" ..
2021-04-19 16:57:17 INFO  tbb01 [PluginManager] Loading plugin "plugins/perspective.so" ..

Caught a critical exception: [xml.cpp:1047] Error while loading "test.xml" (near line 29, col 6): could not instantiate shape plugin of type "obj": 
[xml.cpp:1047]   [OBJMesh] Error while loading OBJ file "dragon.obj": file not found`

**Comment by Speierers** [comment]
Hi @comewei ,

Are you sure this issue is related to your problem? It simply looks like Mitsuba can't find the `dragon.obj` file. Could you make sure it is placed in the right directory (e.g. in the same folder as the xml file)?

**Comment by comewei** [comment]
> Hi @comewei ,
> 
> Are you sure this issue is related to your problem? It simply looks like Mitsuba can't find the `dragon.obj` file. Could you make sure it is placed in the right directory (e.g. in the same folder as the xml file)?

sir,sorry. I solved it. as a beginner,use the wrong xml file.
my question is that I don't how to use cmake create the 'plugins/ldrfilm.so'  
I hope It will show **INFO [PluginManager] Loading plugin "plugins/ldrfilm.so" ..**
can you help me,thanks.
> ``

**Comment by merlinND** [comment]
@comewei Simply add a line similar to this in the `CMakeLists.txt` file of the directory where you create your new plugin:

https://github.com/mitsuba-renderer/mitsuba2/blob/275222876ddb85eb255d6a4ff82d4893848bd6e0/src/films/CMakeLists.txt#L3

**Comment by iewUstc** [comment]
> Hi @karim-eladl ,
> 
> Is the file `lightsource.serialized` place in the same directory as the `xml` file?
Is the file "lightsource.serialized" generated through plugins of the mitsuba?

**Comment by Hoodie-Zhang** [comment]
@alex-karim-eladl I also encountered the same problem, I want to ask if you solved it

**Comment by merlinND** [comment]
Hello @Hoodie-Zhang,

The officially supported version of Mitsuba is 3.0+, if you are encountering a difficulty, feel free to open an Issue in the Mitsuba 3 repo (making sure to fill in the issue template): https://github.com/mitsuba-renderer/mitsuba3
