### ISSUE TITLE
[❔ other question] Assigning BSDF to grouped shape files

### ISSUE THREAD

**Issue by standardisedfitting** [mitsuba-renderer/mitsuba2#332]
Hi,

first of all thank for very much providing the Mitsuba software. I've been using it for a couple of months now and it's been performing really well so far!

## Summary

I am currently trying to render multiple models in spectral mode. They each will consist of multiple materials, with spectra that I have measured in the lab. Additionally I would like to import BSDF data from the RGL database (http://rgl.epfl.ch/materials) with the `measured` plug-in.

I couldn't quite figure out how to assign materials to different parts of a grouped OBJ or PLY file using the Python dictionary option. The documentation does not cover that, I think.
Ideally, I would like to set a material tag to each surface of the object which specifies any one of the materials, that I load into Mitsuba separately.
Would you have a recommendation of how to achieve this efficiently?
 
The previous Mitsuba version had the `mtsimport` utility, that could convert from OBJ to serialized. I am wandering if I convert an OBJ file to serialized using this and assign the materials one-by-one to each shape in the serialized file?

Sorry if I am missing something, I am not very familiar with the composition of these shape files yet.

**Comment by Speierers** [comment]
Hi @standardisedfitting ,

Currently, only the `serialized` shape plugin support multiple models (e.g. from a single file). For OBJ and PLY you will need to split you model into seperate files and add those one by one to the scene (assigning the corresponding material).

If you would rather use the `serialized`, the `resources/data/scene/matpreview/matpreview.xml` scene file is a good example on how to assign different material to the different "sub-shapes".

Mitsuba 2 doesn't support shape to serialized conversion yet, but the files created with the Mitsuba 0.6 utility should be compatible with Mitsuba 2.

**Comment by standardisedfitting** [comment]
Hi @Speierers,

thank you very much for the clarification.
I think you are right, in that case it would probably be best for me to convert my shapes to serialized first.
