### ISSUE TITLE
Plugin "pathreparam" not found!

### ISSUE THREAD

**Issue by nauman-tintash** [mitsuba-renderer/mitsuba2#334]
- [🔨 compilation issue]

## Summary

I think there is something wrong with the way I am compiling the repo. I can't seem to be able to make the vertex positions differentiable. I also tried the code and examples from pathreparam-optix7 branch but no help.

## System configuration

- Platform: Ubuntu 20.4
- Compiler: CMAKE 3.16.3
- Python version: 3.8.5
- Mitsuba 2 version: mitsuba-2
- CUDA : 10.2
- Compiled variants:
    * `scalar_rgb`
    * 'gpu_autodiff_rgb'

## Description

There is something wrong with my installation as it doesn't install pathreparam plugin. I also can't seem to verify if my Optix is setup properly or if there is some issue there.

**Comment by Speierers** [comment]
Hi @nauman-tintash ,

Which branch would you like to compile at the end? `master` doesn't contains the `pathreparam` plugin. I suggest that you clean your `build` directly and build from scratch after checking out the `pathreparam-optix7` branch.

**Comment by nauman-tintash** [comment]
I did that, deleted my build directory, checked out the 'pathreparam-optix7' branch and did cmake and make from scratch again. Still wasn't able to run with 'pathreparam' plugin.

Is there anything special we need to do to install specific plugins? Or to verify optix setup?

**Comment by nauman-tintash** [comment]
Hi @Speierers ,

Apologies, its my bad, reinstalling cuda drivers and then compiling from scratch using `pathreparam-optix7` branch fixed the issue. Now I get the coda_malloc issue which I think I can look into since other people seem to have faced that as well. Thanks for the help.
