### ISSUE TITLE
  [❔ other question] Changing Sampler's seed without reloading the scene ...

### ISSUE THREAD

**Issue by karticsubr** [mitsuba-renderer/mitsuba2#335]
## Summary

Is there a way to change the seed before re-rendering a scene (Python)  ? 

## Description

My scene takes a fair amount of time to load, so I would like to avoid re-loading the scene with a $seed option before rendering again. I searched through the documentation but could not find a way to do this. I saw the modifier that allows me to change a sampler object’s seed, but I can’t seem to update the scene’s sampler with the altered version. Is there a way to update individual aspects of a scene (e.g. just the sensor,  just the sampler, etc.)

(I have the opposite requirement as on this thread: https://github.com/mitsuba-renderer/mitsuba2/issues/317)

**Comment by merlinND** [comment]
Hi @karticsubr,

Unless you created another one manually, the sampler used by the sensor, which is discussed in #317, should be the only one being used when rendering the seed. So when you call `sampler.seed()`, all random numbers used in the next `render()` call should derive from the seed you set. This will allow you to render with multiple seeds without reloading the scene in between.

Please feel free to reopen this issue if it doesn't work for you.

**Comment by karticsubr** [comment]
Thanks for your quick response, @merlinND. Would you please tell me what I am doing wrong in that case? I've created some representative code below. 

Do I need to call some 'update' function between the following lines of code? 
 sensor.sampler().seed(SeedChange)

 mitsuba_scene.integrator().render(scene=mitsuba_scene, sensor=sensor)

Thanks

---------------------------- full code 

import numpy as np
import mitsuba
import imageio
from datetime import datetime

mitsuba.set_variant(value="scalar_rgb")

#(x, y, z) = ((1, 0, 0), (0, 1, 0), (0, 0, 1))

LightPos = (0, 0, 1)
LightRad = .2
OccPos = (0, 0, .5)
OccRad = .1
ReceiverL = 1
ReceiverW = 1
Brightness = 30

receiver = {
    "receiver": {
    "type": "rectangle",
    "to_world": (
            mitsuba.core.Transform4f.translate(v=(-ReceiverL / 2, -ReceiverW / 2, 0))
            * mitsuba.core.Transform4f.scale(v=(ReceiverL, ReceiverW,1))
    ),
    "material": {
        "type":"diffuse",
         "reflectance": {"type":"rgb", "value": (0.6, .45, .15)},
    },
}
}

emitter = {
    "light": {
    "type": "sphere",
    "center": LightPos,
    "radius": LightRad,
    "light": {
        "type": "area",
        "radiance": {"type": "spectrum", "value": Brightness},
    },
}
}

occluder = {
    "occluder": {
        "type": "sphere",
        "center": OccPos,
        "radius": OccRad,
        "material": {"type": "roughconductor"}
    }
}

camera = {
    "type": "perspective",
    "to_world": mitsuba.core.Transform4f.look_at(
    origin=(-ReceiverL/2, -ReceiverW/2, OccPos[2]), target=(0, 0, OccPos[2]*.1), up=(0, 0, 1),
    ),
    "fov": 45.0,
}

camera["film"] = {
    "type": "hdrfilm",
    "pixel_format": "rgb",
    "crop_offset_x":220,
    "crop_offset_y": 273,
    "crop_height": 2,
    "crop_width": 1,
    "width": 512,
    "height": 512,
}


surfaces=receiver
surfaces.update(emitter)
surfaces.update(occluder)
camera["sampler"] = {"type": "independent", "seed": 0, "sample_count": 1024}
integrator = {"type": "path", "hide_emitters": False}
scene = {"type": "scene", "camera": camera, "integrator": integrator}
scene.update(surfaces)

mitsuba_scene = mitsuba.core.xml.load_dict(scene)


for i in range(1,5):
    SeedChange = datetime.now().microsecond
    
    sensor = mitsuba_scene.sensors()[0]
    sensor.sampler().seed(SeedChange)

    mitsuba_scene.integrator().render(scene=mitsuba_scene, sensor=sensor)

    film = sensor.film()
    img = film.bitmap(raw=True).convert(mitsuba.core.Bitmap.PixelFormat.Y,       mitsuba.core.Struct.Type.Float32, srgb_gamma=False)
    I = np.array(img)
    print(I)

**Comment by merlinND** [comment]
Thanks for sharing your nice self-contained script.
My bad, I thought you were using one of the wavefront variants of the renderer.
When calling `integrator().render()`, the sampler is seeded for each pixel of each block of the image:

https://github.com/mitsuba-renderer/mitsuba2/blob/76445e90e74eb083b43240d586e2fe453186560d/src/librender/integrator.cpp#L199

However, the sampler receives that seed and interprets it as an offset from the `base_seed`:

https://github.com/mitsuba-renderer/mitsuba2/blob/76445e90e74eb083b43240d586e2fe453186560d/src/librender/sampler.cpp#L83-L87

So what you could do is either:

- Add a setter to `Sampler` to change the `base_seed` at each iteration. @Speierers, do you think we should have this setter available by default?
- Create a new sampler at each iteration with the `base_seed` property of your choice. At this point though, I think you'd also have to re-create the `Sensor` that refers to the new sampler, because we don't have a setter for that either.

Also, when testing, make sure that the scene you are rendering is not accidentally 100% noise-free, otherwise you wouldn't be able to tell the difference between seeds.

**Comment by karticsubr** [comment]
Thank you. Although I have the dictionaries for the sensor and sampler in this toy example, in reality I read it from an xml file. Is there a way to 
1) create only the sensor from the xml file (with variables as with the entire scene), OR 
2) Convert between objects and dictionaries? i.e. I would like to take scene.sensors()[0], convert it to a dictionary, update the sampler's seed (which I assume is base_seed) and then create a new sensor object from the modified dictionary. 

If neither of these is possible, I'm not sure how to implement your suggestion to 're-create the sensor' from its description in the xml file without re-creating the entire scene. Does that make sense?

**Comment by merlinND** [comment]
I see, if your scene is loaded from XML, then adding a `set_base_seed` setter to the `Sampler` interface will really be the most straightforward solution because neither (1) nor (2) would be easy.

**Comment by karticsubr** [comment]
OK, appreciate the quick guidance. Thanks!

**Comment by merlinND** [comment]
No problem, thanks for taking the time to provide a nice self-contained example!

**Comment by Yingyan-Xu** [comment]
Hi, I have a issue related to this one. I'm working on inverse rendering with `gpu_autodiff_rgb` variant. I need to perform different screen space cropping (because of memory limits). Is it possible to change the crop size and offset of the film in each iteration? Currently it says 
```
AttributeError: 'mitsuba.render.Sensor' object attribute 'film' is read-only
```

**Comment by merlinND** [comment]
@Yingyan-Xu Yes, you should be able to call `sensor.film().set_crop_window()` without re-creating the film:

https://github.com/mitsuba-renderer/mitsuba2/blob/76445e90e74eb083b43240d586e2fe453186560d/include/mitsuba/render/film.h#L78-L80

**Comment by karticsubr** [comment]
Update: I used the following work-around:

1. Extract the sensor string from the xml file 
2. use load_string to create a sensor object within the loop 
3. call render with the newly created sensor object 

I had to add a 'version' tag to the sensor section of the XML for this to work, but I thought this is easier than mucking about in the C++ code. Hope that helps.

**Comment by Yingyan-Xu** [comment]
Thanks a lot for your swift replies!
