### ISSUE TITLE
[❔ other question] gpu rendering slower than cpu

### ISSUE THREAD

**Issue by naachoo0** [mitsuba-renderer/mitsuba2#338]
Hello everyone!

I would like you to answer a couple of questions:

- Why the gpu (GTX 1060 - 3GB) rendering is a bit slower or equal than cpu (i7-7700)? it shouldn't be faster?
- If the graphics card were an RTX, it would improve the execution times?
- And the last one. I only can render with a 512x512 with 8 samples when rendering is in gpu_* mode. If I have a graphics card with more GB of VRAM (12GB for example), I could only render with 1024x1024 with 8 samples or 512x512 with 32 samples, right?

I'm sorry I have so many questions but I was thinking of buying an rtx if the execution times are improved.

Thanks in advance

**Comment by Speierers** [comment]
Hi @naachoo0 ,

We are well aware that performance of the GPU variants in Mitsuba 2 are not optimal and can even be worst than the CPU variants. The upcoming Mitsuba 2 release addresses this issue, as well as the issue of memory consumption (3rd question). You will then be able to render much larger scene and faster with your current GPU.

A RTX graphics card will definitely improve execution times, although this is very much scene dependent. Take a look at the Mitsuba 2 profiler output to see whether most of the time spend is for ray tracing or not. This might not always be the case.

Good luck with your projects!
