### ISSUE TITLE
Cannot find 'mitsuba-render.dll' when compiling [🔨 compilation issue]

### ISSUE THREAD

**Issue by Shao-Kui** [mitsuba-renderer/mitsuba2#339]
## Summary
I followed the documentation and tried building mitsuba on Windows with VS2019. However, when I entered mitsuba.sln and build in release mode, the compilation finally said ''can not find mistsuba-render.dll'' and the compilation failed...

## System configuration

- Platform: Windows 10
- Compiler: 
- Python version: 3.6
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    "scalar_rgb"
    "scalar_spectral"

**Comment by Speierers** [comment]
Hi @Shao-Kui ,

Did you build Mitsuba 2 withing a `build` folder as described in the doc?

**Comment by Shao-Kui** [comment]
Hi @Speierers , thanks so much for the reply, but I'm a bit confused...

I did follow the document. The document says `Afterwards, open the generated mitsuba.sln file and proceed building as usual from within Visual Studio. You will probably also want to set the build mode to Release there.` (Chapter: Compiling the system) Thus, I tired to build the project using this .sln file and got the `missing .dll file` message...

**Comment by Speierers** [comment]
Yes. To get the `.sln` file you must have used `CMake`, and I believe it is important that you run `cmake` from within a `build` directory rather than at the root Mitsuba folder.
```
git clone ....
cd mitsuba2
mkdir build
cd build
cmake ..
```

**Comment by Shao-Kui** [comment]
Yeah...but I still got the following error...

``` 
ljm@ShaoKui MINGW64 /g/mitsuba2/build
cmake -G "Visual Studio 16 2019" -A x64
... ... ...
CMake Error at CMakeLists.txt:18 (message):
  The Mitsuba dependencies are missing! You probably did not clone the
  project with --recursive.  It is possible to recover by invoking

  $ git submodule update --init --recursive


-- Configuring incomplete, errors occurred!
See also "G:/mitsuba2/build/CMakeFiles/CMakeOutput.log".

```

I cloned this directory using '--recursive'. Much apologize for bordering you again...

**Comment by Speierers** [comment]
Are you pointing to the parent folder when running `cmake` from the `build` directory? (e.g. add `..` at the end of the `cmake` command)

**Comment by GoodKuro** [comment]
To the problem with the "missing Mitsuba-Render.dll", i had the same problem sometimes when i reinstalled it, it made no difference if i used a build folder or used the root-mitsuba folder.
It helped building the whole solution (Build -> Build Solution) and not only the mitsuba project in my case. After that the problem was gone, maybe it helps.

**Comment by Shao-Kui** [comment]
Thanks so much!!! @GoodKuro 

This really works for me after I re-built the entire solution, and I finally ran a demo. 

Thanks again for the kindly help! @Speierers @GoodKuro
