### ISSUE TITLE
[❔ other question] Scene setup with linear polarizing filter to both emitter and cameras

### ISSUE THREAD

**Issue by Yingyan-Xu** [mitsuba-renderer/mitsuba2#341]
How should I set up a scene where the emitter (`envmap`) and cameras are applied horizontal or vertical linear polarizing filters? I'm currently struggling to get the correct scene configuration. Could please refer me to some example scene files? Thanks a lot!

**Comment by tizian** [comment]
Hi,
Here is an example scene from our [paper on measured pBRDFs](http://rgl.epfl.ch/publications/Baek2020Image) that is similar to what you want to achieve I think:
https://www.dropbox.com/s/o5gyzdqt5h1486q/dragon.zip?dl=0

It has scene files for a few different filters placed in front of the camera (NDF filter, horizontal & vertical linear polarizer, left & right circular polarizer).
It just places a `rectangle` shape with the appropriate material in front of the camera. This can be achieved simply by giving the shape the same transform as the camera, with some additional offset along the camera's z-axis.

Example camera transform:
```
<transform name="to_world">
    <rotate x="0.0" y="1.0" z="0.0" angle="180.00"/>
    <rotate x="1.0" y="0.0" z="0.0" angle="-32.13"/>
    <rotate x="0.0" y="1.0" z="0.0" angle="-114.95"/>
    <rotate x="0.0" y="0.0" z="1.0" angle="-0.77"/>
    <translate x="-1.027193" y="1.043566" z="-0.508638"/>
</transform>
```
Example rectangle shape for the case of a horizontal linear polarizer:
```
<shape type="rectangle">
    <bsdf type="polarizer">
    </bsdf>

    <transform name="to_world">
        <translate z="0.1"/>
        <rotate z="1" angle="0"/>   <!--  This angle (in degrees) can be tweaked to rotate the filter. -->

        <rotate x="0.0" y="1.0" z="0.0" angle="180.00"/>
        <rotate x="1.0" y="0.0" z="0.0" angle="-32.13"/>
        <rotate x="0.0" y="1.0" z="0.0" angle="-114.95"/>
        <rotate x="0.0" y="0.0" z="1.0" angle="-0.77"/>
        <translate x="-1.027193" y="1.043566" z="-0.508638"/>
    </transform>
</shape>
```

Note that the scene file uses some of the measured pBRDF data (from [here](http://vclab.kaist.ac.kr/siggraph2020/pbrdfdataset/kaistdataset.html)) as a default, but you can replace the BSDF with e.g. a `conductor` or `roughconductor` material.

Please also make sure that you're working on the (yet to be merged) branch [`polarbrdf-old`](https://github.com/mitsuba-renderer/mitsuba2/tree/polarbrdf-old) that includes a lot of polarization specific bugfixes.

There is currently no good way to make the `envmap` emitter somehow polarized. It is unclear what "horizontal" polarization would even mean for such a light source. If you have some specific usecase in mind for this, you might need to tweak some of the implementation of the `envmap` to return the right Stokes vector that you need.

Best,
Tizian

**Comment by Yingyan-Xu** [comment]
Thanks a lot @tizian ! The examples are really helpful. My `envmap` is actually captured from polarized light source. I think I need to find another way to model the lighting.

**Comment by Yingyan-Xu** [comment]
Hi @tizian , thanks again for your previous reply! I have 2 other questions related to this issue:

1. Does the polarization feature work with inverse rendering currently in Mitsuba 2? According to issue #159 , it seems that answer is NO? In my project I don't need to differentiate wrt polarimetric quantities. I just want to keep them as fixed parameters and reconstruct some other material properties.
2. Regarding the `envmap` problem above, does it work if I want to attach a `polarizer` BSDF to a `sphere` shape? I would think it's still not well defined regarding the optic axis. Do you have any idea on this?

Thanks again!

**Comment by tizian** [comment]
1. As pointed out in #159, this is unfortunately not quite ready at this point.

2. When attaching a polarization filter to a shape, it will use the underlying UV coordinate axes as horizontal and vertical axes of the polarizer. I'm not sure if the mapping of the `sphere` shape would give you what you want here.

**Comment by wxw19990405** [comment]
Hi @tizian , recently I run into a problem when i used the example sence from https://www.dropbox.com/s/o5gyzdqt5h1486q/dragon.zip?dl=0. the code didn't work when i setmi.set_variant("llvm_spectral_polarized"), i know it should be "scalar_spectral_polarized", but it turn out very slow when i set <default name="spp" value="1024"/>

**Comment by wxw19990405** [comment]
> Hi @tizian, I set the variant "llvm_spectral_polarized" to get no errors, but when I do render image = mi.render(scene), it does not report errors but does not generate the render result. Do you know why this happens and what should I do to solve it?

**Comment by tizian** [comment]
I don't think the LLVM variants in Mitsuba 2 ever compiled correctly when polarization is enabled. This is all pretty outdated at this point. I'd suggest you re-try with [Mitsuba 3](https://github.com/mitsuba-renderer/mitsuba3) and, if necessary, open a new issue over there.

**Comment by wxw19990405** [comment]
@tizian Actually I am just using mitsuba3
