### ISSUE TITLE
ImportError: The 'mitsuba' native modules could not be imported. 

### ISSUE THREAD

**Issue by liweixue0215** [mitsuba-renderer/mitsuba2#342]
*Please add one of the following label to your issue's title, and delete this section:*

- [🐛 bug report]
- [🔨 compilation issue]
- [✨ feature request]
- [❔ other question]

## Summary

*Please enter a brief description of your issue <- [remove this]*

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: ...
- Compiler: ...
- Python version: ...
- Mitsuba 2 version: ...
- Compiled variants:
    * `scalar_rgb`
    * ...

## Description

*Please enter the full description of your issue <- [remove this]*

## Steps to reproduce

*For bug report, please enumerate the steps to follow in order to reproduce the issue <- [remove this]*

1. ...
2. ...

**Comment by keepwonder** [comment]
我和你遇到的问题应该是一样的，要设置一下环境变量，你可以先直接运行下setpath.bat(setpath.sh),重启电脑，不行的话，就手工设置一下，我的设置完了，就可以直接运行了，不知道你解决了没有，FYI
