### ISSUE TITLE
[? other question] Custom Python BRDF with texture

### ISSUE THREAD

**Issue by AakashKT** [mitsuba-renderer/mitsuba2#343]
From BSDF plugin the example here https://mitsuba2.readthedocs.io/en/latest/src/advanced_topics/custom_plugins.html, if I instead change m_reflectance to
```
self.m_reflectance \
            = load_string('''<texture version='2.0.0' type="bitmap" name="reflectance">
        <string name="filename" value="resources/diffuse.jpg"/>
    </texture>''')
```
I get the following error:
```
​[Texture] BitmapTexture::eval(): not implemented!
```

Is there an alternative way to add texture to custom BSDF plugins? Or is this a pybind11 issue?

Thanks!

**Comment by Speierers** [comment]
Hi @AakashKT,

For this to work you will need to call `expand()[0]` on the result of the `load_string`. `BitmapTexture` is a generic type that needs to be "specialized" based on the type of images (here RGB). In Mitsuba 2 this can be achieved at runtime via the `.expand()` method.

Note that you could also use the `load_dict` function which is a bit cleaner IMO:
```python
        self.m_reflectance = load_dict({
            'type' : 'bitmap',
            'filename' : 'resources/data/common/textures/carrot.png'
        }).expand()[0]
```

In the future we will try to make the error message more explicit.

**Comment by AakashKT** [comment]
Thank you for the quick reply! 
You and your teams efforts on Mitsuba 2 are really invaluable and it's a great tool for new researchers!
