### ISSUE TITLE
[❔ other question] depth rendering：Can I use it to render depth maps？

### ISSUE THREAD

**Issue by liweixue0215** [mitsuba-renderer/mitsuba2#345]
I tested the depth map rendering file in the example, but I could not get the depth map.

**Comment by merlinND** [comment]
Hi @liweixue0215,

Could you please provide more detail about your issue: what are you trying to achieve, which scene you have rendered, what output did you get and how is it different from what you expected.
Please also specify which mode you are using.

**Comment by liweixue0215** [comment]
Hi @merlinND ,
I used the program of this path /mitsuba2/docs/examples/02_depth_integrator/depth_integrator.py . the mode is packet_rgb. 
I extracted the value of rgb and displayed it in the picture, and extracted the value of a and w. All black pictures displayed on channel a and channel w. 
Here, I uploaded an rgb picture, showing a different scene from the normal rendering.
![output](https://user-images.githubusercontent.com/52693021/100613608-c8d88c80-334f-11eb-8fed-a65cc3a7d902.jpg)

**Comment by merlinND** [comment]
Could you try the same thing in `scalar_rgb` mode?

**Comment by liweixue0215** [comment]
@merlinND ,
I can use this mode to render the scene.
I decide not to use this to solve my depth rendering problem, I find an easier way is to set the depth integrator.
Thanks.

**Comment by merlinND** [comment]
True, the depth integrator should work well.

**Comment by pablospe** [comment]
> I decide not to use this to solve my depth rendering problem, I find an easier way is to set the depth integrator.

Could you please provide more details about your solution? How did you set the depth integrator to make it work?
