### ISSUE TITLE
[❔ other question] Blurry edges from pathreparam integrator?

### ISSUE THREAD

**Issue by Yingyan-Xu** [mitsuba-renderer/mitsuba2#347]
## Summary

Does the `pathreparam` integrator produce blurry edges when rendering or is it just that I did not get the right parameter setting?

## Description

I'm working with `pathreparam` integrator to optimize displacement. And I noticed that this integrator somehow gives much blurry renders than `path` or `direct`. Pictures attached are rendered with exactly the same setting except for the integrator.

![pathreparam](https://user-images.githubusercontent.com/38786301/100759304-c417e500-33f0-11eb-8135-a5379bdc6769.png)
![direct](https://user-images.githubusercontent.com/38786301/100759361-d003a700-33f0-11eb-8802-e83c76851820.png)

I was wondering whether it's because I didn't get the right parameter settings or it's just the characteristics of the `pathreparam` integrator. The blur artifacts can be removed by moving the camera closer to the object (with larger `fov`) but I cannot move the cameras in my case because they are fixed in the capture setting. And I need sharp renders to recover to geometric details.

xml file for the attached pictures
```
<scene version="2.0.0">
	<!-- <integrator type="direct"/> -->
	<integrator type="pathreparam"/>

    <shape type="sphere">
        <bsdf type="diffuse"/>
    </shape>

	<sensor type="perspective">
		<float name="fov" value="0.5"/>
        <transform name="to_world">
			<lookat target="0 0 0" origin="300 0 0" up="0 1 0"/>
        </transform>

		<sampler type="independent">
            <integer name="sample_count" value="1"/>
        </sampler>

		<film type="hdrfilm">
			<integer name="height" value="256"/>
			<integer name="width" value="256"/>
		</film>
	</sensor>

	<emitter type="constant"/>
</scene>
```

Thanks a lot!

**Comment by Speierers** [comment]
Hi @Yingyan-Xu ,

It is recommended to use the `box` reconstruction filter with the `pathreparam` integrator as the pixel filtering is already taken care of within the integrator (so to capture discontiniuties in the pixel filter integral). Let me know whether this helps!

Other than that, I believe the `pathreparam` integrator should blur the "primal" image.

**Comment by Yingyan-Xu** [comment]
Hi @Speierers ,

Thanks for your quick reply. I just tried `box` reconstruction filter but it didn't help with the blur.
![sphere_pathreparam_box](https://user-images.githubusercontent.com/38786301/100767842-828c3780-33fa-11eb-947f-1be617cf5472.png)

**Comment by Speierers** [comment]
Could you try the following two things:
1. Render the `cbox.xml` with both `path` and `pathreparam` to see whether this problem occors on other scenes as well. Otherwise it must be related to your specific scene.
2. In `pathreparam`, at the beginning of the `sample()` function you will find the following line:
```c++
Float target_mean_cos =
                min(cos(angle * 0.4f /*arbitrary*/), Float(1.f - 1e-7f));
```
Could you try with different values here, replacing the constant `0.4f`.

I suspect that your `fov=0.5` is a pretty extrem case where this heuristic that computes the meancosine of the pixel filter fails. Maybe twicking this constant value, you will get it to work. You could expose it as a parameter of the integrator it you don't wanna have to recompile every time ;)

**Comment by merlinND** [comment]
@Yingyan-Xu Note that the FoV angle is specified in degrees, so indeed 0.5 is quite an extreme value.

**Comment by Yingyan-Xu** [comment]
Hi @Speierers and @merlinND , I tried twicking the heuristic constant value as suggested. It changes a lot to the render. Below are 4 renders with the constant equal to 5, 3, 1, 0.5. The rendered image doesn't change if I set the constant smaller than 0.5.
![sphere_5](https://user-images.githubusercontent.com/38786301/101108115-23821a80-35d4-11eb-832c-0dc777bd7871.png)![sphere_3](https://user-images.githubusercontent.com/38786301/101108121-25e47480-35d4-11eb-869d-c12a44b2a50f.png)
![sphere_1](https://user-images.githubusercontent.com/38786301/101108128-28df6500-35d4-11eb-9540-65e523a2780b.png)![sphere_0 5](https://user-images.githubusercontent.com/38786301/101108134-2b41bf00-35d4-11eb-8ca2-ff93ba9f7474.png)
Going with higher `spp` helps but still you can see some artifacts around the boundary. Pictures below is rendered with `spp=32` and the constant set to 0.5.
![sphere_spp32](https://user-images.githubusercontent.com/38786301/101108651-4bbe4900-35d5-11eb-83eb-ee51f520c4c3.png)

For the project I'm working on, I need to recover some high frequency geometric details, where the camera parameters should be fixed. The original `fov` is larger but the mesh is much larger and also the film resolution. What I'm trying now is to crop a patch and zoom in to see the result. `pathreparam` integrator also gave blurry renders in my original scene setup. And I can't go with higher spp due to GPU memory limit. It seems that `pathreparam` integrator currently cannot work with really high res meshes?

**Comment by Speierers** [comment]
Hi @Yingyan-Xu,

Have you tried to manually set a very high value to `kappa_camera` in the integrator (rather than changing the constant in the meancosine heuristic)? Something like `1e5` or `1e6`.

**Comment by Yingyan-Xu** [comment]
Hi @Speierers , I tried setting `kappa_camera` to `1e6` and it didn't reallly help.

> If I understand correctly, you are ideally trying to render an image with a larger `fov` and a higher resolution be are unable due to GPU memory limitation?

Yes. 

> If this is the case, could you maybe try to use the `crop` feature of the `film` rather than changing the `fov` value?

This is actually what I'm doing. But I think it's not the issue in this case. Let's say my original film resolution is 2kx2k, and `fov` is 9. I crop a 100x100 patch in the center (or maybe just 50x50). The `fov` related to this patch is small anyway (since I cannot change the original camera setting). You can see the sphere example I gave as a cropped patch from a very high resolution film. The real problem lies at how high resolution the `pathreparam` integrator can handle. I'm trying to recover high frequency details, e.g., displacement of human skin. My settings may not be that extreme as the given sphere example. But the `pathreparam` integrator failed to provide sharp enough render. And I think the cause is the same as the sphere example. I attached some real example in my project below. I didn't change the `fov` setting in the example below and just did cropping. The left picture is the forward render given by `pathreparam`, and the right is the target of the inverse rendering, given by `direct` integrator.

![pathreparam](https://user-images.githubusercontent.com/38786301/102379084-cb311c80-3fc6-11eb-9d33-990b200d4d06.png)![direct](https://user-images.githubusercontent.com/38786301/102379095-ce2c0d00-3fc6-11eb-8523-dea9e9be8a73.png)

> Also have you try to split your render in multiple passes (e.g. very small number of spp per pass and accumulate the resulting gradients)?

The original resolution is too high that even forward rendering with `spp` set to 1 would lead to out of memory error on GPU. So I have to do cropping.

**Comment by Speierers** [comment]
I finally had the time to give this a try. Rendering your simple sphere scene with `kappa_camera = 1e8` produces a reasonably sharp image. Could you try this on your end?

**Comment by Yingyan-Xu** [comment]
Hi @Speierers , setting `kappa_camera = 1e8` solved the problem for the given sphere example. Thanks a lot!
