### ISSUE TITLE
[❔ other question]how to import mitsuba2 in python version 3?

### ISSUE THREAD

**Issue by keepwonder** [mitsuba-renderer/mitsuba2#349]
## Summary

in mitsuba version 0.5 , code like this can be functional
=======
`import os
import sys

**sys.path.append('D:/Program Files/Mitsuba 0.5.0/python/2.7')
os.environ['PATH'] = 'D:/Program Files/Mitsuba 0.5.0' + os.pathsep + os.environ['PATH']**

import mitsuba
import numpy as np
from mitsuba.core import *

myVector = normalize(Vector(1.0, 2.0, 3.0))
trafo = Transform.rotate(Vector(0, 1, 0), 90)

print trafo * myVector`
=============
In mitsuba2 and with python3 , how to write my code or make some settings like bold codes ?

anyone meet this problem?

tks!

**Comment by Speierers** [comment]
Hi @keepwonder,

You will need to run the `setpath.sh` (or `setpath.bat` on windows) script as described in the documentation.

**Comment by merlinND** [comment]
If you want to set the path directly from Python, check the contents of the `setpath.sh` script and add these same paths to your `sys.path`.

**Comment by keepwonder** [comment]
@Speierers @merlinND thank you guys! The problem is been done! In my environment, I did clicked the setpath.bat, and restart my windows, but somehow it won't work yestoday, and it makes me think that I did it in a wrong way? and when I see you guys anwsers, and I did it again, but  i did it manually  instead of run bat file directly, and it worked...  In a word ,Thank you guys!!!

**Comment by justanhduc** [comment]
if you use Ubuntu, you can make a soft link for the built `enoki` and `mitsuba` in `site-packages`. It worked for me.
