### ISSUE TITLE
[❔ other question] Enoki going out of memory

### ISSUE THREAD

**Issue by darthgera123** [mitsuba-renderer/mitsuba2#352]
We are trying to do multiview material and lighting optimization using mitsuba by overwritting the optimized texture and lighting over and over. However, enoki apparently goes out of memory at certain consistent points. 
Here is the code:
https://pastebin.com/iypNcufi

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: Ubuntu 20.04
- Compiler: gcc 8, clang 9
- Python version: 3.8
- Mitsuba 2 version: 2.06
- Compiled variants:gpu_autodiff_rgb
    

## Description
Error recieved: 
```
cuda_check(): runtime API error = 0002 "cudaErrorMemoryAllocation" in ../ext/enoki/src/cuda/horiz.cu:326.
terminating with uncaught exception of type std::runtime_error: CUDABackend: referenced unknown variable 55247872
```

**Comment by Speierers** [comment]
Hi @darthgera123 ,

Could you try to reduce the `spp` or the resolution of the film to see whether this fixes your issue?

**Comment by darthgera123** [comment]
@Speierers  is there a way to clear memory after every individual optimization? ek.clear_malloc didnt quite work

**Comment by darthgera123** [comment]
also @Speierers is there a better way to do multi view optimization apart from running individually like this? maybe using something in cache or something ?

**Comment by Speierers** [comment]
> @Speierers . Thanks for the reply. Is there a way to clear memory after every individual optimization? ek.clear_malloc didnt quite work

Have you tried `ek.cuda_malloc_trim()`?

> also @Speierers is there a better way to do multi view optimization apart from running individually like this? maybe using something in cache or something ?

It is hard to properly answer your question with such little information. Their is currently not "caching' mechanism that could be shared between renders from different view point. I guess you could implement techniques like path guiding and share the importance cache between those renders. But you will need to implement this yourself unfortunately.
