### ISSUE TITLE
How to use the software mitsuba2 to synthesize four kinds of maps into one.

### ISSUE THREAD

**Issue by litc-rgb** [mitsuba-renderer/mitsuba2#353]
How to use the software mitsuba2 to synthesize four kinds of maps into one.
Details:
Now we hope to generate more original images based on limited map, changing illumination and so on.

**Comment by Speierers** [comment]
Hi @litc-rgb ,

I don't really understand your question. What do you mean by "map"? Are you talking about environment map?

**Comment by litc-rgb** [comment]
Thank you very much .The question I want to ask is how to combine four materials into one new material. Another problem is that:each SVBRDF can be converted to the four Cook-Torrance parameter maps。The opposite process：Can four cook Torrance parameter maps be merged into one SVBRDF？

**Comment by Speierers** [comment]
Could you use the [`blendbsdf'](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#blended-material-blendbsdf) for that? I have the feeling that this question is out of scope for this issue tracker and is not necessarly related to Mitsuba 2.

You could also use Mitsuba 2 as an inverse renderer to compute the parameters of your "fused" BSDF. Is this what you are looking for?

**Comment by litc-rgb** [comment]
Thanks.Another problem is that:how to use Mitsuba 2 as an inverse renderer to compute the parameters of my "fused" BSDF？

**Comment by Speierers** [comment]
Your BSDF plugin will need to expose its parameters overiding the `traverse()` and `parameters_changed()` methods (e.g. see `diffuse.cpp` as an example). 

They you should be able to follow the [inverse rendering tutorials](https://mitsuba2.readthedocs.io/en/latest/src/inverse_rendering/diff_render.html) to optimize your BSDF parameters.

**Comment by litc-rgb** [comment]
Thank you very much.I want to ask you another question:How to decompose an image into multiple images using this software mitsuba2.
input:
An original image
output
material_Base Color.png
material_Height.png
material_Metallic.png
material_Normal.png
material_Opacity.png
material_Roughness.png
material_Specular Level.png

**Comment by Speierers** [comment]
If the original image is a rendering of a scene, you will then need to use Mitsuba as a inverse renderer to optimize those textures. For this you will first need to implement a differentiable BSDF plugin that uses all of those.

Good luck with your projet!
