### ISSUE TITLE
[❔ other question] how to generate a new material by use other four kind material 

### ISSUE THREAD

**Issue by keepwonder** [mitsuba-renderer/mitsuba2#354]
## Summary

Now I have four png as below:

marble_red_01_height.png
marble_red_01_metallic.png
marble_red_01_normal.png
marble_red_01_roughness.png

and  the task is to use this four png to generate a new picture with some other parameters such as light direction、intensity...

can mitsuba2 get this done?

or how can i write my xml file or code?

any idea?

Thanks!

**Comment by Speierers** [comment]
Hi @keepwonder ,

Those look like textures that you would feed to a BSDF model similar to the Disney BRDF, which hasn't been ported yet. You can still use a combination of `normalmap` and `roughconductor` BSDFs to produce images with you `normal.png` and `roughness.png` maps.

Regarding how to write the XML file, I refer you to the following documentation pages:
- [Scene file format](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/file_format.html)
- [Roughconductor BSDF](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#rough-conductor-material-roughconductor)
- [Normalmap BSDF](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#normal-map-bsdf-normalmap)

Porting the Disney BSDF to Mitsuba 2 is on our roadmap, although it is not going to happen in the next couple months as this is not high priority.

**Comment by keepwonder** [comment]
@Speierers Thanks a lot!
