### ISSUE TITLE
[❔ other question] How to generate python api document？

### ISSUE THREAD

**Issue by liweixue0215** [mitsuba-renderer/mitsuba2#357]
When I use mitsuba, I often cannot find a suitable python API. When I check the compilation and installation guide, the python document will be generated by sphix, but it is not generated. Do I need to make the document myself?

python3-sphinx python3-guzzle-sphinx-theme python3-sphinxcontrib.bibtex have been installed.

**Comment by Speierers** [comment]
Hi @liweixue0215 ,

You will need to run `make mkdoc` to build the `HTML` documentation locally.

You can also use the `search` feature of the online documentation to browse the Python API.

**Comment by merlinND** [comment]
Closing for now, please feel free to reopen with further questions.
