### ISSUE TITLE
[🐛 bug report] Spectra are broken in double precision variants, because create_texture_from_spectrum uses raw float* pointers

### ISSUE THREAD

**Issue by tomasiser** [mitsuba-renderer/mitsuba2#358]
## Summary

When parsing .xml scene files, if you define a spectrum such as:

```xml
<spectrum name="albedo" value="400:0.5, 800:0.5" />
```

this spectrum is parsed in `xml.cpp` and goes through the `create_texture_from_spectrum` function. However, this function takes `std::vector<float>` wavelengths and values, which are passed as raw pointers **`float*`** to `props` via `props.set_pointer`.

Unfortunately, when this goes to the `RegularSpectrum` constructor in `regular.cpp` (and similarly for irregular):

```cpp
const ScalarFloat *values = (ScalarFloat *) props.pointer("values");
```

it expects the raw pointer to be `ScalarFloat*`, which evaluates to **`double*`** in double precision variants.

This causes the spectrum to have rubbish values, which you can confirm in Python by doing:

```python
scene = load_file(...)
print(scene)
```

and getting

```
RegularSpectrum[
        distr = ContinuousDistribution[
          size = 2,
          range = [400, 800],
          integral = 0.00610352,
          pdf = [3.05176e-05, 0]  <<---------- SHOULD BE [0.5, 0.5]
        ]
```

## Possible fixes and why they do not work

I think the easiest fix would be to change `create_texture_from_spectrum` to use `Float` or `ScalarFloat`. Unfortunately, in `xml.h`, where the function is declared, `Float` is not declared yet. That is why I created this issue so that someone more experienced in the variant templates can fix this. Also, in `xml.cpp`, there is the following line, which breaks `double` compatibility:
```cpp
using Float = float;
MTS_IMPORT_CORE_TYPES()
```

Alternatively, an inverse change could be made in `regular.cpp`, `irregular.cpp`, and possibly other plugins to load the values as `float*`. Unfortunately, that breaks compatibility with other plugins, e.g., `d65`, which correctly uses `ScalarFloat` pointers.

**Comment by Speierers** [comment]
Hi @tomasiser ,

Thanks for reporting this issue and for your investigation.

This is a known issue and it most likely won't be fixed until the next release landed. I will make sure it happens after that.

Unfortunately the `double` variants of Mitsuba were not thoroughly tested.

In the mean time, did you managed to find a workaround?

**Comment by Speierers** [comment]
I am closing this here as it will be fixed in the upcoming release of the codebase.
