### ISSUE TITLE
PluginManager in Mitsuba2

### ISSUE THREAD

**Issue by fareeha** [mitsuba-renderer/mitsuba2#36]
How can we invoke PluginManager in Mitsuba2? It seems that in Mitsuba2, PluginManager it's not an object of `mitsuba.core` (like it was for the previous version).

```
    pmgr = PluginManager.getInstance()
NameError: name 'PluginManager' is not defined
```

**Comment by fangchangma** [comment]
It would be great to add a minimal working example of how to use Python to create a scene (rather than loading an XML file).

**Comment by Speierers** [comment]
The current release doesn't implement python bindings for the `PluginManager` class. This is likely to come in a future release. 

In the meantime, the only way to create a scene is generate an XML file and load it.

**Comment by arpit15** [comment]
@Speierers I took a stab at it. I am able to create a scene in python with classes that are constructible in python(SamplingIntegrator, Sensor, Emitter) and render a scene. However, I am the not able to create a scene which all the supported xml tags. 
The problem has been that I need access to base class ptr to call `PluginManager::create_object`. For ex: to create `HDRFilm` I need access to `Film::m_class`. On digging deeper in `xml.cpp`, I found that it has a variable `tag_class` which stores all the base class pointers. 
Can you guide me on how to access base class ptr to make a call to `PluginManager::create_object` for all the tags supported in Mitsuba?

**Comment by Speierers** [comment]
Hi @arpit15,
Thanks for looking into this!
At this point it would be easier to open a PR so I could have a look a your code to guide you further.

**Comment by arpit15** [comment]
I have created a PR [here](https://github.com/mitsuba-renderer/mitsuba2/pull/45). 
There is a lot of unnecessary code on python side. A better way would be to have a dictionary like `tag_class` in [xml.cpp](https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/libcore/xml.cpp#L110) and use the property like `node_name` to pass in a lambda function in plugin_v.cpp. However, I can't seem to figure out how to get access to class ptr as done in xml.cpp

**Comment by Speierers** [comment]
Thanks @arpit15. I am closing this as further discussions should take place in the PR from now.
