### ISSUE TITLE
[✨ feature request]will mitsuba2 support network rendering in the future

### ISSUE THREAD

**Issue by X-skyer** [mitsuba-renderer/mitsuba2#360]
Hi, I know that mitsuba1 supports network rendering which can make use of lots PCs in our lab, but in mitsuba2 this feature seems missing, will this feature be supported in the feature? Thanks!

**Comment by Speierers** [comment]
Hi @X-skyer, 

This isn't something we have planned yet, although it is a feature that would be nice to have in the long term. Given the flexibility of the Python API of Mitsuba 2, it should be possible to implement a simple pipeline that distributes rendering jobs on many machines yourself.

**Comment by hakanyi** [comment]
Thanks @Speierers! Does Mitsuba2 allow for parallelization of one rendering job across several GPUs (which would be helpful to render large objects/scenes that wouldn't fit into one GPU with, for example, AD wrt the vertex buffer enabled)?

**Comment by Speierers** [comment]
Multi-GPU isn't currently supported although this is on our "longer-term" roadmap.
