### ISSUE TITLE
Paste an image on the rectangle to render. The result after rendering is opposite to the original image. How can I correct it?Thank you.

### ISSUE THREAD

**Issue by litc-rgb** [mitsuba-renderer/mitsuba2#361]
The rendered image and the actual image are symmetrical。
example:
bsdf_diffuse_textured.xml
<scene version="2.0.0">
    <path value="../../common"/>

	<bsdf type="diffuse" id="object_bsdf">
        <texture name="reflectance" type="bitmap">
            <string name="filename" value="textures/wooden_planks_01_basecolor.png"/>
			 
        </texture>
		
	</bsdf>
    <include filename="include/matpreview.xml"/>
</scene>

**Comment by merlinND** [comment]
Hi @litc-rgb,

Could you please post the rendered result vs what you expected?

It's difficult to say without seeing your scene file, but if the image looks reversed or flipped, it could simply be that your rectangle or camera are rotated in the wrong direction, or scaled by `-1`. The UVs of your rectangle could also be flipped.

If the objects and camera are placed as you wanted in the scene but the texture is not placed as you wish, you can adjust the local texture space transform, e.g.:

```
<texture name="reflectance" type="bitmap">
    <string name="filename" value="textures/wooden_planks_01_basecolor.png"/>
    <transform name="to_uv">
        <scale y="-1"/>
    </transform>		 
</texture>
```
