### ISSUE TITLE
[🔨 compilation issue]compilation issue

### ISSUE THREAD

**Issue by cccchensir** [mitsuba-renderer/mitsuba2#365]
## Summary

(base) cauchy@cauchy-VirtualBox:~/mitsuba2/build$ ninja
[0/1] Re-running CMake...
-- Building the following variants of Mitsuba:
--  * scalar_rgb
--  * scalar_spectral
--  * packet_spectral
--  * packet_rgb
-- Mitsuba: using libc++.
-- Mitsuba: building the Python plugin.
-- Enoki: building the Python plugin.
-- pybind11 v2.4.dev4
-- TBB: using libc++.
-- Mitsuba: using builtin implementation for CPU ray tracing.
-- Mitsuba: LTO support enabled.
-- Mitsuba: sampling profiler enabled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cauchy/mitsuba2/build
[3/733] Building CXX object ext_build/...-scalar.dir/src/python/scalar_0d.cpp.o
FAILED: ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_0d.cpp.o 
/usr/bin/clang++-9  -DENOKI_BUILD=1 -Denoki_python_scalar_EXPORTS -I/usr/include/libcxxabi -I../ext/enoki/include -I../ext/pybind11/include -I/home/cauchy/anaconda3/include/python3.7m -stdlib=libc++ -D_LIBCPP_VERSION -std=c++17 -O3 -DNDEBUG -fPIC -fvisibility=hidden   -march=native -fno-stack-protector -fomit-frame-pointer -fno-math-errno -ffp-contract=fast -flto=thin -g0 -Os -std=gnu++1z -MD -MT ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_0d.cpp.o -MF ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_0d.cpp.o.d -o ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_0d.cpp.o -c ../ext/enoki/src/python/scalar_0d.cpp
In file included from ../ext/enoki/src/python/scalar_0d.cpp:1:
In file included from ../ext/enoki/src/python/common.h:9:
In file included from ../ext/enoki/include/enoki/dynamic.h:16:
In file included from ../ext/enoki/include/enoki/array.h:30:
In file included from ../ext/enoki/include/enoki/array_generic.h:14:
In file included from ../ext/enoki/include/enoki/array_static.h:3:
In file included from ../ext/enoki/include/enoki/array_base.h:14:
In file included from ../ext/enoki/include/enoki/array_router.h:18:
../ext/enoki/include/enoki/array_fallbacks.h:130:28: error: always_inline function '_mm_fnmadd_ss' requires target feature 'fma', but would be inlined into function 'rsqrt_scalar' that is compiled without support for 'fma'
            r = _mm_mul_ss(_mm_fnmadd_ss(t1, r, c1), t0);
                           ^
1 error generated.
[4/733] Building CXX object ext_build/...-scalar.dir/src/python/scalar_1d.cpp.o
FAILED: ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_1d.cpp.o 
/usr/bin/clang++-9  -DENOKI_BUILD=1 -Denoki_python_scalar_EXPORTS -I/usr/include/libcxxabi -I../ext/enoki/include -I../ext/pybind11/include -I/home/cauchy/anaconda3/include/python3.7m -stdlib=libc++ -D_LIBCPP_VERSION -std=c++17 -O3 -DNDEBUG -fPIC -fvisibility=hidden   -march=native -fno-stack-protector -fomit-frame-pointer -fno-math-errno -ffp-contract=fast -flto=thin -g0 -Os -std=gnu++1z -MD -MT ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_1d.cpp.o -MF ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_1d.cpp.o.d -o ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_1d.cpp.o -c ../ext/enoki/src/python/scalar_1d.cpp
In file included from ../ext/enoki/src/python/scalar_1d.cpp:1:
In file included from ../ext/enoki/src/python/common.h:9:
In file included from ../ext/enoki/include/enoki/dynamic.h:16:
In file included from ../ext/enoki/include/enoki/array.h:30:
In file included from ../ext/enoki/include/enoki/array_generic.h:14:
In file included from ../ext/enoki/include/enoki/array_static.h:3:
In file included from ../ext/enoki/include/enoki/array_base.h:14:
In file included from ../ext/enoki/include/enoki/array_router.h:18:
../ext/enoki/include/enoki/array_fallbacks.h:130:28: error: always_inline function '_mm_fnmadd_ss' requires target feature 'fma', but would be inlined into function 'rsqrt_scalar' that is compiled without support for 'fma'
            r = _mm_mul_ss(_mm_fnmadd_ss(t1, r, c1), t0);
                           ^
1 error generated.
[5/733] Building CXX object ext_build/...-scalar.dir/src/python/scalar_2d.cpp.o
FAILED: ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_2d.cpp.o 
/usr/bin/clang++-9  -DENOKI_BUILD=1 -Denoki_python_scalar_EXPORTS -I/usr/include/libcxxabi -I../ext/enoki/include -I../ext/pybind11/include -I/home/cauchy/anaconda3/include/python3.7m -stdlib=libc++ -D_LIBCPP_VERSION -std=c++17 -O3 -DNDEBUG -fPIC -fvisibility=hidden   -march=native -fno-stack-protector -fomit-frame-pointer -fno-math-errno -ffp-contract=fast -flto=thin -g0 -Os -std=gnu++1z -MD -MT ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_2d.cpp.o -MF ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_2d.cpp.o.d -o ext_build/enoki/CMakeFiles/enoki-python-scalar.dir/src/python/scalar_2d.cpp.o -c ../ext/enoki/src/python/scalar_2d.cpp
In file included from ../ext/enoki/src/python/scalar_2d.cpp:1:
In file included from ../ext/enoki/src/python/common.h:9:
In file included from ../ext/enoki/include/enoki/dynamic.h:16:
In file included from ../ext/enoki/include/enoki/array.h:30:
In file included from ../ext/enoki/include/enoki/array_generic.h:14:
In file included from ../ext/enoki/include/enoki/array_static.h:3:
In file included from ../ext/enoki/include/enoki/array_base.h:14:
In file included from ../ext/enoki/include/enoki/array_router.h:18:
../ext/enoki/include/enoki/array_fallbacks.h:130:28: error: always_inline function '_mm_fnmadd_ss' requires target feature 'fma', but would be inlined into function 'rsqrt_scalar' that is compiled without support for 'fma'
            r = _mm_mul_ss(_mm_fnmadd_ss(t1, r, c1), t0);
                           ^
In file included from ../ext/enoki/src/python/scalar_2d.cpp:1:
In file included from ../ext/enoki/src/python/common.h:9:
In file included from ../ext/enoki/include/enoki/dynamic.h:16:
In file included from ../ext/enoki/include/enoki/array.h:43:
../ext/enoki/include/enoki/array_sse42.h:757:65: error: always_inline function '_mm_fnmadd_pd' requires target feature 'fma', but would be inlined into function 'fnmadd_' that is compiled without support for 'fma'
    ENOKI_INLINE Derived fnmadd_  (Ref b, Ref c) const { return _mm_fnmadd_pd  (m, b.m, c.m); }
                                                                ^
../ext/enoki/include/enoki/array_sse42.h:755:65: error: always_inline function '_mm_fmadd_pd' requires target feature 'fma', but would be inlined into function 'fmadd_' that is compiled without support for 'fma'
    ENOKI_INLINE Derived fmadd_   (Ref b, Ref c) const { return _mm_fmadd_pd   (m, b.m, c.m); }
                                                                ^
../ext/enoki/include/enoki/array_sse42.h:756:65: error: always_inline function '_mm_fmsub_pd' requires target feature 'fma', but would be inlined into function 'fmsub_' that is compiled without support for 'fma'
    ENOKI_INLINE Derived fmsub_   (Ref b, Ref c) const { return _mm_fmsub_pd   (m, b.m, c.m); }
                                                                ^
../ext/enoki/include/enoki/array_sse42.h:758:65: error: always_inline function '_mm_fnmsub_pd' requires target feature 'fma', but would be inlined into function 'fnmsub_' that is compiled without support for 'fma'
    ENOKI_INLINE Derived fnmsub_  (Ref b, Ref c) const { return _mm_fnmsub_pd  (m, b.m, c.m); }
                                                                ^
5 errors generated.
ninja: build stopped: subcommand failed.

## System configuration
- Platform: Ubuntu 18.04
- Compiler: Clang
- Python version: python3.7
- Mitsuba 2 version: lasted
- Compiled variants:
   --  * scalar_rgb
--  * scalar_spectral

**Comment by cccchensir** [comment]
I have no ideal to figure it out....

**Comment by Speierers** [comment]
Which version of Clang are you using here?

**Comment by cccchensir** [comment]
> Which version of Clang are you using here?

clang9

**Comment by cccchensir** [comment]
> Which version of Clang are you using here?
I follow this command：sudo apt install -y clang-9 libc++-9-dev libc++abi-9-dev cmake ninja-build

**Comment by Speierers** [comment]
When you run `cmake` for the first time it should tell you which compiler it picked from your system. Otherwise you might have to set those environment variables manually:
```export CXX=clang++-9
export CC=clang-9
```
Could you double check that it is picking the right compiler?

**Comment by cccchensir** [comment]
> When you run `cmake` for the first time it should tell you which compiler it picked from your system. Otherwise you might have to set those environment variables manually:
> 
> ```
> export CC=clang-9
> ```
> 
> Could you double check that it is picking the right compiler?

I add thoese commands in ./bashrc.Is this path correct?
export CC=/usr/bin/clang-9
export CXX=/usr/bin/clang++-9

**Comment by cccchensir** [comment]
> When you run `cmake` for the first time it should tell you which compiler it picked from your system. Otherwise you might have to set those environment variables manually:
> 
> ```
> export CC=clang-9
> ```
> 
> Could you double check that it is picking the right compiler?

-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
-- Check for working C compiler: /usr/bin/clang-9
-- Check for working C compiler: /usr/bin/clang-9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-9
-- Check for working CXX compiler: /usr/bin/clang++-9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /home/cauchy/anaconda3/bin/python3.7 (found version "3.7.3") 
-- Found PythonLibs: /home/cauchy/anaconda3/lib/libpython3.7m.so
-- Building the following variants of Mitsuba:
--  * scalar_rgb
--  * scalar_spectral
--  * packet_spectral
--  * packet_rgb
-- Setting build type to 'Release' as none was specified.
-- Mitsuba: using libc++.
-- Mitsuba: building the Python plugin.
-- Enoki: building the Python plugin.
-- pybind11 v2.4.dev4
-- LTO enabled
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- TBB: using libc++.
-- Mitsuba: using builtin implementation for CPU ray tracing.
-- Mitsuba: LTO support enabled.
-- Check if the system is big endian
-- Searching 16 bit integer
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Mitsuba: sampling profiler enabled.
-- Found Sphinx: /home/cauchy/anaconda3/bin/sphinx-build  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cauchy/mitsuba2/build

Here is the output log after cmake operation.

**Comment by Speierers** [comment]
Hi @cccchensir ,

Is this still an issue?

**Comment by velikodniy** [comment]
@cccchensir You can set the `CXXFLAGS` variable *before running CMake* to force the compiler to generate code using FMA, BMI2, F16C that are required for building.

```bash
export CXXFLAGS="-mavx2 -mfma -mbmi2 -mf16c"
```

But after compiling make sure that your CPU supports these instruction sets.

@Speierers I think the issue might be closed.
