### ISSUE TITLE
[❔ other question] Roughness parameter not differentiable?

### ISSUE THREAD

**Issue by Yingyan-Xu** [mitsuba-renderer/mitsuba2#366]
## Summary

Is the roughness parameter alpha of `roughplastic` not differentiable or currently not supported?

## Description

I was trying to optimize wrt the alpha parameter in the `roughplastic` plugin and got an error that seems to be because it's not differentiable. However, the alpha parameter of the `roughdielectric` plugin works.

**Comment by Speierers** [comment]
Hi @Yingyan-Xu,

Indeed this is a current limitation of the `roughplastic` BSDF. The reason for this is that this BSDF precomputes data when constructed which is then used in the sampling/evaluation routines. Right now this precomputation happens on the CPU and is therefore not differentiable.

For now you will have to stick with the `roughconductor` BSDF for differentiable rendering.

We will likely fix this in the future although this is low priority.

**Comment by binorchen** [comment]
Hello Speierers, 

I am also expecting more parameters in the `roughplastic` plugin to be differentiable. 
I know you guys are busy, but may I ask if this problem will be tackled soon?
Thanks a lot for your help!

**Comment by Speierers** [comment]
This is definitely something we are interested in but won't be realised anytime soon. For now we are focus on the upcoming release.

**Comment by binorchen** [comment]
I see. Thank you!
