### ISSUE TITLE
❔Does this software （mitsuba）support moving point light? If so, how can I save the rendered image as a. GIF file after rendering

### ISSUE THREAD

**Issue by litc-rgb** [mitsuba-renderer/mitsuba2#368]
input:
wooden_planks_01_ambient_occlusion.jpg
wooden_planks_01_basecolor.jpg
wooden_planks_01_height.jpg
wooden_planks_01_metallic.jpg
wooden_planks_01_normal.jpg
wooden_planks_01_roughness.jpg

out：
how can I save the rendered image as a. GIF file after rendering

**Comment by Speierers** [comment]
Mitsuba renders a single frame at a time. You should be able to generate a sequence of XML scene files with different light positions and later assemble the rendered images in a GIF to create the impression of motion.
