### ISSUE TITLE
[❔ other question] Getting NaN when setting specular_reflectance to 0 in roughplastic

### ISSUE THREAD

**Issue by Yingyan-Xu** [mitsuba-renderer/mitsuba2#369]
Hi, I am using `roughplastic` material with `specular_reflectance` set to 0 as the appearance model for some cross-polarized reference photos in my inverse rendering project. However, it gave NaN in this setting. Setting `specular_reflectance` to a very small value (i.e., `1e-8`) works though. Could it be due to some minor bugs of Mitsuba 2? 

Thanks a lot and happy new year :D

**Comment by tizian** [comment]
Hi!

Could you please provide a small example scene that reproduces this issue? I likely won't have time to look into the details until next month, but it sounds like you have a workaround at least for now.

The `roughplastic` plugin currently does not support any polarization by the way, so you might want to use something like `roughconductor` instead. I'm also not sure what the physically meaning of `specular_reflectance=0` is exactly. Wouldn't that in a sense revert back to a normal `diffuse` BSDF then?

Best,
Tizian

**Comment by Yingyan-Xu** [comment]
Hi, @tizian . Thanks a lot for the reply! Unfortunately, I recently finished my project and lost the access to GPU. I created a simple scene and a python script but wasn't able to test it.

scene file `sphere.xml`
```
<scene version="2.0.0">
	<integrator type="direct"/>

    <bsdf type="roughplastic" id="mybsdf">
        <rgb name="diffuse_reflectance" value="0.3 0.3 1"/>
        <rgb name="specular_reflectance" value="0"/>
    </bsdf>

    <shape type="sphere">
        <ref id="mybsdf"/>
    </shape>

	<sensor type="perspective">
		<float name="fov" value="5"/>
        <transform name="to_world">
			<lookat target="0 0 0" origin="50 0 0" up="0 1 0"/>
        </transform>

		<sampler type="independent">
            <integer name="sample_count" value="1"/>
        </sampler>

		<film type="hdrfilm">
			<integer name="height" value="256"/>
			<integer name="width" value="256"/>
		</film>
	</sensor>

	<emitter type="directional"/>
</scene>
```

python script
```
import enoki as ek
import mitsuba

mitsuba.set_variant('gpu_autodiff_rgb')
from mitsuba.python.autodiff import render, Adam
from mitsuba.core.xml import load_file
from mitsuba.python.util import traverse

scene = load_file('sphere.xml')
params = traverse(scene)
params.keep(['mybsdf.diffuse_reflectance.value'])
params.update()

image_ref = render(scene, spp=8)

params['mybsdf.diffuse_reflectance.value'] = [.9, .9, .9]
adam = Adam(params, lr=0.02)

for it in range(100):
    image = render(scene, optimizer=adam)
    ob_val = ek.hsum(ek.sqr(image - image_ref)) / len(image)
    ek.backward(ob_val)
    adam.step()

    print(ob_val)
```

What I encountered before is that `ob_val` is always `nan`. Changing `specular_reflectance` to `1e-8` worked. 

My project is related to this [paper](https://studios.disneyresearch.com/wp-content/uploads/2020/07/Single-Shot-High-Quality-Facial-Geometry-and-Skin-Appearance-Capture.pdf), in which the polarization is not modeled accurately (using stoke vectors). For cross-polarized views, the underlying material model is assumed to be a two-layer model with specular intensity set to 0. That's why I need this setting.

I'm not in a hurry on this (since I found a work-around).

Thanks a lot!

**Comment by garrido-pablo** [comment]
Hi @Yingyan-Xu,

I think that the problem could be related to numerical stability issues of floating-point operations while doing automatic differentiation.

Did you check the validity of the gradients? Please make sure your gradients are valid. If not, set them to zero.
Not the cleanest workaround but works in practice...

I hope this helps.

**Comment by Yingyan-Xu** [comment]
Thanks @garrido-pablo ! It works!
