### ISSUE TITLE
[❔ other question] SmoothDiffuse reflectance in aov

### ISSUE THREAD

**Issue by Leekta** [mitsuba-renderer/mitsuba2#370]
## Summary

Hi,

My aim is to gather information from the surface interaction to create a special aov : create an output only on a specific spectrum band. (I know of the pull request and already tested it but it is not what I want in the end)
The information needed is inside the SmoothDiffuse class and is outputed as such when doing a std::cout.
My problem is that I want the reflectance from that object but in the code the element that I get from SurfaceInteraction.shape->bsdf() is a const BSDF pointer, not a const SmoothDiffuse pointer.

Is there a way to get the reflectance from the SmoothDiffuse class inside the aov class through the SurfaceInteraction class ?

**Comment by Speierers** [comment]
Hi @Leekta ,

What you are asking for isn't supported at the moment, although there are various ways to could implement this yourself. For instance to could add an `virtual ScalarColor3f BSDF::albedo() const` method that returns the albedo of the BSDF. This way, once you have a surface interaction, you could recover that albedo in the following way: `si.shape->bsdf()->albedo()`.

Not that you will need to add one line of macro at the bottom of the `bsdf.h` header file to register this new method as a virtual function, smoething like that: `ENOKI_VCALL_METHOD(albedo)`

Good luck!

**Comment by pixiaonuo** [comment]
@Leekta Have you solved this problem? I am also trying to output BSDF value in AOV integrator.
