### ISSUE TITLE
 [✨ feature request] It is possible to set the number of spectral bands at runtime?

### ISSUE THREAD

**Issue by jianboqi** [mitsuba-renderer/mitsuba2#376]
Hi, 
  Thanks all of you for providing such an amazing renderer.
  I just wan to ask is there a way to set the number of spectral bands (in spectral mode) at runtime dynamically, because our simulation may have various number of spectral bands (from 1 to 100, for example).
  I noticed that mitsuba 2 set the "scalar_spectral"  as "spectrum": "Spectrum<Float, 4>" before the compiling.
  I don't know if this feature is already at hand? or How to implement this feature? in Mitsuba 1, actually I have made such a modification, but with a lot of effort? It is easier in Mitsuba 2?
Thanks.

**Comment by Speierers** [comment]
Hi @jianboqi ,

Mitsuba 2 being a "retargetable" renderer, it should be possible to compile a variant of Mitsuba where the `Spectrum` type is a dynamic array. Althought this has never been done before, it might require a bit of work to get it to compile.

**Comment by merlinND** [comment]
One low-effort check you could make is to compare the performance when using 100 spectral bands vs 4 spectral bands. If the performance is acceptable at 100 bands, you could just always run it in that mode and ignore the extra wavelengths.
