### ISSUE TITLE
[❔ other question] is the 'next' branch ready to preview?

### ISSUE THREAD

**Issue by caron** [mitsuba-renderer/mitsuba2#378]
## Summary

I noticed a lot of current development was happening in the `next` branch. I was wondering if this branch is stable enough to preview/use/test? I understand it wouldn't be something you want to support but I wanted to at least know if it was building on Windows at this time?

**Comment by Speierers** [comment]
Hi @caron ,

The `next` branch is in a very experimental state, and has never been compiled / tested on Windows. It will also changed quite a bit in the coming weeks so I wouldn't rely on it at the moment.
