### ISSUE TITLE
[❔ other question] differentiating direction parameter of the directional emitter?

### ISSUE THREAD

**Issue by caron** [mitsuba-renderer/mitsuba2#379]
## Summary

I am looking to use Mitsuba 2 differentiable rendering to recover the `direction` parameter of the `directional` emitter. When I print the parameters of a scene and note what can be differentiated, I don't see the `direction` parameter listed with an asterisk, or even listed at all actually. I do see `DirectionalEmitter.irradiance.value` though...

Please excuse my naivety on the subject but what is the reason for not being able to differentiate the `direction` parameter on the `directional` emitter? Is it just lake of support and can be added or is this not something Mitsuba or inverse rendering can solve?

## System configuration

- Platform: Windows 10
- Compiler: Visual Studio Community 2019
- Python version: 3.7.4
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`
    * `gpu_rgb`
    * `gpu_autodiff_rgb`

## Description

See Summary ^

## Steps to reproduce

1. Add a `directional` emitter to your scene
2. traverse the scene and print the params

**Comment by Speierers** [comment]
Hi @caron ,

Looking at `directional.cpp`:
```c++
    void traverse(TraversalCallback *callback) override {
        callback->put_object("irradiance", m_irradiance.get());
    }
```
    
Only the `irradiance` member of this object is exposed via the `traverse` mechanism. You could expose `direction` here using `callback->put_parameter(...)` but I am warning you, differentiating w.r.t. to `direction` will introduce discontinuities in the rendering integral, yielding biased gradients if not properly handled. Please refer to [this article](https://rgl.epfl.ch/publications/Loubet2019Reparameterizing) for more information on this.

**Comment by caron** [comment]
Thanks @Speierers, I stumbled upon this earlier. I was able to add the parameter to the traverse callback but the parameter doesn't show with an asterisk `*` so I stopped digging.

Thank you for the link, I am afraid this might be too far beyond of my current understanding.

**Comment by Speierers** [comment]
Indeed the `m_world_transform` (constructed from `direction`) of `DirectionalEmitter` is a `ScalarTransform4f` which is a non-differentiable type. This is on our roadmap to make those transform differentiable, but this will require quite a few changes accross the codebase.
