### ISSUE TITLE
mtsgui not working

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/mitsuba2#38]
Unable to render or load a scene in the mtsgui 
## Steps to reproduce
- `./dist/mtsgui`
- Click on any button. For ex: `Open` button 
 
Are there any directions which are missing, on how to use mitsuba GUI?

**Comment by merlinND** [comment]
Hello @arpit15,

The GUI is not ready for usage yet, what is currently in `mtsgui` is more of a mockup of the future UI.
