### ISSUE TITLE
[✨ feature request] Updating scene geometry 

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/mitsuba2#383]
## Summary
The ability to change scene geometry is a very useful feature to me. This feature is currently supported on the GPU. I would very much like to have it in non-GPU variants. I have implemented a solution in [my fork](https://github.com/arpit15/mitsuba2/tree/shapeupdate). 

The current method recreates Embree and KD tree following the corresponding `accel_init_cpu` functions. Kindly let me know if there is a cheaper solution to changing geometry.  

I know the project is going a major refactor. I took a look at `blender_refactoring` branch. It looks that my changes are orthogonal.

**Comment by Speierers** [comment]
Hi @arpit15,

Thanks for sharing your solution. This will be supported in the upcoming refactored codebase, therefore we are not going to make any changes on `master` regarding this feature request.
