### ISSUE TITLE
[❔ other question] Differentiable rendering of participating media 

### ISSUE THREAD

**Issue by webanck** [mitsuba-renderer/mitsuba2#385]
## Summary

Where can I find examples of differentiable rendering of participating media  ?

## Description

Hello !

According to the section about participating media in the Mitsuba 2 article, the inverse rendering optimization is done via a ray marching approximation. Whether bias is very detrimental to the optimization however is not totally clear to me.
Differentiation of delta-tracking is also mentioned, and I am curious about its limitations, but I didn't find the volumetric optimization example in Mitsuba 2's documentation, is it available somewhere else, maybe somewhere in this repo ?

**Comment by dvicini** [comment]
Hi, 

The current version of the Mitsuba 2 code unfortunately does not support heterogeneous volume optimizations very well. If you want to just run some optimization, I would recommend to use the code base from the radiative backrpopagation paper (https://rgl.epfl.ch/publications/NimierDavid2020Radiative). 

However, we are also currently working on supporting optimization using delta tracking, so you can stay tuned for that :) 

Delio
