### ISSUE TITLE
[🔨 compilation issue] Sphinx:3.5.1 build fix.

### ISSUE THREAD

**Issue by bartoszek** [mitsuba-renderer/mitsuba2#388]
## Summary

There's a small hiccup when building against {sphinx:3.5.1,sphinxcontrib-bibtex:2.1.4}
 * Sphinx complains about deprecated function `add_stylesheet` being dropped in favor of `add_css_file`
 * Sphinxcontrib-bibtex complains about missing configuration `.bib` file

## System configuration

- Platform: Linux(Arch)
- Compiler: clang
- Python version: 3.9
- Mitsuba 2 version: 31e243825dfbc78cf8219a20c79431025b6b3d44
- Sphinx: 3.5.1
- Sphinxcontrib-bibtex: 2.1.4

## Solution sketch

```diff
diff --git a/docs/conf.py b/docs/conf.py
index d55711a2..fe409f71 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -164,6 +164,9 @@ todo_include_todos = True

 extensions.append('sphinxcontrib.bibtex')

+# Add bibfile
+bibtex_bibfiles = ['references.bib']
+
 # Touch the bibliography file to force a rebuild of it
 Path('zz_bibliography.rst').touch()

@@ -370,4 +373,4 @@ def custom_step(app):
 def setup(app):
     # Texinfo
     app.connect("builder-inited", custom_step)
-    app.add_stylesheet('theme_overrides.css')
+    app.add_css_file('theme_overrides.css')
```
Above builds fine against `{Sphinx:3.5.1,Sphinxcontrib-bibtex:2.1.4}`
 * Haven't tested if previous versions of `Sphinx{,contrib-bibtex}` still works
 * Haven't tested if documentation files differs from previous `Sphinx` version build.

**Comment by Speierers** [comment]
This will be fixed in the upcoming release. Thanks for you solution sketch!
