### ISSUE TITLE
[🐛 bug report] Possible issue with render tests

### ISSUE THREAD

**Issue by schunkes** [mitsuba-renderer/mitsuba2#389]
## Summary

It seems there is an issue with the usage of the moment integrator in `test_renders.py`

## System configuration

- Platform: Manjaro Linux
- Compiler: Clang 10
- Python version: 3.8
- Mitsuba 2 version: 
- Compiled variants:
    * `scalar_mono_double`
    * ...

## Description

In the script for the render tests (`src/librender/tests/test_renders.py`) is a method to extract the first and second moment results from the Bitmap returned by the moment integratror:

```python
def bitmap_extract(bmp):
    # AVOs from the moment integrator are in XYZ (float32)
    split = bmp.split()
    img = np.array(split[1][1], copy=False)
    img_m2 = np.array(split[2][1], copy=False)
    return img, img_m2 - img * img
```

I am using this function to create my own render tests based on the specialized scenes used in the EO community.

However I noticed, that the return value of `bmp.split()` in the function above does not match the usage of these returned values.

Below you see the return value of the mentioned call. It is apparent, that `split[1]` holds the second moment results, while `split[2]` holds the first moment results. The `bitmap_extract()` function however, expects these two values to be switched. (Note that 'subintegrator' is the label I gave to the nested path tracing integrator in my scene)

Maybe the `Bitmap.split` method changed over time, but the `test_renders` script did not, since the reference results are not recreated often?

```
[('<root>', Bitmap[
  type = rgba,
  component_format = float32,
  size = [90, 1],
  srgb_gamma = 0,
  struct = Struct<16>[
    float32 R; // @0, premultiplied alpha
    float32 G; // @4, premultiplied alpha
    float32 B; // @8, premultiplied alpha
    float32 A; // @12, alpha
  ],
  data = [ 1.41 KiB of image data ]
]), ('m2_subintegrator', Bitmap[
  type = xyz,
  component_format = float32,
  size = [90, 1],
  srgb_gamma = 0,
  struct = Struct<12>[
    float32 X; // @0, premultiplied alpha
    float32 Y; // @4, premultiplied alpha
    float32 Z; // @8, premultiplied alpha
  ],
  data = [ 1.05 KiB of image data ]
]), ('subintegrator', Bitmap[
  type = xyz,
  component_format = float32,
  size = [90, 1],
  srgb_gamma = 0,
  struct = Struct<12>[
    float32 X; // @0, premultiplied alpha
    float32 Y; // @4, premultiplied alpha
    float32 Z; // @8, premultiplied alpha
  ],
  data = [ 1.05 KiB of image data ]
])]
```

## Steps to reproduce

1. Create a valid scene with a moment integrator
2. Render the scene and pass the results to the aforementioned `bitmap_extract` function
3. Print the results

**Comment by Speierers** [comment]
Hi @schunkes ,

Thanks for pointing this out. The reason for this is that bitmaps list resulting from `split` will come in alphabetic order. By naming your nested integrator `subintegrator`, it comes last.

Here is what I get when not specifying any names for the nested integrator:
```
[('<root>', Bitmap[
  type = rgba,
  component_format = float16,
  size = [48, 48],
  srgb_gamma = 0,
  struct = Struct<8>[
    float16 R; // @0, premultiplied alpha
    float16 G; // @2, premultiplied alpha
    float16 B; // @4, premultiplied alpha
    float16 A; // @6, alpha
  ],
  data = [ 18 KiB of image data ]
]), ('_arg_0', Bitmap[
  type = xyz,
  component_format = float16,
  size = [48, 48],
  srgb_gamma = 0,
  struct = Struct<6>[
    float16 X; // @0, premultiplied alpha
    float16 Y; // @2, premultiplied alpha
    float16 Z; // @4, premultiplied alpha
  ],
  data = [ 13.5 KiB of image data ]
]), ('m2__arg_0', Bitmap[
  type = xyz,
  component_format = float16,
  size = [48, 48],
  srgb_gamma = 0,
  struct = Struct<6>[
    float16 X; // @0, premultiplied alpha
    float16 Y; // @2, premultiplied alpha
    float16 Z; // @4, premultiplied alpha
  ],
  data = [ 13.5 KiB of image data ]
])]
```

The `bitmap_extract` function in `test_renders.py` should indeed be more robust and handle this case. A quick fix and a PR for this would be more than welcome 🚀
