### ISSUE TITLE
 [✨ feature request]: how to save mesh in Mitsuba2: ply in GPU

### ISSUE THREAD

**Issue by arthurlirui** [mitsuba-renderer/mitsuba2#394]
## Summary
I want to save optimized ply into a new ply file to disk. Mesh data is allocated in GPU, most of the data types are ```enoki.cuda_autodiff.Float32```.  but mitsuba.render.Mesh has function write_ply requires ```enoki.dynamic.Float32```

So, right now I have a ply file and load this mesh data into scene.
Then, I set the variant to be ```mitsuba.set_variant('gpu_autodiff_rgb')```, and perform inverse reconstruction to optimize some parameters e.g., vertex, reflectance etc. I want to save the new ply file, according to the ```mitsuba.render.Mesh¶``` there are two import parameters ```vertex_positions_buffer``` and ```vertex_texcoords_buffer```, the type are  ```enoki.dynamic.Float32``` which means in CPU. But my data is in GPU, datatype is ```enoki.cuda_autodiff.Float32```. Directly save ply by calling write_ply will not have output.

Do I need to convert ```enoki.cuda_autodiff.Float32``` to ```enoki.dynamic.Float32```, and how to do it？
Or is there any way to save a ply file in ```mitsuba.set_variant('gpu_autodiff_rgb')```

**Comment by arthurlirui** [comment]
`plymesh = scene.shapes()[0]
 plymesh.write_ply(filename='test_ply.ply')`

`PLYMesh[
  name = "meshed-poisson.ply",
  bbox = BoundingBox3f[
    min = [-12.8478, -7.64084, -3.81525],
    max = [13.1675, 16.3534, 20.7658]
  ],
  vertex_count = 1463068,
  vertices = [50.2 MiB of vertex data],
  face_count = 2923686,
  faces = [33.5 MiB of face data],
  disable_vertex_normals = 0,
  surface_area = 0,
  mesh attributes = [
    vertex_color: 3 floats
  ]
]`

Here is example code and data, it doesn't work, only output a empty ply files.

**Comment by Speierers** [comment]
Hi @arthurlirui ,

If I understand correctly, you are loading the mesh *before* calling `mitsuba.set_variant('gpu_autodiff_rgb')`, is that right? Could you try to move this statement at the very top of your python script (e.g. right after `import mitsuba`)?

**Comment by HsiangYangChu** [comment]
@Speierers Hi,
I also encounter a `Segmentation fault (core dumped)` error when I am using `write_ply`. The following is the output on the terminal:
```
2021-11-29 13:46:06 INFO  main  [Mesh] Writing mesh to "/home/zhuxiangyang/work/test_nerf_hotdog/nerf_hotdog/geo/mesh_0001.ply" ..
Segmentation fault (core dumped)
```
Looking forward to your insights!

**Comment by Speierers** [comment]
Could you please compile in DEBUG mode to see whether you get any extra information regarding this segmentation fault?

**Comment by HsiangYangChu** [comment]
> Could you please compile in DEBUG mode to see whether you get any extra information regarding this segmentation fault?

Sorry, I still don't know how to compile in DEBUG mode now! Just give me some time to learn, and then, I will give you the feedback immediately!

**Comment by binorchen** [comment]
Hello @Speierers,

I would like to ask the same question as @arthurlirui  here. Is there a simple way or function to write the vertex position buffer data in GPU, which is in format `enoki.cuda_autodiff.Float32` to a `.ply` file?

Thanks a lot!

**Comment by Speierers** [comment]
This will be fixed in the upcoming relesase.

**Comment by binorchen** [comment]
Looking forward to the upcoming release. Thank you guys for your effort on this!
