### ISSUE TITLE
[✨ feature request] Does polarized mode work at latest version?

### ISSUE THREAD

**Issue by GCChen97** [mitsuba-renderer/mitsuba2#396]
## Summary
I can't find any doc about rendering stokes. What I can only found is the scene file `integrator_stokes_cbox.xml` . But rendering it don't output images containing the 4 component of stokes.
So I wonder if the implementation of polarized mode is finished now ?

**Comment by tizian** [comment]
Hi,
Yes, the work on the polarized rendering is more or less complete now. Please check out the `next` branch which includes some critical bugfixes related to that.

Rendering `integrator_stokes_cbox.xml` seems to work just fine for me (tested just now in `scalar_spectral_polarized` mode). It outputs a `.exr` image file with multiple channels. (The first 4 are RGBA, and then there are 4 more sets of RGB channels for S0, S1, S2, S3.)

Btw: I'm in the process of writing an extensive documentation about the complete polarization implementation that will (hopefully) soon replace the currently very minimal description in the docs.

Best,
Tizian

**Comment by GCChen97** [comment]
Hi,
Thanks for replying. Now I know how to  extract stokes from the output exr . Yesterday I extracted RGBA as stokes which confused me.

But I found that diffuse reflection is not polarized. In another issue you said that the implementation of polarized diffuse reflection was still in future plan.  Is it implemented at latest version ?

Best,
GC

**Comment by tizian** [comment]
Yes that's right. A model for diffuse polarization (in particular the pBRDF propsed by [Baek et al. 2018](http://vclab.kaist.ac.kr/siggraphasia2018p2/index.html)) is on the roadmap to be implemented, but is not included yet.

**Comment by GCChen97** [comment]
Look forward to the complete polarized mode of this excellent raytracer !

**Comment by tizian** [comment]
FYI: There is now a (work in progress) pull request for the diffuse + specular pBRDF that you  mentioned: https://github.com/mitsuba-renderer/mitsuba2/pull/402
