### ISSUE TITLE
[🐛 bug report] encountered ray with nan using sphere emitter

### ISSUE THREAD

**Issue by GoodKuro** [mitsuba-renderer/mitsuba2#397]
## Summary
I made a scene using a sphere as an emitter. When the emitter is showing in the scene i get a "error: encountered ray with nan or inf values:"

## System Configuration

- Platform: Windows 10
- Compiler:  CMAKE 3.19.4
- Python version: 3.8.5
- Mitsuba 2 version: the lastest as of today
- Compiled variants:
    scalar_rgb
    gpu_rgb

## Description

This only happens when the sphere is an emitter and i choose rendering with my GPU.
I updated Mitsuba and even reinstalled it but the bug still happens for me.
Made a little example scene and copy and paste some of the error-code.

<scene version="2.0.0">
	<integrator type="direct"/>
	
	<shape type="sphere">
        <bsdf type="diffuse"/>
    </shape>
	
	<sensor type="perspective">
        <transform name="to_world">
            <lookat origin="-0.02, 40, 40"
                    target="-0.02, 2, 0"
                    up="0, 1, 0"/>
        </transform>

        <float name="fov" value="40"/>

        <film type="hdrfilm">
            <string name="pixel_format" value="rgb"/>
            <integer name="width" value="500"/>
            <integer name="height" value="500"/>
        </film>
		
    </sensor>
	
	<shape type="sphere">
		<point name="center" value="-8, 0, 8"/>
        <emitter type="area">
            <spectrum name="radiance" value="10"/>
        </emitter>
    </shape>
	
</scene>

and the error-message for example:

(  23,10321,   0) error: encountered ray with nan or inf values:
(  25,10321,   0) error: encountered ray with nan or inf values:
(  27,10321,   0) error: encountered ray with nan or inf values:
(  28,10321,   0) error: encountered ray with nan or inf values:
(  30,10321,   0) error: encountered ray with nan or inf values:
       origin:          [-7.943953, 0.774784, 7.370263]
       direction:       [nan, nan, nan]
       tmin:            0.000800
       tmax:            0.000000
       rayTime:         0.000000
       call location:   No source location available. The input PTX may not contain debug information (nvcc option: -lineinfo), OptixModuleCompileOptions::debugLevel set to OPTIX_COMPILE_DEBUG_LEVEL_NONE, or no useful information is present for the current block.

The weird thing, the problem isn't affecting the image after all. But better safe than sorry.
## Steps to reproduce

1. Downloading Mitsuba
2. Using gpu_rgb
2. Making a sphere-shaped emitter which is seen in the scene

**Comment by Speierers** [comment]
This is a known issue with the current version of Mitsuba (`master`) with DEBUG builds. It will be fixed in the upcoming release.

Otherwise, compiling a Release build should solve this issue.
