### ISSUE TITLE
'ninja pytest' not working

### ISSUE THREAD

**Issue by hchoi405** [mitsuba-renderer/mitsuba2#40]
As the document [[link](https://mitsuba2.readthedocs.io/en/latest/src/developer_guide/testing/)] says, I tried to run pytest through ninja to parallelize the test, but it didn't work.

Specifically, when I run the following command `ninja pytest` in both root and build directories, it says 
`ninja: error: loading 'build.ninja': No such file or directory` in root directory and
`ninja: error: unknown target 'pytest', did you mean 'tent'?` in build directory.

Environments:
OS: Ubuntu 18.04
CMake: 3.15.4
Ninja: 1.8.2
Python: 3.7.4
pytest: 5.2.1

**Comment by acrlakshman** [comment]
Please make sure you have pytest installed and try again from build directory. `sudo apt install python3-pytest python3-pytest-xdist python3-numpy` -> [instructions](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling/)

**Comment by hchoi405** [comment]
@acrlakshman Thank you for the comment. I solved the problem by installing the pytest-xdist package through `pip install pytest-xdist`.
