### ISSUE TITLE
Compile Mitsuba2 with choosen python installation 

### ISSUE THREAD

**Issue by vucenovic** [mitsuba-renderer/mitsuba2#401]
Hello, I am trying to compile mitsuba with my miniconda environment instead of my python installation set in PATH. How do I achieve this? There is no documentation or ovious CMAKE parameters. 

Thanks

**Comment by diiigle** [comment]
Choosing python is pybind11's task and has nothing to do with mitsuba. 

This [pybind11 doc page](https://pybind11.readthedocs.io/en/stable/compiling.html#findpython-mode) should give you a good explanation which links to
the cmake [FindPython documentation](https://cmake.org/cmake/help/latest/module/FindPython.html#hints).

**Comment by LeonardEyer** [comment]
Setting `PYTHON_EXECUTABLE=[path]` as cmake variable worked for me.

**Comment by vucenovic** [comment]
I tried changing both the Python_Root_Dir and Executable, nothing works. If I rename the python installation it usually finds, it even throws a configuration error:

CMake Error at ext/pybind11/tools/FindPythonLibsNew.cmake:96 (message):
  Python config failure:

Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)

**Comment by vucenovic** [comment]
After deciding to letting it be with the python installation, I renamed my python installation to work again, and even though it finds it again, now it tells me that optix.h cannot be found, without me changing anything in the cmake configuration..

**Comment by vucenovic** [comment]
I investigated the optix issue, and the path in the cmake configuration is the one where optix.h is. CMake even found it automatically, but I still get the error.

**Comment by vucenovic** [comment]
It seems that my CMAKE Cache was corrupted by trying out different solutions. I reinstalled both cmake and mitsuba2 and got it to run with ```PYTHON_EXECUTABLE=[path]``` when first configuring/generating with cmake for VS 2019. Thank you both for the help!
