### ISSUE TITLE
Inconsistency between conductor and dielectric plugins

### ISSUE THREAD

**Issue by schunkes** [mitsuba-renderer/mitsuba2#41]
I noticed an inconsistency between the conductor-type (`conductor`, `roughconductor`)  and dielectric-type (`dielectric`, `thindielectric`, `roughdielectric`) plugins and would like clarification.

For the dielectric-type plugins, a user is asked to specify the internal and external indices of refraction and their ratio is computed in the plugins' constructors. However, for the conductor-type plugins, a user is asked to specify only one set of eta and kappa values, which are not processed further before being used.

This implies one of two things for me: Either the conductor-type plugins assume an IOR of 1 for the external medium, or users must specify the ratio between the external and internal indices of refaction, when using these plugins.

Is this design intentional? If not, I would be happy to provide a pull request, aligning the conductor-type plugins with the interface of the dielectric-type plugins.

Thank you and take care!

**Comment by wjakob** [comment]
Hi @schunkes,

apologies in the delay responding to your message. That is indeed an omission, and we should properly compute the (complex-valued!) relative OR when a real-valued external IOR is provided. Probably not too much an issue in most cases (air), but potentially problematic when metals are observed under water. A PR would be welcomed, though the important thing will be to retain compatibility with the parameter conventions of Mitsuba 1.

Now that said, we could adopt a new set of parameter names (e.g. `int_eta`, `int_k`, and `ext_eta`) that are documented exclusively and preferred by the plugin if available.

Best,
Wenzel

**Comment by schunkes** [comment]
Hi @wjakob,

thank you for your answer. At this moment we are not targeting under water scenes as you mentioned them, so I expect I will not have the time to create such a PR. However, should problems with the conductor type plugins block our work, I'll make sure to create a PR for our changes.

Best wishes,
Sebastian
