### ISSUE TITLE
[❔ other question] Distance from camera in BSDF plugin

### ISSUE THREAD

**Issue by zadinvit** [mitsuba-renderer/mitsuba2#412]
## Summary

*Hi, 
Is there any way to get a distance from a camera in the BSDF plugin sample/eval function? 
I want to implement mipmapping in my BTF texture rendering BSDF plugin,
 but I have a problem getting positions of the camera and ray intersection with an object
 or a simple distance from the camera for mipmap indexing/level inside BSDF plugin.  
 

Thank you
Vít *

**Comment by merlinND** [comment]
Hi @zadinvit,

For mipmaps, I believe these fields give you the information you need:
https://github.com/mitsuba-renderer/mitsuba2/blob/e1c09283a54848e74fe8d84802b72857ab25007f/include/mitsuba/render/interaction.h#L121-L122

You may need to double-check that they are always computed when needed, since we haven't used them a lot so far.

**Comment by zadinvit** [comment]
Hi @merlinND ,
duv_dx and duv_dy are always zero, so I think they are not computed. I found in documentation mitsuba.render.HitComputeFlags, but I don't know how I can change those flags or add the _dPdUV_ flag to compute those coordinates. 

I tried to add the flag in a plugin constructor, but it doesn't work.

```      
m_flags    = BSDFFlags::DiffuseReflection | BSDFFlags::FrontSide;
m_flags = +HitComputeFlags::dPdUV;
```

**Comment by Speierers** [comment]
Hi @zadinvit ,

When the integrator queries the `BSDF` for a given `SurfaceInteraction`
``` c++
BSDFPtr bsdf = si.bsdf(ray);
```
the partials derivatives will be computed **only** when the BSDF requires it. For this, you will need to add `BSDFFlags::NeedsDifferentials` to `BSDF::m_flags` of your BSDF  (e.g. in its constructor).

Then you should be able to use those partial derivatives in the `sample()`/`eval()` methods of your BSDF.

**Comment by zadinvit** [comment]
@Speierers 
thank you. 

I need some function to choose the mipmap level.  I used this  function, but the level is very often negative. I know that old Mitsuba implements mipmaps for bitmap Texture, but I can't find how to choose mipmap levels. 

Don't you know where is the problem in my solution?

Level 0 = original image. 

```
 float width = max(max(si.duv_dx[0], si.duv_dx[1]), max(si.duv_dy[0], si.duv_dy[1]));
 level = float(big_render->maxMipLevel) + log2(width); //maxMipLevel is 9, i work with small images for example 228x192 
```


PBR uses this, but I don't understand how I could use it like this if every texture has a different number of images.
`Float level = Levels() - 1 + Log2(std::max(width, (Float)1e-8));`

**Comment by Speierers** [comment]
Hi @zadinvit ,

Could the level value be negative when the approriate level given the ray differentials is above the `maxMipLevel` of you texture? Or the other way around, e.g. when you are so close to the texture it will need to rely on pixel interpolation (already at the maximum resolution of the texture)? In which case you would simply need to clamp: `ek::clamp(level, 0, maxMipLevel)`.

I would recommand you run this in the debugger to find out whether the intermediate values make senses (e.g. `si.duv_dx`, `width`, ...).

**Comment by zadinvit** [comment]
Hi @Speierer , 
thank you for answer,
I already solve it. I just rescale si si.duv_dy and si.duv_dy by original image size and now it work fine. I find this in old Mitsuba implementation of mipmap. 

```
float width = max(max(si.duv_dx[0] * big_render->mip.isotropic[0].cols, si.duv_dx[1] * big_render->mip.isotropic[0].cols), max(si.duv_dy[0] * big_render->mip.isotropic[0].rows, si.duv_dy[1] * big_render->mip.isotropic[0].rows));
level = min(float(big_render->maxMipLevel), float(big_render->maxMipLevel) + log2(width));
```
Now I have this levels in my scene.
![mipmaplevels](https://user-images.githubusercontent.com/34831565/114829462-65656d80-9dcb-11eb-9be5-e2e6ae7ea192.png)

Render example from my BTF plugin
![complex_front](https://user-images.githubusercontent.com/34831565/114829734-bbd2ac00-9dcb-11eb-8612-3cb7e42ecd61.png)

Thanks to all for your help.
