### ISSUE TITLE
[❔ other question]problem about ek.arange() function

### ISSUE THREAD

**Issue by Andy3531** [mitsuba-renderer/mitsuba2#413]
[❔ other question]

## Description

Here is the python code
`import enoki as ek`
`import numpy as np`
`import mitsuba`
`mitsuba.set_variant('scalar_rgb')`
`from mitsuba.core import Float, UInt32, UInt64, Vector2f, Vector3f`
`from mitsuba.core.xml import load_dict`

`film = load_dict({`
`        "type" : "hdrfilm",`
`        "width" : 512,`
`        "height" : 512,`
`    })`
`film_size = film.size()`
`spp = 8`
`total_sample_count = ek.hprod(film_size) * spp`

`pos = ek.arange(UInt32, total_sample_count)`

then error occurs: 

AttributeError  Traceback (most recent call last)
<ipython-input-3-5c6b0c313d80> in <module>
----> 1 pos = ek.arange(UInt32, total_sample_count)

AttributeError: type object 'int' has no attribute 'arange'

This is the example code in mitsuba2 documentation, so where is wrong?

**Comment by Speierers** [comment]
Hi @Andy3531 ,

This kind of code only makes sense when using a vectorized mode (e.g. `packet`, `gpu`). In your case `UInt32` is an alias for `int` so it won't be able to carry a whole array of values.

I would recommand you switch to one of the vectorized variant of mitsuba for this.

**Comment by Andy3531** [comment]
here is the original code location:  https://mitsuba2.readthedocs.io/en/latest/src/python_interface/rendering_scene.html#custom-rendering-pipeline-in-python

**Comment by Andy3531** [comment]
wow, thank you a lot
