### ISSUE TITLE
[❔ other question] Differentiate wrt light source position

### ISSUE THREAD

**Issue by weberhen** [mitsuba-renderer/mitsuba2#414]
*Please add one of the following label to your issue's title, and delete this section:*

- [❔ other question]

## Summary

*Differentiate wrt light source position*

## Description

*Hi! I would like to perform differentiable rendering in order to move a light source to match a GT image. I see that the parameter to_world is not differentiable, so I was wondering if you have an idea on how to do this, if there is something else regarding a light source position I could optimize for example. Any tip will help!*

**Comment by weberhen** [comment]
sorry was to quick asking this. The answer is on https://github.com/mitsuba-renderer/mitsuba2/blob/pathreparam-optix7/docs/examples/10_inverse_rendering/invert_pose.py

Anyway, thanks for the amazing project!

**Comment by pjessesco** [comment]
Hi @weberhen, thanks for sharing your issue and hint. I have a similar issue with you, and I'm trying point light case for testing.

I created a differentiable variable in the parameter map as below in python script,

    # Create differential parameter to be optimized
    to_world = Transform4f.translate(Vector3f(1,2,3))

    # Create a new ParameterMap (or dict)
    params_optim = {
        "to_world" : to_world
    }

and I'm stuck in applying it.

I roughly think that I have to expose `to_world` parameter of point light with fixing `traverse()`, 

    void traverse(TraversalCallback *callback) override {
        callback->put_object("intensity", m_intensity.get());
        callback->put_parameter("m_world_transform", m_world_transform); // Not working
    }

but it seems not working. Could you give me some detailed advice?

Thanks.
