### ISSUE TITLE
[🐛 bug report] volpath takes forever to finish in LLVM/CUDA variants (next branch)

### ISSUE THREAD

**Issue by tomasiser** [mitsuba-renderer/mitsuba2#417]
## Summary

The `volpath` and `volpathmis` integrators in the `next` branch of Mitsuba 2 take forever to finish rendering when used in LLVM and CUDA variants (tried `llvm_spectral`, `cuda_spectral`, `llvm_rgb`, `cuda_rgb`). When used with very very low resolutions (e.g., 16x16), they actually do finish, but are orders of magnitude slower than `scalar` variants.

**Note:** the `direct` and `path` integrators seem to work totally fine with `llvm_` and `cuda_` variants.

## System configuration

- Platform: Docker container based on `nvidia/cuda:11.2.0-devel-ubuntu20.04`
- Compiler: `clang++-9`
- Python version: 3.8.5
- Mitsuba 2 version: latest `next` branch (commit a29aa6b0)
  - `Mitsuba version 2.2.1 ([], Linux, 64bit, 32 threads, 8-wide SIMD)`
  - `Enabled processor features: cuda llvm avx2 avx fma f16c sse4.2 x86_64`
- Compiled variants:
"scalar_spectral", "llvm_spectral", "cuda_spectral", "llvm_rgb", "cuda_rgb", "scalar_rgb"
- Hardware:
  - GPU: 2x GeForce GTX 1080 Ti
    ```
    NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2
    ```
  - CPU: 2x AMD Ryzen Threadripper 1950X 16-Core Processor
  - RAM: 112 GB

## Steps to reproduce

1. Edit the scene `resources/data/scenes/hello.xml`, replacing the `direct` integrator with `volpath`:
```xml
    <!-- <integrator type='direct'>
        <integer name="emitter_samples" value="4"/>
        <integer name="bsdf_samples" value="0"/>
    </integrator> -->

    <integrator type='volpath'>
        <integer name="max_depth" value="10"/>
        <integer name="rr_depth" value="10"/>
    </integrator>
```
2. Render with `-m scalar_spectral` or `-m scalar_rgb`, see that it finished very fast.
3. Render with `llvm_` and `cuda_` variants, observe that it does not finish (I even let it run overnight on a 32-core machine).

**Comment by tomasiser** [comment]
Hm, I actually suspect it is because, for some reason, in the new Enoki versions, it is extremely inefficient to use the old for-loops instead of `ek::Loop`. Whereas the `path` integrator already uses `ek::Loop`, the `volpath` one still uses an old-style `for` loop. No idea why this wasn't a problem in the `master` branch.

**Comment by dvicini** [comment]
Hi Tomáš!

This was actually always a problem actually. Even on the master branch, the volumetric integrators would be extremely inefficient to run and differentiate. The old version of Enoki doesn't handle these cases well. We will somewhat soon provide updated versions of these integrators that use `ek::loop` on the `next` branch. This is fairly high on my TODO list :) 

Delio
