### ISSUE TITLE
- [❔ other question] Pytorch version of invert_pose.py

### ISSUE THREAD

**Issue by weberhen** [mitsuba-renderer/mitsuba2#419]
## Summary

Pytorch version of invert_pose.py

## Description

Hi! I'm trying to use the example [invert_pose.py](https://github.com/mitsuba-renderer/mitsuba2/blob/pathreparam-optix7/docs/examples/10_inverse_rendering/invert_pose.py) with pytorch, but I'm not able to make it work so far. I see that  the function render_torch (from [invert_cbox_torch.py](https://github.com/mitsuba-renderer/mitsuba2/blob/pathreparam-optix7/docs/examples/10_inverse_rendering/invert_cbox_torch.py)) needs the parameters both as enoki arrays and pytorch arrays, but since the parameter 'translate' is not in the enoki array, the function fails when it creates an interface between the underlying computation graphs.

Does anyone here tried to do a similar thing and succed?

Thanks!

**Comment by Speierers** [comment]
Hi @weberhen,

Could you clarify what you mean by that?

>  the parameter 'translate' is not in the enoki array

You issue probably comes from the indirection `translate -> object.vertex_positions_buf` which is not reflected in `render_torch`. For this you will probably need to implement you own version of `render_torch` unfortunately.

**Comment by weberhen** [comment]
Hi Speierers, and congrats for the amazing work!

When I call render_torch, I need to send params (enoki array) and params_torch (pytorch array). The parameter we want to optimize for must be present in both variables right? But I cant put 'translate' inside the enoki array, so the render_torch gives an error saying it couldnt find 'translate' in the enoki array. 

I was doing what you suggested (implementing my own version of render_torch) but I ended up switching to redner to perform my experiments. Will go back to mitsuba once what I need is possible since I really like mitsuba and have been using for some years now.

Thanks!
