### ISSUE TITLE
[❔ other question] Request an example on rendering volume files

### ISSUE THREAD

**Issue by yuehaowang** [mitsuba-renderer/mitsuba2#420]
## Summary

I am a beginner in using Mitsuba2. I'm wondering if there are any scene file examples on rendering .vol files.

## Description

I would like to render .vdb files through Mitsuba2. I managed to convert .vdb files to .vol files using mitsuba2-vdb-converter. Then I am stuck in creating a scene file for rendering .vol files. I have tried the example "hetvol" but it seems not working on Mitsuba2. Below is listed my adapted scene file of "hetvol".

```xml
<scene version="2.0.0">
	<integrator type="volpath">
		<integer name="max_depth" value="8"/>
	</integrator>

	<medium type="homogeneous" id="smoke">
		<string name="method" value="woodcock"/>

		<volume name="density" type="gridvolume">
			<string name="filename" value="smoke.vol"/>
		</volume>

		<float name="scale" value="100"/>
	</medium>

	<shape type="obj">
		<string name="filename" value="bounds.obj"/>

		<ref name="interior" id="smoke"/>
	</shape>

	<shape type="obj">
		<!-- Shiny floor -->
		<string name="filename" value="plane.obj"/>

		<bsdf type="diffuse">
            <rgb name="reflectance" value="0.9 0.9 0.0"/>
        </bsdf>
		<transform name="to_world">
			<translate y=".48"/>
		</transform>
	</shape>

	<sensor type="perspective">
		<float name="focus_distance" value="1.25668"/>
		<float name="fov" value="45.8402"/>
		<string name="fov_axis" value="x"/>
		<transform name="to_world">
			<scale x="-1"/>

			<lookat target="-0.166029, 0.148984, -0.537402" origin="-0.61423, 0.154197, -1.43132" up="-0.000640925, -0.999985, -0.0055102"/>
		</transform>

		<sampler type="ldsampler">
			<integer name="sample_count" value="64"/>
		</sampler>

		<film type="hdrfilm">
			<integer name="height" value="576"/>
			<integer name="width" value="768"/>

			<rfilter type="gaussian"/>
		</film>
	</sensor>

	<shape type="sphere">
		<point name="center" x="0" y="-2" z="-1"/>
		<float name="radius" value=".2"/>

		<emitter type="area">
			<spectrum name="radiance" value="400"/>
		</emitter>
	</shape>
</scene>
```
However, the scene file will cause an error `Error while loading "./hetvol.xml" (near line 6, col 3): unreferenced object GridVolume...`.

It seems the documentation seldom introduces related topics. So I have difficulties in solving this problem.

I would greatly appreciate it if you can kindly provide any example on rendering .vol files.

**Comment by merlinND** [comment]
Hello @yuehaowang,

Please have a look at the test scenes in that directory, there should be relevant examples including homogeneous and heterogeneous media: https://github.com/mitsuba-renderer/mitsuba-data/tree/85cc978f5637b4c948a3737c9f5e611117f78d33/tests/scenes/participating_media

**Comment by Speierers** [comment]
Hi @yuehaowang ,

There seems to be a typo in you XML scene description:
```diff
- <medium type="homogeneous" id="smoke">
+ <medium type="heterogeneous" id="smoke">
```

**Comment by yuehaowang** [comment]
> Hello @yuehaowang,
> 
> Please have a look at the test scenes in that directory, there should be relevant examples including homogeneous and heterogeneous media: https://github.com/mitsuba-renderer/mitsuba-data/tree/85cc978f5637b4c948a3737c9f5e611117f78d33/tests/scenes/participating_media

Thank you very much. The provided examples are quite helpful to me.

**Comment by yuehaowang** [comment]
> Hi @yuehaowang ,
> 
> There seems to be a typo in you XML scene description:
> 
> ```diff
> - <medium type="homogeneous" id="smoke">
> + <medium type="heterogeneous" id="smoke">
> ```

Thanks very much for your suggestion. Actually, I used to try "heterogeneous" medium but Mitsuba2 reported `Error while loading "hetvol_new.xml" (near line 6, col 3): could not instantiate medium plugin of type "heterogeneous"`. So I changed to use "homogeneous".

**Comment by merlinND** [comment]
> could not instantiate medium plugin of type "heterogeneous"

If you encounter an issue like this, there should be another error message a few lines above / below that tell you what went wrong while instantiating the plugin. Usually it's a missing property or a property of the wrong type.

**Comment by yuehaowang** [comment]
Thanks again. I managed to render my own volumes based on the provided examples.
My goal is to render two volumes in the same scene. So I simply add a new medium and a new shape to the scene file. However, it seems only one of the mediums can be rendered. The scene file is as below:
```xml
<scene version='2.0.0'>
    <path value="../../../common"/>

    <include filename="include/test-scene-base-no-bg.xml"/>

    <medium id="medium1" type="heterogeneous">
        <float name="scale" value="5"/>

        <volume name="sigma_t" type="gridvolume">
            <transform name="to_world">
                <translate x="-0.5" y="-0.7" z="-0.5"/>
                <scale x="1.5" y="1.5" z="1.5"/>
            </transform>
            <boolean name="use_grid_bbox" value="false"/>
            <string name="filename" value="textures/smoke_1vol"/>
        </volume>

        <rgb name="albedo" value="0.99, 0.5, 0.5"/>
        <phase type="isotropic" />
    </medium>

    <medium id="medium2" type="heterogeneous">
        <float name="scale" value="5"/>

        <volume name="sigma_t" type="gridvolume">
            <transform name="to_world">
                <translate x="-0.5" y="-0.7" z="-0.5"/>
                <scale x="1.5" y="1.5" z="1.5"/>
            </transform>
            <boolean name="use_grid_bbox" value="false"/>
            <string name="filename" value="textures/smoke_2.vol"/>
        </volume>

        <rgb name="albedo" value="0.5, 0.5, 0.99"/>
        <phase type="isotropic" />
    </medium>


    <shape type="obj">
        <string name="filename" value="meshes/unit_cube_centered.obj"/>
        <bsdf type="null"></bsdf>
        <ref id="medium1" name="interior"/>
        <transform name="to_world">
            <translate x="-0.2" y="0" z="0"/>
            <scale x="1.5" y="1.5" z="1.5"/>
        </transform>
    </shape>

    <shape type="obj">
        <string name="filename" value="meshes/unit_cube_centered.obj"/>
        <bsdf type="null"></bsdf>
        <ref id="medium2" name="interior"/>
        <transform name="to_world">
            <translate x="0" y="0" z="0"/>
            <scale x="1.5" y="1.5" z="1.5"/>
        </transform>
    </shape>

    <shape type="obj">
        <string name="filename" value="meshes/unit_cube_centered.obj"/>
        <bsdf type="diffuse">
            <rgb name="reflectance" value="0.0, 0.0, 0.0"/>
        </bsdf>
        <emitter type="area">
            <rgb name="radiance" value="1500.387, 1500.9873, 1500.75357"/>
        </emitter>

        <transform name="to_world">
            <translate x="0.0" y="0.0" z="5.0"/>
        </transform>
    </shape>

</scene>
```

**Comment by dvicini** [comment]
Hi, 
Rendering multiple volumes in the same scene should not be an issue. However, we don't support multiple volumes *overlapping*. Is that maybe the case in your scene? Could you share example outputs?

Delio

**Comment by yuehaowang** [comment]
> Hi,
> Rendering multiple volumes in the same scene should not be an issue. However, we don't support multiple volumes _overlapping_. Is that maybe the case in your scene? Could you share example outputs?
> 
> Delio

Hi Delio,

It's true that I render two overlapped volumes. But I need to render a blend of two smoke with different colors. Is there a handy solution to achieve my goal?

**Comment by dvicini** [comment]
Could you maybe just blend the volume parameters and then render the volume that has already been blended? Alternatively, you would need to extend `volpath` to be able to keep track of a list of volumes, and then evaluate them all jointly. We don't plan to support this in the near future, since handling overlapping volumes introduces quite a bit of complexity to the code for a more niche use case. I am closing this issue for now

**Comment by yuehaowang** [comment]
Thanks for your reply.

I have another question: what's the physical size of the volume.
