### ISSUE TITLE
Traverse(scene) has no key 'object.vertex_positions'- [🐛 bug report]

### ISSUE THREAD

**Issue by yanglixiao1994** [mitsuba-renderer/mitsuba2#421]
Hi,
I'm running test_object_position.py from reparam-tests. The script broke on "vertex_positions = properties['**object.vertex_positions**']" which should be **'object.vertex_positions_buf**' from debugger.
How can i get rid of this mismatching? Thank you.

- Platform: windows 10
- Compiler: vs2019
- Python version: 3.8.5
- Mitsuba 2 version:  Branch:pathreparam-optix7
- Compiled variants:
        "scalar_rgb",
        "scalar_spectral",
	"gpu_autodiff_rgb"

**Comment by Speierers** [comment]
The `reparam-tests` repo seems to be out of date. `vertex_positions` was replaced by `vertex_positions_buf`.

Please take a look at this [example script](https://github.com/mitsuba-renderer/mitsuba2/pull/157/files#diff-a32c775a8bfb30019b4f10bcb42b3f2b32ceabd38d87106c39051d58fb3b71a4).

You will need to do something like this:
```python
positions = ravel(params['object.vertex_positions_buf'])
new_positions = t.transform_point(positions)
unravel(new_positions, params['object.vertex_positions_buf'])
params.set_dirty('object.vertex_positions_buf')
```

Please let me know if this helps!

**Comment by yanglixiao1994** [comment]
Thanks, Speierers. It's working!
