### ISSUE TITLE
[🔨 compilation issue]zlib.lib missing

### ISSUE THREAD

**Issue by YuZhang-steven** [mitsuba-renderer/mitsuba2#422]
- [🔨 compilation issue]

## Summary
I am using Window. When I try to build the project, it shows an error: zlib.lib missing. 
I tried to download the lib and then put it in the ext_build/Zlib/, but nothing changed.
![image](https://user-images.githubusercontent.com/70283073/115350963-95659580-a16a-11eb-939f-76aa30034a39.png)

**Comment by Speierers** [comment]
Hi @YuZhang-steven ,

Is this on the `master` branch?

**Comment by YuZhang-steven** [comment]
Thank you for replying.

I checked it. Yes, it is on master branch

**Comment by merlinND** [comment]
Hi @YuZhang-steven,

Have you clicked 'Build all' instead of building a specific component? `zlib` is supposed to be build automatically on Windows.

https://github.com/mitsuba-renderer/mitsuba2/blob/275222876ddb85eb255d6a4ff82d4893848bd6e0/ext/CMakeLists.txt#L89-L100

**Comment by YuZhang-steven** [comment]
Hi @merlinND Thank you for replying.

Yes, I used "build all".  I noticed the zlib folder in "mitsuba2\ext\zlib" . But after click "build all", I don't find zlib.lib in the "ext_build/zlib/" folder. Should I download and install zlib in some ways? I am also trying to build the project on another computer.

**Comment by Speierers** [comment]
Hi @YuZhang-steven,

Could you try to explicitely build the zlib target in VS? Otherwise try using the command
```
cd build
cmake --build . --target ext_build/zlib/zlib
```

**Comment by YuZhang-steven** [comment]
Hi @Speierers ,

I reread the compiling chapter in the document. 
https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html

I noticed I tried to directly build the project after the cloning repo. 
I am very new to CS and C++ stuff. Sorry for wasting your time to help me debug. 
Thank you so much for replying immediately.

**Comment by merlinND** [comment]
Glad you got it to work!
To make sure I understand, was the missing step the CMake configure / generation?

**Comment by YuZhang-steven** [comment]
Hi @merlinND ,
I clone the repo in visual studio, and then I directly click the build all in the visual studio. It shows zlib.lib missing. 
I noticed in the document that I should use the command line "cmake -G "Visual Studio 16 2019" -A x64" to build. And then open the generated mitsuba.sln. 

It works now. 
Thank you so much!
