### ISSUE TITLE
running mitsuba2 from cmd : plugin "srgb" not found!

### ISSUE THREAD

**Issue by jakoaltrd** [mitsuba-renderer/mitsuba2#424]
issue: hi, everyone, when I compiled mitsuba2 and running a XML scene, it throws a exception: plugin "srgb" not found.

does anyone knows why is that and how to fix it?

**Comment by merlinND** [comment]
Closing in favor of #142.

**Comment by merlinND** [comment]
Hello @jakoaltrd,

Please edit your issue to respect the issue template. It includes important information that will help us understand the situation.
Please also make sure to follow the build instructions closely: https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html
