### ISSUE TITLE
 [🐛 bug report] plugin “srgb" not found!

### ISSUE THREAD

**Issue by jakoaltrd** [mitsuba-renderer/mitsuba2#427]
- [🐛 bug report] plugin “srgb" not found!

## Summary
when I compiled mitsuba2 from the master brunch, it went well , but when I run it, it yielded plugin "srgb" not found, while there is no project named "srgb" in the solution, so why is this , and how to fix this?

## System configuration

- Platform: windows10 professional
- Compiler: VS2019
- Python version: python3.9
- Mitsuba 2 version: latest
- Compiled variants:
    * `scalar_rgb`
    * ...

## Steps to reproduce

1. ...
2. ...

**Comment by Speierers** [comment]
Could you make sure you built the BUILD_ALL target in Visual Studio?

**Comment by jakoaltrd** [comment]
@ Speierers 
yes, I did. but it threw some errors. like this:
MSB307 command setlocal .  rgb2spec_opt.
MSB600 cmd quit , code 1.    rgb2spec_opt_run
MSB600 cmd quit , code 1.    dist_copy

**Comment by Speierers** [comment]
Hi @jakoaltrd,

Could you try to clean up the `build` folder and then run the following:
```
cd build
cmake ..
cmake --build . --target ALL_BUILD
```

Please share the log here if this doesn't build successfully.

**Comment by jakoaltrd** [comment]
how to build release version, it seems this method build debug version.







 On Thursday, April 22, 2021, 02:14:01 PM GMT+8, Sebastien Speierer ***@***.***> wrote:










Hi @jakoaltrd,


Could you try to clean up the build folder and then run the following:


cd build
cmake ..
cmake --build . --target ALL_BUILD



Please share the log here if this doesn't build successfully.

**Comment by Speierers** [comment]
You simply need to add `--config Release` to the command above:
```
cmake --build . --target ALL_BUILD --config Release
```
