### ISSUE TITLE
Export object and emitter's transform as parameter

### ISSUE THREAD

**Issue by philcn** [mitsuba-renderer/mitsuba2#43]
I'm playing with Mitsuba 2 to see if I can use it to optimize light and object position in a given scene. I realized that the world transform property is not currently exported during traverse(), and it's not straightforward to export. 

For meshes, their transforms are baked in to their vertex positions during construction. For point emitters, their transform is an "AnimatedTransform" and doesn't support put_object() or put_parameter(), nor does its Transform4f member. 

Is there any plan to support exporting transform parameters, or can you please provide any tips for me to implement them on my own?

Thanks,
Phil

**Comment by Speierers** [comment]
Hi @philcn,

We are currently in the process of adding support for this. (see PR #44 )

Currently, `AnimatedTransform` hasn't been tested for any of the variants. I doubt it works with autodiff. This is also on our TODO list.

Cheers

**Comment by philcn** [comment]
Hi @Speierers,

Thanks for your reply. I took a look at the reparameterizing paper, only then did I understand visibility differentiation doesn't work out of the box. I look forward to the implementation, and I understand that both vertex positions, object transformation and light transformation are going to be supported, right?

Thanks,
Phil

**Comment by Speierers** [comment]
Indeed those 3 should all be supported at the end. We are slowly but surely making our way there 😉
