### ISSUE TITLE
/bin/sh: 1: : Permission denied ninja: build stopped: subcommand failed. [🔨 compilation issue]

### ISSUE THREAD

**Issue by comewei** [mitsuba-renderer/mitsuba2#430]
## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: Ubuntu 20.04 LTS
- Python version: 3.7
- Compiled variants:
    * `scalar_rgb`
    * `gpu_rgb`
    * 

## Description

hello,if I don't add `gpu_rgb`，it will work well.but when I add the `gpu_rgb`.Then I use the command `cmake -GNinja ..`.it will be wrong. its error is below:
`The CUDA compiler

    "/usr/local/cuda/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/xxxx/mitsuba2/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/home/xxxxanaconda3/envs/pytorch/bin/ninja" "cmTC_7a560"
    [1/3] Building CUDA object CMakeFiles/cmTC_7a560.dir/main.cu.o
    nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    [2/3] Linking CUDA executable CMakeFiles/cmTC_7a560.dir/cmake_device_link.o
    nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    [3/3] Linking CUDA executable cmTC_7a560
    FAILED: cmTC_7a560 
    : && ""  CMakeFiles/cmTC_7a560.dir/main.cu.o CMakeFiles/cmTC_7a560.dir/cmake_device_link.o -o cmTC_7a560   && :
    /bin/sh: 1: : Permission denied
    ninja: build stopped: subcommand failed.
    `
I try to sovle it,but not success. like change the version of cmake, change CUDA11.0 into CUDA10.2,but the error is so the same.I don't how to do it,so sad. Hope you can help me,thanks.

**Comment by Speierers** [comment]
This is concerning:
```/bin/sh: 1: : Permission denied```
could it be that you do not have the right to write into the tmp folder?

**Comment by ziyangz5** [comment]
Encontered similiar error. Turns out that my CUDA toolkit was not installed correctly. If you are on a server without sudo privilege, you can install the toolkit in your home directory.
