### ISSUE TITLE
[❔ other question] an example of water material

### ISSUE THREAD

**Issue by zoharl3** [mitsuba-renderer/mitsuba2#431]
I asked it in the pbrt group

https://groups.google.com/g/pbrt/c/Z5JtxpObEgE

and I thought to ask what can mitsuba offer as well.

**Comment by Speierers** [comment]
Hi @zoharl3 ,

Could you please be a little more specific regarding your setup and needs?

Similarly to PBRT, Mitsuba should be able to render those triangular mesh. If the rendering times are too long for you, you might want to reduce the resolution of the film, reduce the number of samples per pixels, or reduce the number of bounces in the path tracer.

It could also be that your geometry is very highly tesselated, in which case preprocessing it (e.g. using Blender) could be an option to bring down rendering times.

I will close this as it isn't an issue, but will remain available for other questions.

**Comment by zoharl3** [comment]
I have a triangle mesh (single component, manifold, 50k facets). I'd 
like to render it that it would look like water, and my budget is a 
couple of minutes. Do you have, perhaps, a specific (template of a) 
scene that would do the trick?

For example, the armadillo that I rendered in maya/arnold. I used for it 
a water preset for a surface shader. What am I not using maya? I don't 
like it much, and I prefer a standalone open source renderer.

**Comment by Speierers** [comment]
For water I would recommend you use the `dielectric` BSDF. You should be able to start with the `resources/data/scenes/hello.xml` scene. Good luck!
