### ISSUE TITLE
[🔨 compilation issue] Unable to completely clone the pbrdf-baek-2018 branch

### ISSUE THREAD

**Issue by akshatdave** [mitsuba-renderer/mitsuba2#432]
## Summary

`enoki-jit` submodule is missing/unreachable resulting in errors while cloning `pbrdf-baek-2018` branch

## Description

Recursively cloning the `pbrdf-baek-2018` branch using the following command

` git clone --recursive --branch pbrdf-baek-2018  https://github.com/mitsuba-renderer/mitsuba2`

results in the following error lines:

```
fatal: repository 'https://github.com/mitsuba-renderer/enoki-jit/' not found
fatal: clone of 'https://github.com/mitsuba-renderer/enoki-jit' into submodule path '/opt/mitsuba2/ext/enoki/ext/enoki-jit' failed
Failed to recurse into submodule path 'ext/enoki'
```
This branch requires the submodule [enoki @ d8c9edb ](https://github.com/wjakob/enoki/tree/d8c9edbce3bba69c22781d79a901468e9be6889c) which requires the submodule [enoki-jit @ 39b3cc6](https://github.com/mitsuba-renderer/enoki-jit/tree/39b3cc6c081556c3e8e58aed49e9ace50af4cbc7) that seems unavailable. 

As a result `mitsuba2/ext/enoki/ext/enoki-jit` is an empty folder in the cloned repository resulting in compilation issues.

**Comment by wjakob** [comment]
Dear @akshatdave , see here for details: https://github.com/mitsuba-renderer/mitsuba2/blob/next/README.md. The `pbrdf-baek-2018` was built on this next branch, though you may be able to backport things to baseline `master`.
