### ISSUE TITLE
[❔ other question] Spectral texture

### ISSUE THREAD

**Issue by JBroki** [mitsuba-renderer/mitsuba2#436]
Hi there,
I want to add spectral texture to shapes loaded from obj or ply files. How can I achieve this? 
I have some ideas:

- Add a bitmap texture to a bsdf. This would work best for me as I create the scene in the xml file directly and don't have any textured cad data. But if I understand the documentation right, there is only the possibility of using rgb data. 
- Load an obj file with associated mtl file containing the spectral texture data. As this is not easy to obtain (at least for me), I would like to know if Mitsuba is able to work with spectral texture stored this way. 

Maybe there is a better way to include spectral texture... I appreciate your help!

**Comment by Speierers** [comment]
Hi @JBroki ,

One way to achieve this would be to implement your own `texture` C++ plugin, something similar to `src/textures/bitmap.cpp`. This plugin could read spectral data from a multi-channel EXR image (e.g. each channel would correspond to a specific wavelength). Then `MySpectralTexture::eval()` would linearly interpolate between the two appropriate channels, given the ray wavelength (use `ek::gather` for this).

I would recommand you take a look at the [developer guide documentation](https://mitsuba2.readthedocs.io/en/latest/src/developer_guide/writing_plugin.html) before getting started.
