### ISSUE TITLE
[🔨 compilation issue] Failed to build any gpu_*_polarized variant

### ISSUE THREAD

**Issue by flycooler** [mitsuba-renderer/mitsuba2#443]
*Please add one of the following label to your issue's title, and delete this section:*
- [🔨 compilation issue]

## Summary
Failed to build any gpu_*_polarized variant.

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: both Windows 10 and Fedora 33
- Compiler: Visual studio 2019 (Windows 10) and Clang-9 (Fedora 33)
- Python version: 3.8
- Mitsuba 2 version: tried both the latest codes (from github) and the 2.2.1 release codes.
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral_polarized`
    * `gpu_autodiff_spectral_polarized`

## Description

I am working on a research project about differentiable rendering for polarization, and considering to use Mitsuba2 as development framework. Today I tried to build Mitsuba2 with the support of both polarization and differentiable rendering, but no luck after trying for a few hours: always have some building error with any gpu_*_polarization variant. The error seems to point to the following structure in **core\traits.h**

`template <typename T>
struct spectrum_traits<MuellerMatrix<T>> : spectrum_traits<T> {
    using Scalar                             = MuellerMatrix<typename spectrum_traits<T>::Scalar>;
    using Unpolarized                        = T;
    static constexpr bool is_polarized       = true;
};`

one of errors is: error C2039: 'Scalar': is not a member of 'mitsuba::detail::spectrum_traits<T>'

## Steps to reproduce

Should be very easy to reproduce: just need to use the latest codes from github and the attached mitsuba.conf file (in the attached .zip file) to build, the errors will show up. Thanks!

[mitsuba_conf.zip](https://github.com/mitsuba-renderer/mitsuba2/files/6562777/mitsuba_conf.zip)

**Comment by Speierers** [comment]
Hi @flycooler ,

Unfortunately I believe this is to be expected. The GPU variants on the `master` branch do not yet support `polarized` spectral modes.

If this is a must have for you, we could potentially give you early access to our **unstable** development branch, which should support AD + GPU + polarization. Please let me know if interested.

**Comment by flycooler** [comment]
@Speierers thanks a lot for the response and clear answers!

Yes, I would need to use AD+GPU+Polarization for the project, so could you please provide me early access to your unstable development branch? 

Thanks a lot, and looking forward to it!

**Comment by Speierers** [comment]
Hi @flycooler ,

Unfortunately I have spoken too quickly. I just realized that we only provide early access to the development branch for those involved in a collaboration with our lab (RGL @ EPFL).

Hence you will have to wait for the official release of the next version of Mitsuba2/enoki which will support GPU+AD+polarization.

Good luck!

**Comment by A-guridi** [comment]
Hi,

I'm commenting here because I'm also having problems with compiling gpu_polarized variants, even if they are not autodiff or spectral. Is "gpu_rgb_polarized" supposed to work or is it correct that it is still in development ?

I have no problems compiling other non-GPU polarized variants in Linux.

Thank you in advance for your time and support !

**Comment by Speierers** [comment]
Hi @A-guridi ,

Unfortunately the `gpu_polarized_*` variants are not supported in the current `master` branch of Mitsuba. You will need to wait until we release the next version of the codebase which will add support for this.
