### ISSUE TITLE
compile error about "scene->shapes()" function when writing a new integrator plugin

### ISSUE THREAD

**Issue by Andy3531** [mitsuba-renderer/mitsuba2#446]
- [❔ other question]

## Description

here is some code

`std::pair<Spectrum, Mask> sample(const Scene *scene, ..., Mask active) const override {`
`MTS_MASKED_FUNCTION(ProfilerPhase::SamplingIntegratorSample, active);`
`std::vector<ref<Shape>> shapes = scene->shapes();`
`...`
`auto s0 = shapes[0].get();`
` ...`
`}`

then error occurs at "shapes[0]":
 
*No viable overloaded operator[] for type 'std::vector<ref<Shape>>' (aka 'vector<ref<Shape<enoki::Packet<float, 8>, Color<enoki::Packet<float, 8>, 3UL>>>>')*

so why can't I use [] operator for std::vector?

**Comment by Speierers** [comment]
Hi @Andy3531,

This is strange indeed. Could you share the whole code snippet? I am suspecting something happens to `shapes` before we get to the `operator[]`.

**Comment by Andy3531** [comment]
I found the problem. Using `shapes[i1]` where `i1` is of type `Int32` caused the problem.
Thank you!
