### ISSUE TITLE
[🔨 compilation issue] command not found: mitsuba

### ISSUE THREAD

**Issue by QiyaoWei** [mitsuba-renderer/mitsuba2#448]
## Summary

Dear authors, I have followed the documentation on https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html, and sucessfully compiled mitsuba (ninja runs to completion). Then, I ran the command "source setpath.sh" with no error. Finally, I try running "mitsuba scene.xml", receiving an error message "zsh: command not found: mitsuba". Is there a step I am missing? Thanks a lot!

## System configuration

- Platform: MacOS
- Compiler: Python
- Python version: 3.8
- Mitsuba 2 version: most recent
- Compiled variants: default
    * `scalar_rgb`
    * ...

## Description

See summary. 

## Steps to reproduce

See summary.

**Comment by Speierers** [comment]
Can you find the `mitsuba` executable in your build folder?

**Comment by QiyaoWei** [comment]
No I can't, I only see .ninja and .cmake files. DOes that mean I did not compile correctly?

**Comment by Speierers** [comment]
Looks like it. Here is the right procedure to compile the system:
```
git clone --recursive ... mitsuba2
cd mitsuba2
mkdir build
cd build
cmake ..
make -j 8
```
Did you miss any of those steps?

**Comment by QiyaoWei** [comment]
I believe the problem was on my side. I simply removed the build folder and followed the docs, successfully building mitsuba. For future reference, here are the steps I followed (verbatim from the docs)
```
git clone --recursive https://github.com/mitsuba-renderer/mitsuba2/ mitsuba2
cd mitsuba2
#if you use mitsuba with python you should add python_rgb and python_spectral in mitsub.conf
mkdir build
cd build
cmake -GNinja ..
ninja
source setpath.sh
```

And then you should be able to do mitsuba scene.xml
