### ISSUE TITLE
[❔ other question] Type mistmatch for new integrator plugin

### ISSUE THREAD

**Issue by MaximilianBader** [mitsuba-renderer/mitsuba2#453]
## Summary

I created my own integrator plugin in C++ extending the capabilities of the simple path-integrator. Even though the compilation of the repository is successfull, I cannot load the plugin due to a type mismatch. 

## System configuration

- Platform: Ubuntu 20.04 in Windows WSL2
- Compiler: Clang
- Python version: 3.8.5
- Mitsuba 2 version: Own forked repo with extension (https://github.com/MaximilianBader/mitsuba2)
- Compiled variants:
    * "scalar_rgb",
    * "scalar_spectral",
    * "scalar_mono",
    * "packet_mono"

## Description

My own integrator plugin is called *path_length_origin* which is defined as *class variant* of *MonteCarloIntegrator* and then exported as it's own plugin. With this definition, I can compile the repository without any issues.

`
MTS_IMPLEMENT_CLASS_VARIANT(PathLengthOriginIntegrator, MonteCarloIntegrator)
MTS_EXPORT_PLUGIN(PathLengthOriginIntegrator, "Path Tracer integrator including path length and last point of interaction");
`

However, if I then create a basic rendering file in Python and try to load a scene which includes the new type as integrator, I encounter an exception:

`
Exception has occurred: RuntimeError
​[xml.cpp:1044] Error while loading "mitsuba_scenes/example_us_scene_2.xml" (near line 3, col 6): could not instantiate integrator plugin of type "path_length_origin": 
[xml.cpp:1044]   [PluginManager] Type mismatch when loading plugin "path_length_origin": Expected an instance of type "Integrator" (variant "scalar_mono"), got an instance of type "MonteCarloIntegrator" (variant "scalar_mono")
`

I assume, I mixed up a type definition somewhere, but as I basically copied the implementation of the standard *path* integrator, I do not fully understand what the type error is triggered by. Do you have any recommendations for me?

## Steps to reproduce

Using the compiled master-branch of my fork repository of your mitsuba2 renderer, try to load the following scene

*example_us_scene_2.xml*
<scene version="2.0.0">
	
    <integrator type="path_length_origin">
	    <integer name="max_depth" value="3"/>
    </integrator>

    
    <emitter type="point">
		<spectrum name="intensity" value="1"/>
		<point name="position" x="-0.01" y="0" z="-0.04"/>
	</emitter>
    
	

	
	<shape type="rectangle">
		
		<transform name="to_world">
			<scale x="0.00001" y="0.00001" />
			<translate x="0" y="0" z="-0.04" />
			
		</transform>
		
		<sensor type="irradiancemeterdirectional">
			<float name="x_max_bound" value="0.02"/>
            <float name="y_max_bound" value="0.005"/>
            <float name="z_max_bound" value="0.02"/>
			
			<film type="hdrfilm">
				<integer name="width" value="1"/>
				<integer name="height" value="1"/>
				<string name="pixel_format" value="luminance"/>
				<string name="file_format" value="pfm" />
			</film>
			
			<sampler type="independent">
                <integer name = "sample_count" value = "10000"/>
            </sampler>
		</sensor>
	</shape>

	
	<shape type="disk">
		<transform name="to_world">
			<scale x="0.001" y="0.001" />
			<translate x="0" y="0" z="0" />
		</transform>
        <boolean name="flip_normals" value="true"/>
		<bsdf type="roughdielectric">
			<float name="int_ior" value="1.5"/>
			<float name="ext_ior" value="1"/>
		</bsdf>
	</shape>
</scene>

**Comment by Speierers** [comment]
Hi @MaximilianBader ,

How is the integrator defined in the scene XML?

**Comment by Speierers** [comment]
Also you will need to add the following line in `src/integrators/CMakeLists.txt`:

```add_plugin(pathlengthorigin, pathLengthOrigin.cpp)```

Then you should be able to load is like this in the XML

```xml
<integrator type="pathlengthorigin"/>
```

**Comment by MaximilianBader** [comment]
Hi @Speierers,

Thanks for your quick response. Unfortunately, somehow the first parts of the xml-file provided in the description cannot be displayed. 
This is the integrator definition.
`<integrator type="path_length_origin">
	    <integer name="max_depth" value="3"/>
    </integrator>`

I also added the following line in `src/librender/CMakeLists.txt` in the end, because I decided to include the plugin in the 'integrator.h' & 'integrator.cpp' files:
`add_plugin(path_length_origin    integrator.cpp)`

**Comment by Speierers** [comment]
That is very likely not going to work. Plugins need to leave in a seperate file :)

**Comment by MaximilianBader** [comment]
All right! I feared this was the bug... :)
Thanks a lot for the help!

**Comment by MaximilianBader** [comment]
Hi @Speierers,

Following up your comment yesterday, I reimplemented my desired plugin as `path_ultrasound` and defined it in it's own `PathUltrasound.cpp` file and added `add_plugin(path_ultrasound PathUltrasound.cpp)`. However, as I changed the sampling-method quite a bit and also had to vary the return parameters, this plugin has a new class `PathLengthOriginIntegrator` as parent. `PathLengthOriginIntegrator` itself inherits from `MonteCarloIntegrator` and is defined in `integrator.h` and `integrator.cpp`. In order to access this new functionality from python scripts, I also added a PyBind class in the `integrator_v.cpp`.

However, if I now run the python-script below, I receive the following error message:
`Traceback (most recent call last):
  File "/home/badermax/source_code_repos/ultrasound_mb_recon/ultrasound_ray_tracing_num_hits.py", line 47, in <module>
    integrator.render_with_length(scene,sensors[0])
AttributeError: 'mitsuba.render.MonteCarloIntegrator' object has no attribute 'render_with_length'`

For me it seems like the plugin `path_ultrasound` is not registered as `PathLengthOriginIntegrator`, but as `MonteCarloIntegrator`. However, I don't understand why this wrong allocation occurs. Do you have any suggestions?

*Python-script*:
```
import os
import numpy as np
import enoki as ek
import mitsuba

# Set the desired mitsuba variant
mitsuba.set_variant('scalar_mono')

from mitsuba.core import Float, UInt32, UInt64, Vector2f, Vector3f
from mitsuba.core import Bitmap, Struct, Thread
from mitsuba.core.xml import load_file
from mitsuba.render import ImageBlock

# Relative path to the scene XML file, appended to FileResolvers's search path & loaded into mitsuba
filename = r'mitsuba_scenes/example_us_scene_2.xml'
Thread.thread().file_resolver().append(os.path.dirname(filename))
scene = load_file(filename)

# Instead of calling the scene's integrator, we build our own small integrator
# This integrator simply computes the depth values per pixel
integrator = scene.integrator()
sensors = scene.sensors()
film = sensors[0].film()
sampler = sensors[0].sampler()
film_size = film.crop_size()
spp = 100000

# Seed the sampler
total_sample_count = ek.hprod(film_size) * spp

print("total_sample_count: " + str(total_sample_count))
print("sampler.wavefront_size(): " + str(sampler.wavefront_size()))

diff_scale_factor = ek.rsqrt(sampler.sample_count())

if sampler.wavefront_size() != total_sample_count:
    sampler.seed(0, total_sample_count)

pos = Vector2f(0,0)
scale = Vector2f(1.0 / film_size[0], 1.0 / film_size[1])


num_hitting_rays = 0
            
i = 0
while i < total_sample_count:
    pos += sampler.next_2d()

    # Sample single ray starting from the camera sensor
    ray, weight = sensors[0].sample_ray_differential(
        time=0,
        sample1=sampler.next_1d(),
        sample2=pos * scale,
        sample3=sampler.next_2d()
    )
  

    if i < 10:
        print(i)
        print(pos*scale)
        print(ray)

    ray.scale_differential(diff_scale_factor)

    (spectrum, last_interaction_point,covered_distances,active) = integrator.sample_with_length_and_origin(scene,sampler,ray,active=True)

    if active:
        num_hitting_rays += 1

    sampler.advance()
    i += 1

print("num_hitting_rays: " + str(num_hitting_rays))

```

*example_us_scene_2.xml*:
```
    <scene version="2.0.0">
	    <!-- Define basic path tracer modeling maximum of 7 scattering events -->
        <integrator type="path_ultrasound">
	        <integer name="max_depth" value="3"/>
        </integrator>
    
        <!-- Define emitter-->
        <emitter type="point">
		    <spectrum name="intensity" value="1"/>
		    <point name="position" x="-0.01" y="0" z="-0.04"/>
	    </emitter>
    
	    <!-- Define sensor type at same position as emitter which detects the incoming irradiance-->
	    <shape type="rectangle">
		    <!-- Transform sensor type to correct direction -->
		    <transform name="to_world">
			    <scale x="0.00001" y="0.00001" />
			    <translate x="0" y="0" z="-0.04" />
			    <!-- rotate y="1" angle="-180" /-->
		    </transform>
		    
		    <sensor type="irradiancemeterdirectional">
			    <float name="x_max_bound" value="0.02"/>
                <float name="y_max_bound" value="0.005"/>
                <float name="z_max_bound" value="0.02"/>
			    <!-- Write to a portable float map containing all luminance values -->
			    <film type="hdrfilm">
				    <integer name="width" value="1"/>
				    <integer name="height" value="1"/>
				    <string name="pixel_format" value="luminance"/>
				    <string name="file_format" value="pfm" />
			    </film>
			    <!-- Define easiest sampler of sensor for ray tracing-->
			    <sampler type="independent">
                    <integer name = "sample_count" value = "10000"/>
                </sampler>
		    </sensor>
	    </shape>
    
	    <!-- Add simple scattering disk in origin flipped towards emitter and detector -->
	    <shape type="disk">
		    <transform name="to_world">
			    <scale x="0.001" y="0.001" />
			    <translate x="0" y="0" z="0" />
		    </transform>
            <boolean name="flip_normals" value="true"/>
		    <bsdf type="roughdielectric">
			    <float name="int_ior" value="1.5"/>
			    <float name="ext_ior" value="1"/>
		    </bsdf>
	    </shape>
    </scene>
```

**Comment by Speierers** [comment]
Hi @MaximilianBader,

Could you show me how you added the pybind class in `integrator_v.cpp`?

**Comment by MaximilianBader** [comment]
Hi @Speierers,

Sure! I varied the `integrator_v.cpp` according to this:
```
MTS_PY_EXPORT(Integrator) {
    MTS_PY_IMPORT_TYPES()
    using PySamplingIntegrator = PySamplingIntegrator<Float, Spectrum>;

    MTS_PY_CLASS(Integrator, Object)
        .def("render",
            [&](Integrator *integrator, Scene *scene, Sensor *sensor) {
                py::gil_scoped_release release;

#if MTS_HANDLE_SIGINT
                // Install new signal handler
                sigint_handler = [integrator]() {
                    integrator->cancel();
                };

                sigint_handler_prev = signal(SIGINT, [](int) {
                    Log(Warn, "Received interrupt signal, winding down..");
                    if (sigint_handler) {
                        sigint_handler();
                        sigint_handler = std::function<void()>();
                        signal(SIGINT, sigint_handler_prev);
                        raise(SIGINT);
                    }
                });
#endif

                bool res = integrator->render(scene, sensor);

#if MTS_HANDLE_SIGINT
                // Restore previous signal handler
                signal(SIGINT, sigint_handler_prev);
#endif

                return res;
            },
            D(Integrator, render), "scene"_a, "sensor"_a)
        .def_method(Integrator, cancel);

    auto integrator =
        py::class_<SamplingIntegrator, PySamplingIntegrator, Integrator,
                    ref<SamplingIntegrator>>(m, "SamplingIntegrator", D(SamplingIntegrator))
            .def(py::init<const Properties&>())
            .def_method(SamplingIntegrator, aov_names)
            .def_method(SamplingIntegrator, should_stop);

    bind_integrator_sample<Float, Spectrum>(integrator);

    MTS_PY_REGISTER_OBJECT("register_integrator", Integrator)

    MTS_PY_CLASS(MonteCarloIntegrator, SamplingIntegrator);

    // Add custom path length integrator
    py::class_<PathLengthOriginIntegrator<Float, Spectrum>, MonteCarloIntegrator,ref<PathLengthOriginIntegrator<Float, Spectrum>>>(m, "PathLengthOriginIntegrator")
        .def(py::init<const Properties&>())
        .def("sample_with_length_and_origin", &PathLengthOriginIntegrator<Float, Spectrum>::sample_with_length_and_origin,
            "scene"_a, "sampler"_a, "ray"_a, "medium"_a = nullptr, "active"_a = true)
        .def("render_with_length",
            [&](PathLengthOriginIntegrator<Float, Spectrum> *integrator, Scene *scene, Sensor *sensor) {
                py::gil_scoped_release release;

#if MTS_HANDLE_SIGINT
                // Install new signal handler
                sigint_handler = [integrator]() {
                    integrator->cancel();
                };

                sigint_handler_prev = signal(SIGINT, [](int) {
                    Log(Warn, "Received interrupt signal, winding down..");
                    if (sigint_handler) {
                        sigint_handler();
                        sigint_handler = std::function<void()>();
                        signal(SIGINT, sigint_handler_prev);
                        raise(SIGINT);
                    }
                });
#endif

                bool res = integrator->render_with_length(scene, sensor);

#if MTS_HANDLE_SIGINT
                // Restore previous signal handler
                signal(SIGINT, sigint_handler_prev);
#endif

                return res;
            },
            "scene"_a, "sensor"_a);
    
}

``` 
I'm thankful for any suggestions, how to implement this in a better way!

**Comment by Speierers** [comment]
And if you print the type of `integrator` do you get the right type?

**Comment by MaximilianBader** [comment]
Unfortunately not
`type(integrator)` gives `<class 'mitsuba.render.MonteCarloIntegrator'>` as output

**Comment by Speierers** [comment]
This is strange. And when you print that integrator, it uses the right `to_string` method?

**Comment by MaximilianBader** [comment]
Yes. It prints the output of the Plugin `path_ultrasound`. However, this plugin does not seem to have `PathLengthOriginIntegrator` as parent but `MonteCarloIntegrator` instead. However, I don't understand why.

**Comment by Speierers** [comment]
Did you properly edit the macros at the bottom of you integrator file?

**Comment by MaximilianBader** [comment]
I included the following macros:
*integrator.h*:
```
MTS_EXTERN_CLASS_RENDER(PathLengthOriginIntegrator)
```

*integrator.cpp*:
```
MTS_IMPLEMENT_CLASS_VARIANT(PathLengthOriginIntegrator, MonteCarloIntegrator)
MTS_INSTANTIATE_CLASS(PathLengthOriginIntegrator)
```

**Comment by Speierers** [comment]
On your github repo I see that you still have a `PathLengthOriginIntegrator` in the `integrators` folder. Could that be the issue?

**Comment by MaximilianBader** [comment]
I don't think so, because I never referenced the file somewhere. Nevertheless, I just deleted the file and recompiled the repo. It does not solve the issue.

**Comment by Speierers** [comment]
in `librender/python/main_v.cpp` could you try to add `PY_TRY_CAST(PathLengthOriginIntegrator);`, maybe that's what's missing :)

**Comment by Speierers** [comment]
Also in `scene_v.cpp` you should probably add 
```
if (auto tmp = dynamic_cast<PathLengthOriginIntegrator*>(o); tmp)
    return py::cast(tmp);
```
to the `integrator` lambda function. 😉

**Comment by MaximilianBader** [comment]
Hi @Speierers,

Thanks for that hint. I actually totally missed this.
Unfortunately, now I cannot build the repo anymore: 
```
../src/librender/python/main_v.cpp: In function ‘pybind11::object caster(mitsuba::Object*)’:
../src/librender/python/main_v.cpp:43:17: error: missing template arguments after ‘PathLengthOriginIntegrator<...auto...>’
   43 |     PY_TRY_CAST(PathLengthOriginIntegrator);
```
Apparantely, the compiler is requesting the template arguments for Float and Spectrum, but I don't understand why as `PathLengthOriginIntegrator` like `MonteCarloIntegrator` is a virtual base class.

**Comment by Speierers** [comment]
Can you try this?
```
PY_TRY_CAST(PathLengthOriginIntegrator<Float, Spectrum>);
```

**Comment by MaximilianBader** [comment]
I now added aliases for `PathLengthOriginIntegrator` in the fwd.h file for consistency with the other Integrator classes. Now the repository both compiled and I can execute my python-script accordingly!

Thanks a lot for the assistance! :)
