### ISSUE TITLE
[✨ feature request] Masked Assignment for SurfaceInteraction3f or Shape or ShapePtr

### ISSUE THREAD

**Issue by saeedhd96** [mitsuba-renderer/mitsuba2#454]
## Summary

Hi! A very helpful feature would be the possibility of masked assignment for non-primitive data structures or at least for Ptr.

## Description

I wish I could do any or all of the following:

```
si[boolean_mask] = si_2
si.shape[boolean_mask] = si_2.shape
ek.scatter(target = si,  value = some_other_si, index = indices )

```

where `si`, `si_2` and `some_other_si` are all instances of `SurfaceInteraction3f` .

Currently, none of these work in my version of mitsuba2!

**Comment by Speierers** [comment]
Hi @saeedhd96 ,

This will be possible in the next version of enoki/mitsuba. In the meantime you should be able to use a select statement:
```
si = ek::select(boolean_mask, si_2, si);
```

**Comment by saeedhd96** [comment]
Thanks!
I tried this:
`ek.select(non_specs, si, current_si)`

I get this error as a result of runing this code:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-67b077b69113> in <module>
----> 1 ek.select(non_specs, si, current_si)

~/brokenMit/mitsuba2/build/python/enoki/router.py in select(m, t, f)
   1128             result = type_t()
   1129             for k in type_t.ENOKI_STRUCT.keys():
-> 1130                 setattr(result, k, select(m, getattr(t, k), getattr(f, k)))
   1131             return result
   1132 

~/brokenMit/mitsuba2/build/python/enoki/router.py in select(m, t, f)
   1131             return result
   1132 
-> 1133         m, t, f = _var_promote_select(m, t, f)
   1134 
   1135     return type(t).select_(m, t, f)

~/brokenMit/mitsuba2/build/python/enoki/router.py in _var_promote_select(a0, a1, a2)
    159 
    160     t0 = base.ReplaceScalar(vt0, diff)
--> 161     t12 = base.ReplaceScalar(_builtins.max(vt1, vt2), diff)
    162 
    163     if type(a0) is not t0:

~/brokenMit/mitsuba2/build/python/enoki/router.py in _replace_scalar(cls, vt, diff)
    197 
    198     module = _modules.get(modname)
--> 199     return getattr(module, name)
    200 
    201 

AttributeError: module 'enoki.cuda' has no attribute 'Pointer'

```


Can you reporoduce this yourself? it might be that I am using a little older version of mitsuba2.

**Comment by Speierers** [comment]
Which version of Mitsuba / Enoki are you using?

**Comment by saeedhd96** [comment]
How can I figure it out?
I pulled the broken branch Sep 2020.

**Comment by Speierers** [comment]
Are you working with `broken` currently? This is a very unstable branch and we won't continue maintaining it as we have move to yet another (private) developement branch.

Unfortunately, until we release the new codebase, I would recommend you stick with the `master` branch.

**Comment by saeedhd96** [comment]
I do work with `broken` currently. Do you think I would lose any functionality by sticking with `master` than `broken`? I have already built my code upon `broken` and also modified my mitsuba local version a lot, and I am worried that as a result of this migration my code would stop working.

Do you think that adding the support to "ek.select()" in my local version would be easy enough to do? I do not know where to modify.

**Comment by Speierers** [comment]
Indeed porting your code back to `master` will be a lot of work and you might lose some functionality on the way.

Your issue seems to be related to the `si.shape` pointer array whose type apparently doesn't have python bindings yet. Adding support for those requires quite a few changes unfortunately. 

In the case where you do not need to use the `si.shape` field on the resulting `si`, then I would recommend you call `ek.select()` on the fields that do interest you and leave out the rest. Would that work for you?

**Comment by saeedhd96** [comment]
Yeah that is the workaround I implemented, indeed. Unfortunately, a significant part of my code is currently such workarounds for `SurfaceInteraction3f`. I manually define methods repeat(), gather(), scatter() an a lot more for `SurfaceInteraction3f`! Sadly, my workarounds aren't successful when I need `shape`. I tried to get around by using `gather` & `scatter`, but that also doesn't work on `ShapePtr`. You know better that `si.shape` is needed to be set in several cases, like bsdf sampling!

I wish I was able to find the quickest way to fix this in Mitsuba to add support of those functions for `shape` or `si`. By the way, I once asked wenzel to add `ShapePtr` and since then, working with `shape` in python bindings became easier. Would `ShapePtr` make it easier to add the needed support in python bindings?

**Comment by saeedhd96** [comment]
I have some knowledge of the Mitsuba python bindings and how to define new methods in them, if that helps. 
Appreciate your time.

**Comment by Speierers** [comment]
You could try to add it yourself then, but I won't really have the time to help you further with this as we are quite busy working on the upcoming release. Here is how I would start:

```c++
py::object ek = py::module_::import("enoki"),
           ek_array = ek.attr("ArrayBase");
                   
using UInt32 = ek::uint32_array_t<ShapePtr>;
using Mask = ek::mask_t<UInt32>;

auto shape_ptr = py::class_<ShapePtr> cls(m, "ShapePtr", ek_array);
shape_ptr.def_static("gather_", 
    [](const ShapePtr &source, const UInt32 &index,
       const Mask &mask, bool permute) {
        if (permute)
            return ek::gather<Array, true>(source, index, mask);
        else
            return ek::gather<Array, false>(source, index, mask);
    });
shape_ptr.def_static("select_",
    [](const Mask &m, const ShapePtr &t, const ShapePtr &f) {
        return ek::select(m, t, f);
    });
```

I haven't tried to compile this code BTW and you might need to add other fields to this python class (see `bind.h`). You could try to add this to `shape_v.cpp`. I took this from our current codebase, although it might be that futher changes inside of enoki as required to make this work.

Good luck!

**Comment by saeedhd96** [comment]
Hi thanks for your help despite being busy with the release! 

It helped; with a lil bit of modification I can now use `ShapePtr.custom_select()`! 
(FYI, gather did not compile! but I can live without it.)

I wish I could define such `custom_select` for `SurfaceInteraction3f` as well, but there is no `SurfaceInteraction3fPTR` and although`ek::select` works for `Interaction3f`, but it doesn't work on `SurfaceInteraction3f`!

That said, I don't expect that you could help me more, since I know you are busy currently.
