### ISSUE TITLE
[❔ other question] How can I build a scene dinamically?

### ISSUE THREAD

**Issue by rjgpinel** [mitsuba-renderer/mitsuba2#457]
## Summary

Hi everyone, 

I am a new user of mitsuba2, and I am really impressed with its capabilities. 

After going through the documentation, I was wondering: is there any way to load multiple objects using `load_dict` function and combine the objects to make a scene? or is it necessary to make a big dictionary with all the scene attributes, shapes, etc. and then use `load_dict` on this dictionary containing everything?

Thank you a lot!

**Comment by merlinND** [comment]
Hi @rjgpinel,

Currently, there's no method to add objects to a scene once it has been created, so indeed the best method is to make a big dictionary and pass it to `load_dict`.
