### ISSUE TITLE
Custom emitter plugin runtime error

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/mitsuba2#46]
I am trying to check how to define custom emitter plugin in python.  [Here](https://gist.github.com/arpit15/aa326fe42519aee54cb276ee1e5dc206) is the link to the point light defined as custom plugin. During rendering(packet_spectral), I am getting following runtime error

`RuntimeError: make_tuple(): unable to convert argument of type 'mitsuba::Interaction<enoki::Packet<float, 8ul>, mitsuba::Spectrum<enoki::Packet<float, 8ul>, 4ul> >' to Python object`

Can somebody provide a hint to what might be the problem?

**Comment by Speierers** [comment]
This is a know issue. Currently, only the `Interaction<DynamicBuffer<Packet<float, 8>>>` type has bindings for the `packet_*` variants. This will be fixed in a later version of Mitsuba 2, involving changes in to the enoki library as well.

The _Custom plugin_ feature has only been tested with `gpu_*` variants of the renderer. If your machine supports it, I would strongly recommend to use the GPU variants for this. As stated in the doc, this feature only really makes sense with wavefront modes for performance reason.

**Comment by arpit15** [comment]
With small corrections( [final plugin class](https://gist.github.com/arpit15/57297b0dc124622045aaeec8864b7cf1)), I was able to render in `scalar_*` variant.  `gpu_rgb` and `gpu_spectral` variants give me following error. 

```bash
Traceback (most recent call last):
  File "test_light_src.py", line 40, in <module>
    scene = load_file(filename, num_bounces=num_bounces, num_samples=num_samples, resolution=resolution)
RuntimeError: ​[xml.cpp:1058] Error while loading "gelsight_model/mitsuba2_visual_illumination_model.xml" (near line 118, col 4): could not instantiate emitter plugin of type "mypoint": TypeError: Unable to convert function return value to a Python type! The signature was
[xml.cpp:1058]  (self: mitsuba.core.Properties, arg0: str) -> object
[xml.cpp:1058]
[xml.cpp:1058] At:
[xml.cpp:1058]   /home/arpit/projects/sensor_optim/myEmitters.py(24): __init__
[xml.cpp:1058]   test_light_src.py(37): <lambda>
[xml.cpp:1058]   test_light_src.py(40): <module>
```

**Comment by Speierers** [comment]
The issue being with this line:
```python
self.m_world_transform = AnimatedTransform(props["to_world"])
```
it would be intersting to print the return value of `props["to_world"]`.

Also, two things I would like to mention here:

1. If I remember correctly, there is a know issue with the python constructor of custom python plugin class regarding reading fields from the `props` object. This is on my TODO list.
2. `AnimatedTransform` haven't been tested much (not at all on GPU, not sure it even works). This is also on my TODO list

**Comment by arpit15** [comment]
I also checked `direct_integrator.py` using `hello.xml` with `gpu_rgb`. I get similar error for `register_integrator` as well.

**Comment by Speierers** [comment]
I just tested this, it works fine for me.
Could you give me more information: compiler, OS, python version, ... and a full log so I can look into it?

Thanks!

**Comment by arpit15** [comment]
False alarm regarding `hello.xml`. The error was because of not using xml properties in hello.xml integrator. 
However, I am still getting an error for the custom emitter. For `gpu_*` variants, if I use python print statement, I don't see any output on the screen. How do I print the type of `props["to_world"]`?

**Comment by arpit15** [comment]
[This](https://gist.github.com/arpit15/d126672cfa8e153529d40894cabfa25c) is the smallest scene, which I am creating. 
When I query `props["intensity"]` in my emitter plugin cstor, I get following output
```bash
RegularSpectrum[
  distr = ContinuousDistribution[
    size = 95,
    range = [360, 830],
    integral = 3.70309,
    pdf = [0.00441316, 0.00467105, 0.00492895, 0.00482895, 0.00472895, .. 85 skipped .., 0.00491663, 0.00517598, 0.00543533, 0.00557121, 0.00570709]
  ]
]
``` 
However, it doesn't have `Texture` class functions like `eval`.
It seems to opaquely casted into `mitsuba.core.Object` which [these](https://gist.github.com/arpit15/ebb77e3554e0b681499b71c3a01c8734) member functions only.

**Comment by Speierers** [comment]
Is this in `gpu_rgb` mode? If it is, you should get a `UniformSpectrum` instead of `RegularSpectrum`.

**Comment by Speierers** [comment]
This is probably a bug in the bindings of `Properties`. I will try to look into this ASAP.

**Comment by Speierers** [comment]
I added bindings for `ScalarTransform4f` in 7599c2e which were necessary in `Properties`.

I was able to load a scene file with you custom `mypoint` emitter successfully, and the constructor seems to be read all the properties correctly now.

Let me know if this fixes your issue.

**Comment by arpit15** [comment]
My [previous post](https://github.com/mitsuba-renderer/mitsuba2/issues/46#issuecomment-604726374) was with `scalar_rgb`. I tried after pulling your changes with both `scalar_rgb` and `gpu_rgb`. I get `UniformSpectrum[value=[1.000000]]` with `gpu_rgb`. 
Loading scene works with proper transform in both variants. However, rendering fails with custom plugin. Both `spectrum` don't have methods of `Texture` class like `eval`.

**Comment by Speierers** [comment]
Could you try again with 53a6b96?

Thanks for reporting all those issues. This _custom plugin feature_ hasn't been tested much so far...

**Comment by arpit15** [comment]
Thanks! This does the magic. I am now able to call texture functions from spectrum and render scenes.
