### ISSUE TITLE
[🐛 bug report] depth integrator produces uniform rings on a sphere

### ISSUE THREAD

**Issue by frautschmied** [mitsuba-renderer/mitsuba2#460]
## Summary

![20000002](https://user-images.githubusercontent.com/46593445/124507978-8b664100-de01-11eb-8ce1-0a7413f0cc6f.png)
This is the center row of rendered pixels. The curve should be smooth.

## System configuration

- Platform: Ubuntu 21.04
- Compiler: clang 9
- Python version: 3.9.5
- Mitsuba 2 version: 2.2.1 master[2cd84c84]
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`

## Description

This effect also appears on all complex mesh.

In another case, plane, count pixels in a depth range.

![plane1](https://user-images.githubusercontent.com/46593445/124510039-9b801f80-de05-11eb-84e2-8bc7484dddbb.png)

The pattern of peaks varies at a distance of 2^n. I am so confused.

## Steps to reproduce

Render the following scene file.

```
<scene version="2.0.0">
<integrator type="depth"> </integrator>
<sensor type="perspective">
<float name="fov" value="120"/>
<sampler type="independent">
<integer name="sample_count" value="32"/>
</sampler>
<film type="hdrfilm">
<integer name="width" value="1920"/>
<integer name="height" value="1080"/>
</film>
</sensor>
<shape type="sphere">
<point name="center" x="0" y="0" z="5"/>
<float name="radius" value="3"/>
<bsdf type="diffuse"/>
</shape>
</scene>
```

Read the output, an EXR image. Plot the center row.

**Comment by Speierers** [comment]
Hi @frautschmied ,

Thanks for reporting this. Indeed this doesn't look great. 

Two questions:
1. Which ray tracing backend are you using here? (e.g. Embree or the native kdtree)
2. Does this happen with both the `scalar` and `packet` variants?

**Comment by frautschmied** [comment]
Hi @Speierers ,

Thanks for replying.

1. I am using native kdtree.
2. This happens with both the `scalar_rgb` and `packet_rgb` variants.

**Comment by Speierers** [comment]
And could you maybe try to see whether this also happens when switching to the embree ray tracing backend?

**Comment by frautschmied** [comment]
Recompiled with `-DMTS_ENABLE_EMBREE=1`. The same thing happened.

**Comment by Speierers** [comment]
Have you tried with the `component_format` of the film set to `float32`?

**Comment by frautschmied** [comment]
![f32](https://user-images.githubusercontent.com/46593445/124723921-164c5600-df3e-11eb-97ad-98438835a1bc.png)
It worked! Thanks! Setting `Float` to f32 alone doesn't give an f32 image. Maybe add a notice in [doc](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/variants.html#part-4-precision)?
