### ISSUE TITLE
[✨ feature request] Volumetric light emitter for inverse rendering

### ISSUE THREAD

**Issue by MaximilianBader** [mitsuba-renderer/mitsuba2#462]
## Summary

Recover emittance in each voxel of a volume performing inverse rendering

## Description

In #455, I described mentioned:
> Instead of creating a large number of small emitters in each voxel of a volume, I'd like to define a general volume and then assign an light emitting density function to this volume. Is it possible to implement this with Mitsuba2

In a subsequent step, I would like to recover the volume emittance performing inverse rendering. Thus, I would like to recover the emittance of each voxel in the medium. My first thought would be to treat the luminance in each voxel as variable. However, this would be highly inefficient in my opinion, because the number of variables would be enormous. 
In your opinion, is there a more efficient possibility to implement such a feature in Mitsuba?

**Comment by Speierers** [comment]
You should definitely not assign a variable to each voxel of your volume. The volume grid should be represented with a single flatten enoki array (e.g. 64x64x64=262144 entries). 

This is similar to optimizing a 2D texture in Mitsuba. E.g. see this [example](https://mitsuba2.readthedocs.io/en/latest/src/inverse_rendering/advanced.html). Unfortunately the current version of the codebase doesn't provide any example script for volume optimization.

**Comment by MaximilianBader** [comment]
Hi @Speierers,

Thanks for the hint. I will try to adapt the 2D texture optimization to a 3D volume optimization for emittance.

I'll close this issue for now and might reopen it, if I have an additional question or I encounter new issues!

**Comment by MaximilianBader** [comment]
Hi @Speierers,

It's me again and I'm still trying to add volume emitters to Mitsuba 2. I've read through Prof. Jakob's book (pbrt) to understand the full principles of the different approaches. As in Mitsuba, the inclusion of volume emitters is excluded in the volume rendering derivation. Now I'm wondering, what method I could apply to accurately sample a volume emission event. My current approach would be to add differentiate between medium interaction and surface interactions and then seperate between medium interaction based on emission or in-scattering. However, in this case I need to sample between in-scattering and emission events as well. Currently, I'm struggeling to find a proper sampling strategy for these 2 events. Do you have any suggestions?

**Comment by MaximilianBader** [comment]
Hi @Speierers,

sorry to bother you again with this issue, but I'm curious what your suggestions might be. Any hints or comments from your side?

**Comment by Speierers** [comment]
Hi @MaximilianBader ,

Unfortunately AFAIK volume emitters aren't supported in the currently available volumetric integrators in Mitsuba 2.

There exist a whole range of stategies to importance sample volumetric emitters, and those depend on the use-cases. I suggest you take a close look at the `volpath` integrators and build upon those. You could start with a "naive" strategy that doesn't do anything special, but still accounts for the volume emission. This will probably be slow and noisy but at least you should be able to render the correct image. Once there I would investigate more elaborate sampling strategies to reduce the variance of your integrator.

Good luck!
