### ISSUE TITLE
[❔ other question] Differentiate camera position

### ISSUE THREAD

**Issue by rjgpinel** [mitsuba-renderer/mitsuba2#463]
## Summary

Hi, I'm using a Perspective pinhole camera and I would like to know: is it possible to optimize over the camera position or any other parameter of the camera? If yes, is there any example or documentation illustrating this?

Thank you very much in advance.

**Comment by Speierers** [comment]
Hi @rjgpinel ,

Unfortunately this is not possible at the moment. To handle this properly you will need to account for visibility discontinuities when computing the gradients. See this [paper](https://rgl.epfl.ch/publications/Zeltner2021MonteCarlo) for more details.

An implementation of the algorithms described in this paper should be available in the near future.
