### ISSUE TITLE
[❔ other question] Are the examples from reparameterizing paper available?

### ISSUE THREAD

**Issue by rjgpinel** [mitsuba-renderer/mitsuba2#464]
## Summary

Hi, 

I'm really impressed by the results shown in the paper [Reparameterizing discontinuous integrands for differentiable rendering](https://rgl.epfl.ch/publications/Loubet2019Reparameterizing). 

I was wondering, do you know if the pear or starfish example is available somewhere?

Thank you in advance.

**Comment by Speierers** [comment]
Hi @rjgpinel ,

The implementation of this paper is available here:
https://github.com/mitsuba-renderer/mitsuba2/pull/157

Also some examples and figures from the paper can be found here:

https://github.com/loubetg/mitsuba2-reparam-tests

Good luck!
