### ISSUE TITLE
- [🐛 bug report] Cannot compile advanced polarized modes

### ISSUE THREAD

**Issue by A-guridi** [mitsuba-renderer/mitsuba2#467]
## Summary

Can only compile the polarized feature in `scalar` mode, `packet` and `gpu` do not work.

## System configuration

- Platform: Ubuntu 20.4
- Compiler: Clang 9, CUDA 11.0
- Python version: 3.8
- Mitsuba 2 version:  2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral_polarized`
    * `gpu_rgb`
    * `packet_rgb`

## Description

After much testing and trying, I haven't been able to compile any polarization renderer apart from the `scalar_spectral_polarized`. Note that I haven't tried `mono` versions, since I'm looking for colorful images. However, all the `packet`, `gpu` or `gpu_autodiff` modes, whether it is `RGB` or `spectral` do not compile the polarized packages. I was able to compile some gpu and packet modes though, as described above. 

Is this a known issue ? I have seen some people having problems with polarization too, but I don't know if for the moment only scalar polarization is working or I'm compiling something wrong. The error in the compilers always come at some part of the code in some specific files and libraries.

## Steps to reproduce

Simply follow the instructions to clone the repo, create a build directory and compile it inside (tried both ninja and standard cmake)

**Comment by Speierers** [comment]
Hi @A-guridi ,

Yes this is a known issue and will only be fixed in the upcoming version of the codebase.

Unfortunately there isn't much I can do for you, you will need to wait a little longer for the next release.
