### ISSUE TITLE
 [🔨 compilation issue] Error when compiling with VS2019 on Windows8

### ISSUE THREAD

**Issue by wjcyt** [mitsuba-renderer/mitsuba2#468]
## Summary

I have generated mitsuba.sln file and proceed building as usual from within Visual Studio. I set the build mode to Release here. However, error happened when building.

C3861 "_BitScanReverse64": cannot find Identifier.
LNK1181 cannot open file "...\build\src\libcore\mitsuba-core-obj.dir\Release\qmc.obj"

**Comment by Speierers** [comment]
Not really sure why this is happening on your system. In any case, you should be able to delete the code related to QMC as it isn't used anywhere at the moment.
