### ISSUE TITLE
- [❔ other question] How to set the render_torch function to call two GPUs？

### ISSUE THREAD

**Issue by pixiaonuo** [mitsuba-renderer/mitsuba2#469]
## Summary
  When running the render_torch function, if the number of samples increases to 16, it will prompt an error: cuda_malloc(): out of memory.
  There are 2 GPUs in my computer, but I find that every time I run the render_torch function, only one GPU can be called. Please help me to solve this problem. How to set the render_torch function to call two GPUs？

**Comment by Speierers** [comment]
Multi-GPU isn't currently supported in Mitsuba2. This is on our TODO list although it has a low priority. The upcoming release won't  as needy with regard to GPU memory so this shouldn't be an issue.
