### ISSUE TITLE
[❔ other question] Stokes parameter multichannel output

### ISSUE THREAD

**Issue by A-guridi** [mitsuba-renderer/mitsuba2#470]
## Summary

Hello, 
I am trying to render some images with the stokes integrator, but I am unable to divide the images into its multiple channels.

## System configuration

- Platform: Ubuntu 20.4
- Compiler: Ninja
- Python version: 3.8
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_spectral_polarized`

## Description

I am trying to generate some polarized images for testing in spectral mode. The whole rendering of images goes well and I can see them normally. The only issue is when using the `stokes` integrator on top of the `path` one, I cannot export the images using `bitmap` as I usually do. After the rendering, I get a bitmap with 17 channels, which I split into 17 bitmaps, but I don't know how to combine them again and which channels match each parameter (I guess the first 4 for the normal image, 5th for black&white s0 and the other s1,s2 and s3 with RGBA, is that correct ? ).

For the moment I have tried the accumulate() function or convert them into numpy arrays and then save them using matplotlib, but all was unsuccessful. 

How do I export that 17 multichannel bitmap into the 4 stokes parameters images and then into a colorful ".jpg" format ?

Many thanks in advance for your support and help.

**Comment by tizian** [comment]
Hi @A-guridi,

The channels encode the following information:
- [0-3]: The normal RGBA channels of the image
- [4-6]: S0, written as an RGB image (this is effectively a copy of ch [0-2])
- [7-9]: S1, written as an RGB image
- [10-12]: S2, written as an RGB image
- [13-15]: S3, written as an RGB image

Here is a short example script that exports these things as JPGs using matplotlib.
```
import mitsuba
mitsuba.set_variant("scalar_rgb")
from mitsuba.core import Bitmap

import numpy as np
import matplotlib.pyplot as plt

# Load bitmap ...
bitmap = Bitmap("example.exr")
print("Bitmap info:")
print(bitmap)
print()

# ... and convert to NumPy array
array = np.array(bitmap) #.astype('float32') # Matplotlib doesn't support saving of 16bit images
print("Numpy array")
print("shape =", array.shape)

# Channels 0-3: RGBA
rgba = array[:, :, :4]

# Save normal image. Here, we apply the most simple form of tonemapping + clipping
plt.imsave("rgba.jpg", np.clip(rgba**(1/2.2), 0, 1))

# Channels 4-6:   S0 (written as RGB, effectively a copy of channels 0-2)
s0 = array[:, :, 4:7]
# Channels 7-9:   S1 (written as RGB)
s1 = array[:, :, 7:10]
# Channels 10-12: S2 (written as RGB)
s2 = array[:, :, 10:13]
# Channels 13-15: S3 (written as RGB)
s3 = array[:, :, 13:]

# S1 - S3 encode positive and negative values, so as an example we just write
# out the "R" channels using a colormap and some arbitrary scale.
plt.imsave("s1.jpg", s1[:,:,0], cmap='coolwarm', vmin=-0.01, vmax=+0.01)
plt.imsave("s2.jpg", s2[:,:,0], cmap='coolwarm', vmin=-0.01, vmax=+0.01)
plt.imsave("s3.jpg", s3[:,:,0], cmap='coolwarm', vmin=-0.001, vmax=+0.001)
```

I hope that helps!
Best,
Tizian

**Comment by A-guridi** [comment]
Thanks!!
It worked perfectly !!
