### ISSUE TITLE
[❔ other question] AOV Integrator bitmap channels  relate to #351

### ISSUE THREAD

**Issue by yl949** [mitsuba-renderer/mitsuba2#471]
## Summary
What I want just the normal of surface. So I just add below code in xml:
```xml
<integrator type="aov">
        <string name="aovs" value="nn:sh_normal"/>
</integrator>
```

But the numpy array I have got by converting the MultiChannel type bitmap output has 8 channels. I have checked 'exr' file with 'tev', it suppose to be 7 channel.

![image](https://user-images.githubusercontent.com/30380980/125940534-262be994-3393-40be-afcd-b5b382282934.png)

I have visualize the each 3 channels in numpy array, but no one has the same result with normal map shows in 'tev'.
below is the last 3 channels I have visualized:
![testing](https://user-images.githubusercontent.com/30380980/125942685-da6643ae-41ef-486b-83f3-24e864865244.jpg)

So What information does each channel of numpy array represent? And how to get  3 channels normal map of object surface from it? 

Thanks，
yl949

**Comment by yl949** [comment]
The above visualization of normal map is uncorrect because I haven't normalize the normal vector right. Below is the visualization of correct normalized normal map:
![image](https://user-images.githubusercontent.com/30380980/126104160-e0854507-e54d-49d7-97b5-a8044b0f137c.png)

But I still don't know the 5th channel of numpy array means?

**Comment by Speierers** [comment]
@yl949 could you print the `bitmap` object in Python and share the log string here?

**Comment by yl949** [comment]
```python
img = film.bitmap(raw=True).convert(Bitmap.PixelFormat.MultiChannel, Struct.Type.Float32, srgb_gamma=False)
```
The type of img is "<class 'mitsuba.core.Bitmap'>"
![image](https://user-images.githubusercontent.com/30380980/126280952-1b36406b-cb14-48d4-bbaa-19f7394c3821.png)

**Comment by Speierers** [comment]
The 5th channel is probably the `W` (weight) channel as you requested a `raw` bitmap.

**Comment by yl949** [comment]
> The 5th channel is probably the `W` (weight) channel as you requested a `raw` bitmap. Which would also explain why the normals aren't normalized. This should work if you try with `raw=False`.

Yeah，I try ```raw=False```, and get a 7 channel bitmap with last three channel normal map with unit direction vector. 
Thank you very much!

By the way, if there any method to update the scene in python pipeline instead loading with xml file? I'd like to build a synthetic dataset, which need using different lights and materials to get different render result of object. So it will be more convenient to change this things by code automatically than to manually revise xml file and load it.

**Comment by Speierers** [comment]
Yes checkout `mitsuba.python.util.traverse()`. Take a look at the inverse rendering examples in the doc on how to use it.

**Comment by merlinND** [comment]
Although note that with `traverse`, you can only change parameters of the scene's existing plugins (BSDF, emitters, etc), not add or swap them in the scene.

To dynamically construct scenes from python, check out `load_dict`.

**Comment by yl949** [comment]
Thank you a lot! @Speierers @merlinND
