### ISSUE TITLE
- [❔ other question] In bitmap, something wrong when i specify "wrap_mode"

### ISSUE THREAD

**Issue by pixiaonuo** [mitsuba-renderer/mitsuba2#473]
When I specify the wrap_mode parameter in bitmap, it prompts me the following error: Error while loading "E:\code\mitsuba2\mitsuba\mitsuba2-master2\resources\data\tests\scenes\participating_media\test_surf_area_light.xml" (near line 87, col 7): unreferenced property ["wrap_mode"] in texture plugin of type "bitmap"

I don’t know if the texture of my xml file is wrong, the following is the texture part:

```xml
<texture name="diffuse_reflectance" type="bitmap">
                <string name="filename" value="textures/rural_rock_wall_BaseColor.jpg"/>
                <string name="wrap_mode" value="clamp"/>
</texture>
```

Please help me to solve this problem.

(Edited by @merlinND to put XML in a codeblock)

**Comment by mmmovania** [comment]
I believe your code is not visible to us.

**Comment by Speierers** [comment]
@pixiaonuo could you please share the xml file that is causing this issue?

**Comment by pixiaonuo** [comment]
> @pixiaonuo could you please share the xml file that is causing this issue?

<scene version='2.0.0'>
 <integrator type='volpathmis'>
       <integer name="max_depth" value="13"/>
    </integrator> 
	
     <emitter type="envmap">
		<string name="filename" value="textures/envmap.exr"/>
	</emitter>
	
	
	
    <sensor type="perspective">
        <float name="near_clip" value="1"/>
        <float name="far_clip" value="1000"/>

        <transform name="to_world">
            <lookat target="0.0, 0, 0.0"
                    origin="0.0 1.5 2.598"
                    up    ="0.0, 1.0, 0.0"/>
        </transform>

        <film type="hdrfilm">
           <integer name="width" value="128"/>
			<integer name="height" value="128"/>
            <rfilter type="box"/>
           
        </film>

        <sampler type="independent">
            <integer name="sample_count" value="16"/>
        </sampler>
     </sensor>
    <phase type="hg" id="hg1">
            <float name="g" value="0.7"/>
    </phase>
    <medium id="medium1" type="homogeneous">
       <rgb name="sigma_t" value="0.9, 0.9, 0.9"/>
        <rgb name="albedo" value="0.9, 0.9, 0.9"/>
          <float name="density" value="30.0"/>
		<ref id="hg1"/>
    </medium>
	   
	
   <shape type="obj">
        <string name="filename" value="meshes/arn1.obj"/>

        <bsdf type="roughplastic">
         <string name="distribution" value="beckmann"/>
	
		   <texture name="diffuse_reflectance" type="bitmap">
                <string name="filename" value="textures/rural_rock_wall_BaseColor.jpg"/>
		        <string name="wrap_mode" value="clamp"/>
		
            </texture>
		    <texture name="alpha" type="bitmap"> 
		  <string name="filename" value="textures/rural_rock_wall_roughness.jpg"/> 
		  <string name="wrap_mode" value="clamp"/>
          </texture>
		
        </bsdf>
    </shape> 
	
	
 
     <shape type="obj">
        <string name="filename" value="meshes/luck.obj"/>
        <bsdf type="null">
        </bsdf>
        <ref id="medium1" name="interior"/>
    </shape>
      
	
</scene>

**Comment by merlinND** [comment]
Hello @pixiaonuo,

I don't have access to the files used in your scenes, but the following simplified version worked fine on the [latest `master`](https://github.com/mitsuba-renderer/mitsuba2/commit/b92ddc234d1cb3510cba4db1601cd7f03e65a138):

```xml
<scene version='2.0.0'>
    <integrator type='path'/>

    <emitter type="constant"/>

    <sensor type="perspective">
        <float name="near_clip" value="1"/>
        <float name="far_clip" value="1000"/>
        <transform name="to_world">
            <lookat target="0.0, 0, 0.0"
                    origin="0.0 1.5 5"
                    up    ="0.0, 1.0, 0.0"/>
        </transform>

        <film type="hdrfilm">
            <integer name="width" value="256"/>
            <integer name="height" value="256"/>
            <rfilter type="box"/>
        </film>

        <sampler type="independent">
            <integer name="sample_count" value="32"/>
        </sampler>
    </sensor>

    <shape type="obj">
        <string name="filename" value="../resources/data/common/meshes/sphere.obj"/>

        <bsdf type="roughplastic">
            <string name="distribution" value="beckmann"/>

		    <texture name="diffuse_reflectance" type="bitmap">
                <string name="filename" value="../resources/data/common/textures/wood.jpg"/>
		        <string name="wrap_mode" value="clamp"/>
            </texture>

            <float name="alpha" value="0.1"/>
            <!-- <texture name="alpha" type="bitmap">
                <string name="filename" value="../resources/data/common/textures/wood.jpg"/>
                <string name="wrap_mode" value="clamp"/>
            </texture> -->
        </bsdf>
    </shape>
</scene>
```

Note that the `alpha` property of the `roughplastic` BSDF is supposed to be a `float`, but your scene used a `texture` so I'm assuming you're not using `master` and the problem might come from there.
Even if you're on another branch, the code reading `wrap_mode` is pretty simple:

https://github.com/mitsuba-renderer/mitsuba2/blob/b92ddc234d1cb3510cba4db1601cd7f03e65a138/src/textures/bitmap.cpp#L109-L118
