### ISSUE TITLE
[🐛 bug report] AttributeError when using python

### ISSUE THREAD

**Issue by wjcyt** [mitsuba-renderer/mitsuba2#474]
## Summary

Some problems orrured when i try to run the integrator example in docs/examples/03_direct_integrator/direct_integrator.py

## System configuration

- Platform:  windows8
- Compiler: VS2019
- Python version: Anaconda3.6.5
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`

## Description

Some functions seem to fail to be found, for example,

AttributeError: type object 'mitsuba.render.Emitter' has no attribute 'eval_vec';

AttributeError: type object 'mitsuba.render.BSDF' has no attribute 'flags_vec'

AttributeError: type object 'mitsuba.render.BSDF' has no attribute 'eval_vec'
...

**Comment by Speierers** [comment]
Hi @wjcyt ,
You will need to compile the `cuda_*` variant of the renderer for those to be available. For this you will need to modify the `build/mitsuba.conf` file.
