### ISSUE TITLE
[🐛 bug report]solve_quadratic function behavior

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/mitsuba2#475]
## Summary
The `solve_quadratic` function mentioned [here](https://github.com/mitsuba-renderer/mitsuba2/blob/master/include/mitsuba/core/math.h#L371) will return `active` as False if equation is linear and has `b<0`. This behavior doesn't match the behavior of a similar function in old mitsuba and the comments above the function are a bit misleading. 
 Can you kindly confirm if there is a bug or the expected behavior is correct and `active` should be false for equation like `-2x-3=0`?

**Comment by Speierers** [comment]
Hi @arpit15 ,

Yes this looks like a bug, good catch! I will patch this right now. Thanks for reporting it 😄

**Comment by arpit15** [comment]
@Speierers Thanks for confirming the bug. There are 2 problems with your patch
1. Your patch will go inside the `if` condition to find the solution for quadratic case, which is unnecessary
How about the following patch
```
    using Scalar = scalar_t<Value>;
    using Mask = mask_t<Value>;

    /* Is this perhaps a linear equation? */
    Mask linear_case = eq(a, Scalar(0));

    /* Initialize solution with that of linear equation */
    Value x0, x1;
    x0 = x1 = -c / b;

    /* Check if the quadratic equation is solvable */
    Value discrim = fmsub(b, b, Scalar(4) * a * c);
    
    Mask active = !linear_case && (discrim >= 0);

    if (likely(any_or<true>(active))) {
        Value sqrt_discrim = sqrt(discrim);

        /* Numerically stable version of (-b (+/-) sqrt_discrim) / (2 * a)
         *
         * Based on the observation that one solution is always
         * accurate while the other is not. Finds the solution of
         * greater magnitude which does not suffer from loss of
         * precision and then uses the identity x1 * x2 = c / a
         */
        Value temp = -Scalar(0.5) * (b + copysign(sqrt_discrim, b));

        Value x0p = temp / a,
              x1p = c / temp;

        /* Order the results so that x0 < x1 */
        x0 = min(x0p, x1p);
        x1 = max(x0p, x1p);
    }

    active = linear_case || active; 

    return std::make_tuple(active, x0, x1);
```
2. May need to also patch [cuda version](https://github.com/mitsuba-renderer/mitsuba2/blob/master/include/mitsuba/render/optix/math.cuh#L11) as well

**Comment by Speierers** [comment]
Indeed. Thanks for those remarks. I just patched it 🚀
