### ISSUE TITLE
[✨ feature request] tradeoff between rendering speed and memory cost

### ISSUE THREAD

**Issue by f1shel** [mitsuba-renderer/mitsuba2#476]
## Summary

To use less memory when rendering on GPU.

## Description

When playing Mitsuba2 in GPU mode, I always encounter `cudaErrorMemoryAllocation` error(raised by ../ext/enoki/src/cuda/horiz.cu). I use `nvidia-smi` to check memory situation, and find that even when rendering a 528x297@56spp image(I think this is really a low resolution) in mode gpu_rgb on a 10GB memory RTX 2080Ti Card, the memory can run out easily. I have already tried something like `enoki.cuda_malloc_trim()` which does not seem to work however.

Though reducing spp is an efficient way to tackle this problem, it will introduce some bad effects(e.g. too much noise). I wonder if there would be some considerations on rendering with high resolution image, high spp, as well as more loose memory requirements in Mitsuba's roadmap.

I guess most of users are looking forward to this feature and can accept the speed down when using less memory to render. After all, rendering is too slow on cpu compared with on gpu.

**Comment by Speierers** [comment]
Hi @f1shel ,

The integrator let you define (in the XML) a `samples_per_pass` attribute to split a render in multiple passes. Hence trading efficiency for memory in this case. 

If you are working from the Python side, you should be able to average the results of multiple smaller renders that fit on your GPU.

Note that the upcoming version of the codebase will lift this massive memory usage.
