### ISSUE TITLE
Saving Spectral Images out of Mitsuba 2? - [❔ other question]

### ISSUE THREAD

**Issue by alexfry** [mitsuba-renderer/mitsuba2#477]
Whilst I seem to be able to do spectral renders in Mitsuba 2 without issue.
I cannot seem to find any way to actually get multi channel spectral data out of it in image form.

"MultiChannel" is not treated as a valid pixel format, nor is "spectral".

> [HDRFilm] The "pixel_format" parameter must either be equal to "luminance", "luminance_alpha", "rgb", "rgba",  "xyz", "xyza". Found multichannel.

Am I just missing something obvious here? My understanding is that this was possible under Mitsuba 0.6

**Comment by Speierers** [comment]
Hi @alexfry ,

This is not currently implemented and you will need to define your own `film` plugin to achieve this. You might also need to slighly modify the `Integrator::render()` method to support this.
