### ISSUE TITLE
Warning in Bitmap when using Raw=True [❔ other question]

### ISSUE THREAD

**Issue by Microno95** [mitsuba-renderer/mitsuba2#480]
## Summary

When using a Bitmap image with the raw flag set to True, mitsuba still gives the warning that pixel values exceed the range [0,1]. This seems unnecessary considering the raw flag indicates that the stored data is not color data. 

## System configuration

- Platform: Windows 
- Compiler: MSVC 2019 (Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29337 for x64)
- Python version: 3.8
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `scalar_mono`
    * `scalar_spectral`

## Description

Essentially, I am using the Bitmap class to load the toroidal cross-section of a volume as a 2D image which lets me define a volume in cylindrical coordinates (via rotational symmetry). In this case, the data in the bitmap texture is set to values that exceed the [0,1] range and thus I've set the `raw` flag of the instance to `true`, but this still leads to the warning:

```cpp
BitmapTexture: texture named "dummy_cross_section.pfm" contains pixels that exceed the [0, 1] range!
```

Thus I'm simply curious as to how much sense this warning makes considering that the flag has explicitly indicated that the data is not color data. Maybe I'm misunderstanding the meaning of the warning and/or the flag.

## Steps to reproduce

1. Create a `.pfm` image with pixel values exceeding 1
2. Load this image as a bitmap with `raw=true`

**Comment by Speierers** [comment]
Hi @Microno95 ,

Thanks for reporting this. It should be fixed now: 388a4c
