### ISSUE TITLE
mitsuba2 compilation failed

### ISSUE THREAD

**Issue by jakoaltrd** [mitsuba-renderer/mitsuba2#483]
- [🔨 compilation issue]

## System configuration
cmake 3.17.1
win10 vs2019 x64
cuda11
optix7
rtx3070 laptop
python3.8.3

- Compiled variants:
        "scalar_rgb",
        "gpu_autodiff_spectral_polarized",
        "scalar_spectral"

## Description
![image](https://user-images.githubusercontent.com/67615360/128977363-81183407-90c7-4a26-a0fc-f0d6d2f61a54.png)

**Comment by tizian** [comment]
Can you try compiling without the `gpu_autodiff_spectral_polarized` variant? It is a known issue at this point that all polarization+GPU variants don't compile on the current master branch unfortunately. This support will be added in the next release.

**Comment by jakoaltrd** [comment]
thanks for your reply, then how about gpu_autodiff_spectral variant? does that compile on the master branch?

**Comment by jakoaltrd** [comment]
when I use gpu_autodiff_spectral variant, and run command:
**mitsuba -m gpu_autodiff_spectral D:\mitsuba2\resources\data\scenes\cbox\cbox-spectral.xml**
it threw an error:
_Caught a critical exception: [xml.cpp:223] Error while loading "D:\mitsuba2\resources\data\scenes\cbox\cbox-spectral.xml" (at line 3, col 8):
[xml.cpp:223]   [xml.cpp:223] Error while loading "D:\mitsuba2\resources\data\scenes\cbox\fragments\bsdfs-spectral.xml" (at line 4, col 13):
[xml.cpp:223] [xml.cpp:223]   [PluginManager] Plugin "regular" not found!.._

**Comment by Speierers** [comment]
It could be that the `cbox-spectral.xml` scene is outdated. Can you render the simple `cbox.xml` scene?

> BTW, does mitsuba2 has a nanoGUI based GUI like mitsuba2-gui?

No GUI at this point

**Comment by jakoaltrd** [comment]
well. I replace cbox-spectral.xml with cbox.xml , which is mitsuba -m gpu_autodiff_spectral D:\mitsuba2\resources\data\scenes\cbox\cbox.xml
_Caught a critical exception: [xml.cpp:223] Error while loading "D:\mitsuba2\resources\data\scenes\cbox\cbox.xml" (at line 28, col 37):
[xml.cpp:223]   [PluginManager] Plugin "regular" not found!._

when I use gpu_rgb variant, it yeilds
_Caught a critical exception: [xml.cpp:273] Unsupported variant: gpu_rgb_
it seems I need to rebuild the whole project with this variant

**Comment by Speierers** [comment]
Are you sure you compiled all the targets (e.g. the plugins) in Visual Studio? That's very likely you problem here.

**Comment by jakoaltrd** [comment]
it seems that's the problem, but more errors appeared this time, 

**错误	C2039	"scatter": 不是 "enoki::struct_support<enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<enoki::CUDAArray<float>>,4>,4>,int>" 的成员 (编译源文件 D:\mitsuba2\src\librender\python\emitter_v.cpp)	render_gpu_autodiff_spectral_polarized_ext-obj	D:\mitsuba2\ext\enoki\include\enoki\array_struct.h	87	
错误	C2039	"scatter": 不是 "enoki::struct_support<enoki::Matrix<mitsuba::Spectrum<enoki::DiffArray<enoki::CUDAArray<float>>,4>,4>,int>" 的成员 (编译源文件 D:\mitsuba2\src\librender\python\bsdf_v.cpp)	render_gpu_autodiff_spectral_polarized_ext-obj	D:\mitsuba2\ext\enoki\include\enoki\array_struct.h	87	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: float __cdecl mitsuba::ReconstructionFilter<struct enoki::DiffArray<struct enoki::CUDAArray<float> >,struct enoki::Matrix<struct mitsuba::Spectrum<struct enoki::DiffArray<struct enoki::CUDAArray<float> >,4>,4> >::radius(void)const " (__imp_?radius@?$ReconstructionFilter@U?$DiffArray@U?$CUDAArray@M@enoki@@@enoki@@U?$Matrix@U?$Spectrum@U?$DiffArray@U?$CUDAArray@M@enoki@@@enoki@@$03@mitsuba@@$03@2@@mitsuba@@QEBAMXZ)	core_gpu_autodiff_spectral_polarized_ext	D:\mitsuba2\src\libcore\python\rfilter_v.obj	1	
错误	LNK1181	无法打开输入文件“D:\mitsuba2\src\librender\python\render_gpu_autodiff_spectral_polarized_ext-obj.dir\Release\bsdf_v.obj”	render_gpu_autodiff_spectral_polarized_ext	D:\mitsuba2\src\librender\python\LINK	1	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: unsigned int __cdecl mitsuba::ReconstructionFilter<struct enoki::DiffArray<struct enoki::CUDAArray<float> >,struct enoki::Matrix<struct mitsuba::Spectrum<struct enoki::DiffArray<struct enoki::CUDAArray<float> >,4>,4> >::border_size(void)const " (__imp_?border_size@?$ReconstructionFilter@U?$DiffArray@U?$CUDAArray@M@enoki@@@enoki@@U?$Matrix@U?$Spectrum@U?$DiffArray@U?$CUDAArray@M@enoki@@@enoki@@$03@mitsuba@@$03@2@@mitsuba@@QEBAIXZ)	core_gpu_autodiff_spectral_polarized_ext	D:\mitsuba2\src\libcore\python\rfilter_v.obj	1	
错误	LNK2001	无法解析的外部符号 "__declspec(dllimport) public: struct enoki::DiffArray<struct enoki::CUDAArray<float> > __cdecl mitsuba::ReconstructionFilter<struct enoki::DiffArray<struct enoki::CUDAArray<float> >,struct enoki::Matrix<struct mitsuba::Spectrum<struct enoki::DiffArray<struct enoki::CUDAArray<float> >,4>,4> >::eval_discretized(struct enoki::DiffArray<struct enoki::CUDAArray<float> >,struct enoki::DiffArray<struct enoki::CUDAArray<bool> >)const " (__imp_?eval_discretized@?$ReconstructionFilter@U?$DiffArray@U?$CUDAArray@M@enoki@@@enoki@@U?$Matrix@U?$Spectrum@U?$DiffArray@U?$CUDAArray@M@enoki@@@enoki@@$03@mitsuba@@$03@2@@mitsuba@@QEBA?AU?$DiffArray@U?$CUDAArray@M@enoki@@@enoki@@U34@U?$DiffArray@U?$CUDAArray@_N@enoki@@@4@@Z)	core_gpu_autodiff_spectral_polarized_ext	D:\mitsuba2\src\libcore\python\rfilter_v.obj	1	

错误	MSB8066	“D:\mitsuba2\CMakeFiles\b8b68c05fab333caa2b0357dca18624f\core.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\b8b68c05fab333caa2b0357dca18624f\scalar.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\b8b68c05fab333caa2b0357dca18624f\dynamic.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\b8b68c05fab333caa2b0357dca18624f\cuda.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\b8b68c05fab333caa2b0357dca18624f\cuda_autodiff.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\asmjit.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\mitsuba-core.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\pugixml.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\IlmThread.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\Half.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\Imath.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\IlmImf.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\Iex.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\tbb.dll.rule;D:\mitsuba2\CMakeFiles\74b220d7dc6c3c3a7f9802b927ae7b5d\core_scalar_rgb_ext.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\74b220d7dc6c3c3a7f9802b927ae7b5d\core_gpu_autodiff_spectral_ext.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\74b220d7dc6c3c3a7f9802b927ae7b5d\core_scalar_spectral_ext.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\74b220d7dc6c3c3a7f9802b927ae7b5d\core_ext.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\zlib1.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\jpeg-mitsuba.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\libpng16-mitsuba.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\enoki-autodiff.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\enoki-cuda.dll.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\mitsuba-render.dll.rule;D:\mitsuba2\CMakeFiles\74b220d7dc6c3c3a7f9802b927ae7b5d\render_scalar_rgb_ext.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\74b220d7dc6c3c3a7f9802b927ae7b5d\render_gpu_autodiff_spectral_ext.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\74b220d7dc6c3c3a7f9802b927ae7b5d\render_scalar_spectral_ext.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\74b220d7dc6c3c3a7f9802b927ae7b5d\render_ext.cp38-win_amd64.pyd.rule;D:\mitsuba2\CMakeFiles\b0ed5b25d9b5304c7645a98bc51f4480\mitsuba.exe.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\blendbsdf.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\bumpmap.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\conductor.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\dielectric.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\diffuse.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\mask.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\measured.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\normalmap.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\null.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\plastic.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\roughconductor.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\roughdielectric.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\roughplastic.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\thindielectric.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\twosided.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\polarizer.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\retarder.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\circular.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\measured_polarized.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\pplastic.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\area.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\point.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\constant.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\envmap.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\directional.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\spot.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\projector.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\hdrfilm.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\depth.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\direct.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\path.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\aov.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\stokes.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\moment.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\volpath.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\volpathmis.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\homogeneous.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\heterogeneous.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\hg.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\isotropic.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\box.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\tent.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\lanczos.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\mitchell.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\catmullrom.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\gaussian.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\independent.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\stratified.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\multijitter.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\orthogonal.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\ldsampler.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\perspective.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\radiancemeter.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\thinlens.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\irradiancemeter.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\obj.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\ply.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\blender.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\serialized.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\cylinder.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\disk.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\rectangle.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\sphere.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\shapegroup.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\instance.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\blackbody.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\uniform.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\regular.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\irregular.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\d65.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\srgb.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\srgb_d65.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\bitmap.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\checkerboard.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\constvolume.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\gridvolume.dll.rule;D:\mitsuba2\CMakeFiles\55c7209948bb13abd847ada6e9df843a\mesh_attribute.dll.rule;D:\mitsuba2\CMakeFiles\b9290bfe1d8c8ffc6187c37866779341\srgb.coeff.rule;D:\mitsuba2\CMakeFiles\7dc204351089bb272167c91647cb20a7\dist-copy.rule;D:\mitsuba2\CMakeLists.txt”的自定义生成已退出，代码为 1。	dist-copy	D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241**

**Comment by Speierers** [comment]
You shouldn't enable the `gpu_spectral_polarized` variant as it is not supported at the moment.

**Comment by marcoromelli** [comment]
I just tried with `gpu_autodiff_spectral_polarized` and it doesn't work on windows. What are the working configurations with polarized enabled?
