### ISSUE TITLE
Caught a critical exception: cuda_malloc(): out of memory!

### ISSUE THREAD

**Issue by jakoaltrd** [mitsuba-renderer/mitsuba2#486]
You shouldn't enable the `gpu_spectral_polarized` variant as it is not supported at the moment.

_Originally posted by @Speierers in https://github.com/mitsuba-renderer/mitsuba2/issues/483#issuecomment-897478413_

this is what I am doing in mitsuba.conf
    _"enabled": [
        # The "scalar_rgb" variant *must* be included at the moment.
        "scalar_rgb",
        "gpu_autodiff_spectral",
        "scalar_spectral"
    ],_

I fix it because I regenerated the whole project, then I compiled it successfully, but a new error occurred:
### Caught a critical exception: cuda_malloc(): out of memory!
that should nou happen cause I render a small scece like cornell box, so why is that?

**Comment by MarisaKirisame** [comment]
can I see what you are trying to render? very interested...

**Comment by jakoaltrd** [comment]
> can I see what you are trying to render? very interested...
just a small scene, from mitsuba2 sample data.

**Comment by Speierers** [comment]
Hi @jakoaltrd ,

A few questions:
1. What's your system specifications? 
2. What is the resolution of the scene you are trying to render?
3. What is the amount of `sampler_per_pixel` you picked?

Please try to reduce the amount of spp or the resolution of the render, this should fix your problem. Also see the `samples_per_pass` argument of the integrators plugin.

**Comment by jakoaltrd** [comment]
> Hi @jakoaltrd ,
> 
> A few questions:
> 
> 1. What's your system specifications?
> 2. What is the resolution of the scene you are trying to render?
> 3. What is the amount of `sampler_per_pixel` you picked?
> 
> Please try to reduce the amount of spp or the resolution of the render, this should fix your problem. Also see the `samples_per_pass` argument of the integrators plugin.

1. my specifications
win10 x64 vs2019 RTX3070(driver version 471.68) CMake3.17.1 CUDA11.4 Optix7.3 
2. the resolution is default , I don't know what it is
3. sampler_per_pixel is also default, 16 I guess
BTW, I use the command like this: mitsuba -m gpu_autodiff_spectral D:\mitsuba2\resources\data\scenes\cbox\cbox-spectral.xml
it is just cornell box scene, so should not be too expensive, and my video adapter should be able to handle it!

**Comment by Speierers** [comment]
Please try with `spp=1` and a lower resolution.

**Comment by jakoaltrd** [comment]
how to set this, I will test _rgb later!

> Please try with `spp=1` and a lower resolution to see whether this helps. Also, does this only happen with `*_spectral` variants? Or do you see similar issue with the `*_rgb` variants?

**Comment by Speierers** [comment]
In the XML scene description.

Please read the documentation to learn how perform those basic operations.

**Comment by jakoaltrd** [comment]
I had reset the parameters, and I can't tell the differences between gpu_autodiff_spectral and non-gpu outputs, what is the main difference between them?

> In the XML scene description.
> 
> Please read the documentation to learn how perform those basic operations.

**Comment by Speierers** [comment]
They should both produce the same output. One running on the GPU and the other on the CPU.
