### ISSUE TITLE
[❔ other question]How to eliminate the black on the edge in the shape that is not smooth enough?

### ISSUE THREAD

**Issue by xyx2999** [mitsuba-renderer/mitsuba2#488]
*Please add one of the following label to your issue's title, and delete this section:*

- [❔ other question]

## Summary

*How to eliminate the black on the edge in the shape that is not smooth enough?*

## System configuration
mitsuba 2.2.1

## Description
I use mitsuba 2.2.1 to render an object. Why the black edge emerge from the shape that  is not smooth ? Like in this picture.
![33](https://user-images.githubusercontent.com/28378102/129655962-8e778fd6-848c-4c0c-9f8c-b9d57f02baf7.PNG)

And how to eliminate the black?

Thank you!

**Comment by Speierers** [comment]
Hi @xyx2999 ,

This looks like bad geometry, maybe you should fix your model first.

You can also use the `twosided` BSDF so that those "interior" regions flip the shading normals. This will likely get rid of those black artefacts.
