### ISSUE TITLE
cuda_malloc(): out of memory!

### ISSUE THREAD

**Issue by jakoaltrd** [mitsuba-renderer/mitsuba2#489]
I test it with the command mitsuba -m gpu_autodiff_spectral ..\resources\data\scenes\cbox\cbox.xml
when I scale the output to 512x512, it crashed with cuda_malloc():out of memory, but when I decrease it to 256x256, it works fine, I think 512x512 is not a high resolution to render since I am using RTX3070, so the problem may be anywhere else, this may be a bug and may need to be reported!
win10 , cuda11, Optix7.3, rtx3070,cmake 3.17.1
_Originally posted by @Speierers in https://github.com/mitsuba-renderer/mitsuba2/issues/486#issuecomment-899475013_

**Comment by Speierers** [comment]
This is expected with the current version of the codebase.
You'll have to wait for the upcoming release which won't use as much memory.
