### ISSUE TITLE
[🐛 bug report][❔ other question] Light cannot pass through the transparent object, creating an unreasonable shadow.

### ISSUE THREAD

**Issue by Daiqy** [mitsuba-renderer/mitsuba2#491]
## Description
Hi, I am now using Mitsuba2 for my research. 
There are a bunny and a floor plane in the scene, with a camera (left) and a projector (right). I set the bunny as a transparent material (["Smooth dielectric material"](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#smooth-dielectric-material-dielectric) ), and use a ["Projection light source"](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#projection-light-source-projector) to project an image to the scene. 
However, I found that the unreasonable shadow can be seen behind the glass bunny, which seems the light cannot pass through the object to reach the floor. But in fact, the object is transparent as shown in the rendered image.
![output](https://user-images.githubusercontent.com/26495036/131826265-eecf4dec-8d78-4bc8-907e-37eaa8dc608f.jpg)
I am wondering what may cause that. Is it a bug? If I want to generate a reasonable result (most lights pass through the transparent object, no all-black shadow), what should I do?
Thanks and regards! 

## System configuration
- Platform: Ubuntu 18.04
- Python version: Python 3.9
- Mitsuba 2 version: 2.2.1
- Compiled variants: 'scalar_rgb'

## Reproduce
Here is my scene XML:
```
<scene version="0.5.0" >
	
	<integrator type="path" >
		<integer name="maxDepth" value="64" />
	</integrator>

	<emitter type="projector">
		<texture name="irradiance" type="bitmap">
			<string name="filename" value="./mandrill.png"/>
			<boolean name="raw" value="true" />
		</texture>
		<float name="scale" value="1000000" />
		<float name="fov" value="58.13" />
		<transform name="to_world">
			<lookat origin="75, 300, 300" target="75, 50, 0" up="0, 1, 0"/>
		</transform>
	</emitter>

	<sensor type="perspective" >
		<float name="fov" value="58.13" />
		<transform name="toWorld" >
			<lookat origin="0, 300, 300" target="0, 50, 0" up="0, 1, 0"/>
		</transform>
		
		<sampler type="ldsampler" >
			<integer name="sampleCount" value="256" />
		</sampler>
		
		<film type="hdrfilm" >
			<integer name="width" value="640" />
			<integer name="height" value="480" />
			<string name="pixelFormat" value="rgb" />
			<boolean name="banner" value="false" />
			<rfilter type="tent" />
		</film>
	</sensor>

	<shape type="obj" >
		<string name="filename" value="./floor.obj" />
	</shape>
	
	<shape type="obj" >
		<string name="filename" value="./bunny.obj" />
		<bsdf type="dielectric">
			<float name="int_ior" value="1.51"/>
			<float name="ext_ior" value="1.0"/>
		</bsdf>
	</shape>
</scene>
```
All my code and other files (.obj model, image, etc.) are here: 
[issue.zip](https://github.com/mitsuba-renderer/mitsuba2/files/7098545/issue.zip)

**Comment by kontramind** [comment]
I'm also getting issues as @Daiqy. Here is a scene with a checkerboard and a transparent bottle. The projector here is sending some stripes (ones that can be used in structured light). This does not look physically correct.

Please advise on what are we doing wrong.

![projector_and_transparent_bottle](https://user-images.githubusercontent.com/166078/132117546-dd38577c-dd27-401d-8b85-bacb65a4b223.png)

Will make some more experiments; eg. using roughdielectrict and send my code/models.

**Comment by Daiqy** [comment]
Hi, could any Mitsuba contributor give some advice about the question? Thanks again!

**Comment by Daiqy** [comment]
> ## Description
> Hi, I am now using Mitsuba2 for my research.
> There are a bunny and a floor plane in the scene, with a camera (left) and a projector (right). I set the bunny as a transparent material (["Smooth dielectric material"](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#smooth-dielectric-material-dielectric) ), and use a ["Projection light source"](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#projection-light-source-projector) to project an image to the scene.
> However, I found that the unreasonable shadow can be seen behind the glass bunny, which seems the light cannot pass through the object to reach the floor. But in fact, the object is transparent as shown in the rendered image.
> ![output](https://user-images.githubusercontent.com/26495036/131826265-eecf4dec-8d78-4bc8-907e-37eaa8dc608f.jpg)
> I am wondering what may cause that. Is it a bug? If I want to generate a reasonable result (most lights pass through the transparent object, no all-black shadow), what should I do?
> Thanks and regards!
> 
> ## System configuration
> * Platform: Ubuntu 18.04
> * Python version: Python 3.9
> * Mitsuba 2 version: 2.2.1
> * Compiled variants: 'scalar_rgb'
> 
> ## Reproduce
> Here is my scene XML:
> 
> ```
> <scene version="0.5.0" >
> 	
> 	<integrator type="path" >
> 		<integer name="maxDepth" value="64" />
> 	</integrator>
> 
> 	<emitter type="projector">
> 		<texture name="irradiance" type="bitmap">
> 			<string name="filename" value="./mandrill.png"/>
> 			<boolean name="raw" value="true" />
> 		</texture>
> 		<float name="scale" value="1000000" />
> 		<float name="fov" value="58.13" />
> 		<transform name="to_world">
> 			<lookat origin="75, 300, 300" target="75, 50, 0" up="0, 1, 0"/>
> 		</transform>
> 	</emitter>
> 
> 	<sensor type="perspective" >
> 		<float name="fov" value="58.13" />
> 		<transform name="toWorld" >
> 			<lookat origin="0, 300, 300" target="0, 50, 0" up="0, 1, 0"/>
> 		</transform>
> 		
> 		<sampler type="ldsampler" >
> 			<integer name="sampleCount" value="256" />
> 		</sampler>
> 		
> 		<film type="hdrfilm" >
> 			<integer name="width" value="640" />
> 			<integer name="height" value="480" />
> 			<string name="pixelFormat" value="rgb" />
> 			<boolean name="banner" value="false" />
> 			<rfilter type="tent" />
> 		</film>
> 	</sensor>
> 
> 	<shape type="obj" >
> 		<string name="filename" value="./floor.obj" />
> 	</shape>
> 	
> 	<shape type="obj" >
> 		<string name="filename" value="./bunny.obj" />
> 		<bsdf type="dielectric">
> 			<float name="int_ior" value="1.51"/>
> 			<float name="ext_ior" value="1.0"/>
> 		</bsdf>
> 	</shape>
> </scene>
> ```
> 
> All my code and other files (.obj model, image, etc.) are here:
> [issue.zip](https://github.com/mitsuba-renderer/mitsuba2/files/7098545/issue.zip)

Hi, could any Mitsuba contributor give some advice about the question? Thanks again!

**Comment by merlinND** [comment]
Hello @Daiqy,

In my understanding, this is a limitation of the rendering algorithm (path tracing): your light source only occupies a single point in space, and the bunny object has a delta BSDF.
This means that once your light path reached e.g. the diffuse floor plane, there's no way to create a connection back to the light source _through the glass bunny_ with vanilla path tracing.

If you replace the projector by an area light source, you should see this is no longer a problem.

**Comment by kontramind** [comment]
> Hello @Daiqy and @kontramind,
> 
> In my understanding, this is a limitation of the rendering algorithm (path tracing): your light source only occupies a single point in space, and the bunny object has a delta BSDF.
> This means that once your light path reached e.g. the diffuse floor plane, there's no way to create a connection back to the light source _through the glass bunny_ with vanilla path tracing.
> 
> If you replace the projector by an area light source, you should see this is no longer a problem.
> Likewise, if you replace the bunny / bottle's BSDF by a non-delta one, like @kontramind did in his experiment above, these connections become possible (but still difficult to render if the roughness is low).

Hi @merlinND 

Many thanks for your answer.
To "simulate" an projector one could instantiate a rectangular shape, attach a texture (image) and then add area light? 
How would one make sure that light is emitted only from one side of the rectangle; eg. tweaking normals?

Aleksandar[kontramind]

**Comment by merlinND** [comment]
By default, area lights emit only in the direction of the normal (see e.g. light source in the Cornell box), so that wouldn't be a problem.

One difference to the projector is that the light would be emitted in all directions of the hemisphere, so I don't believe you would get the sharp patterns you are looking for. You can already try without the glass object to see how it goes.

When adding back the glass object, you can still expect pretty significant noise since light paths need to hit the rectangular light source "by chance" after refracting through glass (specular interaction, can't sample the emitter directly to ensure it gets hit).

**Comment by kontramind** [comment]
@merlinND 

Yes, I was afraid that getting sharp(focused) patterns with area light would not be viable.
Then it seems that I cannot make my scene with mistusba :). 
I'll try area light in any case.
