### ISSUE TITLE
[🔨 compilation issue] cannot compile with polarization enabled.

### ISSUE THREAD

**Issue by logos-mhr** [mitsuba-renderer/mitsuba2#493]
## Summary
cannot compile with polarization enabled.

## System configuration

- Platform: Windows 10 with VS2019 Community 16.11.2
- Compiler: MSVC with Windows SDK version 10.0.19041.0
- Python version: 3.8.3
- Mitsuba 2 version:  commit b92ddc234d1cb3510cba4db1601cd7f03e65a138 
- Compiled variants: 
      "scalar_rgb",
      "scalar_spectral",
      "scalar_rgb_polarized",
      "scalar_spectral_polarized"

## Description

While it is fine to compile with 

> "scalar_rgb",
> "scalar_spectral"

When I tried to compile with polarization enabled, following errors pop up.

```
D:\mitsuba2\src\bsdfs\measured_polarized.cpp(276,1): error C2668: “enoki::isnan”: ambiguous call to overloaded function [D:\mitsuba2\build\src\bsdfs\measured_polarized-obj.vcxproj]
D:\mitsuba2\src\bsdfs\measured_polarized.cpp(276,27): error C2672: “enoki::any”: no matching overloaded function found [D:\mitsuba2\build\src\bsdfs\measured_polarized-obj.vcxproj]
D:\mitsuba2\src\bsdfs\measured_polarized.cpp(276,13): error C2672: “masked”: no matching overloaded function found [D:\mitsuba2\build\src\bsdfs\measured_polarized-obj.vcxproj]

```

## Steps to reproduce
`
git clone --recursive https://github.com/mitsuba-renderer/mitsuba2

mkdir build

cd build

cmake .. -DMTS_ENABLE_EMBREE=1 -G "Visual Studio 16 2019" -A x64

cmake --build . --target ALL_BUILD --config Release
`

**Comment by merlinND** [comment]
Duplicate of: #467

We'll post about the status of the upcoming release in issue #490.

**Comment by tizian** [comment]
Actually not a duplicate (#467 is about GPU modes)

@logos-mhr I just pushed a small fix, can you try compiling again?

**Comment by logos-mhr** [comment]
> Actually not a duplicate (#467 is about GPU modes)
> 
> @logos-mhr I just pushed a small fix, can you try compiling again?
Currently compile is good.
Thank you.
