### ISSUE TITLE
- [✨ feature request] the index of refraction（eta）in Rough dielectric material is not differentiable

### ISSUE THREAD

**Issue by pixiaonuo** [mitsuba-renderer/mitsuba2#501]
Hi, I'm trying to render a scene of rough transparent objects using roughdielectric class. The alpha parameter is differentiable but the index of refraction（eta）is not. I want to know if the parameter eta is differentiable. If it is, how can I implement it?
Thanks a lot!

**Comment by Speierers** [comment]
Hi @pixiaonuo ,

This isn't supported at the moment. To add it yourself you will need the following changes in `roughdielectric.cpp` (un-tested):
```c++
    void parameters_changed(const std::vector<std::string> &/*keys*/ = {}) override {
        m_inv_eta = ek::rcp(m_eta);
    }

    void traverse(TraversalCallback *callback) override {
        ....
        callback->put_parameter("eta", m_eta);
        ....
    }
```

**Comment by pixiaonuo** [comment]
@Speierers  
Thank you for your help. I change the code in roughdielectric.cpp as you said. And I also change the type of eta from ScalarFloat to Float. 
But when I optimize the eta parameter in Python code, the eta value becomes Nan after opt. Step () runs.
Below is my Python code.
![409](https://user-images.githubusercontent.com/26535108/135236287-1d56e430-f3c5-4464-a45a-9b3608c5a668.png)
In this code, the x after opt. Step () is Nan. How can I solve this problem?
Thank you!

**Comment by Speierers** [comment]
I would recommend you track down those NaN values to understand where they come from. E.g. look at the gradient of this parameter before the optimizer step. If that is the case, some operation with `eta` causes it's gradient to be NaN and you will need to investigate where this is happening.

**Comment by merlinND** [comment]
Also, when running such an optimization, you'll probably want to ensure that `eta` remains in its valid range after getting updated.

**Comment by pixiaonuo** [comment]
@merlinND Thank you for your reply！
I want to ask about the valid range of  eta.  1~2? or other range?
Thank you!

**Comment by merlinND** [comment]
Hi @pixiaonuo,

[This list](https://en.wikipedia.org/wiki/List_of_refractive_indices) of refractive indices could be helpful to determine a valid range. In the end, it's all based on your application!
