### ISSUE TITLE
[🐛 bug report] Default name parsing wrong when variables share prefix

### ISSUE THREAD

**Issue by hyperknot** [mitsuba-renderer/mitsuba2#504]
## Summary

Having defaults with names like `light` and `light_w` doesn't work. `$light_w` gets parsed as `$light` + `_w`.

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: macOS Big Sur
- Compiler: default
- Python version: 3.9
- Mitsuba 2 version: 2.21 / master as of today
- Compiled variants:
    * `scalar_rgb`

## Steps to reproduce

```
  <default name="light" value="10"/>
  <default name="light_w" value="3.333"/>
```

->

`$light_w` -> gets parsed as `10_w`, not as `3.333`

**Comment by merlinND** [comment]
Hi @hyperknot,

I believe this behavior will be improved in the next major release. In the meantime, you can change the order of definition of your variables so that the shortest one appears last:

```
<default name="light_w" value="3.333"/>
<default name="light" value="10"/>
```

This will lead it to be replaced first in the scene.
