### ISSUE TITLE
No module named 'enoki.core'

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2#509]
- [🐛 bug report]

## Summary

I compiled the mitsuba successfully, but when I ran the case in the docs, I got:

```
(drbir) zhuxiangyang@Zkti:~/work/mitsuba-test/testgeo$ python invert_heightfield.py 
Traceback (most recent call last):
  File "invert_heightfield.py", line 3, in <module>
    import enoki as ek
  File "/home/zhuxiangyang/mitsuba2/build/dist/python/enoki/__init__.py", line 1, in <module>
    __import__("enoki.core")
ModuleNotFoundError: No module named 'enoki.core'
```
I can run the code successfully on another machine!

## System configuration

- Platform: Ubantu 18.04
- Compiler: cuda 11.0
- Python version: 3.8
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`
    * `packet_spectral`
    * `gpu_autodiff_spectral`
    * `gpu_autodiff_rgb`
    * `gpu_autodiff_mono`
- Hardware: RTX 3090

**Comment by merlinND** [comment]
Have you sourced `setpath.sh` in the same terminal that you're using to run the script?

**Comment by HsiangYangChu** [comment]
> Have you called `source setpath.sh` before run python code?

I get it, it is about the version of python! Thanks for your reply!
