### ISSUE TITLE
[❔ other question] Is there an automatic scene deserializer/serializer?

### ISSUE THREAD

**Issue by calvin-godfrey** [mitsuba-renderer/mitsuba2#521]
## Summary

I was sent a scene already in the serialized format as described [here](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#shape-serialized). I'm able to get it working just fine, but I'd like to make some tweaks to some of the meshes, and as far as I can tell in the documentation, there's no way to do this other than coding up the deserializer yourself. It's entirely possible that I missed something in the documentation, but does Mitsuba (or some other tool) have a way to automatically serialize/deserialize from the specified format?

**Comment by Speierers** [comment]
Hi @calvin-godfrey ,

After loading the mesh in Python (e.g. using `xml.load_dict()` you should be able to use the `Mesh.write_ply()` method to get a `.ply` file for that mesh. You can then import it in Blender and edit the mesh as you like.
