### ISSUE TITLE
How to convert colors ?

### ISSUE THREAD

**Issue by Xingxiangrui** [mitsuba-renderer/mitsuba2#522]
- [❔ other question]

## Summary

How to convert colors ?

## Background

I use codes below:

```
scene.integrator().render(scene, scene.sensors()[0])
bmp = film.bitmap(raw=True)
bmp_linear_rgb = bmp.convert(Bitmap.PixelFormat.RGB, Struct.Type.UInt8, True)
```

In mitsuba2, the following three operations are executed sequentially
1. `integrator.cpp` render a scene and convert `spec_u` from RGB to XYZAW block
2. `hdrfilm.cpp` initialize the XYZAW block to `Bitmap` 
3. `bitmap.cpp` convert XYZAW film to RGB

mitsuba2 source codes are shows below: 

https://github.com/mitsuba-renderer/mitsuba2/blob/4e7628c6eed365904ca2ba536b795d1b03410344/src/librender/integrator.cpp#L267-L285

https://github.com/mitsuba-renderer/mitsuba2/blob/4e7628c6eed365904ca2ba536b795d1b03410344/src/films/hdrfilm.cpp#L257-L263

https://github.com/mitsuba-renderer/mitsuba2/blob/4e7628c6eed365904ca2ba536b795d1b03410344/src/libcore/bitmap.cpp#L360-L365

This seems that, the codes transforms from RGB to XYZAW to RGB again.

## Problem

In order to simplify the color convert operation, I modify the codes as below:
1. `integrator.cpp` render a scene and only return RGB channels
```
Color3f rgb;
rgb = spec_u;
aovs[0] = rgb.b();
aovs[1] = rgb.g();
aovs[2] = rgb.r();
```

2. `hdrfilm.cpp` initialize the RGB block to `Bitmap` 
```
 ref<Bitmap> source = new Bitmap(m_channels.size() != 3 ? Bitmap::PixelFormat::MultiChannel 
                                                        : Bitmap::PixelFormat::RGB, 
                   struct_type_v<ScalarFloat>, m_storage->size(), m_storage->channel_count(), 
                   (uint8_t *) m_storage->data().managed().data()); 
  
 if (raw) 
     return source; 
```

3. `bitmap.cpp` not modified. 

I use the same python codes as described above.
```
scene.integrator().render(scene, scene.sensors()[0])
bmp = film.bitmap(raw=True)
bmp_linear_rgb = bmp.convert(Bitmap.PixelFormat.RGB, Struct.Type.UInt8, True)
```

However I found the RGB image I got have a color distortation.

distorted color:
![distorted](https://user-images.githubusercontent.com/24759309/140036965-e32c2e56-c5d6-4cef-a04a-b64f92261f8d.png)
Initial color: 
![Initial](https://user-images.githubusercontent.com/24759309/140036972-c8ce1575-b872-4f48-8392-0d9ac45db545.png)

## Question ? 
How can I convert the right color ? 

Very grateful for your help!

**Comment by Speierers** [comment]
Hi @Xingxiangrui ,

> This seems that, the codes transforms from RGB to XYZAW to RGB again.

Yes this is correct. This part of the system is pretty rigid and will be more flexible in the upcoming release.

In your experiment, could it be that you forgot to divide by the `weight` channel of the image?

**Comment by Xingxiangrui** [comment]
Hi @Speierers ,

I think you are right, I did not divide by the weight channel of the image.

I got it `weight` channel is initialized as `1.f` in the `XYZAW` mode,

https://github.com/mitsuba-renderer/mitsuba2/blob/4e7628c6eed365904ca2ba536b795d1b03410344/src/librender/integrator.cpp#L279-L283

I still have the following questions : 

- Did the value of `weight` channel be modified in the afterward operation ? Is it set to `1.f` and unchanged ? 
- In which function did the weight channel be divided ?  I did not found it in the `bitmap::convert` function. I want to find a function for a reference. 
- Specifically, should I divide each `RGB channel` by `weight` channel ? Or `XYZ` be divided by `weight` channel ?

**Comment by Speierers** [comment]
> Did the value of weight channel be modified in the afterward operation ? Is it set to 1.f and unchanged ?

Every sample has a weight of one, which goes through the pixel filter when splatting and then accumulated on the film.

> In which function did the weight channel be divided ? I did not found it in the bitmap::convert function. I want to find a function for a reference.

This happens in the `StructConverter` used in `HDRFilm::bitmap()`

> Specifically, should I divide each RGB channel by weight channel ? Or XYZ be divided by weight channel ?

Both will work.
