### ISSUE TITLE
[❔ other question] Spectral information in Python

### ISSUE THREAD

**Issue by micheleconni** [mitsuba-renderer/mitsuba2#523]
## Summary

I would like to know if there is a way to render spectral information in Mitsuba2's Python API.

## System configuration

- Platform: Windows
- Compiler: Visual Studio 2019, version 16.11.5
- Python version: 3.9.5
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `packet_spectral`

## Description

I am trying to simulate the measurement of a scene with a spectrometer.
Therefore, I would need spectral information as output of my sensor.
However, spectral `pixel_format`s are missing from the [`hdrfilm`](https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/films/hdrfilm.cpp) type (though I noticed that [they were present](https://github.com/mitsuba-renderer/mitsuba/blob/master/src/films/hdrfilm.cpp) in the original Mitsuba, I guess they yet have to be implemented in Mitsuba2): all the available choices convert spectral power distributions to trichromatic colour spaces.
Can this be solved by defining a new `film` type? If that's so, how does one do that?
Also, since I need to convert the results to `numpy.array`s for postprocessing in Python, I guess that I would also need to substitute the `film.bitmap(raw=True).convert()`, given that there is no spectral type in `Bitmap.PixelFormat`, either.
Is there a simple way to achieve this?

**Comment by Speierers** [comment]
Hi @micheleconni ,

This is a known limitation in the current system and will be addressed in the upcoming release. There you will be able to output spectral images with a dedicated `Film` plugin.

Until then, I would recommend you write your own Python rendering pipeline without using the `HDRFilm` at all to achieve this.

Good luck!
