### ISSUE TITLE
[❔ other question] Texture not getting loaded while rendering a mesh obj file

### ISSUE THREAD

**Issue by harora** [mitsuba-renderer/mitsuba2#524]
Trying to render a simple obj file with texture. Following is my xml config. The object shape looks correct but texture isn't getting loaded. 

`

    <scene version='2.0.0'>

    <path value="mitsuba2/resources/data/common"/>

    <integrator type="aov">
        <string name="aovs" value="sh_normal:sh_normal"/>
        <integrator type="direct" name="my_image"/>
    </integrator>

    <emitter type="constant" id="my_envmap">
        <float name="radiance" value="0.5" />
    </emitter>

    <shape type="obj">
        <string name="filename" value="115_norm.obj"/>
        <bsdf type="plastic">
            <texture name="diffuse_reflectance" type="bitmap">
                <string name="filename" value="115.png"/>
            </texture>
        </bsdf>
    </shape>

    <sensor type="perspective">
        <transform name="to_world">
            <lookat origin="0, -2.5, 2.5"
                    target="0, 0, 0"/>
        </transform>

        <float name="fov" value="30"/>

        <sampler type="independent">
            <integer name="sample_count" value="2048"/>
        </sampler>
    </sensor>
    </scene>
`

Can someone help with this? My objective is just to render a obj file with texture and above camera location settings.

**Comment by Speierers** [comment]
Hi @harora ,

Could you provide a debug log when rendering this scene? (e.g. running with `-v)
