### ISSUE TITLE
[❔ other question] Got wrong rendering result when replacing vertex positions of mesh under "scalar_rgb" mode

### ISSUE THREAD

**Issue by leomessi17** [mitsuba-renderer/mitsuba2#526]
## Summary

After initializing a scene using xml file in Python, I replace the vertex positions of mesh in this scene to render a deformed object. However, after replacing, the object in the rendered image started to vainish. In the first frame, only a few points still existed. After a few frames, all points were missing. But it was all right under "gpu_rgb" mode. Is there any difference in replacing vertex positions between these two modes ?

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: Windows, Ubuntu
- Compiler: CMAKE && VS2019, CLANG-9
- Python version: 3.7
- Mitsuba 2 version: newest
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
    * `gpu_rgb`
    * `gpu_spectral`

## Steps to reproduce
1. Initialize a scene object using xml file.
2. Replacing the vertex position using:
```
verts_key = 'OBJMesh.vertex_positions_buf'
ek.scatter(params[verts_key], new_verts, UInt32.arange(len(new_verts)))
params.set_dirty(verts_key)
params.update()
```
3. Render again.

**Comment by Speierers** [comment]
Hi @leomessi17 ,

Currently, updating the scene BVH is only supported in GPU modes.

This will be fixed in the upcoming release of the codebase.
