### ISSUE TITLE
How can I only render the foreground?

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2#529]
- [✨ feature request]

Sorry to bother you, I want to just render the foreground for my research. I want to ask if there is any relevant method, otherwise, I can only further matting on the basis of the image rendered by mitsuba.

**Comment by merlinND** [comment]
Hello @HsiangYangChu,

Yes, this should be possible by setting the `pixel_format` property of the `film` you're using to `RGBA`.
In that case, rays that do not hit any object will result in transparent pixels, which you can then composite over the background of your choice.

```xml
<film type="hdrfilm">
    <string name="pixel_format" value="rgb"/>
    <integer name="width" value="256"/>
    <integer name="height" value="256"/>
</film>
```

If you're using an environment map or other "background" emitter to light your scene, you can also use the `hide_emitters` of integrators to make sure they don't appear in your final image:

```xml
<integrator type="path">
    <boolean name="hide_emitters" value="true"/>
</integrator>
```

**Comment by HsiangYangChu** [comment]
> Hello @HsiangYangChu,
> 
> Yes, this should be possible by setting the `pixel_format` property of the `film` you're using to `RGBA`. In that case, rays that do not hit any object will result in transparent pixels, which you can then composite over the background of your choice.
> 
> ```
> <film type="hdrfilm">
>     <string name="pixel_format" value="rgb"/>
>     <integer name="width" value="256"/>
>     <integer name="height" value="256"/>
> </film>
> ```
> 
> If you're using an environment map or other "background" emitter to light your scene, you can also use the `hide_emitters` of integrators to make sure they don't appear in your final image:
> 
> ```
> <integrator type="path">
>     <boolean name="hide_emitters" value="true"/>
> </integrator>
> ```

Thanks for your reply, But it seems that it does not work, the `xml` file is showing as follows:
```
<scene version="2.2.1">
        <integrator type="path">
            <integer name="max_depth" value="$depth"/>
            <boolean name="hide_emitters" value="true"/>
        </integrator>

        <emitter type="envmap" id="my_envmap">
            <string name="filename" value="museum.exr"/>
            <!-- <string name="filename" value="./schoenbrunn-front_hd.hdr"/> -->
        </emitter>
        
        <shape type="obj">
            <string name="filename" value="cow/cow.obj"/>
            <bsdf type="diffuse">
                <texture type="bitmap" name="reflectance">
                    <string name="filename" value="cow/cow_texture.png"/>
                </texture>
            </bsdf>
        </shape>

        <sensor type="perspective">
            <transform name="to_world">
                <lookat origin="0, 0, 2.5"
                        target="0, 0, 0"
                        up="0, 1, 0"/>
                <rotate y="1" angle="$angle"/>
            </transform>
            <float name="fov" value="60"/>
            <film type="hdrfilm">
                <string name="pixel_format" value="rgb"/>
                <integer name="width" value="512"/>
                <integer name="height" value="512"/>
            </film>

            <sampler type="independent">
                <integer name="sample_count" value="$spp"/>
            </sampler>
        </sensor>
    </scene>
```

**Comment by merlinND** [comment]
Sorry, I had a typo in my XML snippet above. To use the RGBA output format, you need to specify:

```
<string name="pixel_format" value="rgba"/>
```

**Comment by HsiangYangChu** [comment]
> Sorry, I had a typo in my XML snippet above. To use the RGBA output format, you need to specify:
> 
> ```
> <string name="pixel_format" value="rgba"/>
> ```

Still doesn't work! I have tried this!:(

**Comment by Speierers** [comment]
Hi @HsiangYangChu ,

> Still doesn't work!

This isn't really helpful. What is the expected behavior and what do you get when rendering the scene above with `pixel_format=rgba`?

You could also share the EXR image here so I can take a look.

**Comment by HsiangYangChu** [comment]
@Sebastien Speierer,
Thanks for your reply, I just want to render an image that only has a foreground, no background! I have tried the method suggested by [this](https://github.com/mitsuba-renderer/mitsuba2/issues/529#issuecomment-968301153), but unfortunately, I failed!
This is my `png` file:
![010](https://user-images.githubusercontent.com/35549898/141740905-becaab3f-01dc-4b32-921e-b3ff3a30150f.png)

**Comment by Speierers** [comment]
Could you try to output an exr image instead? It could be that hidding the emitters isn't supported for PNG output images.

If that's the case, you could always convert the EXR image into a PNG, applying the alpha channel.

**Comment by HsiangYangChu** [comment]
@Speierers, 
Actually, I have tried to output EXR image, but I can not upload it :(, the follow is the screenshot of the EXR image opened by tev!
![image](https://user-images.githubusercontent.com/35549898/141743281-24bb613d-fa9d-437e-80b3-e948bb9b260d.png)

**Comment by merlinND** [comment]
Hello @HsiangYangChu,

The instructions I gave earlier assumed you were rendering from the `mitsuba` command line.
You're using the `mitsuba.python.autodiff.render` function, which is hardcoded for RGB output. Instead, if you're just trying to render images (e.g. to create a dataset), you can use `integrator.render`:

```py
import os

import mitsuba
mitsuba.set_variant('scalar_rgb')

from mitsuba.core import Thread
from mitsuba.core.xml import load_file

if __name__ == '__main__':
    output_dir = './test_output'
    os.makedirs(output_dir, exist_ok=True)

    # Replace this with your scene
    scene_fname = '../resources/data/scenes/cbox/cbox_rgba.xml'
    Thread.thread().file_resolver().append(os.path.dirname(scene_fname))
    scene = load_file(scene_fname, spp=4)

    sensor = scene.sensors()[0]
    film = sensor.film()

    image1 = scene.integrator().render(scene, sensor)

    fname = os.path.join(output_dir, 'test_{:03d}.exr'.format(0))
    film.set_destination_file(fname)
    film.develop()

    print('[+] Done rendering:', fname)
```

This should work with both `scalar` and `gpu` variants.

**Comment by Speierers** [comment]
Indeed the `write_bitmap` function doesn't support this case. This will be fixed the upcoming codebase.

**Comment by HsiangYangChu** [comment]
Hello!@merlinND,
It is workable!!! 
I appreciate it!!!
By the way, how could I output the PNG file?

**Comment by HsiangYangChu** [comment]
@Speierers,
I appreciate it! 
Looking forward to your next excellent work!!!

**Comment by merlinND** [comment]
Glad that it works!

The `hdrfilm` will always want to output to `exr` or similar floating point formats, so here's an updated example using `Bitmap.convert` to output to PNG manually:

```py
import os

import mitsuba
mitsuba.set_variant('scalar_rgb')

from mitsuba.core import Thread, Bitmap, Struct
from mitsuba.core.xml import load_file

if __name__ == '__main__':
    output_dir = './test_output'
    os.makedirs(output_dir, exist_ok=True)

    scene_fname = '../resources/data/scenes/cbox/cbox_rgba.xml'
    Thread.thread().file_resolver().append(os.path.dirname(scene_fname))
    scene = load_file(scene_fname, spp=4)

    sensor = scene.sensors()[0]
    film = sensor.film()

    image1 = scene.integrator().render(scene, sensor)

    # fname = os.path.join(output_dir, 'test_{:03d}.exr'.format(0))
    # film.set_destination_file(fname)
    # film.develop()
    fname = os.path.join(output_dir, 'test_{:03d}.png'.format(0))
    b = film.bitmap()
    b = b.convert(Bitmap.PixelFormat.RGBA, Struct.Type.UInt8, True)
    b.write(fname)

    print('[+] Done rendering:', fname)
```

**Comment by HsiangYangChu** [comment]
@merlinND,
Terrifically!
I have another question: what is the function of `Thread.thread().file_resolver().append()`, I find that it is still workable if I ignore this.

**Comment by Speierers** [comment]
> @merlinND, Terrifically! I have another question: what is the function of `Thread.thread().file_resolver().append()`, I find that it is still workable if I ignore this.

This one adds the scene folder to the path resolver. But it shouldn't be needed indeed as it should be done automatically.

**Comment by HsiangYangChu** [comment]
@Speierers,
Thanks!!!
