### ISSUE TITLE
A question about the camera model(intrinsic parameter system).

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2#532]
*Please add one of the following label to your issue's title, and delete this section:*

- [✨ feature request]

Now, I have a group of parameters about the intrinsic matrix which contains focal_length & principal points. But, as far as I am concerned, the camera model used in mitsuba2.0 is different! So, my question is how could I convert the parameters I have to the parameters needed by mitsuba2.0?
Looking forward to your answer!

**Comment by Speierers** [comment]
Hi @HsiangYangChu ,

I am afraid I won't have the time to help you with this as it is not a Mitsuba 2 issue per say.

I would recommend you take a look at the [following article](https://link.springer.com/referenceworkentry/10.1007%2F978-0-387-31439-6_152#:~:text=The%20General%20Form%20of%20Perspective,between%20the%20two%20image%20axes.) that explains the basic convertion for intrinsic/explicit camera parameters.

Good luck!

**Comment by HsiangYangChu** [comment]
@Speierers,
Thank you very much!
I am so sorry that I have so many questions, some of them may be so naive! I appreciate your patience!
Thanks, again!
