### ISSUE TITLE
[❔ other question] Throw cudaErrorInvalidResourceHandle error when working with another python module which also uses cuda.

### ISSUE THREAD

**Issue by leomessi17** [mitsuba-renderer/mitsuba2#533]
## Summary

When running mitsuba render process under scalar_rgb mode in python, It's all fine. However, if working with another python module which also using cuda, the program throws an error of "cuda_check(): runtime API error = 0400 "cudaErrorInvalidResourceHandle" in ../ext/enoki/src/cuda/jit.cu:1447". 

## System configuration

- Platform: Ubuntu16.04
- Compiler: CMake
- Python version: 3.7.9
- Mitsuba 2 version: newest
- Compiled variants:
    * `scalar_rgb`
    * `scalar_specular`
    * `gpu_rgb`

## Description

I'm not very familar with CUDA programming. I've checked the error code. The NVIDIA website shows this information "cudaErrorInvalidResourceHandle = 400. This indicates that a resource handle passed to the API call was not valid. Resource handles are opaque types like cudaStream_t and cudaEvent_t.". In fact, the other module saves some variables in gpu which are not released until the whole script ends. Is this the reason? How can I modify the source code to get both of these two modules working?

If initializing the other module first, the python script would throw this error after showing "Loading plugin "plugins/box.so". If initializing mitsuba first and later the other module. The other module works all fine. All functions can be called without any exception.

## Steps to reproduce
1. Initialize the mitsuba scene
2. Initialize the other module
3. Call the render of mitsuba scene (throwing error like above)

**Comment by Speierers** [comment]
Hi @leomessi17 ,

Could you be more specific regarding this "other Python module" that uses CUDA?

**Comment by leomessi17** [comment]
> Hi @leomessi17 ,
> 
> Could you be more specific regarding this "other Python module" that uses CUDA?

I modified this file "jit.cu" by setting "ENOKI_CUDA_USE_STREAMS" to 0 and the error was gone. However, I didn't know if there was some bad influence of this modification. 
```
#define ENOKI_CUDA_USE_STREAMS 1
```
