### ISSUE TITLE
[❔ other question] Map directly visible surface points/texels to subpixel locations

### ISSUE THREAD

**Issue by stefanjp** [mitsuba-renderer/mitsuba2#536]
## Summary

Is it possible to directly render to texture space instead of image space e.g. with a perspective sensor/camera?

## Description

My goal is to render several images with different cameras to get more information about the surface from multiple viewing angles. I would use these texture images to feed texture locations (texels) rendered from different cameras to a neural network. When rendering to image space, and then transforming to texture space I loose information due to the projection and did not find a satisfying method to fill/interpolate the gaps in the projected texture. Sampling and integrating rays in texture space would eliminate the need for projection.

If you could direct my in some way, I would appreciate it. Even if I have to modify/extend Mitsuba 2 source code.

**Comment by stefanjp** [comment]
What I want is close to:

> Or are you trying somehow to map a pixel in the rendered image to a texel on a directly visible surface? In which case you could use raytracing to figure out the surface point and the corresponding UV coordinates.

But in the opposite direction. I am interested in the subpixel location for a texel that is directly visible. With that subpixel location I can interpolate the incoming radiance to the sensor for the corresponding surface position. My original idea of directly rendering incoming radiance at these subpixel locations is not so helpful on second thought (once I use real images as instead of rendered images).

I will try to reformulate my problem: 

I want to create a texture for each sensor in a scene that contains the visible incoming radiance to that sensor. (For the mapping from object surface to texture the mapping defined in the 'Wavefront OBJ' file should be used, as for all other textures)

What I am doing now is rendering an image:
![image](https://user-images.githubusercontent.com/315302/143904456-635526b5-462a-4798-a92d-e5536a250810.png)

And then transforming each pixel to its nearest texel:
![image](https://user-images.githubusercontent.com/315302/143904590-1af2cfc4-cea1-4b7f-b192-3099405d9028.png)

This works, but results in many visible texels that end up with no information (visible surface points that remain black in the texture). Other interpolation approaches would be a way to go, but results are inaccurate and correct interpolation is not trivial (how to find out which texels represent visible surface points without ray tracing).

My reformulated question is:

Is there a simple way in Mitsuba 2 to calculate for each visible surface position represented by texels a subpixel position using raytracing?

I hope my question is now less confusing :)

**Comment by Speierers** [comment]
I believe this kind of connection to the sensor from a given point in the scene isn't currently implemented. You can take a look at this [method](https://github.com/mitsuba-renderer/mitsuba/blob/cfeb7766e7a1513492451f35dc65b86409655a7b/include/mitsuba/render/emitter.h#L157) in Mitsuba 0.6. I believe this is what you are looking for. It should be implemented for the perspective camera as well.

**Comment by stefanjp** [comment]
Thank you for the quick reply and pointing me to the mitsuba 0.6 source code. I'll have a look into it and will post some details, if I manage to solve my problem. Closing the issue for now.

**Comment by UmarSpa** [comment]
@Speierers  does such method exist in Mitsuba3?  I.e. given a point x on some surface in a scene, is it possible to know if it is visible by a camera at location y?

> I believe this kind of connection to the sensor from a given point in the scene isn't currently implemented. You can take a look at this [method](https://github.com/mitsuba-renderer/mitsuba/blob/cfeb7766e7a1513492451f35dc65b86409655a7b/include/mitsuba/render/emitter.h#L157) in Mitsuba 0.6. I believe this is what you are looking for. It should be implemented for the perspective camera as well.

**Comment by Speierers** [comment]
I believe this can be done using `Sensor::sample_direction()`.
