### ISSUE TITLE
An error about the write_bitmap

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2#537]
*Please add one of the following label to your issue's title, and delete this section:*

- [🐛 bug report]

Sorry for bothering you again!
I found an interesting phenomenon when I am running the following code:
```
        write_bitmap(os.path.join(output_path_root, 'output_%03i.png' % 0), opt_image, crop_size)
        write_bitmap(os.path.join(output_path_root, 'output_%03i.png' % 1), opt_image, crop_size)
        write_bitmap(os.path.join(output_path_root, 'output_%03i.png' % 2), opt_image, crop_size)
        write_bitmap(os.path.join(output_path_root, 'output_%03i.png' % 3), opt_image, crop_size)
```
the `output_000.png`:

![output_000](https://user-images.githubusercontent.com/35549898/143874418-bf55c349-0666-47ba-9ea5-4dc25ff0b138.png)
the `output_001.png`:
![output_001](https://user-images.githubusercontent.com/35549898/143874521-15591bd4-c9f8-4352-9689-665696cb7b5b.png)
the `output_002.png`:
![output_002](https://user-images.githubusercontent.com/35549898/143874556-10fcf5a5-16cb-4d52-88e4-d5dc4310ae1d.png)
the `output_003.png`:
![output_003](https://user-images.githubusercontent.com/35549898/143874569-e658f5d0-e842-47c3-b185-5906cd8656a1.png)
Why does this happen?
Looking forward to your insights!

**Comment by Speierers** [comment]
Please @HsiangYangChu use proper issue names otherwise it is really hard for us to keep track of different issues.

You should probably checkout the `write_async` argument of `write_bitmap`, this might solve your issue if you are reading those file before they are finished writing.

**Comment by HsiangYangChu** [comment]
Hi, @Speierers 
Thanks for your reply!
Sorry for the issue name!
The bug has been fixed with your help!

**Comment by Speierers** [comment]
It executes asynchronously on a different thread

**Comment by HsiangYangChu** [comment]
@Speierers Thanks again!
