### ISSUE TITLE
❔ sigma_t, albedo, and scale values to produce a certain color in volume rendering

### ISSUE THREAD

**Issue by BlackPi3** [mitsuba-renderer/mitsuba2#540]
## Summary
As far as I know, scattering and absorption dictate how we see an object in the scene. I'm trying to reproduce an "ink" object with a certain color, but I don't know how to get the color I want using sigma_t, albedo, and scale. I haven't found any documentation explaining these variables. I want to know how mitsuba works with these variables.
I know: `sigma_t := absorption + scattering` and `albedo := scattering / (absorption + scattering)`
## Description
In my scene.xml I've defined a bsdf and medium tag as follows and a shape that uses them:

```
<bsdf type="dielectric" id='ink_bsdf'>
        <float name="int_ior" value="1.45" />
	<string name="ext_ior" value="air" />
</bsdf>
<medium type="homogeneous" id='magenta_medium'>
	<rgb name="sigma_t" value="0.25, 0.3, 1.0"/>
        <rgb name="albedo" value="0.098, 0.01, 0.09"/>
	<float name='scale' value='10'/>
        <phase type="isotropic" />
</medium>
<shape type='obj' id='second_layer'>
	<string name='filename' value='unit_cube_centered.obj' />
	<transform name='to_world'>
		<scale x='10' y='$coating_height' z='10'/>
		<translate x='0' y='$coating_posy' z='0' />
	</transform>
	<ref id='ink_bsdf' />
	<ref name='interior' id='magenta_medium'/>
</shape>
```

I've set the values for the variables based on this table I've found in a paper: 

![image](https://user-images.githubusercontent.com/16107268/144580497-8a84b284-7728-425f-a121-de1370a15573.png)

And, this is what I'm getting, which is nowhere near magenta color:

![vertical_view](https://user-images.githubusercontent.com/16107268/144583280-c29b6535-379a-45cd-9766-e9027aa6be24.jpg)

**Comment by dvicini** [comment]
Hi,
What you describe sounds reasonable. One issue I see is that you scaled the albedo values. That's wrong, since the albedo is independent of scene scale (the scale cancels out). If you render with the correct albedo, hopefully the result will look better
Delio
