### ISSUE TITLE
[❔ other request] Are there any code samples for caustic design/optimization?

### ISSUE THREAD

**Issue by ArmanMaesumi** [mitsuba-renderer/mitsuba2#541]
I was wondering if there were any publicly released code samples that performed caustic optimization (as seen in the original paper).

Thanks!

**Comment by merlinND** [comment]
Hello @ArmanMaesumi,

Thank you for your interest in the caustic optimization application. A particle tracer integrator (light tracer) and a caustic optimization example / tutorial will be part of the next release (#490 ).
Sorry it's still not out!
