### ISSUE TITLE
Is that the mitsuba calculates the normal if there is no normal in the ply file?

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2#543]
- [✨ feature request]
- [❔ other question]

Sorry for bothering you again!
When I do geometry optimization using the method in the doc. 
I find the `ply` file doesn't have normal property, but the scene loaded from `ply` file actually has normal. 
So, I guess that the `mitsuba` calculates the normal if there is no normal in the `ply` file!
Is my guess right?
Looking forward to your reply!

**Comment by Speierers** [comment]
Yes indeed Mitsuba will compute so surface normals is none are provided by the ply file. You can change this behaviour using the `face_normals` flag on the `Shape`.

**Comment by HsiangYangChu** [comment]
@Speierers
I appreciate it!!!
