### ISSUE TITLE
memory leak in bitmap.cpp

### ISSUE THREAD

**Issue by jxo** [mitsuba-renderer/mitsuba2#544]
*Please add one of the following label to your issue's title, and delete this section:*

- [🐛 bug report]
m_data is unique_ptr<uint8_t[]>(new uint8_t[size])

this is not released in dctor,  copy ctor, and other assign to m_data operation.

m_data should be released by delete [] m_data.get()

 so here unique_ptr here is useless.

**Comment by Speierers** [comment]
Hi @jxo ,

Could you be more specific onto where you spotted this issue in the code.

**Comment by jxo** [comment]
@Speierers 
libcore/bitmap.cpp line 75 line 115 and more positions

**Comment by jxo** [comment]
hey, anyone fix that?

**Comment by wjakob** [comment]
Your report is confusing because `unique_ptr` automatically releases its memory (that's the reason for using it here.) Can you provide an example that reproduces an obvious memory leark?

**Comment by jxo** [comment]
@wjakob thanks for your reply
I think I figure out the problem, 
my version
Bitmap::～Bitmap()
{ if (m_own_data) m_data.release(); }
without the "!", so it leaks.
But why should use release here？
