### ISSUE TITLE
Some problems in environment map optimization when the image has background.

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2#545]
- [🐛 bug report]
- [✨ feature request]

Hi, bothering you again.
I am trying to optimization the environment map, but I find some problems. The following is the reconstructed env map:
![env_001](https://user-images.githubusercontent.com/35549898/145676399-62d1a62d-0880-491d-a61f-abce2f3742e5.png)
The ground truth image is:
![r_0](https://user-images.githubusercontent.com/35549898/145676633-d773670d-0268-45ed-9eea-805584be3559.png)
The initial image is:
![output_0000_](https://user-images.githubusercontent.com/35549898/145676663-6879b475-c05a-4fc9-bb3b-ec51094013fe.png)
There is a black block on the env map, which I think is due to that the background is also been rendered by the `mitsuba.python.autodiff.render` function. Actually, we have talked about this in #529. So I am trying to use a mask to deal with the background, but I encounter an error.
This code is my solution:
```
opt.zero_grad()
image = render_torch(scene, params=params, unbiased=True, **params_torch)
image = image * mask
ob_val = mse(image, image_ref)
ob_val.backward()
opt.step()
```
The error info is:
```
Traceback (most recent call last):
  File "inverse_test_torch.py", line 168, in <module>
    ob_val.backward()
  File "/home/zhuxiangyang/anaconda3/envs/drbir/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zhuxiangyang/anaconda3/envs/drbir/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Found dtype Float but expected Double
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDABackend: referenced unknown variable 33586
Aborted (core dumped)
```
So, could you provide some insights to solve this problem?
***
Actually, I have tried another method to use a mask: I let the background pixel in the ground truth image be (1.0, 1.0, 1.0), which means the difference of the two background pixels between rendered image and ground truth image is 0. But I get the result:
![env_004](https://user-images.githubusercontent.com/35549898/145677216-63633977-a63d-498b-95f0-5aacc6bc76bb.png)
There is a white block on the env map! :(
So, I don't think the mask can solve the problem that appeared in the env optimization, on the contrary, I think this problem can't be solved because that the `mitsuba.python.autodiff.render` function can't render only the foreground. Is my view right?
Looking forward to your reply!

**Comment by merlinND** [comment]
Hello @HsiangYangChu,

Indeed it makes sense that the reconstructed envmap would have a black region if you try to match a target image that has a black background.

I think that using a mask should help, maybe as follows:

1. Get the alpha channel of the reference image, making sure that the background pixels have alpha = 0. The alpha channel should probably be of type `Float`.
2. In the loss function, multiply both the rendered and reference RGB values by alpha.

Alternatively, you could create some sort of boolean mask and `select` only values that are not masked before computing the loss.

**Comment by HsiangYangChu** [comment]
Hi @merlinND,
Thanks for your reply!
I succeeded in the method you provided! Thanks again!
This is the reconstructed env map using one view:
![env_001](https://user-images.githubusercontent.com/35549898/145697497-7356a45a-c95b-449c-8a54-1820731f5374.png)
It's pretty good!
But, when using multi-view to reconstruct the env map, some artifacts appear as follows:
![env_002](https://user-images.githubusercontent.com/35549898/145697603-4df81db0-ac0e-44be-bd33-493e1259925b.png)
(2 views)
![env_003](https://user-images.githubusercontent.com/35549898/145697610-ea15b543-37fc-43d3-8427-5f89b03e1999.png)
(3 views)
![env_064](https://user-images.githubusercontent.com/35549898/145697548-dbf57a72-d070-4183-9e22-eaedc473399b.png)
(64 views)
I still have no idea why this happens! Could you provide some insights?

**Comment by Speierers** [comment]
Hi @HsiangYangChu 

We are currently focussing on the upcoming release of the codebase and therefore won't have time to debug this with you. I would take a close look at the gradient produced by each view to better understand how the optimizer introduces those artifacts in the envmap. Also you could try to increase the number of sample per pixels to make sure noise in the images / gradient isn't the problem here.

Good luck!

**Comment by HsiangYangChu** [comment]
I appreciate it!
