### ISSUE TITLE
Outputting a hyperspectral image [❔ other question]

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/mitsuba2#549]
## Summary
I am trying to output an `exr` image in `spectral` as done in `mitsuba0.6` by passing `pixelFormat = spectrum`. However, the output image I get doesn't match the output from `mitsuba0.6` nor does it match after manually converting to linear RGB by integrating using XYZ curves and then converting to linear RGB. 

The main change I made was in the `integrator.cpp` [here](https://github.com/arpit15/mitsuba2/commit/f8f5b9fe407ab2e761de9b1913f54798752ae747#diff-c350fdd1b5cc6e90dfc069a79e8069f7f6fb6d5f13c149d09a600d7e696a337dR296)
My commit is available [here](https://github.com/arpit15/mitsuba2/commit/f8f5b9fe407ab2e761de9b1913f54798752ae747)

[EXR image](https://drive.google.com/file/d/1KxTcVUTVEUsHf_2Kq3YYrzrRQ5EpmGAc/view?usp=sharing) generated after my changes from mitsuba2
[EXR image](https://drive.google.com/file/d/18VXncYPEe8-VKFPTAgnlzENxlQjvEEAs/view?usp=sharing) generated using `mitsuba0.6`

## System configuration
- Platform: Ubuntu 21.04
- Compiler: g++10.3.1
- Python version: 3.7.7
- Mitsuba 2 version: 2.1.1
- Compiled variants:
    * `scalar_spectral30`

Any help is appreciated. Thanks

**Comment by Speierers** [comment]
Hi @arpit15 ,

This isn't supported at the moment and will be in the upcoming release.

**Comment by UNakade** [comment]
Hi. May I ask if there are any plans for this in the near future?

**Comment by wjakob** [comment]
Yes -- check out the 'specfilm' in Mitsuba 3, which will be released later today.
