### ISSUE TITLE
Python binbings crash while printing differatiable parameters

### ISSUE THREAD

**Issue by alexus37** [mitsuba-renderer/mitsuba2#55]
I  following scene scene:

```xml
<?xml version="1.0" ?><scene version="0.6.0">
	<integrator type="direct"/>
  <texture type="bitmap" id="skinTexture">
    <string name="filename" value="MikeAlger_Texture.jpeg"/>
    <transform name="to_uv">
      <scale x="1"/>
    </transform>
  </texture>
	<shape id="main" type="serialized">
		<transform name="to_world">
			<rotate angle="-11.486546301783648" y="1"/>
            <translate x="-64.92164437446417" y="0" z="0.0"/>
		</transform>
		<string name="filename" value="pose_0_2.serialized"/>
		<integer name="shapeIndex" value="0"/>

		<bsdf type="diffuse">
			<ref id="skinTexture" name="reflectance"/>
		</bsdf>
	</shape>
  <emitter type="constant">
    <spectrum name="radiance" value="1.0"/>
  </emitter>
	<sensor type="perspective">
		<float name="far_clip" value="2500.0"/>
		<float name="fov" value="45"/>
		<string name="fov_axis" value="y"/>
		<float name="near_clip" value="2.0"/>
		<transform name="to_world">
			<lookat origin="-4.21425, 105.008, 327.119" target="-4.1969, 104.951, 326.12" up="0.0, 1.0, 0.0"/>
		</transform>

		<sampler type="independent">
			<integer name="sampleCount" value="32"/>
		</sampler>

		<film type="hdrfilm">
			<rfilter type="box"/>
      <integer name="width" value="432"/>
      <integer name="height" value="368"/>
		</film>
	</sensor>
</scene>
````

from which I want to print the differentiable parameters using the following python code:

```python
Thread.thread().file_resolver().append('pose_scene')
scene = load_file('pose_scene/scene.xml')

# Find differentiable scene parameters
params = traverse(scene)
print(params)
```

However, this seems to crash the python bindings see screenshot:
![Selection_064](https://user-images.githubusercontent.com/7422767/78017093-0f529300-734c-11ea-9e52-10f658e93f98.png)

**Comment by Speierers** [comment]
Thanks for reporting this!
It should now be fixed (d066893012).

**Comment by alexus37** [comment]
Wow, thanks for the quick fix! Love the spirit!

**Comment by garethwalkom** [comment]
I'm getting a similar error when using the example at https://mitsuba2.readthedocs.io/en/latest/src/inverse_rendering/pytorch.html:

`>>> import enoki as ek
>>> import mitsuba
>>> mitsuba.set_variant('gpu_autodiff_spectral')
>>>
>>> from mitsuba.core import Thread, Vector3f
>>> from mitsuba.core.xml import load_file
>>> from mitsuba.python.util import traverse
>>> from mitsuba.python.autodiff import render_torch, write_bitmap
>>> import torch
>>> import time
>>>
>>> Thread.thread().file_resolver().append('cbox')
>>> scene = load_file('../resources/data/scenes/cbox/cbox.xml')
2020-04-02 00:34:07 INFO  main  [xml.cpp:1129] Loading XML file "..\resources\data\scenes\cbox\cbox.xml" ..
2020-04-02 00:34:07 INFO  main  [xml.cpp:1130] Using variant "gpu_autodiff_spectral"
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\regular.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\path.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\independent.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\gaussian.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\hdrfilm.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\perspective.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\diffuse.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\area.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\d65.dll" ..
2020-04-02 00:34:07 INFO  main  [PluginManager] Loading plugin "plugins\obj.dll" ..
2020-04-02 00:34:07 INFO  main  [Scene] Validating and building scene in OptiX.
>>> params = traverse(scene)
>>> params.keep(['red.reflectance.value'])
>>> param_ref = params['red.reflectance.value'].torch()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u0120819\mitsuba2\dist\python\mitsuba\python\util.py", line 41, in __getitem__
    return self.get_property(*(self.properties[key]))
KeyError: 'red.reflectance.value'
>>> print(params)
ParameterMap[
]`

I also haven't changed anything from the example scene cbox.xml.

I'm unsure how to fix this, but I have pulled and built the gpu_autodiff_spectral variant with the latest mitsuba2 release.

**Comment by garethwalkom** [comment]
@Speierers thanks! That did the job.

> Also is should be
> 
> `params.keep(['red.reflectance.values'])`
> as you are in spectral mode.
Is the above included in the documentation? I couldn't see it when following https://mitsuba2.readthedocs.io/en/latest/src/inverse_rendering/pytorch.html

A few lines down, I now have the following error:
```
>>> param_ref = params['red.reflectance.values'].torch()
>>> print(param_ref)
tensor([0.0400, 0.0460, 0.0480, 0.0530, 0.0490, 0.0500, 0.0530, 0.0550, 0.0570,
        0.0560, 0.0590, 0.0570, 0.0610, 0.0610, 0.0600, 0.0620, 0.0620, 0.0620,
        0.0610, 0.0620, 0.0600, 0.0590, 0.0570, 0.0580, 0.0580, 0.0580, 0.0560,
        0.0550, 0.0560, 0.0590, 0.0570, 0.0550, 0.0590, 0.0590, 0.0580, 0.0590,
        0.0610, 0.0610, 0.0630, 0.0630, 0.0670, 0.0680, 0.0720, 0.0800, 0.0900,
        0.0990, 0.1240, 0.1540, 0.1920, 0.2550, 0.2870, 0.3490, 0.4020, 0.4430,
        0.4870, 0.5130, 0.5580, 0.5840, 0.6200, 0.6060, 0.6090, 0.6510, 0.6120,
        0.6100, 0.6500, 0.6380, 0.6270, 0.6200, 0.6300, 0.6280, 0.6420, 0.6390,
        0.6570, 0.6390, 0.6350, 0.6420], device='cuda:0')
>>> image_ref = render_torch(scene, spp=8)
>>> crop_size = scene.sensors()[0].film().crop_size()
>>> write_bitmap('out.png', image_ref, crop_size)
>>> params['red.reflectance.values'] = [.9, .9, .9]
>>> params.update()
>>> params_torch = params.torch()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u0120819\mitsuba2\dist\python\mitsuba\python\util.py", line 95, in torch
    return {k: v.torch().requires_grad_() for k, v in self.items()}
  File "C:\Users\u0120819\mitsuba2\dist\python\mitsuba\python\util.py", line 95, in <dictcomp>
    return {k: v.torch().requires_grad_() for k, v in self.items()}
AttributeError: 'float' object has no attribute 'torch'
```

Thanks.

**Comment by Speierers** [comment]
First of all, you are using `mitsuba.set_variant('gpu_autodiff_spectral')`, meaning that `red.reflectance.values` is not a `Color3f` here but a set of values (see `regular.cpp`).

Could you try again with `gpu_autodiff_rgb` (and use ``red.reflectance.value` then)?

**Comment by merlinND** [comment]
Also I think that on this line, you might need to use an Enoki type rather than a raw list?

```
params['red.reflectance.values'] = [.9, .9, .9]
```

**Comment by Speierers** [comment]
> Also I think that on this line, you might need to use an Enoki type rather than a raw list?
> 
> ```
> params['red.reflectance.values'] = [.9, .9, .9]
> ```

Not sure about this. This is how it is done in the tuto. I think the implicit cast can figure it out.

**Comment by garethwalkom** [comment]
> Could you try again with `gpu_autodiff_rgb` (and use ``red.reflectance.value` then)?

This worked, thank you! Pretty cool. Does it not work with spectral rendering?

**Comment by Speierers** [comment]
I should work with spectral rendering. You will need to provide spectral values instead of RGB here tho.
