### ISSUE TITLE
Does integrating Optix into Mitsuba likely to remain differentiable?  [❔ other question]

### ISSUE THREAD

**Issue by hubert0527** [mitsuba-renderer/mitsuba2#550]
## Summary

I am trying to add a denoiser to my pipeline and see Optix includes a [denoiser](https://raytracing-docs.nvidia.com/optix7/api/optix__denoiser__tiling_8h.html) as a part of its API. It seems like importing the function may be the most straightforward solution, but I am not sure if the output remains differentiable (or requires additional handling to the backward calculation).

## Description

If I understand correctly, the Mitsuba framework uses Enoki to achieve auto-differentiable, and Enoki supports tracking the gradient of cuda arrays that are being used in Optix for rendering. Therefore, as a part of the Optix API, applying [Optix denoiser](https://raytracing-docs.nvidia.com/optix7/api/optix__denoiser__tiling_8h.html) to a cuda array should remain differentiable, right?

Apologies if the answer to the question is straightforward, I am pretty new to this ecosystem. Sincerely thanks and grateful for any reply!

**Comment by Speierers** [comment]
Hi @hubert0527,

Indeed the image resulting from the denoiser will not be "attached" to the automatic-differentiation backend anymore. 

It is possible to re-attach such variables using the `enoki.reattach(a, b)` function but this means that you will need to manually compute the gradients which might be difficult as the OptiX denoiser is a black box.
