### ISSUE TITLE
Mitsuba2 Profiler Error - [🔨 compilation issue]

### ISSUE THREAD

**Issue by Vmbundu** [mitsuba-renderer/mitsuba2#552]
*Please add one of the following label to your issue's title, and delete this section:*

- [🐛 bug report]
- [🔨 compilation issue]
- [✨ feature request]
- [❔ other question]

## Summary

After I completed the compilation instructions, I tried running the mitsuba executable, and get the error, "terminating with uncaught exception of type std::runtime_error: ​[Profiler] profiler_start(): failure in setitimer(): Invalid argument
Aborted (core dumped)"

## System configuration

- Platform: Ubuntu 18.04.6
- Compiler: CMake/Clang
- Python version: Python 3.9.7
- Mitsuba 2 version: newest
- Compiled variants:
    * `scalar_rgb`
    * 'scalar_spectral'
    * 'packet_rgb'

## Description

After I performed repository clone and compilation steps, I attempted the run mitsuba scene.xml, and the aforementioned error would occur. I even ran mitsuba --help and the same error would pop up. I redid the steps 4 times and the same issue came up. 

## Steps to reproduce

*For bug report, please enumerate the steps to follow in order to reproduce the issue <- [remove this]*

1. cloned repository
2. git pullall
3. sudo apt the tools
4. edit ./bashrc files
5. created the build directory and ran cmake -GNinja ..
6. ran ninja
7. ran mitsuba scene.xml
8. Error message

**Comment by Speierers** [comment]
Hi @Vmbundu ,

What version of clang and cmake are you using here?

**Comment by Vmbundu** [comment]
clang: clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)
cmake: cmake version 3.10.2

**Comment by Speierers** [comment]
Could you try with a more recent version of cmake (wiping the `build` directory first)?

**Comment by Vmbundu** [comment]
Hi, I was able to update cmake to  3.22.1, but the problem still still persist after I retraced my steps.

**Comment by Speierers** [comment]
Ok, and one last request: could you compile in debug mode to see whether the problem persists? You might also get more information when it crashes.

**Comment by Vmbundu** [comment]
Hi, I ran cmake in debug mode and I got a far amount of warnings. The messages said "Poilcy CMP0102 is not set" and the other said the same thing but with CMP0112. I also ran mitsuba in gdb, and said that it couldn't find the "libc-start.c" file. More specifically, it said .......

288         Class::static_shutdown();
(gdb) n
289         Jit::static_shutdown();
(gdb) n
293         return error_msg.empty() ? 0 : -1;
(gdb) n
294     }
(gdb) n
__libc_start_main (main=0x40a010 <main(int, char**)>, argc=1, argv=0x7ffffffedd18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffffffedd08) at ../csu/libc-start.c:344
344     ../csu/libc-start.c: No such file or directory.
(gdb) n
[Inferior 1 (process 2691) exited normally]
(gdb)
