### ISSUE TITLE
[❔ other question] Custom rendering pipelines in Python: function calls on batches of SurfaceInteractions seem to throw errors

### ISSUE THREAD

**Issue by ArnoCo** [mitsuba-renderer/mitsuba2#556]
## Summary

Function calls on a packet of SurfaceInteractions seem to throw errors when used in a Python environment.

## System configuration

- Platform: Ubuntu 20.04
- Compiler: gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
- Python version: 3.16.13
- Mitsuba 2 version: v2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`

## Description

I'm extending some previously written `scalar_rgb` code to a packet version and I seem to have hit a wall. When I try to call a function on a batch of surface interactions, I get the following error:

```python
Unable to convert function return value to a Python type! The signature was
	(self: mitsuba.render.SurfaceInteraction3f, scene: mitsuba.render.Scene, active: enoki.dynamic.Mask = True) -> 
enoki::DynamicArray<enoki::Packet<mitsuba::Emitter<enoki::Packet<float, 8ul>, mitsuba::Color<enoki::Packet<float, 8ul>, 3ul> > 
const*, 8ul> >
```

The example code (which worked in the scalar variant) could look like this:

```python
 for its in intersections:
    if its.emitter(scene) is not None:
        pass # do something
```

or 

```python
emitters = intersections.emitter(scene)
```

Both of which throw the same error. It is worth noting that the example given in the documentation: `result = surface_interaction.t` does work and returns the correct values. I'm not sure if I'm misunderstanding how I should use this variant or if this could be a potential bug in Mitsuba 2 (or in Enoki).

**Comment by Speierers** [comment]
Could you maybe try to pass a `True` argument to it? e.g. `its.emiter(scene, True)`

**Comment by ArnoCo** [comment]
I have tried this, and this does not fix the issue.

**Comment by ArnoCo** [comment]
I just discovered that compiling the `gpu_rgb` variant does allow me to evaluate these kind of expression. Concretely this call `        emitters = intersections.emitter(scene)` does return something sensible.

**Comment by ArnoCo** [comment]
I've currently moved to using `gpu_rgb` as that does meet my requirements, on my end this can be closed.
