### ISSUE TITLE
- [❔ other question] How to render the normal map related to the camera's  view 

### ISSUE THREAD

**Issue by s1752729916** [mitsuba-renderer/mitsuba2#557]
## Summary

How to render the normal map related to the camera's  view 

## Description

I used `aov` integrator
```
` <integrator type="aov">
  <string name="aovs" value="dd.y:depth,nn:sh_normal"/>
 </integrator>`
```
 but the rendered normal map seems to have nothing to do with the camera's angle of view. just like these:
 <img src="https://user-images.githubusercontent.com/42924289/148647739-758b89cb-5cae-4ae6-ae8a-45058658b201.png" width = "300" height = "300" alt="080"  />
 <img src="https://user-images.githubusercontent.com/42924289/148648109-098db196-073a-4527-8895-dc69af7ee8a7.png" width = "300" height = "300" alt="180"  />

I want to get the normal map related to the camera's view as shown in following two pictures. Is there any way to achieve this?  
 <img src="https://user-images.githubusercontent.com/42924289/148648003-2196cc61-d838-40ee-8034-84e880443c9a.png" width = "243" height = "204" alt="180"  />
 <img src="https://user-images.githubusercontent.com/42924289/148648132-ef65130f-df34-42cf-84fa-e786d457ec6b.png" width = "243" height = "204" alt="180"  />

**Comment by Speierers** [comment]
For this you can simply add a custom AOV in the `aov.cpp` integrator. That aov would output the transformed shading normal in camera space I suppose.
