### ISSUE TITLE
- [🔨 compilation issue] “ssize_t”: undeclared  identifier 

### ISSUE THREAD

**Issue by pixiaonuo** [mitsuba-renderer/mitsuba2#558]
## Summary
I am using Window. When I try to build the project in VS2019, it shows an error: error C2065 “ssize_t”: undeclared  identifier and error C2338 “ssize_t”: undeclared  identifier.  Please how can I solve this problem

![20220112063414](https://user-images.githubusercontent.com/26535108/149078809-10298f6c-cfef-4c0d-b67d-3445a85179be.jpg)

**Comment by LeonardoHoltz** [comment]
I had this issue too. If anyone managed to solve it, please share.

**Comment by Speierers** [comment]
This will be fixed in the upcoming release :)
