### ISSUE TITLE
The function load_file() (from mitsuba.core.xml) does not work if it is called after some specific Python imports

### ISSUE THREAD

**Issue by GuillaumeZahnd** [mitsuba-renderer/mitsuba2#560]
- [🐛 bug report]

## Summary

The function ``load_file()`` (from: ``mitsuba.core.xml``) needs to be called prior to some specific Python ``import``'s, otherwise it fails to execute correctly.

## System configuration

- Platform: Linux Ubuntu 20.04
- Compiler: cmake version 3.16.3
- Python version: 3.8.10
- Mitsuba 2 version: Supposedly the most recent (due to ``git pullall``), please kindly indicate how to identify the Mitsuba 2 version.
- Compiled variants: ``scalar_mono``

#### Essence of the problem

1. When the function ``load_file()`` is called prior to some specific Python ``import``'s, the function executes correctly.
2. When the function ``load_file()`` is called after some specific Python ``import``'s, the function fails to execute correctly.
3. The identified culprit imports (which must be imported after ``load) are:

```sh
import matplotlib.pyplot as plt
from libraries.mitsuba2.src.visualization.scene_visualization import visualize_scene, visualize_scene_rays, visualize_scene_ray_paths
```

4. The error is:
```sh
RuntimeError: ​[xml.cpp:223] Error while loading "PATH_AND_NAME_OF_MY_XML_SCENE.xml" (at line 10, col 3): 
[xml.cpp:223]   [xml.cpp:223] Error while loading "PATH_AND_FILE_NAME_OF_MY_PROBE_FILE.xml" (at line 9, col 7): could not parse floating point value "-0.04"..
```

#### Looking at the first lines of the corresponding "MY_XML_SCENE.xml" file (until the error is triggered):

```sh
<scene version="2.0.0">
    
    <!-- Define basic path tracer modeling maximum of 7 scattering events -->
    <!-- integrator type="path"-->
	<integrator type="path_ultrasound">
	    <integer name="max_depth" value="5"/>
    </integrator>

	<!-- Include sensors & emitter from file -->
	<include filename="PATH_AND_FILE_NAME_OF_MY_PROBE_FILE.xml"/> # <--- [Line 10 (reported in the error)]
```

#### Looking at the first lines of the corresponding "MY_PROBE_FILE.xml" file (until the error is triggered):

```sh
<scene version="2.0.0">
  <default name="sample_count_transducers" value="5000000"/>
  <default name="r_focus_detector" value="0.04"/> # <--- [This value cannot be parsed (reported in the error)]

  <!-- Define detector consisting of transducer array-->
  <shape type="ply">
    <string name="filename" value="PATH_AND_FILE_NAME_OF_MY_PLY_FILE.PLY"/>
    <transform name="to_world">
    	<translate x="0" y="0" z="-$r_focus_detector"/> # <--- [Line 9 (reported in the error)]
```

#### Looking at the relevant lines of ```mitsuba.conf```

```sh
"enabled": [
  # The "scalar_rgb" variant *must* be included at the moment.
  "scalar_rgb",
  "scalar_spectral",
  "scalar_mono",
  "packet_mono",
  "scalar_rgb_double",
  "scalar_spectral_double",
  "scalar_mono_double",
  "packet_mono_double"
]
```

#### Trying to replace the culprit numerical value in "MY_PROBE_FILE.xml":

Setting ``<default name="r_focus_detector" value="4"/>`` (namely, to an integer value) instead of ``<default name="r_focus_detector" value="0.04"/>`` allows the script to successful parse this line, but the error is triggered at the next occurrence of a float value.

### Steps to reproduce for successful execution of the ``load_file()`` function

1. At the very top of the main Python script, import the modules that are strictly needed to load the scene

```sh
import os
import mitsuba
from mitsuba.core import Thread
from mitsuba.core.xml import load_file
```

2. Set the variant

```sh
mitsuba.set_variant('scalar_mono')
```

3. Append the scene to the search path of FileResolver

```sh
Thread.thread().file_resolver().append(os.path.dirname(PATH_AND_FILE_NAME_OF_MY_XML_SCENE.xml))
```

4. Load the scene into mitsuba

```sh
scene = load_file(PATH_AND_FILE_NAME_OF_MY_XML_SCENE.xml) # < --- [This works fine]
```

5. Then continue down the Python script, and the ray tracing routines:

```sh
# //... Successfully import all other required Python/Mitsuba/Enoki modules
# //... Successfully run the ray tracing simulation and obtain results
```

### Steps to reproduce for erroneous execution of the ``load_file()`` function

1. At the very top of the main Python script, import all modules

```sh
# THESE CAN BE IMPORTED BEFORE LOADING THE SCENE
import os
import time
import numpy as np
import enoki as ek
import mitsuba
from mitsuba.core import Thread
from mitsuba.core.xml import load_file
from mitsuba.core import Float, UInt32, UInt64, Vector2f, Vector3f, Point3f

# THESE CANNOT BE IMPORTED BEFORE LOADING THE SCENE
import matplotlib.pyplot as plt
from libraries.mitsuba2.src.visualization.scene_visualization import visualize_scene, visualize_scene_rays, visualize_scene_ray_paths
```

2. Set the variant

```sh
mitsuba.set_variant('scalar_mono')
```

3. Append the scene to the search path of FileResolver

```sh
Thread.thread().file_resolver().append(os.path.dirname(PATH_AND_FILE_NAME_OF_MY_XML_SCENE.xml))
```

4. Load the scene into mitsuba

```sh
scene = load_file(PATH_AND_FILE_NAME_OF_MY_XML_SCENE.xml) # < --- [This returns an error]
```

**Comment by wjakob** [comment]
This is very likely by locale changes done by the other import. It will be fixed in an upcoming version that switches to locale-independent floating point parsing. In the meantime, you could recompile mitsuba with
```
 setlocale(LC_NUMERIC, "C");
 ```
patched into the implementation of `load_file`.

**Comment by GuillaumeZahnd** [comment]
Thanks,
My attempt to fixing the problem did not work, the same error occurs.

Steps:

1. Add:

```sh
setlocale(LC_NUMERIC, "C");
```
within the ``main`` function of the file ``MY_GIT_REPO_FOLDER/libraries/mitsuba2/ext/pugixml/docs/samples/load_file.cpp``

2. Delete the ``build`` folder from ``MY_GIT_REPO_FOLDER/libraries/mitsuba2/``.
3. Recompile via:

```sh
mkdir build
cd build
cmake -GNinja ..
ninja
```

**Comment by wjakob** [comment]
It's the wrong file, you need `libcore/xml.cpp`.

**Comment by GuillaumeZahnd** [comment]
Thanks,
Adding:

```sh
setlocale(LC_NUMERIC, "C");
```

in the body of the function ``load_file`` that is located in ``mitsuba2 > src > libcore > xml.cpp`` does the trick.
