### ISSUE TITLE
- [🐛 bug report] Low GPU usage on low <integer name="samples_per_pass" /> values

### ISSUE THREAD

**Issue by AnasFX** [mitsuba-renderer/mitsuba2#568]
## Summary
to try to avoid the `out of memory` problem on GPU, usually it is advised to lower the resolution, or add this option to the integrator `<integer name="samples_per_pass" value="4"/>`.
The problem as I have read is about some problems with the `Enoki` library, that converts the code to a compatible GPU code, and it should be addressed in the next release.

Any news about this fix, cause the problem with using low `samples_per_pass` is that it creates very low work load for the GPU, and doesn't use its full potential. I don't know if this is a bug or a natural product from using lower `samples_per_pass`, but I hope to hear from you about this issue and about a fix to leverage all of the GPU full potential power.

Thank you very much for the awesome work, and I hope there is a fix for it in the horizon.
Best regards.

**Comment by Speierers** [comment]
Hi @AnasFX ,

Indeed this will no longer be a issue in the new upcoming codebase. Please wait for a little longer, we should be able to release soon.

**Comment by Mephisto405** [comment]
@Speierers Can we get a little more information (e.g., expected due date) on the upcoming codebase?

This is related to the issue https://github.com/mitsuba-renderer/mitsuba2/issues/489 closed several months ago.

**Comment by Speierers** [comment]
@Mephisto405 while I can't give your a specific date, I can tell you that we are making good progess on the upcoming release. Mostly polishing the last implementation details and writing documentation at the moment. We hope to be able to release it soon!

Thanks for your patience. We are working hard to make sure it was worth the wait 🚀
