### ISSUE TITLE
Unable to load .ply files from blender

### ISSUE THREAD

**Issue by abhinavvs** [mitsuba-renderer/mitsuba2#57]
Since inbuilt shape plugins like `rectangle`, `sphere`, etc., aren't compatible with the gpu_ variants, I created meshes (as .ply files) using blender and tried loading them into Mitsuba2. However, I keep getting the following error message: 
```python
RuntimeError: ​[xml.cpp:1057] Error while loading "hallway/hallway_scene_build.xml" (near line 139, col 3): could not instantiate shape plugin of type "ply": 
[xml.cpp:1057]   [PLYMesh] Error while loading PLY file "hallway_lights.ply": 
[xml.cpp:1057] [PLYMesh]   [PLYMesh] Trailing tokens after end of PLY file!
```
However, I am able to load some of the standard .ply files from the repository (like `mitsuba-data/ply/sphere.ply`). I can see that the `sphere.ply` and the .ply file I obtained from blender are of the same format. Here is the "hallway_lights.ply" (generated by blender):
```
ply
format ascii 1.0
element vertex 12
property float x
property float y
property float z
element face 3
property list uchar uint vertex_indices
end_header
-1.550000 -0.990000 -0.670000
-1.450000 -0.990000 -0.670000
-1.450000 -0.990000 1.330000
-1.550000 -0.990000 1.330000
1.450000 -0.990000 -0.670000
1.550000 -0.990000 -0.670000
1.550000 -0.990000 1.330000
1.450000 -0.990000 1.330000
-0.750000 -0.990000 1.550000
-0.750000 -0.990000 1.450000
0.750000 -0.990000 1.450000
0.750000 -0.990000 1.550000
4 0 1 2 3
4 4 5 6 7
4 8 9 10 11
```
It is a simple object comprised of 3 different rectangles. Could someone tell me what I am doing wrong? Should I change something with the way I generate my .ply files using Blender?

**Comment by Speierers** [comment]
I think the problem here is that you ply is a quadmesh (instead of triangular mesh), is that possible?

If this is the problem, then we should have better warnings in `PLYMesh`. Let me know!

**Comment by abhinavvs** [comment]
Yes, I think the .ply file Blender generates by default is a quadmesh (by looking at the last few lines in the .ply file above). Quadmeshes don't work with mitsuba2? If so, could you tell me how to generate triangular ply mesh on Blender (I can't find any resources on how to do that)?

Also, I see that there are new commits to the repository all the time. For staying up-to-date with the latest version of Mitusba, is it sufficient to simply do a `git pullall` as mentioned in the docs, or should I build and compile the software again as well?

Thanks for the help!

**Comment by Speierers** [comment]
You will need to apply the `Triangulate` modifier on your mesh in Blender.

You will need to build+compile after running `git pullall` in order to have the latest Mitsuba 2 version.
