### ISSUE TITLE
[❔ other question] Question Regarding Camera Model

### ISSUE THREAD

**Issue by DaoyiG** [mitsuba-renderer/mitsuba2#570]
## Summary
Thanks for the amazing project! I have 2 questions regarding the settings of the perspective camera model.  
1. I would like to know whether it's possible to set the perspective camera model with different ```fov```, e.g., different ```fov``` wrt ```x```-axis and ```y```-axis. 
2. I would like to know how to define ```principal_point_offset_x``` and ```principal_point_offset_y``` properly. E.g., given an image with ```W=612, H=512```, and the ```cx=303, cy=248```, if I directly set the ```principal_point_offset_x = cx``` and ```principal_point_offset_y = cy```, the rendered result is incorrect. Did I misunderstand the defination of ```principal_point_offset_x``` in the [documentation](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#sensors)?

**Comment by Speierers** [comment]
Hi @DaoyiG,

1. As explained in [the documentation](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#perspective-pinhole-camera-perspective), it is possible to define `fov` and `fov_axis` which lets you control how the `fov` value is used. Is this what you are looking for?

2. Could you explain futher what you are trying to achieve? What is the output you expected in your example, and what did you get?

**Comment by DaoyiG** [comment]
Hi @Speierers ,

Thanks for your reply, maybe I should make my question clearer.  

1. I would like to set **different** ```fov``` values wrt ```x-``` and ```y- axis```, but if I configure the _sensors_ in the xml file like following:  
```	
<float name="fov" value="86"/>  
<string name="fov_axis" value="x"/>
<float name="fov" value="75.83"/>
<string name="fov_axis" value="y"/>
```
I would get an error ```[properties.cpp:372] Property "fov" was specified multiple times!.```  Hence, I would be grateful to know how to configure ```fov``` values wrt ```x-``` and ```y- axis``` separately.   

2. I assume the default ```cx``` and ```cy``` values are calculated as half of the image width and height, but I would like to configure those values to match the calibration results of my real camera, which are different than the half of image width and height. In this case, if I directly set the real ```cx``` and ```cy``` values to ```principal_point_offset_x``` and ```principal_point_offset_y```, the rendered results are incorrect. Hence, I would like to know how to set those values correctly.

**Comment by Speierers** [comment]
1. I see now. Unfortunately you can't specify them directly. However as the ratio between the two will depend on the aspect ratio of your film, with a little bit of math, you should be able to compute the right `diagonal` fov value for a target `x-fov` and `y-fov`.

2. As those values are offset, their default values are `0.0` (e.g. don't apply any offset). If you are using a different convention, you could try to substract half of the image width and height to `cx` and `cy` in order to get what you want?

**Comment by DaoyiG** [comment]
Thanks for the hint!

1. I think I solve the first issue by setting the diagonal fov value to  <img src="https://render.githubusercontent.com/render/math?math=fov_{diag}=2*arctan(sqrt(w^{2} %2B h^{2}) /(2*(0.5*(f_x %2B f_y))))">, do you think this is the correct format?
2. I tried to set ```principal_point_offset_x``` to ```w/2 - cx``` and ```principal_point_offset_y``` to ```h/2 - cy```, but the rendered result is still incorrect. It seems the change is way too large even if I only intend to change a few pixel shifts.

**Comment by Speierers** [comment]
2. Looking at the implementation, you might need to divide by the film resolution?

**Comment by DaoyiG** [comment]
Thanks! Now I think the issue is solved.
