### ISSUE TITLE
[❔ other question]

### ISSUE THREAD

**Issue by inversetrs** [mitsuba-renderer/mitsuba2#571]
thanks for the amazing work. 

I am trying to compile the pathparam-optix7 branch, with the  ptracer integrator and directionalarea emmiter (found some breadcrumbs in the issues) to build an application on top of the caustic optimization example, however, I now see the status "Due to the awkward and uncertain status of this project, we decided to take it offline for the time being. April 28, 2021" does it mean the project continuation is uncertain?

**Comment by Speierers** [comment]
@inversetrs for futur issues, could you please add a proper issue title. This will increase your chances to have us taking a look it ;)

**Comment by Speierers** [comment]
The upcoming release will have a proper implementation of the ptracer as well as a caustic optimization example script. So you will need a little longer to be able to play with it unfortunately.

Not that for this specific task, you do not need a full "reparameterized" integrator.
