### ISSUE TITLE
[❔ other question] Camera poses optimisation

### ISSUE THREAD

**Issue by waytobehigh** [mitsuba-renderer/mitsuba2#573]
A quick question: do you guys plan to implement camera poses optimisation in the upcoming release? I didn't managed to find the answer in release notes.

**Comment by Speierers** [comment]
Hi @waytobehigh ,

The upcoming release will contain the implementation of a "reparameterization path tracer" to handle visibility discontinuities, but camera optimization will likely not be supported right away unfortunately. This is high on our TODO list tho.

**Comment by waytobehigh** [comment]
Thank you for clarifying!
