### ISSUE TITLE
[🔨 compilation issue] Git submbodules not included in release

### ISSUE THREAD

**Issue by notklaatu** [mitsuba-renderer/mitsuba2#576]
I've downloaded v2.2.1 from the release page, and when I try to compile, I'm told that I should have Git cloned recursively:

```bash
$ cmake -GNinja ..
[...]
CMake Error at CMakeLists.txt:18 (message):
  The Mitsuba dependencies are missing! You probably did not clone the
  project with --recursive.  It is possible to recover by invoking

  $ git submodule update --init --recursive
```

## System configuration

- Platform: Linux x86_64
- Compiler: clang 13
- Mitsuba 2 version: 2.2.1

## Steps to reproduce

```bash
$ wget https://github.com/mitsuba-renderer/mitsuba2/archive/v2.2.1/mitsuba2-2.2.1.tar.gz
$ tar xvf mitsuba2-2.2.1.tar.gz && cd mitsuba2-2.2.1
$ mkdir build && cd build
$ cmake -GNinja ..
```

Unfortunately, the suggested resolution doesn't work. No Git submodules are pulled, I assume because this wasn't a Git checkout but a release download.

I'd expect a release tarball to contain everything required to build.

**Comment by Speierers** [comment]
Hi @notklaatu ,

Unfortunately think is not going to happen on this version of the codebase. You need to pull (recursive) the repository using Git and not use the release tarball.
