### ISSUE TITLE
❔ Freestanding sensor for lens simulation , and dispersion

### ISSUE THREAD

**Issue by peroveh** [mitsuba-renderer/mitsuba2#577]
I am considering using Mitsuba2 for lens simulation, where the lens is given by a stack of defined lens elements with given shape and glass type (and an enclosure?). Now i would like to put a sensor in the focal plane...i.e. I dont want to put the normal  "camera" there (pinhole or thin lens), but a plain RGB bayer pattern sensor with given pixel size, well size etc.. How is this best achieved?
Also: In the documentation i noted that dispersion is said to be a future feature. Any thoughts on when?

Looking forward to

**Comment by Speierers** [comment]
Hi @peroveh,

Sounds like you will need to implement your own `sensor` plugin for this. You could also try doing everything from Python (e.g. sensor and integrator implemented in a Python directly, bypassing the plugin system).

Regarding dispersion, this isn't on our radar at this point, there are many other things we need to focus on before getting to it. This being said, if you are intetested in dispersion, feel free to work on your own implementation and submit a PR with your code. We will be more than happy to review it and get it into shape to later include it in the main codebase.

Good luck!
