### ISSUE TITLE
❔ Modelling lenses II

### ISSUE THREAD

**Issue by peroveh** [mitsuba-renderer/mitsuba2#578]
Thanks for previous comments.
Can mitsuba2 model lenses by 3D subtracting geometry (for example a cylindrical cut-out of a sphere, an intersection of two spheres etc)?

If only surface description: Can it model surfaces using the zemax description (sphere + even order polynomial describing the z dimension as fn of r) OR do we have to use either PLY or mesh representation of the surface? 

Do you have any examples of a scene with such a smooth radially symmetric object. I saw an translucent egg in one of your publications... Is the description file for this object available somewhere? (I could not find anything in the files from the mitsuba2 download

**Comment by Speierers** [comment]
Hi @peroveh,

Lenses from geometry (or surface descriptors) is not supported in Mitsuba 2, but you should be able to implement your own sensor plugin that does so.

Regarding the egg shape translucent object, you might be able to find it in one of those scenes:

https://benedikt-bitterli.me/resources/

**Comment by peroveh** [comment]
Hi Speierers...Thx for reply.. I tested one of the scenes you pointed to. Do you know if these are for mitsuba or mitsuba-2 ?

**Comment by Speierers** [comment]
These are for Mitsuba 0.6 but you should be able to adapt them easily for Mitsuba 2. Let me know if you are struggling with this.

**Comment by peroveh** [comment]
> These are for Mitsuba 0.6 but you should be able to adapt them easily for Mitsuba 2. Let me know if you are struggling with this.
Hi ... Yes struggeling a bit here. As a test case trying to import a scene defined by a set of two .obj, .mtl files (found from one of the elements , a  
Chocofur_Free_Lamp, which is used in a larger scene.
It does not appear that any automatic search for the usemtl material tags in the .mtl file. In fact I cannot see that it is opened at all in the mitsuba2 code.

**Comment by Speierers** [comment]
`mtl` files aren't supported in Mitsuba. You will need to define the materials in the XML file yourself.
