### ISSUE TITLE
[🐛 bug report] tbb.dll is not found 

### ISSUE THREAD

**Issue by kirdaybov** [mitsuba-renderer/mitsuba2#579]
## Summary

Mitsuba compiles (but not all projects), but when I try to run it from Visual Studio the window appears saying `The code execution cannot proceed because tbb.dll was not found. Reinstalling the program may fix the problem.`

Running from a command line leads to the same window plus consequent windows showing that other .dlls are also not found (mitsuba-render.dll and mitsuba-core.dll).

I'm not sure it's related, but I also have compile errors like these: `error C2065: 'ssize_t': undeclared identifier (compiling source file C:\work\mitsuba2\src\libcore\python\rfilter.cpp)`. Some of the project won't build because of that, see the full [log](https://github.com/mitsuba-renderer/mitsuba2/files/8245789/compile_errors.txt).

## System configuration

- Platform: Windows 10
- Compiler: msvc (visual studio 2019 v142)
- Python version: 3.10.0
- Mitsuba 2 version: master, v2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`

## Description

All in the summary

## Steps to reproduce

1. Follow the compile steps described in the documentation on Windows.
2. When choosing the version select scalar_rgb or packet_rgb
3. Compile the whole solution (notice the compilation errors)
4. Run the program (notice .dlls not found windows)

**Comment by Speierers** [comment]
Hi @kirdaybov ,

I am intrigued by the following error in your log: `error C2338: ssize_t != Py_intptr_t`. Could you try with a more recent version of MSVC?

**Comment by kirdaybov** [comment]
Hi @Speierers,

The documentation mentioned that the tested version is Visual Studio 2019 16.4.5 (mine is 16.10.3) and v142 is the most recent toolset available for it. Do you want me to try to compile in VS2022 with v143 toolset?

**Comment by Speierers** [comment]
Yes, the documentation might be outdated, please give a try at VS2022.

**Comment by Andyfanshen** [comment]
> Hi @kirdaybov ,
> 
> I am intrigued by the following error in your log: `error C2338: ssize_t != Py_intptr_t`. Could you try with a more recent version of MSVC?

I fixed the error by adding a line code at the top of the "numpy.h" : "typedef SSIZE_T ssize_t;"

**Comment by Andyfanshen** [comment]
> I'm not sure it's related, but I also have compile errors like these: `error C2065: 'ssize_t': undeclared identifier (compiling source file C:\work\mitsuba2\src\libcore\python\rfilter.cpp)`. Some of the project won't build because of that, see the full [log](https://github.com/mitsuba-renderer/mitsuba2/files/8245789/compile_errors.txt).

I fixed the error by adding a line code at the top of the "numpy.h" : "typedef SSIZE_T ssize_t;"

**Comment by TSaber7** [comment]
I also have the same error and it seems because ssize_t is not defined on Windows, finally I fix it by adding some code at the top of "numpy.h" like :
#include <BaseTsd.h> 
typedef SSIZE_T ssize_t;
