### ISSUE TITLE
replace __OSX__ as __APPLE__

### ISSUE THREAD

**Issue by yangfengzzz** [mitsuba-renderer/mitsuba2#58]
I find __OSX__ is not recognized by Xcode in macOS Catalina, It is better to use __APPLE__ as the flag for MacOS[Which macro to wrap Mac OS X specific code in C/C++](https://stackoverflow.com/questions/2166483/which-macro-to-wrap-mac-os-x-specific-code-in-c-c)

**Comment by wjakob** [comment]
We define ``__OSX__`` ourselves (along with ``__LINUX__`` and ``__WINDOWS__``) in ``CMakeLists.txt``.
