### ISSUE TITLE
[❔ other questions] about the area ouside of optimization in the caustic examples 

### ISSUE THREAD

**Issue by inversetrs** [mitsuba-renderer/mitsuba2#583]
The result before the optimization converges and the areas outside of the optimization is very interesting. I haven’t seen that in other caustic optimization methods, and am looking forward to experiment with it. 

They behaved differently in the three examples, any ideas why the BW had such small bleeding compared to the two color and RGB images? 

What would happen if one optimizes to a Black Square? 

Would it make sense to use a image for the emitter with a rainbow spectrum, to simulate a diffraction grating to one side of the glass? 

Could it be possible to optimize for an area larger than the emiter ?

Could the same technique be used to optimize for a volume in space?

**Comment by merlinND** [comment]
Hi @inversetrs,

Indeed, the "light leak" patterns are very interesting!

1. I haven't checked this experimentally, but my intuition is that it's related to the overall brightness of the emitter vs the brightness of the target image. Possibly if the emitter is too bright, more light needs to be moved out of the zone of optimization.

2. Optimizing to match a  black square _could_ result in all of the light being redirected to the sides, but the optimization could also become stuck in a local minimum. For example, for the light rays at the center of the target square, moving them slightly in any direction wouldn't really improve the loss. Here, a coarse-to-fine approach should really help.

3. I think so.

4. Yes definitely, the camera can be placed arbitrarily, and anything within the viewport (i.e. part of the image) will be optimized for. It's even possible to add multiple cameras, if it makes sense in your application.

5. We do have volume optimization examples in the Mitsuba 2 paper and subsequent papers. If you mean optimizing for a volumetric caustic, in principle it should be possible but we've never tried. The first issue is that the particle tracer integrator does not support volumes so it would need to be extended. Also, depending on the scene it could become costly to render converged-enough volumetric caustics at each iteration.

I hope this helps!
