### ISSUE TITLE
[Bug Report] a_p in the fresnel term

### ISSUE THREAD

**Issue by elite-sheep** [mitsuba-renderer/mitsuba2#585]
Hello, when I read the code today, I found `a_p` in `frsenel` term is different from that in `fresnel_polarized`. According to my knowledge, `a_p` here should still be `\frac{abs(cos_i)*eta_it-cos_t}{abs(cos_i)*eta_it+cos_t}`. Do we have a typo here?

**Comment by njroussel** [comment]
Hi,

In Enoki, `fnmadd` is equivalent to `-fmsub` we're therefore computing the negative of the term you mentionned:
`frac{-(abs(cos_i)*eta_it-cos_t)}{abs(cos_i)*eta_it+cos_t}`
This doesn't matter as we're squaring the term to to compute `r`.

I doubt there is a performance benefit to this, but rather that it has a nice symmetry with the `a_s` term.
Either way, I don't believe that there is a bug here.
