### ISSUE TITLE
 [❔ other question] where can I find bunny.xml used for the example in the documentation?

### ISSUE THREAD

**Issue by JungShinPlusPlus** [mitsuba-renderer/mitsuba2#586]
Hi. I just want to try some examples and
the example
**mitsuba2\docs\examples\10_inverse_rendering\invert_bunny.py**
uses 
**bunny.xml**
but I cannot find this. Can anyone tell me where I can find it please?

**Comment by Speierers** [comment]
You can find it in [this folder](https://github.com/mitsuba-renderer/mitsuba-data/tree/23350ff0c9d82820d7721b86a35c84f8f520d720/common/meshes)

**Comment by JungShinPlusPlus** [comment]
Hi @Speierers, thanks for the fast feedback but the folder only has bunny.ply just mesh
while the example uses "**bunny.xml**"
where the example uses parameters in bunny.xml

param_res = params['my_envmap.resolution']
param_ref = Float(params['my_envmap.data'])

so I don't think I can run the example with it or is there something I'm missing?

**Comment by Speierers** [comment]
Sorry I didn't realize you were looking for the scene.

According to the [documentation page related to this example](https://github.com/mitsuba-renderer/mitsuba2/blob/pathreparam-optix7/docs/src/inverse_rendering/advanced.rst) you should be able to download the scene [here](http://mitsuba-renderer.org/scenes/bunny.zip).

**Comment by owaranainatsu** [comment]
> 

Sorry I cannot click in this link.

**Comment by Speierers** [comment]
If the link doesn't work for you, maybe you can try using a different mesh / scene? All you need for this example is a scene with a `envmap` with the `id="my_envmap"` and a shiny object in the center to reflect the envmap, e.g. using a `conductor` BSDF.
