### ISSUE TITLE
[✨ feature request]Is there an interface that I can access the texel according to the `uv coordinate`?

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2#589]
Hello, I am trying to access texel according to `uv coordinate`. Is there an interface that can do this conveniently?

**Comment by Speierers** [comment]
Hi @HsiangYangChu ,

Could you be a little more specific? For instance it would be great if you could provide a snippet of code with what you have tried so far and better illustrate what you are trying to achieve here.

**Comment by HsiangYangChu** [comment]
Thank you for your quick reply!
Specifically, you were experimenting with the `roughconductor BSDF plugin`. I can access the `uv coordinate` of a group of vertex, and a specular texture map which is 1024*1024*3, I want to get the `specular coefficients` of each vertex. So, is there an interface provided by `mitsuba2` that can do this conveniently?

**Comment by Speierers** [comment]
What I would do is the following:

1. Get the `vertex_uv_coordinates` buffer of the mesh
2. Construct a `SurfaceInteraction3f` with those uvs
3. Evaluate the BSDF / texture using this `SurfaceInteraction3f`

The result of this will be the value of the BSDF / texture at every vertices of your mesh.

**Comment by HsiangYangChu** [comment]
Thanks!!!!
