### ISSUE TITLE
Differentiating w.r.t transformation parameters 

### ISSUE THREAD

**Issue by abhinavvs** [mitsuba-renderer/mitsuba2#59]
This is slightly related to #26. 

I have a problem where I want to differentiate w.r.t the orientation of a given object in the scene, i.e. it's `translate`, `scale`, and/or `rotation` values. 

However, if I do `traverse(scene)`, I am not able to see these are separate parameters (I guess they are baked into the `__.vertex_positions` and `__.vertex_normals` parameters. Is this something that can be easily done in Mitsuba2 with the introduction of the new plugin mentioned in #26? 

This will be very useful for me as I need derivatives w.r.t actual values of these transformations (they are the parameters of interest in my model) and not just the vertex positions, normals, etc., for my application. 

Any insights on this would be great! Thanks in advance!

**Comment by Speierers** [comment]
Hi @abhinavvs ,

Indeed this is not possible at the moment but we are working on it in PR #44.

Keep an eye on this PR 😉
