### ISSUE TITLE
[❔ other question] is pre_render_callback callback removed?

### ISSUE THREAD

**Issue by JungShinSoulmachine** [mitsuba-renderer/mitsuba2#590]
## Summary

I was trying some example and some of them has 
'pre_render_callback' however, when I run it I get

 image = render(scene,
TypeError: render() got an unexpected keyword argument 'pre_render_callback'

## System configuration

Mitsuba version 2.2.1 (master[4e7628c6], Windows, 64bit, 24 threads, 8-wide SIMD)
Copyright 2020, Realistic Graphics Lab, EPFL
Enabled processor features: cuda avx2 avx fma f16c sse4.2 x86_64

**Comment by Speierers** [comment]
Which example are you referring to?

**Comment by JungShinSoulmachine** [comment]
https://github.com/mitsuba-renderer/mitsuba2/blob/70af33ff4d69e6d14205f1826d63c9cf0bdcb639/docs/examples/10_inverse_rendering/invert_pose.py

which is not the latest one I think. (invert_pose.py example is not in the latest branch)
so I assumed it is gone but I was wondering if there is equivalent feature like the 
"pre_render_callback"

**Comment by Speierers** [comment]
Did you try to checkout the `pathreparam-optix7` branch? This branch implement a integrator that properly compute visibility gradients (e.g. when optimizing the pose of an object). You will need this to run this tutorial.

All of this will be properly handled in the upcoming version of the codebase by the way. This code is quite old and not well maintained unfortunately.

**Comment by JungShinSoulmachine** [comment]
Thank you @Speierers. I'll try pathreparam-optix7.
and looking forward to see the new version as well :)
