### ISSUE TITLE
❔ mitsuba2\dist\python\mitsuba is empty after compiling and some .dll files not found

### ISSUE THREAD

**Issue by Li-Jiren** [mitsuba-renderer/mitsuba2#591]
## Summary

When installing mitsuba2, mitsuba2\dist\python\mitsuba is empty after compiling, so I cannot import it in python.
Some .dll files not found when trying to run mitsuba.exe

## System configuration

- Platform: Windows 10
- Compiler: MSVC (VS 2022)
- Python version: 3.9.8
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    "scalar_rgb",
    "gpu_autodiff_rgb"

## Description

I am not sure whether these errors or warnings are problems:

1. When I run `cmake -G "Visual Studio 17 2022" -A x64`, it gives the following warning:

```
CMake Warning (dev) in ext/enoki/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "enoki-cuda".
This warning is for project developers.  Use -Wno-dev to suppress it.
```

2. When I compiled and built the project in Visual Studio, all 27 items succeeded. However, when it tries to run mitsuba.exe automatically, several system errors occurred, which says:
`The code execution cannot proceed because tbb.dll was not found`, and the same for 'mitsuba-render.dll' and 'mitsuba-core.dll'.

I used `git clone --recursive` to clone the repository, I don't know why these .dll files are missing.

## Steps to reproduce
Follow the steps in the documentation to install mitsuba2.

**Comment by Speierers** [comment]
Please make sure you compiled every target presents in the VS solution. You can also tried to compile directly using cmake, e.g. running:
```bash
cmake --build --config Release ..
```

**Comment by Li-Jiren** [comment]
Thank you!
