### ISSUE TITLE
CUDA_malloc out of memory!

### ISSUE THREAD

**Issue by jakoaltrd** [mitsuba-renderer/mitsuba2#601]
I successfully built mitsuba2 with the gpu_autodiff_spectral variants:
    _"enabled": [
        # The "scalar_rgb" variant *must* be included at the moment.
        "scalar_rgb",
        "scalar_spectral",
        "gpu_autodiff_spectral",
        "gpu_autodiff_rgb"
    ],_
and run it with the command: _mitsuba -m gpu_autodiff_spectral cbox.xml -o autodiff.jpeg_then get the error:
Caught a critical exception: cuda_malloc(): out of memory!
cuda_shutdown()
then I change the film width to a small integer **300**
_integer name="width" value="300"
integer name="height" value="300"_
it works well, so how to solve this issue , specifications:
win10, cmake, python3.8 cuda11.4 rtx3070 vs2019 optix7.1
<img width="148" alt="捕获" src="https://user-images.githubusercontent.com/67615360/170719661-f5bff4dc-20fb-440d-b9f9-122844726ddc.PNG">
there are 8 gigabytes VRAM available, so gpu memory should not be the bottleneck.

**Comment by merlinND** [comment]
Hi @jakoaltrd,

Please have a look at previous issues related to this problem: https://github.com/mitsuba-renderer/mitsuba2/issues?q=is%3Aissue+out+of+memory

The solution is to render with fewer samples per pixel, lower resolution, or to use smaller value of `samples_per_pass` (it can be added to the `integrator`'s properties in the XML scene file).

The upcoming version of Mitsuba will allow rendering with a much smaller GPU memory footprint.

**Comment by MarisaKirisame** [comment]
Hi, I work on memory saving for autodiff, in particular gradient checkpointing. Are you interested in hearing more about how it work? I could give a talk on my work, dynamic tensor rematerialization, if you are interested about it.

**Comment by merlinND** [comment]
Hi @MarisaKirisame,

In the context of differentiable rendering, we were able to modify the algorithm so that it inherently uses less memory ([Radiative Backpropagation](https://rgl.epfl.ch/publications/NimierDavid2020Radiative)) and relies on AD only very locally, which means that we don't have to create large graphs.

That being said it's always interesting to read about other techniques, would you have a paper or writeup available on that topic?
