### ISSUE TITLE
Any reason why anisotropy is not supported? [❔ other question]

### ISSUE THREAD

**Issue by anderslanglands** [mitsuba-renderer/mitsuba2#606]
The glossy BSDFs throw if the alpha parameters are detected to be anisotropic. Is it just that anisotropy has not been implemented or is there a deeper reason why this is not supported? i.e. if I implemented the necessary adjustments to sample, eval and pdf, would it work or would something else break?

**Comment by Speierers** [comment]
I suppose you are talking about the `roughplastic` BSDF?

Indeed for this one anisotropy isn't supported yet. This BSFD relies on precomputed tables that would be too expensive to compute for two axis. You will need to switch to `roughconductor` or `roughdielectric` if you really need anisotropy.
