### ISSUE TITLE
Data at each bounce separately

### ISSUE THREAD

**Issue by UmarSpa** [mitsuba-renderer/mitsuba2#608]
Is it possible to access the data of different bounces (of the light path) individually?

**Comment by merlinND** [comment]
Hi @UmarSpa,

It may be more or less difficult depending on the variant that you are running (CPU or GPU), but I think a good place to start would be the main loop of the path tracer: https://github.com/mitsuba-renderer/mitsuba2/blob/83d1b180ac005d68b2ed5355bfdaef223374a17a/src/integrators/path.cpp#L124-L208

There you could add code to e.g. copy or save out the information that you are interested in at each bounce.

**Comment by UmarSpa** [comment]
@merlinND is it possible to do this in python?

**Comment by merlinND** [comment]
This will become a lot easier in the upcoming release, as the Python interface makes it a lot easier to write e.g. custom integrator.

In the current version, maybe you could add an extra return value to the integrator, or e.g. provide a pointer to a buffer / struct to store the data you care about as an output argument? 

As far as I can tell the only pure-Python solution would be to implement a small path tracer in the spirit of this example:
https://github.com/mitsuba-renderer/mitsuba2/blob/83d1b180ac005d68b2ed5355bfdaef223374a17a/docs/examples/03_direct_integrator/direct_integrator.py
Then you can export whatever quantity you want at each bounce.
