### ISSUE TITLE
Using old and new versions of Mitsuba simultaneously

### ISSUE THREAD

**Issue by abhinavvs** [mitsuba-renderer/mitsuba2#61]
I want to render environment maps using the `envmap` sensor on the older version of Mitsuba (v1) since it is not supported in the new version, yet. However, I still want to use Mitsuba 2 for all its other cool features like differentiable rendering for other applications. 

How can I install both versions separately and switch between them? 
Thanks in advance for the help!

**Comment by Speierers** [comment]
Hi @abhinavvs,

Nothing prevents you from installing both renderer on your system and use them to your needs.

To my knowlegde, the python bindings are very different in Mitsuba 1 so you probably won't be able to switch easily between the two versions in a Python script. However, Mitsuba 2 should be compatible with Mitsuba 1 XML files so you will be able to switch easily in the command line.
