### ISSUE TITLE
[🐛 bug report] Directional lights not always working

### ISSUE THREAD

**Issue by RobinBruneau** [mitsuba-renderer/mitsuba2#610]
## Summary

I tried to render a scene including a sphere with a dielectric BSDF, a camera and a directional light, and the results is a black sphere.

## System configuration

- Platform: Windows 10
- Compiler: CMake 3.23.2
- Python version: 3.9.5
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    *  scalar_rgb
    * gpu_autodiff_rgb
    * packet_rgb

## Description

I tried to render a scene including a sphere with a dielectric BSDF, a camera and a directional light, and the results is a black sphere.
I tried the directional light is a diffuse BSDF sphere and the render is good, same for the dielectric BSDF spehre with an envMap.
But this special combination is not working.

## Steps to reproduce

Try to run the xml code below : 

<scene version="2.0.0">

	<shape type="sphere">
    		<point name="center" x="0" y="0" z="0"/>
    		<float name="radius" value="5"/>

		
		<bsdf type="dielectric">
        		<string name="int_ior" value="amber"/>
        		<string name="ext_ior" value="air"/>
    		</bsdf>
		<medium type="homogeneous" name="interior">
        		<rgb name="albedo" value="1.0, 0.66, 0.53"/>
    		</medium>
		
	</shape>

	<emitter type="directional">
    		<vector name="direction" x="0" y="0" z="-1"/>
		<spectrum name="irradiance" value="3.0"/>
	</emitter>

	<sensor type="perspective">
		<float name="fov" value="50"/>
    		<transform name="to_world">
        		<lookat origin="0, 0, 10" target="0, 0, 0"/>
        		<translate x="0" y="0" z="10"/>
   		</transform>

		<film type="hdrfilm">
            		<integer name="width" value="1920"/>
            		<integer name="height" value="1080"/>
        	</film>
	</sensor>

</scene>

**Comment by Speierers** [comment]
Hi @RobinBruneau ,

What integrator are you using? And what maximum number of bounces did you set?

**Comment by RobinBruneau** [comment]
I set nothing for the integrator and for the number of bounces.
Even when I tried with something like : 

<sampler type="independent">
            <integer name="sample_count" value="10"/>
</sampler>
<integrator type="path">
            <integer name="max_depth" value="10"/>
</integrator>

with "high" values like 10 to be sure to render the transmission and refractive lights, it's not working.

**Comment by merlinND** [comment]
If I understand correctly, you are trying to render a delta material (`dielectric`) with a delta light source (`directional`) and a delta sensor (`perspective`). This is not supported by either path tracers or particle / light tracers (fundamental limitation of the algorithms). One simple solution, if it's acceptable in your application, would be to replace either the BSDF or light source by a non-delta alternative (e.g. rough dielectric).
