### ISSUE TITLE
Can I change the parameter "to_world" in my python file?

### ISSUE THREAD

**Issue by JakeXin7** [mitsuba-renderer/mitsuba2#613]
[❔ other question]

## Description

I list the ParameterMap of camera,

ParameterMap[
    PerspectiveCamera.near_clip,
    PerspectiveCamera.far_clip,
    PerspectiveCamera.focus_distance,
    PerspectiveCamera.shutter_open,
    PerspectiveCamera.shutter_open_time
]

How can I render the scene with a new view direction?
Can I change the parameter "to_world" of the camera in my python file?

**Comment by Speierers** [comment]
Currently this parameter is not exposed in the parameter map. Instead you can instanciate another sensor using the `load_dict` function and use this new sensor for rendering.

**Comment by JakeXin7** [comment]
OK, thanks for help.
