### ISSUE TITLE
[🔨 compilation issue] How to set the python environment for compiling mitsuba?

### ISSUE THREAD

**Issue by JakeXin7** [mitsuba-renderer/mitsuba2#614]
## Description

I create a new python virtual environment by Anaconda. How can I set the environment as the compiling environment?

**Comment by merlinND** [comment]
Hi @JakeXin7,

Once your Anaconda environment is activated in a terminal, if you run `cmake` and your compiler commands in the same terminal, they should pick up that environment automatically.

More general build instructions are in the [documentation](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html).

**Comment by JakeXin7** [comment]
Thanks for reply!
But I've already tried this method before, it didn't work.

Like this:

activate mitsuba
(mitsuba) D:\study\CG\download\mitsuba2\build>cmake .. -G "Visual Studio 16 2019" -A x64

-- Found PythonInterp: C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0/python3.9.exe (found version "3.9.13")
-- Found PythonLibs: C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0/libs/Python39.lib

What's wrong with it?

**Comment by Speierers** [comment]
Did you try to build Mitsuba from the Anaconda terminal directly?

**Comment by merlinND** [comment]
Also, did you fully remove the `build` directory before activating the environment and running the `cmake` command? The caching can be quite persistent.

**Comment by JakeXin7** [comment]
Maybe there's something wrong with my Anaconda. I reinstall Anaconda and fix the problem. Thanks for help!
