### ISSUE TITLE
 [🐛 bug report] Shapegroup: NoneType has no attribute 'traverse'

### ISSUE THREAD

**Issue by jaroslavknotek** [mitsuba-renderer/mitsuba2#615]
## Summary

My goal is to use inverse rendering to calculare right parameters of an object that consist of several identical objects. To do that, I created scene where I grouped all the objects together so they would share the definition of the material I'd like to calculate parameters of.

When I create scene like that and render it with some dummy material, it works. However, when I try to traverse the scene. It crashes with this error

```
/tmp/ipykernel_78/3832233791.py in <module>
     49 scene = mitsuba.core.xml.load_dict(scene_dict)
     50 from mitsuba.python.util import traverse
---> 51 params = traverse(scene)
     52 print(params)

~/mitsuba2/build/dist/python/mitsuba/python/util.py in traverse(node)
    186 
    187     cb = SceneTraversal(node)
--> 188     node.traverse(cb)
    189 
    190     return ParameterMap(cb.properties, cb.hierarchy)

~/mitsuba2/build/dist/python/mitsuba/python/util.py in put_object(self, name, node)
    183                 depth=self.depth + 1
    184             )
--> 185             node.traverse(cb)
    186 
    187     cb = SceneTraversal(node)

~/mitsuba2/build/dist/python/mitsuba/python/util.py in put_object(self, name, node)
    183                 depth=self.depth + 1
    184             )
--> 185             node.traverse(cb)
    186 
    187     cb = SceneTraversal(node)

AttributeError: 'NoneType' object has no attribute 'traverse'
```

## System configuration

- Platform: unix in docker
- Compiler: n/a
- Python version: 3.7.13
- Mitsuba 2 version: HEAD of master from today (28.06.2022)
- Compiled variants:
    * `scalar_rgb`

## Steps to reproduce

Using the code that describes the scene from [this issue](https://github.com/mitsuba-renderer/mitsuba2/issues/607)(use the answer, not the question).

At the end of this code, add this snipped (which is, according to docs, crutial for inverse rendering)

```
from mitsuba.python.util import traverse
params = traverse(scene)
print(params)
```

Is there any work around this? Can I create the scene with multiple objects sharing the same material so the inverse rendering would be possible? The object I use are perfect cylinders so I don't want to triangulate them in some 3d editor and import all of them as a single model. (I would, but thats my last resort).

Thank you

**Comment by Speierers** [comment]
Hi @jaroslavknotek ,

This is a known bug and is already fixed in the upcoming version of the codebase.

Here is the patch if you would like to use it as a temporary solution.

![image](https://user-images.githubusercontent.com/6662561/176197836-56029182-5499-42ec-b6d1-bea5ddc1d3d5.png)
