### ISSUE TITLE
[❔ other question] How to use higher spp to render a scene in case cuda_malloc(): out of memory?

### ISSUE THREAD

**Issue by JakeXin7** [mitsuba-renderer/mitsuba2#619]
## Description

I want to use higher spp to render a scene for less noise. But "RuntimeError: cuda_malloc(): out of memory!" raised. Can I render the scene with higher spp?
For example, can I take more times to render the scene, each get a part of the target image?

**Comment by Speierers** [comment]
You can try to use the `samples_per_pass` property on the integrator to split the workload in multiple pass.

**Comment by JakeXin7** [comment]
OK, thanks for help!
