### ISSUE TITLE
Spherical Camera Implementation

### ISSUE THREAD

**Issue by garethwalkom** [mitsuba-renderer/mitsuba2#62]
Many thanks for Mitsuba 2, I'm loving it so far!

Are there any hopes for a spherical camera sensor like in Mitsuba 1?

Having this would help with viewing rendered images in VR.

**Comment by abhinavvs** [comment]
I was wondering the same thing too! So far I am considering using Mitsuba 1 just for `spherical` sensors and Mitusba 2 for everything else. It would be very useful if that feature can be ported to Mitsuba 2.

**Comment by Speierers** [comment]
There is no plan for it at the moment and we are already quite busy with other feature requests.

However, I would be happy to help and guide you porting the plugin from Mitsuba 1 in a PR. This would definitely befenit a lot of people in this community 😉

**Comment by garethwalkom** [comment]
@Speierers Ah, shame... I would love to do this; however, I also don't have much time right now... When I do and if it still hasn't been implemented, I'll get back to you on this :)
