### ISSUE TITLE
[❔ other question] Absorption/Scattering Coefficient in Mitsuba2

### ISSUE THREAD

**Issue by Vmbundu** [mitsuba-renderer/mitsuba2#620]
## Summary

Is there an ability to directly adjust a medium's absorption/scattering coefficient in Mitsuba2? 

## Description

I saw there were options to adjust the coefficients in the old mitsuba for homogeneous mediums and dipole subsurface scattering. In fact, I was wondering if we could make accurate skin renderings in mitsuba2? If so, what would be the proper approach?

**Comment by dvicini** [comment]
You will have to convert these paramters to sigmat and albedo. We only support providing volume parameters in this format.

We don't support the dipole subsurface scattering anymore, as it's a very inaccurate approximation of SSS and of limited practical use these days. Compared to when the dipole model was first introduced (20 years ago!), hardware has gotten fast enough to simply bruteforce SSS using path tracing (at least for a research renderer like Mitsuba - in production the tradeoffs might be different).

The proper approach to render skin is to use a participating medium enclosed by a rough dielectric boundary. What Mitsuba currently misses is a way to use a surface texture to drive the SSS parameters.
