### ISSUE TITLE
The porlarization example in the demo video

### ISSUE THREAD

**Issue by 774880930** [mitsuba-renderer/mitsuba2#622]
[❔ other question]
Recently I've been studying simulations of optical polarization,Do you have the XML file for the first optical polarization example in the demo video?

**Comment by merlinND** [comment]
Hello @774880930,

I don't have this scene file available, but perhaps this polarization tutorial from Mitsuba 3 helps?
https://mitsuba.readthedocs.io/en/latest/src/rendering/polarized_rendering.html

**Comment by tizian** [comment]
Here is the scene used for the car example:
[polarization-car.zip](https://github.com/mitsuba-renderer/mitsuba2/files/9158252/polarization-car.zip)

This is a modified version of a scene from [Benedikt Bitterli's rendering resources](https://benedikt-bitterli.me/resources/), originally created by Blendswap user "thecali".
