### ISSUE TITLE
 [🔨 compilation issue] 'cmake -GNinja' step

### ISSUE THREAD

**Issue by yuan-tn** [mitsuba-renderer/mitsuba2#623]
## Summary

There is an error at 'cmake -GNinja' step

## System configuration

- Platform: macOS Monterey version 12.4
- Compiler: following steps in documentation 'cmake -GNinja ..
ninja'
- Python version: 3.9
- Mitsuba 2 version: update to 07/22/2022
- -clang version: 13.1.6
- Compiled variants:
        "scalar_rgb",
        "scalar_spectral"

## Description

After I ran the command line 'cmake -GNinja [mitsuba2 path]', there are error messages:

-- Building the following variants of Mitsuba:
--  * scalar_rgb
--  * scalar_spectral
-- Mitsuba: using libc++.
-- Mitsuba: building the Python plugin.
CMake Error at ext/enoki/CMakeLists.txt:88 (message):
  Failed to compile 'archflags' binary: Change Dir:
  /Users/TianYuan/document/mitsuba2-master/mitsuba2/build/CMakeFiles/CMakeTmp

  

  Run Build Command(s):/opt/homebrew/bin/ninja cmTC_59922 && [1/2] Building
  CXX object CMakeFiles/cmTC_59922.dir/archflags_unix.cpp.o

  FAILED: CMakeFiles/cmTC_59922.dir/archflags_unix.cpp.o

  /Library/Developer/CommandLineTools/usr/bin/c++ -stdlib=libc++
  -D_LIBCPP_VERSION -march=native -arch arm64 -isysroot
  /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -MD -MT
  CMakeFiles/cmTC_59922.dir/archflags_unix.cpp.o -MF
  CMakeFiles/cmTC_59922.dir/archflags_unix.cpp.o.d -o
  CMakeFiles/cmTC_59922.dir/archflags_unix.cpp.o -c
  /Users/TianYuan/document/mitsuba2-master/mitsuba2/ext/enoki/resources/archflags_unix.cpp

  clang: error: the clang compiler does not support '-march=native'

  ninja: build stopped: subcommand failed.

**Comment by merlinND** [comment]
Hello @yuan-tn,

Please have a look at [Mitsuba 3](https://github.com/mitsuba-renderer/mitsuba3), which can be installed directly with `pip install mitsuba`. You can also try building it yourself if needed, and open an issue there if you encounter the same error.

**Comment by yuan-tn** [comment]
Thank you!
I installed mitsuba 3 successfully with 'pip install mitsuba'. But I want to use blender exporter. I tried to link the mitsuba-blender addon to the mitsuba 3 build directory. It did not work. The error is 'please verify the path to the library in addon preference.', when I tried to export mitsuba XML file in blender (3.1).  Does it mean mitsuba 3 is not compatible with the blender addon?

**Comment by merlinND** [comment]
Hello @yuan-tn,

The `mitsuba-blender` addon supports Mitsuba 3, although I think that's not quite merged yet (development is on a branch). Feel free to open an issue there to be able to try out the exporter.
