### ISSUE TITLE
[❔ other question]runtime API error = 0719

### ISSUE THREAD

**Issue by JakeXin7** [mitsuba-renderer/mitsuba2#626]
## System configuration

- Platform: Windows 10
- Compiler: Visual Studio 2019
- Python version: 3.9.3
- Compiled variants:
    * `scalar_rgb`
    * `gpu_autodiff_rgb`

## Description

I try to optimize the texture, but sometimes I get the error :
`"cuda_check(): runtime API error = 0719 "cudaErrorLaunchFailure" in path_to_mitsuba2/ext/enoki/src/cuda/horiz.cu:88."`
What's wrong with it and how can I avoid this error?

Here's the main code:

```
params = traverse(scene)
params.keep(['texture.reflectance.data'])

iterations = 10000
opt = Adam(params, lr=0.01)

for it in range(iterations):
    image = render(scene, optimizer=opt, unbiased=True, spp=4)
    loss = ek.hsum(ek.sqr(image - image_ref)) / len(image)
    ek.backward(loss)
    opt.step()
    print('Iteration %03i: ' % it, 'loss=%g' % loss[0])
```

**Comment by Speierers** [comment]
Hi @JakeXin7 ,

I would recommand you take a look at Mitsuba 3. The system was completely redesign and such issues should be fixed.
