### ISSUE TITLE
[❔ other question] Performance on Windows much lower than Linux?

### ISSUE THREAD

**Issue by Mike-Leo-Smith** [mitsuba-renderer/mitsuba2#628]
## Summary

Hello, everyone!

We are currently working on a rendering system and benchmarking it with Mitsuba 2. However, we found that Mitsuba's performance on Windows is significantly lower than on Linux.

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: Windows 11 / Linux Manjaro
- Compiler: MSVC 17 / clang-14
- Python version: N/A
- Mitsuba 2 version: 2.2.1 (commit 238001a5)
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
    * `gpu_rgb`
    * `gpu_spectral`

## Description

We use several scenes (namely, Living Room, Staircase, Spaceship, Glass of Water, and Coffee) from the [Rendering Resources](https://benedikt-bitterli.me/resources/) website (converted from the Mitsuba 0.6 scene format to the Mitsuba 2 format; we can share them if needed). We rendered the scenes on Windows and Linux resp. but found that the Windows build consumes a lot more time...

Below are the timings (two runs for each OS):

scene | backend | sampler | resolution | spp | max depth | rr depth | spectrum | time consumption (Linux1) | time consumption (Linux2) | time consumption (Windows1) | time consumption (Windows2)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
living-room | cuda | Independent | (1920, 1080) | 1024 | 16 | 5 | RGB | 5.549m | 5.262m | 34.251m | 33.778m
living-room | cuda | Independent | (1920, 1080) | 1024 | 16 | 5 | Spectral | Error | Error | Error | Error
living-room | cpu | Independent | (1920, 1080) | 1024 | 16 | 5 | RGB | 14.427m | 14.536m | 35.94m | 35.857m
living-room | cpu | Independent | (1920, 1080) | 1024 | 16 | 5 | Spectral | Error | Error | Error | Error
coffee | cuda | Independent | (1200, 1800) | 1024 | 16 | 5 | RGB | 4.3511m | 4.3648m | 7.4024m | 7.8863m
coffee | cuda | Independent | (1200, 1800) | 1024 | 16 | 5 | Spectral | 4.7924m | 4.7924m | 8.2762m | 8.7747m
coffee | cpu | Independent | (1200, 1800) | 1024 | 16 | 5 | RGB | 4.7701m | 4.6594m | 13.658m | 13.524m
coffee | cpu | Independent | (1200, 1800) | 1024 | 16 | 5 | Spectral | 5.0735m | 5.1251m | 13.993m | 13.932m
glass-of-water | cuda | Independent | (1920, 1080) | 1024 | 16 | 5 | RGB | 2.8178m | 2.8359m | 5.9105m | 6.1903m
glass-of-water | cuda | Independent | (1920, 1080) | 1024 | 16 | 5 | Spectral | 3.1962m | 3.1617m | 6.6171m | 6.907m
glass-of-water | cpu | Independent | (1920, 1080) | 1024 | 16 | 5 | RGB | 5.7487m | 5.767m | 16.084m | 15.834m
glass-of-water | cpu | Independent | (1920, 1080) | 1024 | 16 | 5 | Spectral | 6.1755m | 6.1182m | 16.26m | 16.162m
spaceship | cuda | Independent | (1920, 1080) | 1024 | 16 | 5 | RGB | 7.4143m | 6.1194m | 13.152m | 13.723m
spaceship | cuda | Independent | (1920, 1080) | 1024 | 16 | 5 | Spectral | 8.4429m | 7.0395m | 14.784m | Error
spaceship | cpu | Independent | (1920, 1080) | 1024 | 16 | 5 | RGB | 5.1661m | 5.2028m | 15.579m | 15.534m
spaceship | cpu | Independent | (1920, 1080) | 1024 | 16 | 5 | Spectral | 5.6908m | 5.6965m | 16.311m | 16.181m
staircase | cuda | Independent | (1080, 1920) | 1024 | 16 | 5 | RGB | 8.4279m | 6.3982m | 22.182m | 21.227m
staircase | cuda | Independent | (1080, 1920) | 1024 | 16 | 5 | Spectral | 13.076m | 8.2829m | Error | 30.603m
staircase | cpu | Independent | (1080, 1920) | 1024 | 16 | 5 | RGB | 15.28m | 15.24m | 41.609m | 41.292m
staircase | cpu | Independent | (1080, 1920) | 1024 | 16 | 5 | Spectral | 17.793m | 16.507m | 42.823m | 42.452m

We wonder if it is a known issue. If so, what are the possible causes, and are there any fixes/workarounds?

**Comment by Speierers** [comment]
Hi @Mike-Leo-Smith,

We are not aware of this issue. That is very intriguing indeed. 

I would be curious to see whether this performance descrepancy between Linux and Window still exists with Mitsuba 3. We completely redesigned the backend of the system and fix tons of performance issues there. Likely not but it would be very interesting to know.

By any chance could you give this a try? Porting your code to Mitsuba 3 shouldn't be too much work hopefully.

**Comment by Mike-Leo-Smith** [comment]
> By any chance could you give this a try? Porting your code to Mitsuba 3 shouldn't be too much work hopefully.

Thanks for the advice! Thanks for the advice! Seems the Rendering Resources website has already updated the scenes to Mitsuba 3, so should be no problem with a quick test.

**Comment by merlinND** [comment]
And indeed benchmarking against Mitsuba 3 would be more relevant, since @Speierers said so many improvements were made, it is more representative.

**Comment by Mike-Leo-Smith** [comment]
OK, I've run the tests.

Mitsuba 3 gives me the same performance on Windows and Linux (and both are much faster than Mitsuba 2).

**Comment by Speierers** [comment]
Great, so I suppose I can close this issue. Thanks for looking into this.
