### ISSUE TITLE
Can I adjust width of SIMD used in mitsuba2?

### ISSUE THREAD

**Issue by pjessesco** [mitsuba-renderer/mitsuba2#63]
I'd like to control a number of inputs of operations in packet mode(4, 8, or 16). 

In my environment, I checked that it works with 8 input at once, and I want to reduce it as 4.

I wonder is it possible, and how can I achieve it.

Thanks.

**Comment by Speierers** [comment]
I believe in `mitsuba.conf` you should be able to specify the `PacketSize` like this:

```
  "packet_rgb": {
        "float": "Packet<float, PACKET_SIZE>", // <-- specify size here
        "spectrum": "Color<Float, 3>"
    },
```

Although I have never tested this.

**Comment by pjessesco** [comment]
Thanks, it seems working.
