### ISSUE TITLE
[❔ other question] how to uninstall mitsuba2 in linux?

### ISSUE THREAD

**Issue by zhaoguangyuan123** [mitsuba-renderer/mitsuba2#630]
## Summary

Now I use pip install mitsuba to install mitsuba3 onto my Linux system but I find that mitsuba2 is still there and I have not found any official solution to uninstall it. 
Could you kindly let me know if there is a good way to uninstall mitsuba2 and make a smooth transition from mi2 to mi3?
Thank you
![image](https://user-images.githubusercontent.com/48136187/187413590-2bda888e-88fa-4c22-91f9-18eee1141532.png)

## System configuration

Linux. with conda env

**Comment by Speierers** [comment]
There is no official solution to uninstall it as they were no official solution to install it ;) It should be enough to delete the installation directory of Mitsuba 2 on your system. How did you install it in the first place?

**Comment by zhaoguangyuan123** [comment]
> 

I followed the documents in the link https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html.
Honestly, installing mitsuba2 on Linux is much complicated than installing mitsuba3. 

Did you mean simply deleting the file is enough?

Best
Guangyuan

**Comment by Speierers** [comment]
Yes, or removing Mitsuba 2 from you path.

**Comment by zhaoguangyuan123** [comment]
> 

Sure. I removed the MI2 that way.
Thank you
