### ISSUE TITLE
The examples of Differentiable rendering applications

### ISSUE THREAD

**Issue by 774880930** [mitsuba-renderer/mitsuba2#631]
[❔ other question]

I have been studying about  the differentiable rendering applications ,Do you have the examples of the "Reconstruction of a heterogeneous smoke volume" from different viewpoints and van Gogh's wheat field with Cypresses optimization on translucent material.

**Comment by Speierers** [comment]
@774880930 please use the Discussions page for such questions.

**Comment by Speierers** [comment]
Also I would recommend you take the time to go through the tutorial section. There is already some material covering heterogeneous volume optimization:
https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering_tutorials.html
