### ISSUE TITLE
[🐛 bug report] OptiX "arithmetic involving uninitialized variable!" with Certain Scenes

### ISSUE THREAD

**Issue by rrubberr** [mitsuba-renderer/mitsuba2#632]
## Summary

When trying to render my attached "kairos-new-gpu" scene (exported from Blender 2.76 with the add-on for Mitsuba 0.6) Mitsuba2 throws the error `Caught a critical exception: cuda_trace_append(): arithmetic involving uninitialized variable!`. The scene renders fine with `scalar_rgb` and `packet_spectral` and I am able to render sample scenes such as the Cornell box with `gpu_rgb`. I am aware that Mitsuba2 has been superseded by Mitsuba3, but is there a known fix for this issue?

## System configuration

- Platform: Debian 11
- Compiler: clang 9.0.1-16.1
- Python version: 3.9.2
- Mitsuba 2 version: latest
- Compiled variants:
    * `scalar_rgb`
    * `packet_spectral`
    * `gpu_rgb`

- GPU: NVIDIA RTX A5000
- NVIDIA Driver: 470.141.03
- CUDA: 11.2.2

## Description

Based on other issues, the "Caught a critical exception: cuda_trace_append(): arithmetic involving uninitialized variable!" may be related to an out of memory error, however I have already lowered the `samples_per_pass` parameter to 10 with no success.

## Steps to reproduce

1. `./mitsuba -m gpu_rgb -v -o ~/Documents/output.exr ~/Documents/kairos-new-gpu/kairos-new-gpu.xml`

[kairos-new-gpu.zip](https://github.com/mitsuba-renderer/mitsuba2/files/9749374/kairos-new-gpu.zip)
[cbox.zip](https://github.com/mitsuba-renderer/mitsuba2/files/9749388/cbox.zip)

**Comment by Speierers** [comment]
Hi @rrubberr,

I would recommend you switch to the [new version of Mitsuba](https://github.com/mitsuba-renderer/mitsuba3). Likely this issue was fixed in the meantime.
