### ISSUE TITLE
Something about code

### ISSUE THREAD

**Issue by Akua1919** [mitsuba-renderer/mitsuba2#634]
- [❔ other question]

## Summary

I am curious about the code in 'CMakeLists.txt' in root directory.

## System configuration

- Platform: win11 / ubuntu22.04
- Compiler: VS2022/2019
- Python version: 3.9
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`

## Description

As it shows around line 77

```
if (UNIX)
  option(MTS_ENABLE_PROFILER "Enable sampling profiler" ON)
endif()
```
Does it matters if I compile on windows?

**Comment by njroussel** [comment]
Hi @Akua1919 

No this option does not matter. I believe it's only used to get performance statistics about which parts of the code Mitsuba is spending it's time in.
