### ISSUE TITLE
[✨ feature request] Does the mitsuba2 support bsdf for cloth model?

### ISSUE THREAD

**Issue by Theo-Wu** [mitsuba-renderer/mitsuba2#636]
I notice that in Mitsuba 0.5.0 there is an implementation of irawan's bsdf for cloth. Is it possible to implement it in Mitsuba2 or is there any difficulty to do that? Looking forward to your reply!

**Comment by merlinND** [comment]
Hello @Theo-Wu,

Mitsuba 3 is the currently maintained version: https://github.com/mitsuba-renderer/mitsuba3
The cloth BSDF that you mentioned has not been ported yet from Mitsuba 0.5, but I don't think there's any particular reason apart from lack of time / other priorities.
