### ISSUE TITLE
Rendered polarized images' intensity doesn't change according to the change of polarization angle- [❔ other question]

### ISSUE THREAD

**Issue by jiazhangW** [mitsuba-renderer/mitsuba2#638]
Hello,

I am using Mitsuba 2 to render polarized images. Basically, I put a linear polarizer in front of the camera. But when I rotate the filter, the rendered images are the same. I attached my xml below. Please correct me if you find anything wrong. Thanks!

<?xml version="1.0"?>
<scene version="2.2.1">
    
    <default name="resx" value="1024" />
    <default name="resy" value="1024" />
    

    <integrator type="stokes">
        <integrator type="path">
            <integer name="max_depth" value="10"/>
        </integrator>
    </integrator>
    <sensor type="perspective">
        <string name="fov_axis" value="x" />
        <float name="fov" value="45" />
        <float name="near_clip" value="0.001" />
        <float name="far_clip" value="1000.000000" />
        <transform name="to_world">
            <rotate x="1" angle="0" />
            <rotate y="1" angle="0" />
            <rotate z="1" angle="0" />
            <translate x="0" y="0" z="-3" />
        </transform>

        <sampler type="ldsampler">
            <integer name="sample_count" value="64" />
        </sampler>
        <film type="hdrfilm">
            <integer name="width" value="256" />
            <integer name="height" value="256" />
            <rfilter type="gaussian" />
        </film>
    </sensor>

    <shape type="obj" id = "pol">
        
        <string name="filename" value="C:/Mitsuba2/mitsuba2/mitsuba_structured_light_renderer-main/mistuba_examples/scenes/models/filter.obj"/>
        <bsdf type="polarizer">
        </bsdf>

        <transform name="to_world">
            <scale x="10" y="10" z="10"/>
            <translate x="0" y="0" z="-2.9" />
            <rotate x="0" y="0" z="1" angle="90"/>
            <rotate x="1" y="0" z="0" angle="-90"/>
 
        </transform>
    </shape>    
    
    
    <bsdf type="blendbsdf" id="blend_mat">
        <float name="weight" value="0"/>
        <bsdf type="conductor" id="bsdf0" />
        <bsdf type="diffuse" id="bsdf1" />
    </bsdf>
    <bsdf type="roughconductor" id="metal">
        <float name="alpha" value="0.2"/>
        <string name="distribution" value="ggx"/>
        <spectrum name="eta" value="0.051585"/>
        <spectrum name="k" value="3.9046"/>
    </bsdf>

    
    <bsdf type="conductor" id="mirror" />

    <shape type="sphere">
        <float name="radius" value="1"/>        
        <transform name="to_world">
            <translate x="0" y="0" z="0"/>
        </transform>
        <ref id="blend_mat" name="bsdf" />
    </shape>  
    
    
    <shape type="obj" id = "screen">
        <string name="filename" value="C:/Mitsuba2/mitsuba2/mitsuba_structured_light_renderer-main/mistuba_examples/scenes/meshes/plane.obj" />
        <emitter type="area">
            <texture name="radiance" type="bitmap">
                <string name="filename" value="C:/Mitsuba2/mitsuba2/mitsuba_structured_light_renderer-main/mistuba_examples/scenes/textures/sample.png" />
            </texture>
        </emitter>
        <transform name="to_world">
            <scale x="1" y="1" z="1" />
            <translate x="-1.5" y="0" z="-1.5" />
        </transform>
    </shape>

**Comment by merlinND** [comment]
Hello @jiazhangW,

I have no expertise about polarization, but if this was due to a bug, it might have been fixed in the meantime in [Mitsuba 3](https://github.com/mitsuba-renderer/mitsuba3). Could you please try that, and open an issue there if the problem persits?
