### ISSUE TITLE
[❔ other question] setting the variant("llvm_spectral_polarized"), the code didn't work 

### ISSUE THREAD

**Issue by wxw19990405** [mitsuba-renderer/mitsuba2#639]
## Summary

recently I run into a problem when i used the example sence from https://www.dropbox.com/s/o5gyzdqt5h1486q/dragon.zip?dl=0. 
the code didn't work when i set the variant("llvm_spectral_polarized"). i know it should be "scalar_spectral_polarized", but it turn out very slow when i set higher values of 'spp' and bigger film size.

mi.set_variant("llvm_spectral_polarized")
scene = mi.load_file('E:/Mitsuba/dragon/scene_lph.xml')
image = mi.render(scene)

the scene can load corrently, but when i do render, the code didn't report any error and the rendering result 'image'.

## System configuration

- Python version: 3.9
- Mitsuba  version: 3

**Comment by njroussel** [comment]
Hi @wxw19990405 

If you're using  Mitsuba 3. Please open your issues and discussions on that repository, Mitsuba 2 is no longer actively maintained.

In Mitsuba3 :
The `measured_polarized` BSDF is not fully supported in JIT variants, you must stick to `scalar_*`variants if you wish to produce a correct ouput (existing [issue](https://github.com/mitsuba-renderer/mitsuba3/issues/694)).

**Comment by wxw19990405** [comment]
@njroussel thank you very much！
