### ISSUE TITLE
[❔ other question]How can we output UV map in python?

### ISSUE THREAD

**Issue by naruki-segawa-78092** [mitsuba-renderer/mitsuba2#640]
## Summary
We are trying to rendering with Mitsuba2 in Python.
When we render the scene loading with XML file, we want to output UV map of an object in the scene.
Could you teach me how to output UV map in Python?

## System configuration

- Platform: ...Windows
- Compiler: ..Visual Studio 2022
- Python version: ...3.9.13
- Compiled variants:
    * `gpu_rgb`

**Comment by njroussel** [comment]
Hi @narukisegawa 

I think what you're looking for si the `aov` integrator ([documentation](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#arbitrary-output-variables-integrator-aov)). With this integrator, you can output an image of the geometrys' UVs in screen space.
