### ISSUE TITLE
- [❔ other question] I want to optimize the values in the transform component of my sensor plugin 

### ISSUE THREAD

**Issue by VijayVikasM** [mitsuba-renderer/mitsuba2#641]
- [❔ other question] I want to optimize the values in the transform component of my sensor plugin 

## Summary

I want to optimize the values in the transform component of my sensor plugin (scale and lookat matrix)
<transform name="to_world">
            
            <scale x="0.0260" y="0.0240"/>
            <lookat origin="0, 0.00040, 0.120"
                    target="0, 0.00040, 0"
                    up    ="0, 1, 0"/>
        </transform>
But this is by default not differentiable.Is there any way I can achieve this?

**Comment by njroussel** [comment]
Mitsuba 2 cannot handle this sort of optimizations.
I'd recommend you take a look at [Mitsuba 3](mitsuba.readthedocs.io/), where this feasible. If you have any issues or questions you can open a thread in [that repository](https://github.com/mitsuba-renderer/mitsuba3).
