### ISSUE TITLE
Unable to compile: Windows 10: Visual Studio Community 2022

### ISSUE THREAD

**Issue by bansal-parul** [mitsuba-renderer/mitsuba2#642]
*[🔨 compilation issue] : Unable to compile

Unable to compile mitsuba 2 on Windows 10, with Visual Studio Community 2022.

The system Configuration are as follows :
Visual Studio Community Version : 2022, 17
Python Version : 3.11
Cmake Version : 3.27
Compiled variants: default (scalar_rgb, and scalar_spectral)
Mitsuba 2 version : v2.2.1
Windows : 10, 64bit
cuda version : 11
Graphics : RTX 3090

## Description

I faced multiple issues while compiling mitsuba 2. The command used was  : cmake -G "Visual Studio 17 2022" -A x64 -B build.
The build was successful, but when I ran the .sln file, the following errors came up. I used Release and x64 to build the solution.

Please note : I also tried running the sln file from the toolbar using build entire solution again, but it didnt work and errors occurred. 
 The following is the snippet of errors when I rebuilt the entire issue.

![mitsuba_issue](https://github.com/mitsuba-renderer/mitsuba2/assets/70015762/272e4d79-b922-4d28-8d4b-fe6d48eed468)

**Comment by merlinND** [comment]
Hello @bansal-parul,

Mitsuba 2 is not actively maintained, as development continues on Mitsuba 3. 
Could you please try again with [Mitsuba 3](https://github.com/mitsuba-renderer/mitsuba3), and open an issue there if you encounter build errors.
