### ISSUE TITLE
How to get a texture straight?

### ISSUE THREAD

**Issue by PidgeyBE** [mitsuba-renderer/mitsuba2#66]
Dear all

I was trying to simulate/render a scene with a picture inside of it. If I use the `rectangle` shape and apply the picture as a texture, there is no issue:
```
<shape type="rectangle">
	<transform name="toWorld">
		<scale x="1000" y="1000"/>
		<translate z="3990" x="1500" y="1000" />
		<rotate x="1" angle="180"/>
	</transform>
	<bsdf type="diffuse">
		<texture type="bitmap" name="reflectance">
			<string name="filename" value="dummy.jpg"/>
		</texture>
	</bsdf>
</shape>
```
![image](https://user-images.githubusercontent.com/19860056/78464171-3b706a00-76e6-11ea-886e-84c4784eb75f.png)
However, I can't use a rectangle shape because it's not supported by `gpu_autodiff`:

> ---> 13 scene = load_file('pbox.xml')
RuntimeError: ​[xml.cpp:1069] Error while loading "pbox.xml" (near line 3, col 2): could not instantiate scene plugin of type "scene": 
[xml.cpp:1069]   [Shape] Rectangle::optix_geometry(): not implemented!

To solve this issue, I replaced the rectangle with an `obj` shape. In this case however, I can't get the texture right...
[image](https://user-images.githubusercontent.com/19860056/78464128-dfa5e100-76e5-11ea-809a-d8f91b276b84.png). The image gets warped onto the rectangular object etc..
I've tried to play with the `to_uv` transform, but that's not getting me anywhere unfortunately...

So one of two solutions would solve my issue:
* Support rectangle shape in Optix
* Allow to place a texture straight onto an object.

Or maybe there are other ways to solve this?

Best regards, Pieterjan

**Comment by merlinND** [comment]
Hello @PidgeyBE,

This should be solved by modifying the UV mapping of the rectangle your are using. This can be achieved easily in Blender.

**Comment by Speierers** [comment]
You can try the rectangle mesh in :
``` 
resources/data/docs/scenes/meshes/rectangle.obj
```
It should have the right UV mapping.

**Comment by PidgeyBE** [comment]
Thanks @Speierers! That did it!
