### ISSUE TITLE
Build failed on Windows 10

### ISSUE THREAD

**Issue by mehrab2603** [mitsuba-renderer/mitsuba2#68]
Trying to build the following variants

- scalar_rgb
- scalar_spectral
- packet_rgb
- packet_spectral
- gpu_autodiff_rgb
- gpu_autodiff_spectral

CUDA Version: 10.2.89
Optix: 6.5.0
Visual Studio Community 2019 Version 16.5.2

Getting the following errors at the end of compilation.

![error](https://user-images.githubusercontent.com/5913653/78468341-6487ff00-76d4-11ea-8d5c-2109f626d678.PNG)

Any help appreciated.

**Comment by Speierers** [comment]
Hi,
Is this on the latest `master`? 

Don't forget to update the submodule as well:
```
git pull --rebase origin master
git submodule update --recursive
```

**Comment by mehrab2603** [comment]
Yes, freshly pulled before trying to build and then made this issue afterwards. Looking at the other issues, it is exactly what [this issue](https://github.com/mitsuba-renderer/mitsuba2/issues/25) is reporting.

**Comment by Speierers** [comment]
Could you maybe try to apply the changes from PR #34, this might be related?

I will merge those when I have the time.

**Comment by mehrab2603** [comment]
That worked. Closing this. Thanks!
