### ISSUE TITLE
Wavelength type of spectrum_trait(monochrome, rgb) question

### ISSUE THREAD

**Issue by yd8012mw2** [mitsuba-renderer/mitsuba2#69]
Can be a silly question, but I couldn't find anywhere else I can ask a question about this project.
Can you expain why the wavelength spectrum_traits of monochrome image is Color<Float, 1> whereas the rgb image is Color<Float, 0>? Using things I've understood it should be both Color<Float, 1> or Color<Float, 0>.

**Comment by Speierers** [comment]
The concept of wavelength per ray doesn't apply to RGB mode, as the components of a `Color<Float, 3>` variable reprensent weights of 3 *basis functions* describing the color space, and not 3 individual wavelengths.

On the other hand, in `mono` mode, every sampled ray will carry information about a specific wavelength.

For more information on this, please refer to the [doc](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/variants.html#part-2-color-representation)
