### ISSUE TITLE
Spectral Upsampling in Mitsuba 2

### ISSUE THREAD

**Issue by garethwalkom** [mitsuba-renderer/mitsuba2#71]
When reading the docs, I came across [this paper](http://rgl.s3.eu-central-1.amazonaws.com/media/papers/Jakob2019Spectral_3.pdf) regarding spectral upsampling.

Is this the method that Mitsuba 2 uses? From my understanding, Mitsuba 1 used the Smits model.

I was also trying to find where it's been implemented in Mitsuba 2.

**Comment by Speierers** [comment]
Indeed this is what Mitsuba 2 uses.

I believe it is implemented in `ext/rgb2spec`

**Comment by garethwalkom** [comment]
Great! Thanks for the confirmation.
