### ISSUE TITLE
DirectIntegrator does not support hide_emitters property

### ISSUE THREAD

**Issue by mworchel** [mitsuba-renderer/mitsuba2#78]
In contrast to what the documentation says, the `DirectIntegrator` does not support the flag `hide_emitters` and the following error message is produced when loading such a scene:

`unreferenced property ["hide_emitters"] in integrator plugin of type "direct"`

It looks like the flag is usually handled by the base class `MonteCarloIntegrator` but `DirectIntegrator` derives only from `SamplingIntegrator`.

**Comment by Speierers** [comment]
Hi @mworchel ,

Thanks for reporting this! It should be fixed now (bde43b5).
