### ISSUE TITLE
Clarification on the definition of depth

### ISSUE THREAD

**Issue by xEnVrE** [mitsuba-renderer/mitsuba2#79]
I am trying to use an [Arbitrary Output Variables integrator](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#arbitrary-output-variables-integrator-aov) to obtain a depth image given an `xml` scene.

However, when I try to visualize the depth map along with the rgb channels, as a 3D point cloud, using the camera intrinsic parameters obtained according to the field of view, width and height of the Mitsuba `perspective` sensor, I obtain strange distortions. For example, the side of a square table is not more straight as it should.

According to the code and the documentation, the `depth integrator` uses the `distance along the intersected ray` to evaluate the depth. If `O` is the origin of the camera, and `P(u, v)` is the point on the visible surface of a mesh corresponding to the pixel `(u, v)`, does it mean that the depth is evaluated as `norm(P(u, v) - O)` where `norm()` is the Euclidean norm? Or, as happens for the real output of a depth camera, the depth is evaluated as the positive distance between the plane of the camera and the point `P(u,v)`, i.e. the positive z component of `P(u, v) - O` (assuming that z is the axis going from `O` to the target of the camera) expressed in camera frame?

Thank you.

**Comment by Speierers** [comment]
Hi @xEnVrE ,

The depth value should be equivalent to `norm(P(u, v) - O)` where `O` is the origin of the camera defined in the scene description. 

If this isn't what you get, could you please share a simple scene so we can reproduce this issue?

Thanks!

**Comment by xEnVrE** [comment]
Hi @Speierers,

thank you for the clarification. I think this is exactly what I am getting using the `depth` integrator. Since the definition is different from the output depth of a standard depth camera, I wanted to ask whether this was intentional or not.

If this is the case, I think we can close the issue. I was able to reproduce the standard output of a depth camera by using the `position` integrator and the pose of the camera in the world frame in a post-processing step.

**Comment by unpajure** [comment]
> Hi @Speierers,
> 
> thank you for the clarification. I think this is exactly what I am getting using the `depth` integrator. Since the definition is different from the output depth of a standard depth camera, I wanted to ask whether this was intentional or not.
> 
> If this is the case, I think we can close the issue. I was able to reproduce the standard output of a depth camera by using the `position` integrator and the pose of the camera in the world frame in a post-processing step.

Hi @xEnVrE,
Could you please explain exactly what you did to get depths similar to output from a traditional depth camera? Did you transform the world points from the position integrator to the camera's coordinate system and just take the z coordinate?

**Comment by xEnVrE** [comment]
> Did you transform the world points from the position integrator to the camera's coordinate system and just take the z coordinate?

Yes, that is exactly what I did.

**Comment by unpajure** [comment]
> > Did you transform the world points from the position integrator to the camera's coordinate system and just take the z coordinate?
> 
> Yes, that is exactly what I did.

Huh, I did the same thing but the results aren't as expected. Guess there are bugs in my code.

**Comment by xEnVrE** [comment]
I don't known if this can help but, I also got wrong results initially because I was not considering that the camera convention used in the renderer is different from the one used, e.g., in robotics. If I am not wrong, the convention used is the so called _look at_ convention where
- the z axis is pointing from the target to the origin of the camera
- the x axis is pointing rightward
- the y axis is pointing up

The picture [here](https://learnopengl.com/Getting-started/Camera) explains this much better.

Instead, on a standard depth camera, you will have z pointing towards the target, x rightward and y downward.

**Comment by pablospe** [comment]
> If this is the case, I think we can close the issue. I was able to reproduce the standard output of a depth camera by using the `position` integrator and the pose of the camera in the world frame in a post-processing step.

@xEnVrE Do you have an example of this depth map rendering? I am not sure how to reproduce this process. Also the transformation from camera intrinsic/extrinsic.

**Comment by xEnVrE** [comment]
Hi @pablospe, I don't have any publicly available code but once you have a scene ready to be rendered the steps are, more or less:

```
 # render film
 film = sensor.film()
 film.set_destination_file('./film_' + str(frame) + '.exr')
 film.develop()

 # split channels (in my case it was 'rgb' and 'xyz'
 bitmap = film.bitmap().split()
 bitmap_channels = {split[0]:split[1] for split in bitmap}

 # extract 3D positions of visible points in the scene
 xyz_array = numpy.array(bitmap_channels['xyz'], copy = False).squeeze()
 points = numpy.array([[xyz_array[v, u, 0], xyz_array[v, u, 1], xyz_array[v, u, 2]] for u in range(0, camera_width) for v in range(0, camera_height)])
 points = numpy.transpose(points)

 # evaluate points w.r.t to the camera frame origin and express them in camera frame
 points_camera = points - camera_origin
 points_camera_frame = numpy.dot(camera_to_world, points_camera)

 # extract the z coordinates of such points, i.e. the depth
 depth = numpy.empty([camera_height, camera_width], "float32")
 for u in range(0, camera_width):
     for v in range(0, camera_height):
         depth[v, u] = points_camera_frame[2, u * camera_height + v]
```

The rotation matrix `camera_to_world` takes vectors from the camera to any of the point, written in the world frame, and express them in camera frames. It is as follows

```
origin_to_target = camera_target - camera_origin
origin_to_target /= numpy.linalg.norm(origin_to_target)
camera_to_world_row_0 = numpy.cross(origin_to_target.transpose(), camera_up.transpose())
camera_to_world_row_0 /= numpy.linalg.norm(camera_to_world_row_0)
camera_to_world_row_1 = -numpy.cross(camera_to_world_row_0, origin_to_target.transpose())
camera_to_world_row_2 = origin_to_target.transpose()
camera_to_world = numpy.array([camera_to_world_row_0,
                               camera_to_world_row_1,
                               camera_to_world_row_2]).squeeze()
```
where `camera_origin` is the origin of the camera and `camera_target` is the point you are loooking at with the camera.

Given the depth map, in order to move to a 3D point cloud you only need camera intrinsics as follows

```
fx = camera_width / 2.0 / math.tan((camera_hfov / 180.0 * math.pi) / 2.0)
fy = fx
cx = camera_width / 2.0
cy = camera_height / 2.0
```
where `cmaera_hfov` is the horizontal field of view in degrees that you used in your sensor.

**Comment by pablospe** [comment]
great, thanks!
