### ISSUE TITLE
Simple volumetric path tracer does not render directional emitters

### ISSUE THREAD

**Issue by leroyvn** [mitsuba-renderer/mitsuba2#80]
# Issue description

The `volpathsimple` plugin does not render scenes illuminated with delta lights (`directional` and `point`). (I however have the feeling that you are already aware of this considering bad308d4a993721a4c89819e362d0fa0e7aa46d3.)

# Steps to reproduce

Render the xml scene file below with default settings.

# Used setup

- OS: macOS 10.15.4
- Compiler: Clang 11.00.0

# Scene XML

```xml
<scene version="2.0.0">
    <integrator type="volpathsimple"/>
    <!-- <integrator type="volpath"/> -->
    <!-- <integrator type="path"/> -->
    
    <sensor type="perspective">
        <transform name="to_world">
            <lookat origin="0, -25, 15" target="0, 0, 0" up="0, 0, 1"/>
        </transform>
    </sensor>

    <emitter type="directional">
        <vector name="direction" value="0 0 -1"/>
    </emitter>
    <!-- <emitter type="point">
        <point name="position" value="0, 0, 2"/>
    </emitter> -->
    <!-- <emitter type="constant"/> -->
    <!-- <shape type="sphere">
        <emitter type="area"/>
        <point name="center" value="0, 0, 2"/>
        <float name="radius" value="1"/>
    </shape> -->
    
    <shape type="rectangle">
        <transform name="to_world">
            <scale x="5" y="5"/>
        </transform>
        <bsdf type="diffuse">
            <rgb name="reflectance" value="0.5, 0.5, 0.5"/>
        </bsdf>
    </shape>
</scene>
```

**Comment by dvicini** [comment]
Hi, 
Yes, I was already aware and just now pushed a fix. Note that `volpath` often results in better performance and lower noise than `volpathsimple`. The `volpathsimple` integrator is meant to be used in certain special scenarios, e.g. when using dielectric medium boundaries or when polarization support is needed (this is yet to be documented) 

Delio
