### ISSUE TITLE
Is there any way to specify an specific image to be projected from a light source?

### ISSUE THREAD

**Issue by mehrab2603** [mitsuba-renderer/mitsuba2#81]
I am trying to have a projector-like object that projects a certain image onto the scene in a certain direction. In Blender, I could use textures as the color of a point light source to achieve this effect. Is this possible in Mitsuba?

**Comment by Speierers** [comment]
Hi @mehrab2603 ,

Currently there is not plugin to achieve such effect. 

As far as I know, this would correspond to the `spot` plugin of Mitsuba 1.

Feel free to port this and open a PR, I would be happy to review it!

**Comment by mehrab2603** [comment]
I tried but I am afraid I don't have the technical expertise to port it. Not sure how to handle conditional statements that return particular values if true when dealing with Enoki types (lines 92 and 103 in [spot.cpp](https://github.com/tomka/mitsuba-renderer/blob/master/src/luminaires/spot.cpp)) and also some other things. Is there any plan to officially port this plugin in future?

**Comment by Speierers** [comment]
No official plans at the moment. Although as a very common plugin, it is likely that someone will port it in the not too distant future.
