### ISSUE TITLE
Reason underlying the choice of Wien's approximation for the blackbody spectrum plugin?

### ISSUE THREAD

**Issue by leroyvn** [mitsuba-renderer/mitsuba2#84]
What is the reason why the `blackbody` plugin uses Wien's approximation? Couldn't we use Planck's law directly? (Possibly using a carefully chosen dimensionless lookup table)

**Comment by wjakob** [comment]
Hi @leroyvn  -- it's just for importance sampling and the PDF. The evaluation routine uses the full expression. (I wasn't able to derive an analytic importance sampling scheme for Planck's law)

**Comment by leroyvn** [comment]
The analytic expression of Planck's law is unwieldy indeed :( I wrote a `blackbodyinterp` plugin which uses a `ContinuousDistribution` for the PDF and importance sampling, in a dimensionless spectral coordinate space to ensure that the accuracy remains the same regardless the value of the temperature parameter. I didn't benchmark it though, so I am not sure if performance-wise it's good, but it's the only compromise I could come up with to use Planck's law everywhere. I can submit a PR if you think it makes sense.

**Comment by wjakob** [comment]
When I experimented with this a while back, Wiener's approximation was a good fit for reasonable temperature values -- definitely good enough to drive importance sampling. I don't think we need a table-driven solution unless there is numerical evidence that shows this to be under-performing.

**Comment by leroyvn** [comment]
Thank you for the details @wjakob! I'll keep my toy in store and let you know if it proves to be of any practical use. I'll close this PR.
