### ISSUE TITLE
OpenEXR dwaLookups gets Segmentation fault: 11 [OSX Catalina - 10.15]

### ISSUE THREAD

**Issue by guy4261** [mitsuba-renderer/mitsuba2#9]
Hello,

Building on OSX, I get stuck on the OpenEXR execution of `dwaLookups`. Here's the output when I rerun `ninja` after the first crash (hence why I only have 202 goals left instead of the original 700+): 

```bash
$ ninja
[2/202] Generating dwaLookups.h
FAILED: ext_build/openexr/OpenEXR/IlmImf/dwaLookups.h
cd /Users/guy4261/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf && /Users/guy4261/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/./dwaLookups > /Users/guy4261/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/dwaLookups.h
/bin/sh: line 1: 62275 Segmentation fault: 11  /Users/guy4261/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/./dwaLookups > /Users/guy4261/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/dwaLookups.h
```

The `dwaLookups` binary runs, but segfaults. Here's what I get when I run on the shell:

```bash
$ ext_build/openexr/OpenEXR/IlmImf/./dwaLookups
#include <cstddef>



const unsigned short dwaCompressorNoOp[] =
{
    0x0000, 0x0001, 0x0002, 0x0003, 0x0004, 0x0005, 0x0006, 0x0007,
    0x0008, 0x0009, 0x000a, 0x000b, 0x000c, 0x000d, 0x000e, 0x000f,
    0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015, 0x0016, 0x0017,
    0x0018, 0x0019, 0x001a, 0x001b, 0x001c, 0x001d, 0x001e, 0x001f,
...
    0xffe0, 0xffe1, 0xffe2, 0xffe3, 0xffe4, 0xffe5, 0xffe6, 0xffe7,
    0xffe8, 0xffe9, 0xffea, 0xffeb, 0xffec, 0xffed, 0xffee, 0xffef,
    0xfff0, 0xfff1, 0xfff2, 0xfff3, 0xfff4, 0xfff5, 0xfff6, 0xfff7,
    0xfff8, 0xfff9, 0xfffa, 0xfffb, 0xfffc, 0xfffd, 0xfffe, 0xffff,
};



Segmentation fault: 11
```

My enabled modes in `mitsuba_conf` are:

```
    "enabled": [
        "scalar_rgb",
        "scalar_spectral",
        "packet_rgb"
    ],
```

and notice that the problem is with the OpenEXR under `ext_build`, so I assume this does not arise from the OpenEXR that I may already have on my system.

**Comment by wjakob** [comment]
That's very strange. What kind of processor architecture / Linux version is this running on? What compiler version did you use?

**Comment by guy4261** [comment]
Hi @wjakob - that's on OSX, not Linux. My `clang[++]` versions are `Apple clang version 11.0.0 (clang-1100.0.33.12)`.

```bash
$ clang --version  # output for `clang++ --version` is identical
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by andrewwillmott** [comment]
In case it's useful as a sanity check, I've successfully built and run scenes on Mojave (10.14.3) with an older version of clang (clang-1000.11.45.5).

Running ext_build/openexr/OpenEXR/IlmImf/./dwaLookups directly completes successfully.

Seems like it's an OpenEXR issue. Maybe try downloading that and compiling directly as a cross check?

**Comment by wjakob** [comment]
Super weird. Can you build in debug mode & attach LLDB to the crashing ``dwaLookups``? Maybe a backtrace will shed light on what's going on here.

**Comment by nmatsuda** [comment]
I just had this issue, LLDB throws "libdyld.dylib`stack_not_16_byte_aligned_error", which led me to this post:

https://github.com/Homebrew/homebrew-core/issues/44776#issuecomment-537131009

Apparently it's xcode 11 specific. Passing -fno-stack-check appears to resolve the issue.

**Comment by wjakob** [comment]
Amazing, thank you for the detective work! Does this only happen when building in debug mode, or also release mode? It would be a piece of cake to just always provide this parameter to the recursive OpenEXR build.

**Comment by nmatsuda** [comment]
It happens in both as far as I can tell. I put the parameter directly into ext/openexr/CMakeLists.txt, but that homebrew thread makes it sounds like passing it by default globally should be ok.

**Comment by guy4261** [comment]
@nmatsuda sounds good! So if compilation [is done by](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling/#macos)

```bash
$ mkdir build
$ cd build
$ cmake -GNinja ..
$ ninja
```

where does the ` -fno-stack-check`?

```bash
$ ninja  -fno-stack-check  # here?
$ cmake -Gninja -fno-stack-check  # or here?
```

Or otherwise - where do I add it in `ext/openexr/CMakeLists.txt`?

Thanks!

**Comment by guy4261** [comment]
In the `CMAKE_CXX_FLAGS` for `Clang`?

```diff
# Line 13 of ext/openexr/CMakeLists.txt
-  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-switch -Wno-tautological-compare -Wno-deprecated-register")
+  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-switch -Wno-tautological-compare -Wno-deprecated-register -fno-stack-check")
```

**Comment by guy4261** [comment]
Sadly, the `exr` stage seems to cause trouble still. Here's what I get when I try to render a sphere (XML taken from [here](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/file_format/#scene-file-format)):

```bash
# Taken from https://mitsuba2.readthedocs.io/en/latest/src/getting_started/file_format/#scene-file-format
$ cat sph.xml
<scene version="2.0.0">
    <shape type="sphere">
        <float name="radius" value="10"/>
    </shape>
</scene>

$ mitsuba sph.xml
2020-03-12 01:04:14 INFO  main  [mitsuba.cpp:194] Mitsuba version 2.0.0 (master[d30def81], Mac OS, 64bit, 8 threads, 8-wide SIMD)
2020-03-12 01:04:14 INFO  main  [mitsuba.cpp:195] Copyright 2019, Realistic Graphics Lab, EPFL
2020-03-12 01:04:14 INFO  main  [mitsuba.cpp:196] Enabled processor features: avx2 avx fma f16c sse4.2 x86_64
2020-03-12 01:04:14 INFO  main  [mitsuba.cpp:197] Using mode "packet_rgb"
2020-03-12 01:04:14 INFO  main  [xml.cpp:1117] Loading XML file "sph.xml" ..
2020-03-12 01:04:14 INFO  main  [PluginManager] Loading plugin "plugins/sphere.dylib" ..
2020-03-12 01:04:14 INFO  main  [PluginManager] Loading plugin "plugins/diffuse.dylib" ..
2020-03-12 01:04:14 INFO  main  [PluginManager] Loading plugin "plugins/uniform.dylib" ..
2020-03-12 01:04:14 WARN  main  [Scene] No sensors found! Instantiating a perspective camera..
2020-03-12 01:04:14 INFO  main  [PluginManager] Loading plugin "plugins/perspective.dylib" ..
2020-03-12 01:04:14 INFO  main  [PluginManager] Loading plugin "plugins/hdrfilm.dylib" ..
2020-03-12 01:04:14 INFO  main  [PluginManager] Loading plugin "plugins/gaussian.dylib" ..
2020-03-12 01:04:14 INFO  main  [PluginManager] Loading plugin "plugins/independent.dylib" ..
2020-03-12 01:04:14 WARN  main  [Scene] No integrator found! Instantiating a path tracer..
2020-03-12 01:04:14 INFO  main  [PluginManager] Loading plugin "plugins/path.dylib" ..
2020-03-12 01:04:14 INFO  main  [ShapeKDTree] Building a SAH kd-tree (1 primitives) ..
2020-03-12 01:04:14 INFO  main  [ShapeKDTree] Finished. (12 B of storage, took 0ms)
2020-03-12 01:04:14 INFO  main  [SamplingIntegrator] Starting render job (768x576, 4 samples, 8 threads)
Rendering [===============================================================================================] (82ms, ETA: 0ms)
2020-03-12 01:04:14 INFO  main  [SamplingIntegrator] Rendering finished. (took 82ms)
2020-03-12 01:04:14 INFO  main  [HDRFilm] ✔  Developing "sph.exr" ..
Segmentation fault: 11
```

**Comment by wjakob** [comment]
Interesting that OpenEXR is causing so much trouble (working perfectly fine here on MacOS / Mojave). Could you make a debug build, attach via LLDB, and get a backtrace?

**Comment by guy4261** [comment]
I'm on 10.15 (Catalina not Mojave).

Sure, how? Do I `rm -rf *` inside `build`, then this?

```bash
$ cmake -DCMAKE_BUILD_TYPE=Debug -GNinja ..
$ ninja
```

And afterwards `lldb mitsuba sph.xml` ? Or do I need more flags for `lldb` ?

**Comment by guy4261** [comment]
BTW since xcode has been mentioned as a culprit by @nmatsuda , I'm with 11.2.1:

```bash
$ xcodebuild -version
Xcode 11.2.1
Build version 11B500
```

This is not the latest - I can upgrade to 11.3.1 from the App Store.

**Comment by wjakob** [comment]
You can easily toggle the build mode using a tool like "ccmake" or "cmake-gui", then simply run "ninja" once more.

**Comment by wjakob** [comment]
Then `lldb --  mitsuba sph.xml`, `run`, and `bt`.

**Comment by guy4261** [comment]
Thanks for the `lldb` instructions! I thought the cmake part is [as easy as this](https://stackoverflow.com/a/7725055). I'll try with the cmake tools you mentioned.

**Comment by nmatsuda** [comment]
> In the `CMAKE_CXX_FLAGS` for `Clang`?
> 
> ```diff
> # Line 13 of ext/openexr/CMakeLists.txt
> -  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-switch -Wno-tautological-compare -Wno-deprecated-register")
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-switch -Wno-tautological-compare -Wno-deprecated-register -fno-stack-check")
> ```

yes - that's where I put it

**Comment by nmatsuda** [comment]
> BTW since xcode has been mentioned as a culprit by @nmatsuda , I'm with 11.2.1:
> 
> ```shell
> $ xcodebuild -version
> Xcode 11.2.1
> Build version 11B500
> ```
> 
> This is not the latest - I can upgrade to 11.3.1 from the App Store.

I'm on 11.3.1 and unfortunately the issue is still present - I think 11.0 through 11.3 all use the same version of clang. But not issues so far after adding the compiler flag (I think the segfault you got at runtime might have been from one of your previous builds)

**Comment by guy4261** [comment]
OK now:

1. I upgraded XCode via the App store, now

```bash
$ xcodebuild -version
Xcode 11.3.1
Build version 11C504
```

2. I reset my git completely, including the `-fno-stack-check` change because I didn't want to skip a check in the build but then get a segfault during runtime.

3. I ran `cmake -DCMAKE_BUILD_TYPE=Debug -GNinja .. && ninja`.

Now (after `source setpath.sh` of course) - `mitsuba sph.xml` generates a proper `sph.exr` file!

Likewise `cd resources/data/scenes && mitsuba hello.xml` gives me the `hello.exr` with the famous teapot.

Thanks @nmatsuda and @wjakob !

I'll delete everything under `build` and will retry without the `Debug` flag. (@nmatsuda : I always do that, this is why I don't think the previous builds affected me as I always start with the `build` dir empty, correct me if I'm wrong about this please!).

**Comment by guy4261** [comment]
Works just as well on a Release build (i.e. without `-DCMAKE_BUILD_TYPE=Debug`, where `Release` gets picked as the default).

I'll conclude that upgrading XCode via the App Store and reaching a state where

```bash
$ xcodebuild -version
Xcode 11.3.1
Build version 11C504
```

seems to have solved it. No additional changes (such as adding `-fno-stack-check`) were required.

Closing this as solved. Thanks!!!

**Comment by leroyvn** [comment]
Sorry to bring this up again: I got the same issue upon upgrading to XCode 11.4. I rolled back to 11.3.1 and it works fine again.

**Comment by arpit15** [comment]
I confirm that Xcode 11.4 upgrade works with the proposed addition of `fno-stack-check` flag

**Comment by binorchen** [comment]
Hello, I got the exact issue during my compilation. Please help.
System information:
```
Ubuntu 16.04
```
Below is returned by `cmake -GNinja .. -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc`

```
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
-- Check for working C compiler: /usr/bin/clang-10
-- Check for working C compiler: /usr/bin/clang-10 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-10
-- Check for working CXX compiler: /usr/bin/clang++-10 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /home/user/anaconda3/envs/stylegan2/bin/python3.6 (found version "3.6.12")
-- Found PythonLibs: /home/user/anaconda3/envs/stylegan2/lib/libpython3.6m.so
-- Building the following variants of Mitsuba:
--  * scalar_rgb
--  * gpu_autodiff_rgb
-- Setting build type to 'Release' as none was specified.
-- Mitsuba: using libc++.
-- Mitsuba: building the Python plugin.
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Enoki: building the CUDA backend.
-- Enoki: building the autodiff backend.
-- Enoki: building the Python plugin.
-- pybind11 v2.4.dev4
-- LTO enabled
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.54")
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80")
-- TBB: using libc++.
-- Mitsuba: using builtin implementation for CPU ray tracing.
-- Mitsuba: using OptiX for GPU ray tracing.
-- Mitsuba: LTO support enabled.
-- Check if the system is big endian
-- Searching 16 bit integer
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Mitsuba: sampling profiler enabled.
-- Found Sphinx: /home/user/anaconda3/envs/stylegan2/bin/sphinx-build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/software/mitsuba2/build
```

And the error return by `ninja`:
```
[200/684] Generating dwaLookups.h
FAILED: cd /home/user/software/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf && /home/user/software/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/./dwaLookups > /home/user/software/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/dwaLookups.h
/home/user/software/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/./dwaLookups: symbol lookup error: /home/user/software/mitsuba2/build/ext_build/openexr/OpenEXR/IlmImf/./dwaLookups: undefined symbol: _ZTIN9IlmThread6ThreadE
[200/684] Building CXX object ext_build/enoki/CMakeFiles/enoki-python-cuda-autodiff.dir/src/python/cuda_autodiff_matrix.cpp.o
ninja: build stopped: subcommand failed.
```
