### ISSUE TITLE
Fail to load the old scene type.

### ISSUE THREAD

**Issue by kaca0083** [mitsuba-renderer/mitsuba2#92]
Hi there. After successfully compiling the mitsuba2 with the default config, I try to load the scene data provided by http://noobody.org/resources/. I have tried a few of them and got the same "critical exception" as shown in the attached screenshot. Any idea why?
![image](https://user-images.githubusercontent.com/8167439/79564721-c3d90c80-80e1-11ea-92b2-694fd44bb292.png)

**Comment by Speierers** [comment]
As described in the doc ([here](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#path-tracer-path)), the current version of the `path` plugin doesn't have a `strict_normals` option. You'll need to remove this in the XML file in order to render this file.
