### ISSUE TITLE
Using Mitsuba for images out of visual spectra

### ISSUE THREAD

**Issue by mfloresVicomtech** [mitsuba-renderer/mitsuba2#93]
Hi, this is more a question than a problem. I'm involved in a project were we need to be able to emulate imagery taken with an infrared camera shooting an industrial furnace. As burners are emitting at a very high temperature, fire is almost invisible to human eye, and most of the emitting & reflecting light is out of this spectra.

So seen that Mitsuba is able to calculate at spectra level, I would like to know if it handles infrared values and how would in that case represent output.

**Comment by diiigle** [comment]
Maybe #161 helps.

**Comment by Speierers** [comment]
I will close this for now as this isn't a bug.

**Comment by wjakob** [comment]
One quick response from me also for posterity: there should be no problem in using Mitsuba 2 to simulate infrared as long as it still behaves more or less like light in the visible spectrum. You'll have to tweak the sensor response function of the camera, but that's it basically.

Mitsuba won't give good results for long wavelengths where thermal conductance and convention play an increasingly important rule. If this is what you need, then I suggest looking for tools that are specialized for thermal IR simulations.

**Comment by mfloresVicomtech** [comment]
Thanks for all the info, #142 looks promissing on this.
