### ISSUE TITLE
compile issue python related

### ISSUE THREAD

**Issue by eugenedeon** [mitsuba-renderer/mitsuba2#95]
This is probably simple, sorry, but on both Win 10 and Mac OS I get the same python error when attempting to start a compilation:

CMake Error at CMakeLists.txt:39 (message):
  Could not run resources/configure.py script: File
  "/Users/eug/Documents/code/mitsuba2/resources/configure.py", line 182

      end=';' if index < len(enabled) - 1 else '')
         ^

  SyntaxError: invalid syntax

Perhaps this is my systems running 2.7 instead of the installed python 3?  I'm not clear on how to remedy that.

**Comment by wjakob** [comment]
Eugene, you'll definitely need to install a more recent version of Python (e.g. via apt-get on Linux, `brew` on MacOS). Afterwards, run `alias python=python3.7` (Or whatever is installed). Also, wipe out the CMake cache files (`rm -rf CMakeFiles CMakeCache.txt`) and retry.

**Comment by eugenedeon** [comment]
Yep, that did it.  sorry to pester!  thx!
