### ISSUE TITLE
Is there any scene warehouse for mitsuba2？

### ISSUE THREAD

**Issue by kaca0083** [mitsuba-renderer/mitsuba2#97]
Since we need to manually edit the old version scene.xml to fit mitsuba2, a few off-the-shelf test scenes will be nice to quickly test the ability of mitsuba2.

**Comment by Speierers** [comment]
Hi @kaca0083 ,

You can find a few scene in the `resources/data` directory, e.g.:

- `resources/data/scenes`
- `resources/data/docs/scenes`
- `resources/data/tests/scenes`

Moreover, convertion from older Mitsuba scenes should be pretty straightforward, besides missing plugins.
